#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ "${1}" == "GAL" ]; then
  ./gendirs.sh GAL | xargs -I{} echo "cd {}; ~/t; cd .." | xargs -P20 -I{} bash -c "{}" | grep -v "no core file found" | sort -u | tr '\n' '\0' | xargs -0 -I{} ~/kbs REVERSEAUTO "{}"
elif [ "${1}" == "SAN" ]; then  # Used ~/kbsa
  ./gendirs.sh SAN | xargs -I{} echo "cd {}; ~/t; cd .." | xargs -P20 -I{} bash -c "{}" | grep -v "no core file found" | sort -u | tr '\n' '\0' | xargs -0 -I{} ~/kbsa REVERSEAUTO "{}" 
else
  ./gendirs.sh | xargs -I{} echo "cd {}; ~/t; cd .." | xargs -P20 -I{} bash -c "{}" | grep -v "no core file found" | sort -u | tr '\n' '\0' | xargs -0 -I{} ~/kbs REVERSEAUTO "{}"
fi
