#!/bin/bash
# Created by Roel Van de Paar, MariaDB

set "${1^^}" # Make ${1} uppercase ('san' > 'SAN')

# Using OUT+subshell+final sort -u ensures a race condition or similar (likely in xargs -P20) is avoided where ./allstrings_merged ouput could show two indentical uniqueID's rather than those two having been merged: this was observed:
# $ ./allstrings_merged 
# trx->mysql_thd == thd|SIGABRT|innobase_kill_query|kill_handlerton|plugin_foreach_with_mask|ha_kill_query
# trx->mysql_thd == thd|SIGABRT|innobase_kill_query|kill_handlerton|plugin_foreach_with_mask|ha_kill_query

OUT=
if [ "${1}" == "GAL" ]; then
  OUT="$(./gendirs.sh GAL | xargs -I{} echo "cd {}; ~/t 2>/dev/null; cd .." | xargs -P20 -I{} bash -c "{}" | grep -vEi "no core file found|no relevant strings were found" | sort -u)"
elif [ "${1}" == "SAN" ]; then
  OUT=$(./gendirs.sh SAN | xargs -I{} echo "cd {}; ~/t 2>/dev/null; cd .." | xargs -P20 -I{} bash -c "{}" | grep -vEi "no core file found|no relevant strings were found" | sort -u)
elif [ "${1}" == "MSAN" ]; then
  OUT=$(./gendirs.sh MSAN | xargs -I{} echo "cd {}; ~/t 2>/dev/null; cd .." | xargs -P20 -I{} bash -c "{}" | grep -vEi "no core file found|no relevant strings were found" | sort -u)
else
  OUT=$(./gendirs.sh | xargs -I{} echo "cd {}; ~/t 2>/dev/null; cd .." | xargs -P20 -I{} bash -c "{}" | grep -vEi "no core file found|no relevant strings were found" | sort -u)
fi
echo "${OUT}" | sort -u
echo "${OUT}" > /tmp/allstrings_merged
