#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ "${1}" == "GAL" ]; then
  ./gendirs.sh GAL | xargs -I{} echo "cd {}; ~/t; cd .." | xargs -P20 -I{} bash -c "{}" | grep -v "no core file found" | sort -u
elif [ "${1}" == "SAN" ]; then
  ./gendirs.sh SAN | xargs -I{} echo "cd {}; ~/t; cd .." | xargs -P20 -I{} bash -c "{}" | grep -v "no core file found" | sort -u
else
  ./gendirs.sh | xargs -I{} echo "cd {}; ~/t; cd .." | xargs -P20 -I{} bash -c "{}" | grep -v "no core file found" | sort -u
fi
