#!/bin/bash
# With thanks, https://unix.stackexchange.com/a/46801/241016
rm -f /test/multirun.[0-9]*  # Cleanup multirun logs
if [ -z "$PS1" ]; then
  ~/mariadb-qa/pquery-clean-all.sh
else
  ~/mariadb-qa/pquery-clean-all.sh cleanall
fi
#if [ -r ./clean_newbugs ]; then ./clean_newbugs; fi

if [ -r /test/TESTCASES/mvknown ]; then
  cd /test/TESTCASES
  ~/mariadb-qa/move_known.sh
fi
