#!/bin/bash
if [ -d /data ]; then
  cd /data
fi
ls -d --color=never [0-9][0-9][0-9][0-9][0-9][0-9] | xargs -I{} echo "ls {}/[0-9]*/default*_out 2>/dev/null" | xargs -I{} bash -c "{}" | sed 's|/default.*||' | sort -u | sed 's|/.*||' | uniq -c | sort -n
