#!/bin/bash
# Created by Roel Van de Paar, MariaDB

CURPWD="${PWD}"

echo "{noformat:title=Bug Detection Matrix}"
printf "%-3s %-6s %-4s %-7s %-41s %-30s\n" "" "Rel" "o/d" "Build" "Commit" "UniqueID observed"

./gendirs.sh "${1}" | xargs -I{} echo "cd {}; ./line; cd ${CURPWD}" | xargs -I{} bash -c "{}" | sort -V

echo "{noformat}"
