#!/bin/bash
# Created by Roel Van de Paar, MariaDB

REGEX_EXCLUDE="$(cat REGEX_EXCLUDE 2>/dev/null)"  # Handy to exclude a particular build
if [ -z "${REGEX_EXCLUDE}" ]; then REGEX_EXCLUDE="DUMMYSTRINGNEVERSEEN"; fi

SAN_MODE=0
GAL_MODE=0
ERROR_IN_OPTIONS=0
TEXT=
if [ "${1}" == "SAN" -a -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ "${1}" == "GAL" -a -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ "${1}" != "GAL" -a "${1}" != "SAN" -a ! -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ -z "${1}" -o "${ERROR_IN_OPTIONS}" -eq 1 ]; then
  echo "This script expects one or two paramaters;"
  echo "  > For SAN bugs, specify: ./findbug+ SAN 'bug_string_to_look_for' (SAN=UBSAN,ASAN,TSAN)"
  echo "  > For GAL bugs, specify: ./findbug+ GAL 'bug_string_to_look_for' (GAL=Galera)"
  echo "  > For all other bugs, specify: ./findbug+ 'bug_string_to_look_for' without a first option"
  echo "After testing of in.sql is complete, this script will look for the string 'bug_string_to_look_for' in the error log."
  echo "It expects that test_all was already executed"
  exit 1
elif [ "${1}" == "SAN" ]; then
  SAN_MODE=1
  TEXT="${2}"  # Presence of ${2} was checked earlier above (ref ERROR_IN_OPTIONS)
elif [ "${1}" == "GAL" ]; then
  GAL_MODE=1
  TEXT="${2}"
else
  if [ "${1}" == "BBB" ]; then  # Coding dummy string passed by ~/b to enable searching for multitude of strings
    TEXT="[ \t]0x[0-9a-f][0-9a-f][0-9a-f][0-9a-f]|signal|[Aa]ssertion"
  else
    TEXT="${1}"
  fi
fi

rm -f /tmp/pri.t /tmp/sec.t

# Generate full list
if [ "${SAN_MODE}" -eq 1 ]; then
  ls --color=never | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep --binary-files=text "SAN" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text 'mariadb-[\.0-9]+-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]' | sort -u > /tmp/pri.t
elif [ "${GAL_MODE}" -eq 1 ]; then
  REGEX_EXCLUDE="${REGEX_EXCLUDE//EMD|/}"
  ls --color=never | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep --binary-files=text "GAL" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text 'mariadb-[\.0-9]+*.*-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]' | sort -u > /tmp/pri.t
else  # Normal mode; no SAN, no GAL
  ls --color=never | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep -vE --binary-files=text "SAN|GAL" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text 'mariadb-[\.0-9]+-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]' | sort -u > /tmp/pri.t
fi

# Generate bug list
if [ "${SAN_MODE}" -eq 1 ]; then
  grep -Ei --binary-files=text "${TEXT}" */log/master.err | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep --binary-files=text -E "SAN" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text 'mariadb-[\.0-9]+-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]' | sort -u > /tmp/sec.t
elif [ "${GAL_MODE}" -eq 1 ]; then
  REGEX_EXCLUDE="${REGEX_EXCLUDE//EMD|/}"
  grep -Ei --binary-files=text "${TEXT}" */node1/node1.err | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep --binary-files=text -E "GAL" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text 'mariadb-[\.0-9]+*.*-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]' | sort -u > /tmp/sec.t
else  # Normal mode; no SAN, no GAL
  grep -Ei --binary-files=text "${TEXT}" */log/master.err | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | grep -vE --binary-files=text "SAN|GAL" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text 'mariadb-[\.0-9]+-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]' | sort -u > /tmp/sec.t
fi

# Output bug-present-in list
echo "Bug confirmed present in:"
cat /tmp/sec.t | sed 's|-| |;s|mysql|DUMMY2|' | tr '\n' ',' | sed 's|DUMMY2|\nMySQL:|;s|DUMMY2||g;s|,|, |g;s|^mariadb|DUMMY|;s|mariadb ||g;s|DUMMY|MariaDB:|;s|-dbg| (dbg)|g;s|-opt| (opt)|g;' | sed 's|, $||;s|  | |g'; echo ''

# Bug strings for bug-present-in list
#echo -e "\nBug strings for this list:"
#./findbug "$1" | sed 's|:.*||' | xargs -I{} echo "echo {}; ~/mariadb-qa/text_string.sh {}" | xargs -I{} bash -c "{}"

# Compile/output bug-not-present-in list
echo -e "\nBug (or feature/syntax) confirmed not present in:"
diff /tmp/pri.t /tmp/sec.t | grep --binary-files=text '<' | sed 's|^< ||' | sed 's|-| |;s|mysql|DUMMY2|' | tr '\n' ',' | sed 's|DUMMY2|\nMySQL:|;s|DUMMY2||g;s|,|, |g;s|^mariadb|DUMMY|;s|mariadb ||g;s|DUMMY|MariaDB:|;s|-dbg| (dbg)|g;s|-opt| (opt)|g;' | sed 's|, $||;s|  | |g'; echo ''
