#!/bin/bash
set +H
if [ -z "${1}" ]; then echo 'Assert: please pass the string you want to search for (in MYBUG or in the error log) as the first option to this script. If you want to search error logs rather than MYBUG files, add anything as a second option'; exit 1; fi
if [ -d /data -a -r /data/find_reduced_bugs -a "${PWD}" != "/data" ]; then
  echo "Changing directory to /data"
  cd /data
fi
if [ -z "${2}" ]; then
  # -F: Interpret PATTERNS as fixed strings, not regular expressions (UniqueID's have many regex-like symbols)
  grep --binary-files=text -Fi "${1}" [0-9]*/*/MYBUG* 2>/dev/null | sed "s|^|wc -l |;s|MYBUG.*|\*_out|;s=$= 2>/dev/null=" | xargs -I {} bash -c "{}" | grep -v 'total$' | sed 's|^[ \t]\+||' | sort -u | sort -n
else
  # Without -F as we want regex-enabled search for error logs, and we are not searching for UniqueID's but plain strings
  grep --binary-files=text -i "${1}" [0-9]*/*/log/*.err 2>/dev/null | sed "s|^|wc -l |;s|log/master.err.*|\*_out|;s|log/slave.err.*|\*_out|;s=$= 2>/dev/null=" | tr '\n' '\0' |  xargs -0 -I {} bash -c "{}" | grep -v 'total$' | sed 's|^[ \t]\+||' | sort -u | sort -n
fi
