#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ ! -r ./gendirs.sh ]; then echo 'Assert: ./gendirs.sh missing'; exit 1; fi

REGEX_EXCLUDE="$(cat REGEX_EXCLUDE 2>/dev/null)"  # Handy to exclude a particular build. The 'MENT' exclusion is because some SAN issues have for example 'passed as argument 2' in their summary, note the 'ment' in 'argument'
if [ -z "${REGEX_EXCLUDE}" ]; then REGEX_EXCLUDE="DUMMYSTRINGNEVERSEEN"; fi

# The following is not perfect (other upper/lowercase combinations are possible, but we cannot universally change $1 to uppercase as $1 may be a bug string to search for. At least most common combinations are covered.
if [ "${1}" == "san" -o "${1}" == "msan" -o "${1}" == "gal" -o "${1}" == "bbb" -o "${1}" == "San" -o "${1}" == "Gal" -o "${1}" == "Bbb" ]; then
  set "${1^^}" "${2}" "${3}"  # Make ${1} uppercase ('san' > 'SAN')
fi

BBB_MODE=0
ERROR_IN_OPTIONS=0
if [ "${1}" == "SAN" -a -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ "${1}" == "MSAN" -a -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ "${1}" == "GAL" -a -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ "${1}" != "GAL" -a "${1}" != "SAN" -a "${1}" != "MSAN" -a ! -z "${2}" ]; then ERROR_IN_OPTIONS=1; fi
if [ "${ERROR_IN_OPTIONS}" -eq 1 ]; then
  echo "This script expects zero, one or two paramaters;"
  echo "  > For crashing bugs, specify: ./findbug+ 'BBB' (BBB=Common crash strings are all scanned) (and this is also the default when zero parameters are passed)"
  echo "  > For GAL crashing bugs, specify: ./findbug+ 'GAL' 'BBB' (BBB=Common crash strings are all scanned)"
  echo "  > For SAN bugs, specify: ./findbug+ SAN 'bug_string_to_look_for' (SAN=UBSAN,ASAN,TSAN)"  # TODO: TSAN split
  echo "  > For MSAN bugs, specify: ./findbug+ MSAN 'bug_string_to_look_for' (MSAN)"
  echo "  > For GAL bugs, specify: ./findbug+ GAL 'bug_string_to_look_for' (GAL=Galera)"
  echo "  > For all other bugs, specify: ./findbug+ 'bug_string_to_look_for' without a second option"
  echo "After testing of in.sql is complete, this script will look for the string 'bug_string_to_look_for' in the error log."
  echo "It expects that test_all was already executed"
  exit 1
fi
GENDIRS=
TEXT="${1}"  # Note this may be 'SAN', 'GAL', 'BBB' or nothing/empty (which will be translated to 'BBB'). Each one will be replaced differently/respectively below:
if [ -z "${1}" ]; then TEXT='BBB'; fi
if [ "${TEXT}" == "SAN" ]; then
  GENDIRS='SAN'
  TEXT="${2}"  # Presence of ${2} was checked earlier above (ref ERROR_IN_OPTIONS)
elif [ "${TEXT}" == "MSAN" ]; then
  GENDIRS='MSAN'
  TEXT="${2}"  # Presence of ${2} was checked earlier above (ref ERROR_IN_OPTIONS)
elif [ "${TEXT}" == "GAL" ]; then
  GENDIRS='GAL'
  REGEX_EXCLUDE="${REGEX_EXCLUDE//EMD|/}"
  TEXT="${2}"  # Note this may be 'BBB' and if so it will be replaced below
  NODE=1
  if [ ! -z "${3}" ]; then
    NODE="${3}"  # Could be '*' or 1,2,3,... (node to be scanned: all or specific 1,2,3,...)
  fi
fi
if [ "${TEXT}" == "BBB" ]; then  # BBB: coding dummy string passed by ~/b to enable searching for multitude of strings
  BBB_MODE=1
  TEXT="[ \t]0x[0-9a-f][0-9a-f][0-9a-f][0-9a-f]|signal|[Aa]ssertion"
fi

rm -f /tmp/pri.t /tmp/sec.t

VER_SCAN_STRING='mariadb-[-\.0-9]+-[od][pb][tg]|mysql-[\.0-9]+-[od][pb][tg]'

# TODO: the below is not entirely thread safe. If one runs 'b' and 'bs' at the same time and in the remote case where these runs reach the code below/finish in close succession, it is possible that /tmp/pri.t and/or /tmp/sec.t were overwritten/conflict. To be fixed by using mktemp for all files

# Generate a baseline list /tmp/pri.t of all directories (to compare against the list generated below i.e. /tmp/sec.t)
./gendirs.sh ${GENDIRS} | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text "${VER_SCAN_STRING}" | sort -uV > /tmp/pri.t

# Generate list of directories in which the bug is observed as /tmp/sec.t
./gendirs.sh ${GENDIRS} | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | xargs -I{} echo "grep -Ei --binary-files=text '${TEXT}' {}/log/master.err {}/node${NODE}/node${NODE}.err 2>/dev/null" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text "${VER_SCAN_STRING}" | sort -uV > /tmp/sec.t

# If ALSO_CHECK_SAN_BUILDS_FOR_CORES export var is set, then add any core containing dirs to /tmp/sec.t after rename>add>resort
if [ "${GENDIRS}" == 'SAN' -o "${GENDIRS}" == 'MSAN' ]; then
  if [ "${ALSO_CHECK_SAN_BUILDS_FOR_CORES}" == "1" ]; then
    mv /tmp/sec.t /tmp/sec.t.prep  # Rename already obtained list from above
    ./gendirs.sh ${GENDIRS} | xargs -I{} echo "ls {}/data/core* {}/node${NODE}/core* 2>/dev/null" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text "${VER_SCAN_STRING}" | sort -uV >> /tmp/sec.t.prep  # Add to it any *SAN dirs containing cores
    sort -uV /tmp/sec.t.prep > /tmp/sec.t  # Resort to unique
    rm -f /tmp/sec.t.prep
  fi
fi

if [ "${BBB_MODE}" -eq 1 ]; then
  mv /tmp/sec.t /tmp/sec.t.1
  # Allow cores to be fully written. This is especially important when bug_report is running as many servers are terminating at once causing disk IO to backlog. The sleep code below likely resolves the issue which is sometimes seen when running ~/b (mariadb-qa/bug_report.sh) where a certain version would not show as affected, presumably because the core was still writing
  if [ -z "$(ps -ef | grep bug_report | grep -v grep)" ]; then  # bug_report not running
    sleep 3
  else
    sleep 7
  fi 
  ./gendirs.sh ${GENDIRS} | xargs -I{} echo "ls {}/data/core* {}/node${NODE}/core* 2>/dev/null" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" | grep -vEi --binary-files=text "${REGEX_EXCLUDE}" | sed 's|-linux-x86_64||' | grep -oE --binary-files=text "${VER_SCAN_STRING}" | sort -uV > /tmp/sec.t.2
  cat /tmp/sec.t.1 /tmp/sec.t.2 2>/dev/null | sort -uV > /tmp/sec.t
  rm -f /tmp/sec.t.1 /tmp/sec.t.2
fi

# Output bug-present-in list
echo "Bug confirmed present in:"
cat /tmp/sec.t | sed 's|-| |;s|mysql|DUMMY2|' | tr '\n' ',' | sed 's|DUMMY2|\nMySQL:|;s|DUMMY2||g;s|,|, |g;s|^mariadb|DUMMY|;s|mariadb ||g;s|DUMMY|MariaDB:|;s|-dbg| (dbg)|g;s|-opt| (opt)|g;' | sed 's|, $||;s|  | |g'; echo ''
# Bug strings for bug-present-in list
#echo -e "\nBug strings for this list:"
#./findbug "$1" | sed 's|:.*||' | xargs -I{} echo "echo {}; ~/mariadb-qa/text_string.sh {}" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}"

# Compile/output bug-not-present-in list
echo -e "\nBug (or feature/syntax) confirmed not present in:"
diff /tmp/pri.t /tmp/sec.t | grep --binary-files=text '<' | sed 's|^< ||' | sed 's|-| |;s|mysql|DUMMY2|' | tr '\n' ',' | sed 's|DUMMY2|\nMySQL:|;s|DUMMY2||g;s|,|, |g;s|^mariadb|DUMMY|;s|mariadb ||g;s|DUMMY|MariaDB:|;s|-dbg| (dbg)|g;s|-opt| (opt)|g;' | sed 's|, $||;s|  | |g'; echo ''

# Cleanup
rm -f /tmp/pri.t /tmp/sec.t
