#!/bin/bash
set +H

########################################################################################################################
# This script is outdated and replaced by in-reducer.sh code which creates matching reducer scripts per newbug stored! #
########################################################################################################################

# User variables, dynamic
BASEDIR="/test/MD260121-mariadb-10.5.9-linux-x86_64-dbg"  # Base directory to use for testing against

# User variables, likely no change needed to these, ever
REDUCER_MAIN="/home/$(whoami)/mariadb-qa/reducer.sh"  # Reducer template to use
TEXT_STRING_LOC="/home/$(whoami)/mariadb-qa/new_text_string.sh"  # Text string location
KNOWN_BUGS_LOC="/home/$(whoami)/mariadb-qa/known_bugs.strings"  # Known bugs location

# Checks
if [ ! -r ${REDUCER_MAIN} ]; then
  echo "Assert: reducer (${REDUCER_MAIN}) not readable by this script. Terminating."
  exit 1
fi
if [ ! -r /data/NEWBUGS.PREV ]; then
  if [ ! -r ./NEWBUGS.PREV ]; then
    echo 'Assert: Neither /data/NEWBUGS.PREV nor ./NEWBUGS exists. Terminating.'
    exit 1
  else
    cd ./NEWBUGS.PREV
  fi
else
  cd /data/NEWBUGS.PREV
fi

rm -f ./gen_reducer.list
ls --color=never *newbug*.sql > ./gen_reducer.list
while read SQL_FILE; do
  STRING_FILE="$(echo "${SQL_FILE}" | sed 's|\.sql|.string|')"
  if [ ! -r "${STRING_FILE}" ]; then 
    echo "Error for: '${SQL_FILE}' found, but no '${STRING_FILE}' present!"
    continue
  fi
  REDUCER_FILE="$(echo "${SQL_FILE}" | sed 's|\.sql|\.reducer|')"
  if [ -z "${REDUCER_FILE}" ]; then
    echo "Assert: REDUCER_FILE empty?"
    exit 1
  fi
  if [ -r "${REDUCER_FILE}" ]; then 
    rm -f "${REDUCER_FILE}"
  fi
  cp "${REDUCER_MAIN}" "${REDUCER_FILE}"
  # The following code is also present in pquery-prep-red.sh and reducer.sh, please update all at the same time
  TEXT="$(cat "${STRING_FILE}" | head -n1 | sed 's|"|\\\\"|g')"  # The sed transforms " to \" to avoid TEXT containing doube quotes in reducer.sh.
  if [[ "${TEXT}" = *":"* ]]; then
    if [[ "${TEXT}" = *"|"* ]]; then
      if [[ "${TEXT}" = *"/"* ]]; then
        if [[ "${TEXT}" = *"_"* ]]; then
          if [[ "${TEXT}" = *"-"* ]]; then
            echo "Assert (#1)! No suitable sed seperator found. TEXT (${TEXT}) contains all of the possibilities, add more!"
          else TEXT="$(echo "$TEXT"|sed -e "s-&-\\\\\\&-g")";fi  # Escape '&' correctly
        else TEXT="$(echo "$TEXT"|sed -e "s_&_\\\\\\&_g")";fi  # Escape '&' correctly
      else TEXT="$(echo "$TEXT"|sed -e "s/&/\\\\\\&/g")";fi  # Escape '&' correctly
    else TEXT="$(echo "$TEXT"|sed -e "s|&|\\\\\\&|g")";fi  # Escape '&' correctly
  else TEXT="$(echo "$TEXT"|sed -e "s:&:\\\\\\&:g")";fi  # Escape '&' correctly
  sed -i "s|^MODE=[0-9]|MODE=3|" "${REDUCER_FILE}"
  sed -i "s/^TEXT=.*/TEXT='${TEXT}'/" "${REDUCER_FILE}"
  sed -i "s|^SCAN_FOR_NEW_BUGS=[0-9]|SCAN_FOR_NEW_BUGS=1|" "${REDUCER_FILE}"
  sed -i "s|^USE_NEW_TEXT_STRING=[0-9]|USE_NEW_TEXT_STRING=1|"  "${REDUCER_FILE}"
  sed -i "s|^FORCE_SKIPV=[0-9]|FORCE_SKIPV=1|" ${REDUCER_FILE}
  sed -i "s| --sql_mode=ONLY_FULL_GROUP_BY| --sql_mode= --log-bin|" ${REDUCER_FILE}
  sed -i "s|^BASEDIR=.*|BASEDIR=\"${BASEDIR}\"|" ${REDUCER_FILE}
  sed -i "s|^WORKDIR_LOCATION=[0-9]|WORKDIR_LOCATION=1|" ${REDUCER_FILE}
  sed -i "s|^NEW_BUGS_COPY_DIR=.*|NEW_BUGS_COPY_DIR=\"${PWD}\"|" ${REDUCER_FILE}
  sed -i "s|^MULTI_THREADS=[0-9]\+|MULTI_THREADS=3|" ${REDUCER_FILE}
  sed -i "s|^MULTI_THREADS_INCREASE=[0-9]\+|MULTI_THREADS_INCREASE=1|" ${REDUCER_FILE}
  sed -i "s|^MULTI_THREADS_MAX=[0-9]\+|MULTI_THREADS_MAX=7|" ${REDUCER_FILE}
  sed -i "s|^STAGE1_LINES=[0-9]\+|STAGE1_LINES=23|" ${REDUCER_FILE}
  sed -i 's|^INPUTFILE=.*|INPUTFILE="$(ls --color=never -s '"${SQL_FILE}"'* \| grep --binary-files=text -vE "backup\|failing\|prev" \| tac \| head -n1 \| sed \"s\|^[ 0-9]\\+\|\|\")"|' ${REDUCER_FILE}
  sed -i "s|^TEXT_STRING_LOC=.*|TEXT_STRING_LOC=\"${TEXT_STRING_LOC}\"|" ${REDUCER_FILE}
  sed -i "s|^KNOWN_BUGS_LOC=.*|KNOWN_BUGS_LOC=\"${KNOWN_BUGS_LOC}\"|" ${REDUCER_FILE}
  chmod +x ${REDUCER_FILE}
done < ./gen_reducer.list
rm -f ./gen_reducer.list
