#!/bin/bash
# Created by Roel Van de Paar, MariaDB

# The ./kill script ensures the correct PID is selected (via random PORT= assignment)

GENDIRS=gendirs.sh
if [ ! -r ./${GENDIRS} ]; then 
  if [ -r ../${GENDIRS} ]; then
    GENDIRS=../gendirs.sh
  else
    echo "./gendirs.sh not found!"
    exit 1
  fi
else 
  GENDIRS=./gendirs.sh 
fi

set +H
if [ "${1}" == "SAN" ]; then
  ${GENDIRS} SAN | xargs -I{} echo "cd {}; if [ -r ./kill ]; then ./kill; else echo './kill did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} bash -c "{}"
elif [ "${1}" == "MSAN" ]; then
  ${GENDIRS} MSAN | xargs -I{} echo "cd {}; if [ -r ./kill ]; then ./kill; else echo './kill did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} bash -c "{}"
elif [ "${1}" == "GAL" ]; then
  ${GENDIRS} GAL | xargs -I{} echo "cd {}; if [ -r ./gal_kill ]; then ./gal_kill; else echo './gal_kill did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} bash -c "{}"
elif [ "${1}" == "REPL" ]; then
  ${GENDIRS} | xargs -I{} echo "cd {}; if [ -r ./kill_replication ]; then ./kill_replication; else echo './kill_replication did not exist for directory {} - please run ./startup_all or instead do cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} bash -c "{}"
else
  ${GENDIRS} | xargs -I{} echo "cd {}; if [ -r ./kill ]; then ./kill; else echo './kill did not exist for directory {} - running ~/mariadb-qa/startup.sh for cd {}; ~/mariadb-qa/startup.sh; cd -'; fi; cd .." | xargs -P50 -I{} bash -c "{}"
fi

sync
