#!/bin/bash
# Close screens
screen -d -r  | grep '\.pr[0-9]' | sed 's|\..*||' | xargs kill -9
sync
# Stop corresponding mysqld's
ps -ef | grep "/dev/shm/[0-9][0-9][0-9][0-9][0-9][0-9]/" | grep -v grep | awk '{print $2}' | xargs -I{} kill -9 {} 2>/dev/null
sync
screen -wipe
screen -ls
rm -Rf /dev/shm/sql_shuffled /dev/shm/[0-9][0-9][0-9][0-9][0-9][0-9]  # Cleanup temporary working directories
