#!/bin/bash
if [ ! -d /test ]; then echo '/test does not exist, did you create it and execute cp ~/mariadb-qa/mariadb-build-qa/* /home/$(whoami)/mariadb-qa/mariadb-build-qa yet?'; exit 1; fi
if [ ! -d /data ]; then echo '/data does not exist yet? Please create it'; exit 1; fi
mkdir -p /data/NEWBUGS /data/FIREWORKS
ln -fs /home/$(whoami)/mariadb-qa/homedir_scripts/* /home/$(whoami)/ 2>&1
ln -fs /home/$(whoami)/mariadb-qa/mariadb-build-qa/* /test/ 2>&1
ln -fs /home/$(whoami)/mariadb-qa/mariadb-build-qa/* /data/ 2>&1
ln -fs /home/$(whoami)/mariadb-qa/mariadb-build-qa/uniq_newbugs /data/NEWBUGS/uniq_newbugs 2>&1
ln -fs /home/$(whoami)/mariadb-qa/mariadb-build-qa/find_newbug_bugs /data/NEWBUGS/find_newbug_bugs 2>&1
ln -fs /home/$(whoami)/mariadb-qa/mariadb-build-qa/uniq_newbugs /data/FIREWORKS/uniq_newbugs 2>&1
ln -fs /home/$(whoami)/mariadb-qa/mariadb-build-qa/uniq_newbugs /test/TESTCASES/uniq_newbugs 2>&1

echo 'Done!'
exit 0
