#!/bin/bash

# tac: ensures that the earliest started screens (which are most likely to be finished) are shown first
screen -d -r | grep "\.s[_0-9n]\+" | sed 's|\..*||' | sed 's|[^_0-9]||g' | tac > ~/screen_list

COUNT=$(wc -l ~/screen_list 2>/dev/null | sed 's| .*||')

for SCREEN in $(seq 1 ${COUNT}); do
  PID="$(head -n ${SCREEN} ~/screen_list | tail -n1)"
  echo "Connecting you to screen ${SCREEN}/${COUNT} with PID ${PID}" && sleep 0.1
  screen -d -r ${PID}
done

rm -f ~/screen_list
