#!/bin/bash
# Created by Roel Van de Paar, MariaDB
# Test a given MTR input file against all BASEDIRs as generated by gendirs.sh

if [ -z "${1}" ]; then echo
  echo "Expected usage:"
  echo "  ./mtr_testrun.sh {plain-text MTR testcase} {path} {gendirs.sh options}"
  echo "For example:"
  echo "  ./mtr_testrun.sh testcase.test main SAN"
  echo "This command will copy ./testcase.test into all *SAN BASEDIRs (as generated by ./gendirs.sh SAN) into mariadb-test/main (or mysql-test/main as applicable) and execute the testcase using MTR."
  echo "* Note: if {path} is empty, MTR's 'main' subdirectory (mariadb-test/mai) will be used. If {gendirs.sh options} is empty, the default gendirs.sh output will be used which is currently all MD dbg+opt BASEDIRs (MS is filtered in-script)"
  echo "* Note: it is best to give the testcase name a non-generic filename, for example use 'MDEV-12345.test' as testname to avoid MTR selecting multiple tests"
  # For non-tarball builds, the directory is storage/spider/mysql-test/spider/bugfix/t
  echo "For spider testcases, use the following path value: plugin/spider/spider/bugfix/t, for example:"
  echo "  ./mtr_testrun.sh ./MDEV-12345.test plugin/spider/spider/bugfix/t"
  echo "* Note: if the texts 'source ../../t/test_init.inc' and 'Spider' are found in the testcase, the path above will automatically be used (and does not need to be passed)"
  echo "* Note: if you place a file which matches the test name (without .test) and has the .result extension, it will be copied along with the test"
  echo "* Note: if you place a file which matches the test name (without .test) and has the .cnf extension, it will be copied along with the test"
  exit 1
elif [ ! -r "${1}" ]; then echo
  echo "Assert: ${1} could not be read by this script"
  exit 1
elif [ ! -r ./gendirs.sh ]; then echo
  echo "Assert: ./gendirs.sh could be read by this script. It is required and usually present in /test"
  exit 1
fi

MPATH="${2}"
if [ -z "${MPATH}" ]; then
  MPATH="main"
  if grep -qi 'source ../../t/test_init.inc' "${1}"; then
    if grep -qi 'spider' "${1}"; then
      MPATH='plugin/spider/spider/bugfix/t'
    fi
  fi
fi

TEST="$(echo "${1}" | sed 's|\.test$||;s|\.mtr$||;s|^\./||')"
if [ ! -r "${PWD}/${TEST}.test" ]; then
  echo "Assert: ${PWD}/${TEST}.test not found. Please copy the source MTR testcase into the local directory and make sure the file suffix is .test"
  exit 1
fi

TEMP="$(mktemp)"
./gendirs.sh "${3}" | grep 'MD' > ${TEMP}

while read LINE; do
  MTR=
  if [ -d "${LINE}/mariadb-test" ]; then MTR="${LINE}/mariadb-test";
  elif [ -d "${LINE}/mysql-test" ]; then MTR="${LINE}/mysql-test";
  else echo "Error: no mariadb-test nor mysql-test was found for BASEDIR ${LINE}, skipping!"; continue; fi
  if [ "${3}" != "SAN" ]; then
    if [ ! -r "${MTR}/mtr" ]; then echo "Error: ${MTR}/mtr not found for BASEDIR ${LINE}, skipping!"; continue; fi
  else
    if [ ! -r "${MTR}/mtra" ]; then echo "Error: ${MTR}/mtra not found for BASEDIR ${LINE}, skipping! (Tip: run mariadb-qa/startup.sh or 'st' if .bashrc shortcuts are installed (ref linkit) to install mtra which is a script that wraps mtr and ensures the correct UBSAN and ASAN filters are set to avoid common *SAN errors upon MTR/server startup)"; continue; fi
  fi
  if [ ! -d "${MTR}/${MPATH}" ]; then echo "Warning: path ${MTR}/${MPATH} not found, skipping!"; continue; fi
  cp "${1}" "${MTR}/${MPATH}/"
  POSSIBLE_RESULT="$(echo "${1}" | sed 's|\.test$|.result|')"
  if [ -r "${POSSIBLE_RESULT}" ]; then
    echo "Also copying ${POSSIBLE_RESULT}. Note: auto-directory selection is alpha quality, this may fail"
    if [ -d "${MTR}/${MPATH}/../r" ]; then
      cp "${POSSIBLE_RESULT}" "${MTR}/${MPATH}/../r"
    elif [ -d "${MTR}/${MPATH}/r" ]; then
      cp "${POSSIBLE_RESULT}" "${MTR}/${MPATH}/r"
    else
      cp "${POSSIBLE_RESULT}" "${MTR}/${MPATH}/"
    fi
  fi
  POSSIBLE_CNF="$(echo "${1}" | sed 's|\.test$|.cnf|')"
  if [ -r "${POSSIBLE_CNF}" ]; then
    echo "Also copying ${POSSIBLE_CNF}. Note: auto-directory selection is alpha quality, this may fail"
    if [ -d "${MTR}/${MPATH}/../r" ]; then
      cp "${POSSIBLE_CNF}" "${MTR}/${MPATH}/../r"
    elif [ -d "${MTR}/${MPATH}/r" ]; then
      cp "${POSSIBLE_CNF}" "${MTR}/${MPATH}/r"
    else
      cp "${POSSIBLE_CNF}" "${MTR}/${MPATH}/"
    fi
  fi
  cd ${MTR}
  if [ -d "${MTR}/var" ]; then rm -Rf "${MTR}/var"; fi
  if [ "${3}" != "SAN" ]; then
    ./mtr ${TEST}
  else
    ./mtra ${TEST}
  fi
  cd - >/dev/null
done < ${TEMP}
rm -f ${TEMP}

echo '-------------- mtr_testrun.sh Results (core files, if any) --------------'
find . | grep -vE 'MDEV' | grep -E '/mysql-test/|/mariadb-test/' | grep '/var/log/.*/data/' | grep "${TEST}" | grep 'core' | sort -u
echo '-------------- mtr_testrun.sh Results (error log: add your search string and run query) --------------'
echo "SEARCH_STRING='your_search_string'; ./gendirs.sh ${3} | xargs -I{} echo \"grep --binary-files=text -H '\${SEARCH_STRING}' /test/{}/m*test/var/log/*err 2>/dev/null\" | tr '\\n' '\\0' | xargs -0 -I{} bash -c \"{}\""
if [ "${3}" == "SAN" ]; then
  echo '-------------- mtr_testrun.sh Results example for various SAN errors --------------'
  echo "SEARCH_STRING='SUMMARY: '; ./gendirs.sh ${3} | xargs -I{} echo \"grep --binary-files=text -H '\${SEARCH_STRING}' /test/{}/m*test/var/log/*err 2>/dev/null\" | tr '\\n' '\\0' | xargs -0 -I{} bash -c \"{}\""
fi
