#!/bin/bash
# Created by Roel Van de Paar, MariaDB
# Test a given MTR input file against all BASEDIRs as generated by gendirs.sh

if [ -z "${1}" ]; then echo
  echo "Expected usage:"
  echo "  ./mtr_testrun.sh {plain-text MTR testcase} {path} {gendirs.sh options}"
  echo "For example:"
  echo "  ./mtr_testrun.sh testcase.test main SAN"
  echo "This command will copy ./testcase.test into all *SAN BASEDIRs (as generated by ./gendirs.sh SAN) into mariadb-test/main (or mysql-test/main as applicable) and execute the testcase using MTR."
  echo "* Note: if {path} is empty, MTR's 'main' subdirectory (mariadb-test/mai) will be used. If {gendirs.sh options} is empty, the default gendirs.sh output will be used which is currently all MD dbg+opt BASEDIRs (MS is filtered in-script)"
  echo "* Note: it is best to give the testcase name a non-generic filename, for example use 'MDEV-12345.test' as testname to avoid MTR selecting multiple tests"
  # For non-tarball builds, the directory is storage/spider/mysql-test/spider/bugfix/t
  echo "For spider testcases, use the following path value: plugin/spider/spider/bugfix/t, for example:"
  echo "  ./mtr_testrun.sh ./MDEV-12345.test plugin/spider/spider/bugfix/t"
  echo "* Note: if the texts 'source ../../t/test_init.inc' and 'Spider' are found in the testcase, the path above will automatically be used (and does not need to be passed)"
  echo "* Note: if you place a file which matches the test name (without .test) and has the .result extension, it will be copied along with the test"
  echo "* Note: if you place a file which matches the test name (without .test) and has the .cnf extension, it will be copied along with the test"
  exit 1
elif [ ! -r "${1}" ]; then echo
  echo "Assert: ${1} could not be read by this script"
  exit 1
elif [ ! -r ./gendirs.sh ]; then echo
  echo "Assert: ./gendirs.sh could be read by this script. It is required and usually present in /test"
  exit 1
fi

MPATH="${2}"
if [ -z "${MPATH}" ]; then
  MPATH="main"
  if grep -qi 'source ../../t/test_init.inc' "${1}"; then
    if grep -qi 'spider' "${1}"; then
      MPATH='plugin/spider/spider/bugfix/t'
    fi
  fi
fi

TEST="$(echo "${1}" | sed 's|\.test$||;s|\.mtr$||;s|^\./||')"
if [ ! -r "${PWD}/${TEST}.test" ]; then
  echo "Assert: ${PWD}/${TEST}.test not found. Please copy the source MTR testcase into the local directory and make sure the file suffix is .test"
  exit 1
fi

TEMP="$(mktemp)"
REPORT="${PWD}/report.log"  # b-style bug report output (analog of ~/b's report.log)
export MTR_PRINT_CORE=no    # skip MTR's slow inline gdb; matrix stage uses ~/t + stack.sh on saved cores
./gendirs.sh "${3}" | grep 'MD' > ${TEMP}

while read LINE; do
  MTR=
  if [ -d "${LINE}/mariadb-test" ]; then MTR="${LINE}/mariadb-test";
  elif [ -d "${LINE}/mysql-test" ]; then MTR="${LINE}/mysql-test";
  else echo "Error: no mariadb-test nor mysql-test was found for BASEDIR ${LINE}, skipping!"; continue; fi
  if [ "${3}" != "SAN" ]; then
    if [ ! -r "${MTR}/mtr" ]; then echo "Error: ${MTR}/mtr not found for BASEDIR ${LINE}, skipping!"; continue; fi
  else
    if [ ! -r "${MTR}/mtra" ]; then echo "Error: ${MTR}/mtra not found for BASEDIR ${LINE}, skipping! (Tip: run mariadb-qa/startup.sh or 'st' if .bashrc shortcuts are installed (ref linkit) to install mtra which is a script that wraps mtr and ensures the correct UBSAN and ASAN filters are set to avoid common *SAN errors upon MTR/server startup)"; continue; fi
  fi
  if [ ! -d "${MTR}/${MPATH}" ]; then echo "Warning: path ${MTR}/${MPATH} not found, skipping!"; continue; fi
  cp "${1}" "${MTR}/${MPATH}/"
  POSSIBLE_RESULT="$(echo "${1}" | sed 's|\.test$|.result|')"
  if [ -r "${POSSIBLE_RESULT}" ]; then
    echo "Also copying ${POSSIBLE_RESULT}. Note: auto-directory selection is alpha quality, this may fail"
    if [ -d "${MTR}/${MPATH}/../r" ]; then
      cp "${POSSIBLE_RESULT}" "${MTR}/${MPATH}/../r"
    elif [ -d "${MTR}/${MPATH}/r" ]; then
      cp "${POSSIBLE_RESULT}" "${MTR}/${MPATH}/r"
    else
      cp "${POSSIBLE_RESULT}" "${MTR}/${MPATH}/"
    fi
  fi
  POSSIBLE_CNF="$(echo "${1}" | sed 's|\.test$|.cnf|')"
  if [ -r "${POSSIBLE_CNF}" ]; then
    echo "Also copying ${POSSIBLE_CNF}. Note: auto-directory selection is alpha quality, this may fail"
    if [ -d "${MTR}/${MPATH}/../r" ]; then
      cp "${POSSIBLE_CNF}" "${MTR}/${MPATH}/../r"
    elif [ -d "${MTR}/${MPATH}/r" ]; then
      cp "${POSSIBLE_CNF}" "${MTR}/${MPATH}/r"
    else
      cp "${POSSIBLE_CNF}" "${MTR}/${MPATH}/"
    fi
  fi
  cd ${MTR}
  if [ -d "${MTR}/var" ]; then rm -Rf "${MTR}/var"; fi
  if [ "${3}" != "SAN" ]; then
    ./mtr ${TEST}
  else
    ./mtra ${TEST}
  fi
  cd - >/dev/null
done < ${TEMP}

# b-style bug report: reproduce ~/b's JIRA-ready output (testcase, representative backtrace(s), Bug Detection
# Matrix, new-bug list) from the cores the MTR runs above produced. ~/b/findbug_new cannot be reused directly:
# they run from the BASEDIR (where MTR did not write var/), and these tarball basedirs are not startup.sh-prepped
# (no ./line, ./stack). Instead we drive ~/mariadb-qa's version_chk_helper.source, ~/t and stack.sh from each
# tested m*test dir, which is where MTR ran and where all three already locate MTR cores/logs correctly.
BR_MATRIX="$(mktemp)"; BR_CRASH="$(mktemp)"; BR_RAW="$(mktemp)"
while read LINE; do
  MTR=
  if [ -d "${LINE}/mariadb-test" ]; then MTR="${LINE}/mariadb-test";
  elif [ -d "${LINE}/mysql-test" ]; then MTR="${LINE}/mysql-test";
  else continue; fi
  STR="$(cd "${MTR}" && ~/t 2>/dev/null)"  # ~/t exits 0 only when it produced a UniqueID (crash/assert/SAN)
  UID_STR='No bug found'
  if [ $? -eq 0 ]; then
    STR="$(echo "${STR}" | grep -vEi 'no core file found|no relevant strings were found' | head -n1)"
    if [ -n "${STR}" ]; then
      UID_STR="${STR}"
      echo "${STR}" >> "${BR_RAW}"
      if ! grep -qF "${STR}" "${BR_CRASH}" 2>/dev/null; then  # First m*test dir per distinct signature (representative backtrace)
        printf '%s\t%s\n' "${STR}" "${MTR}" >> "${BR_CRASH}"
      fi
    fi
  fi
  # Bug Detection Matrix row (mirrors ~/mariadb-qa .../line, but sourced from the m*test dir)
  ( cd "${MTR}" && source "${HOME}/mariadb-qa/version_chk_helper.source" 2>/dev/null &&
    printf "%-3s %-6s %-4s %-7s %-41s %-30s\n" "${SVR}" "$(echo "${SERVER_VERSION}" | grep -o '[0-9]\+\.[0-9]\+')" "${BUILD_TYPE_SHORT}" "${BUILD_DATE_SHORT}" "${SOURCE_CODE_REV}" "${UID_STR}"
  ) >> "${BR_MATRIX}"
done < ${TEMP}

echo '-------------------- BUG REPORT (b-style) --------------------' | tee "${REPORT}"
echo '{code:sql}' | tee -a "${REPORT}"
grep -v --binary-files=text '^$' "${1}" | tee -a "${REPORT}"
echo -e '{code}\n' | tee -a "${REPORT}"
echo -e 'Leads to:\n' | tee -a "${REPORT}"
if [ -s "${BR_CRASH}" ]; then  # Representative backtrace: one per distinct signature, via stack.sh in the crashing m*test dir
  while IFS="$(printf '\t')" read -r SIG MTR; do
    ( cd "${MTR}" && bash "${HOME}/mariadb-qa/stack.sh" 2>/dev/null ) | tee -a "${REPORT}"
    echo '' | tee -a "${REPORT}"
  done < "${BR_CRASH}"
fi
echo '{noformat:title=Bug Detection Matrix}' | tee -a "${REPORT}"
printf "%-3s %-6s %-4s %-7s %-41s %-30s\n" "" "Rel" "o/d" "Build" "Commit" "UniqueID observed" | tee -a "${REPORT}"
sort -V "${BR_MATRIX}" | tee -a "${REPORT}"
echo '{noformat}' | tee -a "${REPORT}"
if [ -s "${BR_RAW}" ]; then
  echo '----- All NEW (not known yet) strings merged (for adding to ~/kb) -----' | tee -a "${REPORT}"
  sort -u "${BR_RAW}" | grep -v '^[[:space:]]*$' | tr '\n' '\0' | xargs -0 -I{} ~/kbs REVERSE "{}" | tee -a "${REPORT}"
fi
rm -f "${BR_MATRIX}" "${BR_CRASH}" "${BR_RAW}"
echo "Bug report written to ${REPORT}" | tee -a "${REPORT}"

rm -f ${TEMP}

echo '-------------- mtr_testrun.sh Results (core files, if any) --------------'
find . | grep -vE 'MDEV' | grep -E '/mysql-test/|/mariadb-test/' | grep '/var/log/.*/data/' | grep "${TEST}" | grep 'core' | sort -u
echo '-------------- mtr_testrun.sh Results (t results) --------------'
echo "rm /test/mtr_res.txt; ./gendirs.sh  | xargs -I{} echo 'cd {}; cd mysql-test 2>/dev/null; cd mariadb-test 2>/dev/null; t | tee /test/mtr_res.txt; cd /test;'; sort -u /test/mtr_res.txt; rm /test/mtr_res.txt;"
echo '-------------- mtr_testrun.sh Results (error log: add your search string and run query) --------------'
echo "SEARCH_STRING='your_search_string'; ./gendirs.sh ${3} | xargs -I{} echo \"grep --binary-files=text -H '\${SEARCH_STRING}' /test/{}/m*test/var/log/*err 2>/dev/null\" | tr '\\n' '\\0' | xargs -0 -I{} bash -c \"{}\""
if [ "${3}" == "SAN" ]; then
  echo '-------------- mtr_testrun.sh Results example for various SAN errors --------------'
  echo "SEARCH_STRING='SUMMARY: '; ./gendirs.sh ${3} | xargs -I{} echo \"grep --binary-files=text -H '\${SEARCH_STRING}' /test/{}/m*test/var/log/*err 2>/dev/null\" | tr '\\n' '\\0' | xargs -0 -I{} bash -c \"{}\""
fi
