#!/bin/bash
# Created by Roel Van de Paar, MariaDB
# Test a given MTR input file against all BASEDIRs as generated by gendirs.sh

if [ -z "${1}" ]; then echo
  echo "Expected usage:"
  echo "  ./mtr_testrun.sh {plain-text MTR testcase} {path} {gendirs.sh options}"
  echo "For example:"
  echo "  ./mtr_testrun.sh testcase.test main SAN"
  echo "This command will copy ./testcase.test into all *SAN BASEDIRs (as generated by ./gendirs.sh SAN) into mariadb-test/main (or mysql-test/main as applicable) and execute the testcase using MTR."
  echo "* Note: if {path} is empty, the main subdirectory will be used. If {gendirs.sh options} is empty, the default gendirs.sh output will be used which is currently all MD dbg+opt BASEDIRs (MS is filtered in-script)"
  echo "* Note: it is best to give the testcase name a non-generic filename, for example use 'MDEV-12345.test' as testname to avoid MTR selecting multiple tests"
  # For non-tarball builds, the directory is storage/spider/mysql-test/spider/bugfix/t
  echo "For spider testcases, use the following path value: plugin/spider/spider/bugfix/t, for example:"
  echo "  ./mtr_testrun.sh ./MDEV-12345.test plugin/spider/spider/bugfix/t"
  echo "* Note: if the texts 'source ../../t/test_init.inc' and 'Spider' are found in the testcase, the path above will automatically be used (and does not need to be passed)"
  exit 1
elif [ ! -r "${1}" ]; then echo
  echo "Assert: ${1} could not be read by this script"
  exit 1
elif [ ! -r ./gendirs.sh ]; then echo
  echo "Assert: ./gendirs.sh could be read by this script. It is required and usually present in /test"
  exit 1
fi

MPATH="${2}"
if [ -z "${MPATH}" ]; then
  MPATH="main"
  if grep -qi 'source ../../t/test_init.inc' "${1}"; then
    if grep -qi 'spider' "${1}"; then
      MPATH='plugin/spider/spider/bugfix/t'
    fi
  fi
fi

TEST="$(echo "${1}" | sed 's|\.test$||;s|\.mtr$||;s|^\./||')"

TEMP="$(mktemp)"
./gendirs.sh "${3}" | grep 'MD' > ${TEMP}

while read LINE; do
  MTR=
  if [ -d "${LINE}/mariadb-test" ]; then MTR="${LINE}/mariadb-test";
  elif [ -d "${LINE}/mysql-test" ]; then MTR="${LINE}/mysql-test";
  else echo "Error: no mariadb-test nor mysql-test was found for BASEDIR ${LINE}, skipping!"; continue; fi
  if [ ! -r "${MTR}/mtr" ]; then echo "Error: ${MTR}/mtr not found for BASEDIR ${LINE}, skipping!"; continue; fi
  if [ ! -d "${MTR}/${MPATH}" ]; then echo "Warning: path ${MTR}/${MPATH} not found, skipping!"; continue; fi
  cp "${1}" "${MTR}/${MPATH}/"
  cd ${MTR}
  if [ -d "${MTR}/var" ]; then rm -Rf "${MTR}/var"; fi
  ./mtr ${TEST}
  cd - >/dev/null
done < ${TEMP}
rm -f ${TEMP}

echo '-------------- mtr_testrun.sh Results --------------'
echo 'Searching core files...'
find . | grep -E '/mysql-test/|/mariadb-test/' | grep '/var/log/.*/data/' | grep "${TEST}" | grep 'core' | sort -u
