#!/bin/bash
cat results.list | grep '^MON' | sed 's|.*=||' | xargs -I{} echo "cd {}; ./my | sed \"s|^[0-9]\+ .||;s|^|{}|\"; cd -" > /tmp/myspecific.tmp && chmod +x /tmp/myspecific.tmp && /tmp/myspecific.tmp | grep -v "/data$" | xargs wc -l ;rm -f /tmp/myspecific.tmp
