#!/bin/bash
rm -f current-opt
if [ -r ./current-opt ]; then echo "Assert: current-opt exists after removal attempt!"; exit 1; fi
echo '#!/bin/bash' > current-opt
./allruns | grep "10.5.*opt" | grep -vE "MT|MONTY|SAN" | sed 's|:.*||' | tr '\n' '|' | sed 's|^|grep -E "|;s/|$/" current-opt | grep -vE "grep|exit|bin.*bash"\n/' >> current-opt
echo "exit 0" >> current-opt
~/ooo >> current-opt
chmod +x current-opt
./current-opt
