#!/bin/bash
# Created by Roel Van de Paar, MariaDB

MYEXTRA_OPT_PRE="$*"
MYEXTRA_OPT="$(echo "${MYEXTRA_OPT_PRE}" | sed 's|GAL||;s|SAN||;s|REPL||;s|[ \t]\+| |g')"

if [ "${1}" == "GAL" ]; then
  ./gendirs.sh GAL | xargs -I{} echo "cd {}; ./gal_start ${MYEXTRA_OPT}" | xargs -P50 -I{} bash -c "{}"
elif [ "${1}" == "SAN" ]; then
  ./gendirs.sh SAN | xargs -I{} echo "cd {}; ./start ${MYEXTRA_OPT}" | xargs -P50 -I{} bash -c "{}"
elif [ "${1}" == "MSAN" ]; then
  ./gendirs.sh MSAN | xargs -I{} echo "cd {}; ./start ${MYEXTRA_OPT}" | xargs -P50 -I{} bash -c "{}"
elif [ "${1}" == "REPL" ]; then
  ./gendirs.sh | xargs -I{} echo "cd {}; export SRNOCL=1; ./start_replication ${MYEXTRA_OPT}; cd ..; export SRNOCL=; export -n SRNOCL" | xargs -P50 -I{} bash -c "{}"
else
  ./gendirs.sh | xargs -I{} echo "cd {}; ./start ${MYEXTRA_OPT}" | xargs -P50 -I{} bash -c "{}"
fi

sync
