#!/bin/bash
# Created by Roel Van de Paar, MariaDB

SAN_MODE=0
SHORTER_STOP_TIME=25  # TODO: this can be improved

MYEXTRA_OPT="$*"
if [ "${1}" == "SAN" ]; then
   if [ -z "${TEXT}" ]; then   # Passed normally by ~/b and bug_report.sh script
    echo "Assert: TEXT is empty, use export TEXT= to set it!"
    exit 1
  fi
  SAN_MODE=1
  MYEXTRA_OPT="$(echo "${MYEXTRA_OPT}" | sed 's|SAN||')"
fi

rm -f test.result

if [ ! -r ./in.sql ]; then
  echo "./in.sql does not exist!"
  exit 1
fi

# Startup all server fresh (clean data dir) (as background processes; end handling done by ./all_all)
if [ ${SAN_MODE} -eq 1 ]; then
  ./all_all SAN ${MYEXTRA_OPT}
elif [ "${1}" == "GAL" ]; then
  ./all_all GAL ${MYEXTRA_OPT}
else
  ./all_all ${MYEXTRA_OPT}
fi
sync
rm -Rf MD*/data.PREV EMD*/data.PREV MS*/data.PREV  # Cleanup old data dirs for clean runs (after they were created (moved) by ./all scripts as started by ./all_all above

# Copy in.sql to all instances
if [ ${SAN_MODE} -eq 1 ]; then
  ./copy_in.sql_all SAN
elif [ "${1}" == "GAL" ]; then
  ./copy_in.sql_all GAL
else
  ./copy_in.sql_all
fi

# Run the test and stop the servers
if [ ${SAN_MODE} -eq 1 ]; then
  ./gendirs.sh SAN | xargs -I{} echo "cd {}; ./test; timeout -k${SHORTER_STOP_TIME} -s9 ${SHORTER_STOP_TIME}s ./stop; cd .." | xargs -P50 -I{} sh -c "{}"
elif [ "${1}" == "GAL" ]; then
  ./gendirs.sh GAL | xargs -I{} echo "cd {}; ./gal_test; timeout -k${SHORTER_STOP_TIME} -s9 ${SHORTER_STOP_TIME}s ./gal_stop; cd .." | xargs -P50 -I{} sh -c "{}"
else
  ./gendirs.sh | xargs -I{} echo "cd {}; ./test; timeout -k${SHORTER_STOP_TIME} -s9 ${SHORTER_STOP_TIME}s ./stop; cd .." | xargs -P50 -I{} sh -c "{}"
fi
sleep 13  # Give servers some time to properly shutdown. TODO: this can be improved

# Ensure servers are gone
sync
if [ ${SAN_MODE} -eq 1 ]; then
  ./kill_all SAN
elif [ "${1}" == "GAL" ]; then
  ./kill_all GAL
else
  ./kill_all
fi
sync

# Output results and save copy of reasy bug reporting (mariadb-qa/bug_report.sh)
if [ ${SAN_MODE} -eq 1 ]; then
  ./findbug+ SAN "${TEXT}" | tee test.results
elif [ "${1}" == "GAL" ]; then
  ./findbug+ GAL "${TEXT}" | tee test.results
else
  ./findbug+ "${TEXT}" | tee test.results
fi
