#!/bin/bash
grep --binary-files=text 'is aleady known and logged' */pquery-run.log | sed 's|.*bug: ||' | sort | uniq -c | sort | tac | sed 's|^[ ]\+||' | sed 's|\(^[0-9]\+ \)\(.*\)|\2: \1x|' | sed 's|.* ## ||'
