#!/bin/bash
# Created by Ramesh Sivaraman and Roel Van de Paar, MariaDB

USER="$(whoami)"

if [ ! -d /test/TESTCASES -o ! -d /data/NEWBUGS ]; then
  sudo mkdir -p /test /data /test/TESTCASES/ /data/NEWBUGS /data/tmp
  sudo chown -R ${USER}:${USER} /test
  sudo chown -R ${USER}:${USER} /data
  sudo chmod -R +rX /test
  sudo chmod -R +rX /data
fi

# Squirrel/AFL
if [ ! -d /home/${USER}/fuzzing/fuzzing_root/ ]; then
  mkdir -p /home/${USER}/fuzzing/fuzzing_root/ 
fi
ln -fs /home/${USER}/mariadb-qa/squirrel/afl_genstart_tmpfs_nodes /test/afl_genstart_tmpfs_nodes 2>&1
ln -fs /home/${USER}/mariadb-qa/squirrel/go /home/${USER}/fuzzing/fuzzing_root/go 2>&1
ln -fs /home/${USER}/mariadb-qa/squirrel/del_known_bugs /home/${USER}/fuzzing/del_known_bugs
ln -fs /home/${USER}/mariadb-qa/squirrel/stop_all_fuzzing /home/${USER}/fuzzing/stop_all_fuzzing
ln -fs /home/${USER}/mariadb-qa/squirrel/list_unique_bugs /home/${USER}/fuzzing/list_unique_bugs
ln -fs /home/${USER}/mariadb-qa/squirrel/full_report /home/${USER}/fuzzing/full_report
ln -fs /home/${USER}/mariadb-qa/squirrel/partial_report /home/${USER}/fuzzing/partial_report
ln -fs /home/${USER}/mariadb-qa/squirrel/find_uniqueid /home/${USER}/fuzzing/find_uniqueid
ln -fs /home/${USER}/mariadb-qa/squirrel/queue_stats /home/${USER}/fuzzing/queue_stats
ln -fs /home/${USER}/mariadb-qa/squirrel/process_testcases /home/${USER}/fuzzing/process_testcases
ln -fs /home/${USER}/mariadb-qa/squirrel/clean_queues /home/${USER}/fuzzing/clean_queues
ln -fs /home/${USER}/mariadb-qa/squirrel/stop_process_testcases /home/${USER}/fuzzing/stop_process_testcases
ln -fs /home/${USER}/mariadb-qa/squirrel/afl_genstart_tmpfs_nodes /home/${USER}/fuzzing/afl_genstart_tmpfs_nodes
# And basedir './afl' script is done by ~/start already, however it is copied to ~/fuzzing for editing convience ftm
ln -fs /home/${USER}/mariadb-qa/squirrel/afl /home/${USER}/fuzzing/afl

# Homedir scripts
rm -f ~/tcp ~/pge ~/pg ~/tr ~/tc ~/t ~/fc ~/mcl ~/s
ln -fs /home/${USER}/mariadb-qa/homedir_scripts/* /home/${USER}/ 2>&1
ln -fs /home/${USER}/mariadb-qa/testcase_prettify.sh /home/${USER}/tcp 2>&1
ln -fs /home/${USER}/mariadb-qa/pquery-goexp-patch.sh /home/${USER}/pge 2>&1
ln -fs /home/${USER}/mariadb-qa/pquery-goexp-patch.sh /home/${USER}/depge 2>&1
ln -fs /home/${USER}/mariadb-qa/pquery-go-expert.sh /home/${USER}/pg 2>&1
ln -fs /home/${USER}/mariadb-qa/pquery-todays-runs.sh /home/${USER}/tr 2>&1
ln -fs /home/${USER}/mariadb-qa/copy_testcases.sh /home/${USER}/tc 2>&1
ln -fs /home/${USER}/mariadb-qa/new_text_string.sh /home/${USER}/t 2>&1
ln -fs /home/${USER}/mariadb-qa/find_cause.sh /home/${USER}/fc 2>&1
ln -fs /home/${USER}/mariadb-qa/pquery-allsubdir-del-string.sh /home/${USER}/mcl 2>&1
ln -fs /home/${USER}/mariadb-qa/pquery-screen.sh /home/${USER}/s 2>&1
ln -fs /home/${USER}/mariadb-qa/san_text_string.sh /home/${USER}/st 2>&1

# Build scripts (mostly/mainly used from /test)
ln -fs /home/${USER}/mariadb-qa/mariadb-build-qa/* /test/ 2>&1
ln -fs /home/${USER}/mariadb-qa/mariadb-build-qa/* /data/ 2>&1
ln -fs /home/${USER}/mariadb-qa/mariadb-build-qa/current_runs_testcases /home/${USER}/crt 2>&1
rm -f /data/[odut][0-9]  # Remove changedir scripts (like '. ./d7' etc.) normally only used in /test

# Mass testcase scripts
ln -fs /home/${USER}/mariadb-qa/testcase-scripts/* /test/TESTCASES/ 2>&1
ln -fs /home/${USER}/mariadb-qa/newbugs/uniq_newbugs /test/TESTCASES/uniq_newbugs 2>&1

# Newbugs (new bugs found by reducer while reducing) & Fireworks (new bugs found by reducer in fireworks mode)
ln -fs /home/${USER}/mariadb-qa/newbugs/* /data/NEWBUGS/ 2>&1
ln -fs /home/${USER}/mariadb-qa/mariadb-build-qa/clean_newbugs /data/NEWBUGS/clean_newbugs 2>&1

# Link ~/BUGS to ~/mariadb-qa/BUGS for ease-of-access
if [ ! -d /home/${USER}/BUGS ]; then
  ln -fs /home/${USER}/mariadb-qa/BUGS /home/${USER}/BUGS 2>&1
fi

# Add any bugs not commited yet
cd /home/${USER}/mariadb-qa/BUGS
git add *

# Create REGEX_EXCLUDE if it does not exist yet, adding some common defaults
if [ ! -r /test/REGEX_EXCLUDE ]; then 
  echo 'MDEV|VALGRIND' > /test/REGEX_EXCLUDE
fi

# Protect homedir links which are easily overwritten by mistake
chmod -w ~/b ~/c ~/i ~/m ~/o ~/p ~/r

echo 'Done!'
exit 0
