#!/bin/bash
# Created by Roel Van de Paar, Percona LLC
# USAGE TIP: cd /test && ./gendirs.sh | sed 's|^|/test/|' | xargs -P40 -I{} ~/mariadb-qa/mtr_to_sql_v2.sh {} & fg

if [ -z "${1}" ]; then
  echo "This script expects the MySQL (or other vendor) base directory to be passed."
  echo "Run this script for/on both the MYSQL source tree AND the binary build (basedir) tree and merge the resulting files!"
  exit 1
elif [ ! -d "${1}" ]; then
  echo "Assert: ${1} is not a directory"
  exit 1
else
  cd "${1}"
fi

# Information
# - Originally, there were two versions of SQL generation, and they could be selected interdependently by passing an option to this script. This new version instead uses both approaches in sequence - i.e. it first adds the SQL as generated by approach #1 (ref below) to the final SQL file, and then proceeds to add the SQL as generated by approach #2.
#   This results in a larger, but more varied (and thus better), final SQL file/grammar. The new version also re-parses the generated SQL and adds more storage engine variations.
# - This script no longer creates any RQG grammars; RQG use was deprecated in favor of pquery. For a historical still-working no-longer-maintained version, see mtr_to_sql_RQG.sh
# - Current Filter list
#   - Not scanning for "^REVOKE " commands as these drop access and this hinders CLI/pquery testing. However, REVOKE may work for RQG/yy (TBD)
#   - egrep -vi Inline filters
#     - 'checksum.*strict'           - This causes false (i.e. no bug) corruption bugs. Ref http://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_checksum_algorithm
# - Ideas for further improvement
#   - Scan original MTR file for multi-line statements and reconstruct (tr '\n' ' ' for example) to avoid half-statements ending up in resulting file

# Internal variables
RANDOM=$(date +%s%N | cut -b10-19 | sed 's|^0+||')  # RANDOM: Random entropy pool init
TEMP_SQL=${FINAL_SQL}.tmp
DIRECTORY="${1}"  # Should contain mysql-test directory as a first level subdirectory, see TESTS_PATH
TESTS_PATH=$(echo ${DIRECTORY} | sed 's|$|/mysql-test/|;s|//|/|g')
RANDOMD=$(echo $RANDOM$RANDOM$RANDOM | sed 's/..\(......\).*/\1/')
FINAL_SQL=/tmp/mtr_to_sql${RANDOMD}.sql  # Result SQL grammar (i.e. file name for output generated by this script)

echoit(){
  echo "[$(date +'%T')] $1"
}

if [ ! -r ${TESTS_PATH}/t/1st.test -a ! -r ${TESTS_PATH}/main/kill.test ]; then
  if [ ! -r ${TESTS_PATH}/mysql-test/t/1st.test -a ! -r ${TESTS_PATH}/mysql-test/main/kill.test ]; then
    echoit "Assert: this script cannot find any tests in ${TESTS_PATH}"
    echoit "You may want to check the TESTS_PATH setting at the top of this script (currently set to '${TESTS_PATH}')"
    #exit 1
  else
    echoit "Found tests located at ${TESTS_PATH}/mysql-test..."
    TESTS_PATH="${TESTS_PATH}/mysql-test"
  fi
else
  echoit "Found tests located at ${TESTS_PATH}..."
fi

# Setup
rm -f ${TEMP_SQL};  if [ -r ${TEMP_SQL} ]; then echoit "Assert: this script tried to remove ${TEMP_SQL}, but the file is still there afterwards."; exit 1; fi
rm -f ${FINAL_SQL}; if [ -r ${FINAL_SQL} ]; then echoit "Assert: this script tried to remove ${FINAL_SQL}, but the file is still there afterwards."; exit 1; fi
touch ${TEMP_SQL};  if [ ! -r ${TEMP_SQL} ]; then echoit "Assert: this script tried to create ${TEMP_SQL}, but the file was not there afterwards."; exit 1; fi
touch ${FINAL_SQL}; if [ ! -r ${FINAL_SQL} ]; then echoit "Assert: this script tried to create ${FINAL_SQL}, but the file was not there afterwards."; exit 1; fi
echoit "Generating SQL grammar for pquery..."
echoit "* Note this script takes ~11 minutes on a very high end (i7/SSD/16GB) machine, and 1h+ on a high end Google cloud instance..."
echoit "Output file: ${FINAL_SQL}"

# Stage 1: Approach #1
echoit "> Stage 1: Generating SQL with approach #1..."
egrep --binary-files=text -ih "^SELECT |^INSERT |^UPDATE |^DROP |^CREATE |^RENAME |^TRUNCATE |^REPLACE |^START |^SAVEPOINT |^ROLLBACK |^LOCK |^UNLOCK|^XA |^PURGE |^RESET |^SHOW |^CHANGE |^START |^STOP |^PREPARE |^EXECUTE |^DEALLOCATE |^BEGIN |^DECLARE |^FETCH |^CASE |^IF |^ITERATE |^LEAVE |^LOOP |^REPEAT |^RETURN |^WHILE |^CLOSE |^GET |^RESIGNAL |^SIGNAL |^EXPLAIN |^DESCRIBE |^HELP |^USE |^GRANT |^ANALYZE |^CHECK |^CHECKSUM |^OPTIMIZE |^REPAIR |^INSTALL |^UNINSTALL |^BINLOG |^CACHE |^FLUSH |^LOAD |^CALL |^DELETE |^DO |^HANDLER |^LOAD DATA |^LOAD XML |^ALTER |^SET " ${TESTS_PATH}/*/*.test ${TESTS_PATH}/*/*/*.test ${TESTS_PATH}/*/*/*/*.test ${TESTS_PATH}/*/*/*/*/*.test ${TESTS_PATH}/*/*/*/*/*/*.test ${TESTS_PATH}/*/*/*/*/*/*/*.test ${DIRECTORY}/*/*/*.inc ${DIRECTORY}/*/*/*/*.inc ${DIRECTORY}*/*/*/*/*.inc ${DIRECTORY}/*/*/*/*/*/*.inc ${DIRECTORY}/plugin/*/*/*/*.test ${DIRECTORY}/plugin/*/*/*/*/*.test 2>/dev/null | \
 egrep --binary-files=text -vi "Is a directory" | \
 grep --binary-files=text -viE "innodb_fil_make_page_dirty_debug|innodb_trx_rseg_n_slots_debug|innodb_spin_wait_delay|innodb_replication_delay|checksum.*strict|restart_server_args|json_binary::parse_binary|\-\-error|\-\-let|\-\-enable|\-\-disable|\-\-de|\-\-host|\-\-connection|\-\-help|\-\-source|\-\-eval|\-\-echo|\-\-die|\-\-replace|\-\-skip|^print|delete[ \t]\+from[ \t]\+mysql.user;|drop[ \t]\+table[ \t]\+mysql.user;|delete[ \t]\+from[ \t]\+mysql.user[ \t]\+where[ \t]\+user='root'|[updatedelete]\+.*where[ \t]\+user='root'|default_password_lifetime|innodb[-_]track[-_]redo[-_]log[-_]now|innodb[-_]log[-_]checkpoint[-_]now|innodb[-_]purge[-_]stop[-_]now|yfos|^$|mtr.add_suppression|release|dbug|debug[ \t]*=|kill|shutdown|^let" | \
 sed 's|SLEEP[ \t]*([\.0-9]\+)|SLEEP(0.01)|gi;s/.*[^;]$//;s/$/ ;;;/;s/[ \t;]*$/;/' | grep -vE '^[ ;]*$' >> ${TEMP_SQL}

# Approach #2
# First two sed lines (change | and $$ to ; for Stored Procedures) are significant changes, more review/testing later may show better solutions
# DEPRECATED: Tabs are filtered, as they are highly likely CLI result output.  sed 's|\t|FILTERTHIS|' | \
echoit "> Stage 2: Generating SQL with approach #2..."
cat ${TESTS_PATH}/*/*.test ${TESTS_PATH}/*/*/*.test ${TESTS_PATH}/*/*/*/*.test ${TESTS_PATH}/*/*/*/*/*.test ${TESTS_PATH}/*/*/*/*/*/*.test ${TESTS_PATH}/*/*/*/*/*/*/*.test ${DIRECTORY}/*/*/*.inc ${DIRECTORY}/*/*/*/*.inc ${DIRECTORY}*/*/*/*/*.inc ${DIRECTORY}/*/*/*/*/*/*.inc ${DIRECTORY}/plugin/*/*/*/*.test ${DIRECTORY}/plugin/*/*/*/*/*.test 2>/dev/null | \
 sed 's/|/;\n/g;s/$$/;\n/g;s|^ERROR |FILTERTHIS|i;s|^Warning|FILTERTHIS|i;s|^Note|FILTERTHIS|i;s|^Got one of the listed errors|FILTERTHIS|i;s|^variable_value|FILTERTHIS|i;s|^Antelope|FILTERTHIS|i;s|^Barracuda|FILTERTHIS|i;s|^count|FILTERTHIS|i;s|^source.*include.*inc|FILTERTHIS|i;s|^#|FILTERTHIS|;s|^\-\-|FILTERTHIS|;s|^@|FILTERTHIS|;s|^{|FILTERTHIS|;s|^\*|FILTERTHIS|;s|^"|FILTERTHIS|;s|ENGINE[= \t]*NDB|ENGINE=INNODB|gi;s|^.$|FILTERTHIS|;s|^..$|FILTERTHIS|;s|^...$|FILTERTHIS|;s|^[-0-9]*$|FILTERTHIS|;s|^c[0-9]*$|FILTERTHIS|;s|^t[0-9]*$|FILTERTHIS|' | \
 grep --binary-files=text -vE "FILTERTHIS|^$" | tr '\n' ' ' | sed 's|;|;\n|g;s|//|//\n|g;s/END\([|]\+\)/END\1\n/g;' | \
 grep --binary-files=text -viE "innodb[-_]fil[-_]make[-_]page[-_]dirty[-_]debug|innodb_trx_rseg_n_slots_debug|innodb_spin_wait_delay|innodb_replication_delay|checksum.*strict|default_password_lifetime|restart_server_args|restart_server_args|json_binary::parse_binary|\-\-error|\-\-let|\-\-enable|\-\-echo|\-\-die|\-\-replace|\-\-skip|^print|delete[ \t]\+from[ \t]\+mysql.user;|drop[ \t]\+table[ \t]\+mysql.user;|delete[ \t]\+from[ \t]\+mysql.user[ \t]\+where[ \t]\+user='root'|[updatedelete]\+.*where[ \t]\+user='root'|default_password_lifetime|yfos|restart_server_args|json_binary::parse_binary|\-\-error|\-\-let|\-\-enable|\-\-disable|\-\-de|\-\-host|\-\-connection|\-\-help|\-\-source|\-\-eval|\-\-echo|\-\-die|\-\-replace|\-\-skip|^print|^Ob%&0Z_|^E/TB/]o|^no cipher request crashed|^[ \t]*DELIMITER|^[ \t]*KILL|^[ \t]*REVOKE|^[ \t]*[<>{}()\.\@\*\+\^\#\!\\\/\'\`\"\;\:\~\$\%\&\|\+\=0-9]|\\\q|\\\r|\\\u|^[ \t]*.[ \t]*$|^[ \t]*..[ \t]*$|^[ \t]*...[ \t]*$|^[ \t]*\-\-|^[ \t]*while.*let|^[ \t]*let|^[ \t]*while.*connect|^[ \t]*connect|^[ \t]*while.*disconnect|^[ \t]*disconnect|^[ \t]*while.*eval|^[ \t]*eval|^[ \t]*while.*find|^[ \t]*find|^[ \t]*while.*exit|^[ \t]*exit|^[ \t]*while.*send|^[ \t]*send|^[ \t]*file_exists|^[ \t]*enable_info|^[# \t]$|^#|mtr.add_suppression|release|dbug|debug[ \t]*=|kill|shutdown|^let" | \
 sed 's/$/ ;;;/;s/[ \t;]\+$/;/;s|^[ \t]\+||;s|[ \t]\+| |g;s/^[|]\+ //;s///g;s|end//;|end //;|gi;s|[ \t]\+t[0-9]\+[ \t]\+| t1 |gi;s|[ \t]\+m[0-9]\+[ \t]\+| t1 |gi;s|mysqltest[\.0-9]*@|user@|gi;s|mysqltest[\.0-9]*||gi;s|user@|mysqltest@|gi;s|[ \t]\+t[0-9 \t]\+;| t1;|gi;s|[ \t]\+m[0-9 \t]\+;| t1;|gi;s|mysqltest[\.0-9]*@|user@|gi;s|user@|mysqltest@|gi;s| .*mysqltest.*@| mysqltest@|gi;s| test.[a-z]\+[0-9]\+[( ]\+| t1 |gi;s| INTO[ \t]*[a-z]\+[0-9]\+| INTO t1 |gi;s| TABLE[ \t]*[a-z]\+[0-9]\+\([;( ]\+\)| TABLE t1\1|gi;s| PROCEDURE[ \t]*[psroc_-]\+[0-9]*[( ]\+| PROCEDURE p1(|gi;s| FROM[ \t]*[a-z]\+[0-9]\+| FROM t1 |gi;s|DROP PROCEDURE IF EXISTS .*;|DROP PROCEDURE IF EXISTS p1;|gi;s|CREATE PROCEDURE.*BEGIN END;|CREATE PROCEDURE p1() BEGIN END;|gi;s|^USE .*|USE test;|gi;s|^CREATE[ \t]\+DATABASE[ \t]\+.*|CREATE DATABASE test;|gi;s|^DROP[ \t]\+DATABASE[ \t]\+.*|DROP DATABASE test;|gi;s|SLEEP[ \t]*([\.0-9]\+)|SLEEP(0.01)|gi;s|SLEEP[ \t]*([\.0-9]\+)|SLEEP(0.01)|gi' | grep -vE '^[ ;]*$' >> ${TEMP_SQL}

# Grammar variations
echoit "> Stage 3: Adding grammar variations..."
cat ${TEMP_SQL} >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*InnoDB"       | sed 's|InnoDB|Aria|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*InnoDB"       | sed 's|InnoDB|MyISAM|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*InnoDB"       | sed 's|InnoDB|MEMORY|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*InnoDB"       | sed 's|InnoDB|SEQUENCE|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*InnoDB"       | sed 's|InnoDB|RocksDB|gi'             >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*InnoDB"       | sed 's|InnoDB|TokuDB|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MyISAM"       | sed 's|MyISAM|Aria|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MyISAM"       | sed 's|MyISAM|InnoDB|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MyISAM"       | sed 's|MyISAM|MEMORY|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MyISAM"       | sed 's|MyISAM|SEQUENCE|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MyISAM"       | sed 's|MyISAM|RocksDB|gi'             >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MyISAM"       | sed 's|MyISAM|TokuDB|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MEMORY"       | sed 's|MEMORY|Aria|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MEMORY"       | sed 's|MEMORY|MyISAM|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MEMORY"       | sed 's|MEMORY|InnoDB|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MEMORY"       | sed 's|MEMORY|SEQUENCE|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MEMORY"       | sed 's|MEMORY|RocksDB|gi'             >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MEMORY"       | sed 's|MEMORY|TokuDB|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|Aria|gi'                   >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|MyISAM|gi'                 >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|InnoDB|gi'                 >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|MEMORY|gi'                 >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|SEQUENCE|gi'               >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|RocksDB|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*CSV"          | sed 's|CSV|TokuDB|gi'                 >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Aria"         | sed 's|Aria|MyISAM|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Aria"         | sed 's|Aria|InnoDB|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Aria"         | sed 's|Aria|MEMORY|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Aria"         | sed 's|Aria|SEQUENCE|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Aria"         | sed 's|Aria|RocksDB|gi'               >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Aria"         | sed 's|Aria|TokuDB|gi'                >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*SEQUENCE"     | sed 's|SEQUENCE|Aria|gi'              >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*SEQUENCE"     | sed 's|SEQUENCE|MyISAM|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*SEQUENCE"     | sed 's|SEQUENCE|InnoDB|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*SEQUENCE"     | sed 's|SEQUENCE|MEMORY|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*SEQUENCE"     | sed 's|SEQUENCE|RocksDB|gi'           >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*SEQUENCE"     | sed 's|SEQUENCE|TokuDB|gi'            >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=Aria;|gi'      >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=MyISAM;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=InnoDB;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=MEMORY;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=SEQUENCE;|gi'  >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=RocksDB;|gi'   >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*MRG_MyISAM"   | sed 's|ENGINE.*|ENGINE=TokuDB;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=Aria;|gi'      >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=MyISAM;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=InnoDB;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=MEMORY;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=SEQUENCE;|gi'  >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=RocksDB;|gi'   >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "ENGINE.*Merge.*UNION" | sed 's|ENGINE.*|ENGINE=TokuDB;|gi'    >> ${FINAL_SQL}
cat ${TEMP_SQL} | grep --binary-files=text -i "DROP TABLE t1" | head -n 3000 >> ${FINAL_SQL}   # Ensure plenty of DROP TABLE t1
cat ${TEMP_SQL} | grep --binary-files=text -i "DROP TABLE t1" | head -n 3000 | sed 's|DROP TABLE t1|DROP VIEW v1|gi' >> ${FINAL_SQL} # Ensure plenty of DROP VIEW v1
sed -i "s|\(CREATE.*VIEW.*\)t1\(.*\)|\1v1\2|gi" ${FINAL_SQL}  # Avoid views with name t1
sed -i "s|IDENTIFIED[ \t]*BY[ \t]*[PASSWORD]*[ \t]*[^ ,;#/]\+\([ ,;#/]\)|\1|g" ${FINAL_SQL}  # Avoids 'IDENTIFIED BY [PASSWORD]' clauses which may lock out root with statements like 'GRANT INSERT ON *.* TO CURRENT_USER() IDENTIFIED BY 'somepwd';'

# Shuffle final grammar
echoit "> Stage 4: Shuffling final grammar..."
rm -f ${TEMP_SQL}; if [ -r ${TEMP_SQL} ]; then echoit "Assert: this script tried to remove ${TEMP_SQL}, but the file is still there afterwards."; exit 1; fi
mv ${FINAL_SQL} ${TEMP_SQL}; if [ ! -r ${TEMP_SQL} ]; then echoit "Assert: this script tried to mv ${FINAL_SQL} ${TEMP_SQL}, but the ${TEMP_SQL} file was not there afterwards."; exit 1; fi; if [ -r ${FINAL_SQL} ]; then echoit "Assert: this script tried to mv ${FINAL_SQL} ${TEMP_SQL}, but the ${FINAL_SQL} file is still there afterwards."; exit 1; fi
shuf --random-source=/dev/urandom ${TEMP_SQL} >> ${FINAL_SQL}
rm -f ${TEMP_SQL}; if [ -r ${TEMP_SQL} ]; then echoit "Assert: this script tried to remove ${TEMP_SQL}, but the file is still there afterwards."; exit 1; fi

echoit "Done! Generated ${FINAL_SQL} ($(wc -l ${FINAL_SQL} | awk '{print $1}' | tr -d '\n') lines) for use with pquery/pquery-run.sh"
