#!/bin/bash
# Created by Roel Van de Paar, Percona LLC
# Improved by Ramesh Sivaraman, Percona LLC
# Improved by Roel Van de Paar, MariaDB
set +H

SCRIPT_PWD=$(dirname $(readlink -f "${0}"))
TRIAL=$(echo "${1}" | sed 's|_val||' | sed 's|[ \t]*||g')  # _val: for Valgrind bugs (reducer_val{trial}.sh generated by pquery-prep-red.sh)

delete_trial(){
  if [[ $MDG -eq 1 ]];then
    rm -Rf ./${TRIAL_DIR} > /dev/null 2>&1
    if [ -z "${MDG_NODE}" ]; then
      rm -f ./reducer${TRIAL}-*.sh > /dev/null 2>&1
    else
      rm -f ./reducer${TRIAL}-${MDG_NODE}.sh > /dev/null 2>&1
      rm -Rf ./${MDG_TMP_DIR} > /dev/null 2>&1
    fi
    echo "- pquery MDG trial #${TRIAL_DIR} and all related files wiped"
    if  [[ $(ls -d ${TRIAL}/node*/ 2>/dev/null | wc -l) -lt 1 ]]   ; then
      rm -Rf ./${TRIAL}
    fi
  else
    rm -Rf ./${TRIAL} > /dev/null 2>&1
    rm -f ./reducer${TRIAL}.sh > /dev/null 2>&1
    rm -f ./base_reducer${TRIAL}.sh 2>&1
    rm -f ./feature_reducer${TRIAL}.sh 2>&1
    rm -f ./find${TRIAL} 2>&1
    rm -f ./quick_*reducer${TRIAL}.sh > /dev/null 2>&1
    rm -f ./reducer_val${TRIAL}.sh > /dev/null 2>&1
    rm -f ./quick_*reducer_val${TRIAL}.sh > /dev/null 2>&1
    rm -f ./reducer${TRIAL}-*.sh > /dev/null 2>&1
    rm -f ./quick_*reducer${TRIAL}-*.sh > /dev/null 2>&1
    rm -f ./${TRIAL}_bundle > /dev/null 2>&1
    rm -f ./${TRIAL}_bundle.tar.gz > /dev/null 2>&1
    echo "- pquery trial #${TRIAL} and all related files wiped"
  fi
}

# Check if this is a MariaDB Galera Cluster run
MDG=0
if grep -qi 'MDG Mode:.*TRUE' ./pquery-run.log 2>/dev/null; then
  MDG=1
fi

MDG_NODE=
TRIAL_DIR=
if [[ ${MDG} -eq 1 ]];then
  TRIAL_DIR="$(echo $TRIAL | sed 's|-|/node|')"  # Note that TRIAL_DIR can be a root trial dir i.e. ./100 for trial #100 (invoked as ~/dt 100) or a node subdirectory like ./100/node1 for node 1 in trial #100 (invoked as ~/dt 100-1)
  if [[ "${TRIAL}" == *"-"* ]]; then
    MDG_TMP_DIR="$(echo $TRIAL_DIR | sed 's|/node|/tmp|')"
    MDG_NODE="$(echo $TRIAL | cut -d'-' -f2)"
    TRIAL="$(echo $TRIAL | cut -d'-' -f1)"
  fi
fi

if [ -z "${TRIAL}" ]; then
  echo "This script deletes a given pquery trial completely. Execute this script from within the pquery workdir"
  echo "Example: to delete trial 10 (./10), execute as: ./delete_single_trial.sh 10"
  exit 1
elif [ "$(echo ${TRIAL} | sed 's|[0-9]*||')" != "" ]; then
  echo "Trial number should be a numeric value and isn't (value passed to this script which is not considered numeric: '${TRIAL}')"
  exit 1
elif [ ! -d ./${TRIAL} ]; then
  echo "This script deletes a given pquery trial completely. Execute this script from within the pquery workdir"
  echo "Error: trial number '${TRIAL}' was passed as an option to this script. However, no trial ${TRIAL} directory (./${TRIAL}) exists!"
  echo "Will still attempt to delete all related remaining files, if any"
fi

# Delete trial directory, provided it does not contain a significant/major error of interest. Scan first.
# The REGEX_ERRORS_* application and the TEXT-cleanup pipeline live in error_log_scan.sh (single source of truth, shared with pquery-run.sh / pquery-prep-red.sh / pquery-results.sh).
if [[ "${MDG}" -eq 1 ]]; then
  if [ -z "${MDG_NODE}" ]; then
    ERROR_LOG="./${TRIAL_DIR}/node*.err"
  else
    ERROR_LOG="./${TRIAL_DIR}/node${MDG_NODE}.err"
  fi
else
  ERROR_LOG="./${TRIAL}/log/*.err"
fi
if [ ! -z "${ERROR_LOG}" ]; then  # Do not use -r as it will not work if both master.err and slave.err are present, for example
  ERRORS="$(${SCRIPT_PWD}/error_log_scan.sh errors ${ERROR_LOG})"
  ERRORS_LAST_LINE="$(${SCRIPT_PWD}/error_log_scan.sh lastline ${ERROR_LOG})"
  if [ "${2}" = "CHECK" ]; then  # CHECK mode: non-destructive in every branch. Emit cleaned content from any significant error log entries so pquery-prep-red.sh can set the reducer TEXT when MYBUG's UniqueID is a known-still-open bug (see pquery-prep-red.sh's FINDBUG block).
    ${SCRIPT_PWD}/error_log_scan.sh clean ${ERROR_LOG}
  elif [ -z "${ERRORS}" -a -z "${ERRORS_LAST_LINE}" ]; then
    delete_trial  # No significant errors: safe to delete
  elif [ -z "${ERRORS}" -a ! -z "${ERRORS_LAST_LINE}" -a ! -z "$(tail -n1 ${ERROR_LOG} 2>/dev/null | grep --binary-files=text -o 'Assertion .* failed' 2>/dev/null | sed "s|'|.|g" | sed 's|"|.|g' | sed "s|^Assertion .||;s|. failed$||" | xargs -I{} grep --binary-files=text -i "{}" ${SCRIPT_PWD}/known_bugs.strings 2>/dev/null)" ]; then  # No other errors and last-line assertion exactly matches an already-known assertion in the known bugs file: safe to delete
    delete_trial
  else  # There are uknown issues remaining: do not delete unless an overwrite "1" is passed as an option to the script
    if [ "${2}" != "1" ]; then
      if [ "${CA_ACTIVE}" != "1" ]; then  # Supress many messages when 'ca' (/data/clean_all) is used
        echo "Not deleting trial ${TRIAL} (Dir: ${PWD}) as one or more significant error(s) ($( echo "$(if [ ! -z "${ERRORS}" ]; then echo "\"${ERRORS}\""; fi; if [ ! -z "${ERRORS_LAST_LINE}" ]; then echo "\"${ERRORS_LAST_LINE}\""; fi;)" | sed 's|^[ ]+||;s|[ ]\+$||')) was/were found in the error log! To delete it anyways please add a '1' as second option to this script (pquery-del-trial.sh)!"
      fi
    else
      delete_trial
    fi
  fi
else
  if [ "${2}" != "NO_WARNINGS" ]; then
    if [ "${2}" != "CHECK" ]; then
      echo "Warning: ${ERROR_LOG} not found, proceeding to delete all other trial files"
    fi
  fi
  delete_trial
fi
