INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE USER spider@localhost IDENTIFIED BY '';
GRANT ALL ON test.* TO spider@localhost;
FLUSH PRIVILEGES;
CREATE server srv FOREIGN DATA wrapper mysql options (socket '../socket.sock', DATABASE 'test', USER 'spider', PASSWORD '');
CREATE TABLE t (c INT PRIMARY KEY,c1 BLOB, c2 TEXT) ENGINE=InnoDB;
CREATE TABLE tm (c INT KEY,c1 BLOB, c2 TEXT) ENGINE=MyISAM;
INSERT INTO t VALUES (0,NULL,'a'),(1,'B','b'),(2,0,'c');
INSERT INTO tm VALUES (0,NULL,'a'),(1,'B','b'),(2,0,'c');
SET GLOBAL spider_same_server_link=ON;
CREATE TABLE t1 (c INT PRIMARY KEY,c1 BLOB, c2 TEXT) ENGINE=Spider COMMENT='wrapper "mysql", srv "srv", TABLE "t"';
CREATE TABLE t2 (c INT KEY,c1 BLOB, c2 TEXT) ENGINE=Spider COMMENT='wrapper "mysql", srv "srv", TABLE "tm"';
INSERT INTO t VALUES (10,NULL,'a'),(11,'B','b'),(12,0,'c');
INSERT INTO tm VALUES (10,NULL,'a'),(11,'B','b'),(12,0,'c');
SHOW CREATE TABLE t;
SHOW CREATE TABLE tm;
SHOW CREATE TABLE t1;
SHOW CREATE TABLE t2;
INSERT INTO t1 VALUES (3,NULL,'a'),(4,'B','b'),(5,0,'c');
INSERT INTO t2 VALUES (20,NULL,'a'),(22,'B','b'),(23,0,'c');
DELETE FROM t WHERE c=2;
DELETE FROM tm WHERE c=2;
DELETE FROM t2 WHERE c=2;
SELECT * FROM t;
SELECT * FROM t1;
SELECT * FROM t2;
