#!/bin/bash
RANDOM=$(date +%s%N | cut -b10-19 | sed 's|^[0]\+||')  # Random entropy init
RANDF=$(echo $RANDOM$RANDOM$RANDOM$RANDOM | sed 's|.\(..........\).*|\1|')  # Random 10 digits filenr

BIN=
if [ -r ./bin/mysqld ]; then BIN='./bin/mysqld'; fi
if [ -z "${BIN}" -a -r ../mysqld/mysqld ]; then BIN='../mysqld/mysqld'; fi
if [ -z "${BIN}" ]; then echo "Assert: bin/mysqld not found!" exit 1; fi

SOURCE_CODE_REV="$(grep -om1 --binary-files=text "Source control revision id for MariaDB source code[^ ]\+" ${BIN} 2>/dev/null | tr -d '\0' | sed 's|.*source code||;s|Version||;s|version_source_revision||')"
if echo "${PWD}" | grep -q EMD ; then
  SERVER_VERSION="$(${BIN}  --version | grep -om1 --binary-files=text '[0-9\.]\+-[0-9]-MariaDB' | sed 's|-MariaDB||')"
else
  SERVER_VERSION="$(${BIN} --version | grep -om1 --binary-files=text '[0-9\.]\+-MariaDB' | sed 's|-MariaDB||')"
fi

BUILD_TYPE=
LAST_THREE="$(echo "${PWD}" | sed 's|.*\(...\)$|\1|')"
MDG=0
if [ ! -z "$(ls --color=never ./node*/node*.err 2>/dev/null)" ]; then
  MDG=1
fi
if [ "${LAST_THREE}" != "dbg" -a "${LAST_THREE}" != "opt" ]; then  # in-trial ./stack call
  if [ "${MDG}" -eq 1 ]; then
    LAST_THREE="$(grep --binary-files=text -Eo "\-dbg|\-opt" ./node*/node*.err 2>/dev/null | head -n1 | sed 's|\-||')"
  else
    LAST_THREE="$(grep --binary-files=text -Eo "\-dbg|\-opt" ./log/master.err 2>/dev/null | head -n1 | sed 's|\-||')"
  fi
fi
if [ "${LAST_THREE}" == "opt" ]; then BUILD_TYPE=" (Optimized)"; fi
if [ "${LAST_THREE}" == "dbg" ]; then BUILD_TYPE=" (Debug)"; fi

if [ "${MDG}" -eq 1 ]; then
  CORE_COUNT=$(ls --color=never node*/*core* 2>/dev/null | wc -l)
else
  CORE_COUNT=$(ls --color=never data/*core* 2>/dev/null | wc -l)
fi
if [ ${CORE_COUNT} -eq 0 ]; then
  echo "INFO: no cores found at data/*core* nor at node*/*core*"
  exit 1
elif [ ${CORE_COUNT} -gt 1 ]; then
  echo "Assert: too many (${CORE_COUNT}) cores found at data/*core* and/or node*/*core*, this should not happen (as ./all_no_cl was used which should have created a clean data directory, or the same for the matching Galera scripts)"
  exit 1
fi

if [ "${MDG}" -eq 1 ]; then
  ERROR_LOG=$(ls --color=never ./node*/node*.err 2>/dev/null | head -n1)  # This is not perfect in case node2 or node3 crashes TODO
else
  ERROR_LOG=$(ls --color=never ./log/master.err 2>/dev/null | head -n1)
fi
if [ ! -z "${ERROR_LOG}" ]; then
  ASSERT="$(grep --binary-files=text -m1 'Assertion.*failed.$' ${ERROR_LOG} | head -n1)"
  if [ -z "${ASSERT}" ]; then
    ASSERT="$(grep --binary-files=text -m1 'Failing assertion:' ${ERROR_LOG} | head -n1)"
  fi
  if [ ! -z "${ASSERT}" ]; then
    echo -e "{noformat:title=${SERVER_VERSION} ${SOURCE_CODE_REV}${BUILD_TYPE}}\n${ASSERT}\n{noformat}\n"
  fi
fi

LATEST_CORE=
if [ "${MDG}" -eq 1 ]; then
  LATEST_CORE="$(ls -t --color=never node*/*core* 2>/dev/null)"
else
  LATEST_CORE="$(ls -t --color=never data/*core* 2>/dev/null)"
fi

gdb -q ${BIN} ${LATEST_CORE} >/tmp/${RANDF}.gdba 2>&1 << EOF
 set pagination off
 set print pretty on
 set print frame-arguments all
 bt
 quit
EOF

if [ -r /tmp/${RANDF}.gdba ]; then
  echo "{noformat:title=${SERVER_VERSION} ${SOURCE_CODE_REV}${BUILD_TYPE}}"
  grep --binary-files=text -A999 'Core was generated by' /tmp/${RANDF}.gdba | grep --binary-files=text -v '^(gdb)[ \t]*$' | grep --binary-files=text -v '^[0-9]\+.*No such file or directory.$' | sed 's|(gdb) (gdb) |(gdb) bt\n|' | sed 's|(gdb) (gdb) ||'
  rm -f /tmp/${RANDF}.gdba
else
  echo "Assert: /tmp/${RANDF}.gdba not found after gdb was called"
  exit 1
fi
echo '{noformat}'
