USE test;
CREATE TABLE t(c1 INT,KEY(c1))ENGINE=InnoDB;
INSERT INTO t VALUES(55997),(3942);
ALTER TABLE t ENGINE=Aria;
SET GLOBAL aria_encrypt_tables=1;
REPAIR TABLE t USE_FRM;

USE test;
SET GLOBAL table_open_cache=FALSE;
SET default_storage_engine=Aria;
SET GLOBAL aria_encrypt_tables=ON;
CREATE TABLE t(GRADE DECIMAL PRIMARY KEY);
INSERT INTO t VALUES(0);
CREATE TEMPORARY TABLE t SELECT 1 f1;
CREATE USER a@localhost IDENTIFIED WITH '';
DROP TABLE t,t2;
ANALYZE NO_WRITE_TO_BINLOG TABLE t;

SET SQL_MODE='';
SET global aria_encrypt_tables=1;
CREATE TABLE ti (a INT) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t1(a INT PRIMARY KEY, b INT, KEY(b)) ENGINE=Aria;
INSERT INTO t1 VALUES(0,0);
DELETE FROM t1 WHERE a BETWEEN 0 AND 20 OR b BETWEEN 10 AND 20;
INSERT INTO t1 SELECT a, b+8192    FROM t1;
INSERT INTO ti VALUES(1);
INSERT INTO t1 VALUES(2,2);

# mysqld options required for replay: --log-bin
SET SQL_MODE='',tmp_table_size = 65535;
CREATE TABLE t1(c INT) ENGINE=InnoDB;
CREATE TABLE t2(c INT) ENGINE=MyISAM;
XA BEGIN 'a';
SET GLOBAL aria_encrypt_tables=1;
INSERT INTO t1 SELECT * FROM t1;
CREATE TEMPORARY TABLE t1(a INT PRIMARY KEY) ENGINE=Aria;
INSERT INTO t1 VALUES (1);
LOAD INDEX INTO CACHE t1 IGNORE LEAVES;
SELECT * FROM INFORMATION_SCHEMA.user_privileges LIMIT 1;
INSERT INTO t1 VALUES (1);

SET sql_mode='';
SET GLOBAL aria_encrypt_tables=1;
SET SESSION enforce_storage_engine=Aria;
CREATE TEMPORARY TABLE t (a INT KEY,b INT,KEY(b));
INSERT INTO t VALUES (1,REPEAT (1,6));
INSERT INTO t VALUES (412,1);
LOAD INDEX INTO CACHE t KEY(PRIMARY);
SELECT a FROM t;

CREATE DATABASE d2;
SET GLOBAL aria_encrypt_tables=1;
SET default_storage_engine=Aria;
SET sql_select_limit=1;
CREATE TABLE t (c INT KEY,c2 INT,KEY(c2));
INSERT INTO t VALUES (11,1),(12,1),(13,1),(14,2),(15,6);
FLUSH TABLES;
SELECT * FROM t ORDER BY c;

SET SESSION sql_mode='',GLOBAL aria_encrypt_tables=1;
CREATE OR REPLACE VIEW v1 AS SELECT 2 XOR 3 > 3, 2 XOR (3 > 3),(2 XOR 3) > 3;
CREATE TABLE t1 (f1 INT PRIMARY KEY) ENGINE=Aria;
INSERT INTO t1 VALUES ('a'),('b');
ALTER TABLE t1 ENGINE=MERGE UNION (t_not_exists,t1);
DELETE FROM t1 USING v1, t1 WHERE v1.a=t2.a;
