CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT DELETE ROWS;
RENAME TABLE t TO t2;
CREATE GLOBAL TEMPORARY TABLE t (c INT);
XA START 'a';
BINLOG 'a';
INSERT t VALUES (1);
SET pseudo_slave_mode=1;
XA END 'a';
XA PREPARE 'a';
LOCK TABLES t2 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
LOCK TABLES t2 READ;

# mysqld options required for replay:  --innodb_stats_persistent=off
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT DELETE ROWS;
CREATE TABLE t1 (a INT);
XA START 'a';
INSERT t VALUES (1);
BINLOG 'a';
SET pseudo_slave_mode=1;
XA END 'a';
XA PREPARE 'a';
LOCK TABLES t1 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
