USE test;
CREATE TABLE t1(bitk bit);
XA BEGIN '0';
INSERT INTO t1 VALUES(1);
BINLOG ' O1ZVRw8BAAAAZgAAAGoAAAAAAAQANS4xLjIzLXJjLWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAA7VlVHEzgNAAgAEgAEBAQEEgAAUwAEGggAAAAICAgC ';

CREATE TABLE t2 (c1 INT);
XA START 0x7465737462,0x2030405060,0xb;
INSERT INTO t2 VALUES (8513.33);
BINLOG ' mSKWVg8BAAAAdwAAAHsAAAAAAAQANS44LjAtbTE3LWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAACZIpZWEzgNAAgAEgAEBAQEEgAAXwAEGggAAAAICAgCAAAACgoKKioAEjQA AYzz6oU= '/*!*/;

CREATE TABLE t (b INT);
XA START 'a';
INSERT INTO t VALUES(0);
BINLOG ' SOgWTg8BAAAAbgAAAHIAAAAAAAQANS42LjMtbTUtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAABI6BZOEzgNAAgAEgAEBAQEEgAAVgAEGggAAAAICAgCAAAAAAVAYI8=';

CREATE TABLE t (c INT);
XA START 'a';
SELECT * FROM t WHERE c=0;
BINLOG ' O1ZVRw8BAAAAZgAAAGoAAAAAAAQANS4xLjIzLXJjLWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAA7VlVHEzgNAAgAEgAEBAQEEgAAUwAEGggAAAAICAgC ';

# See notes in MDEV-22712 for this testcase
CREATE TABLE t (a INT,b INT,c BINARY (1),d CHAR(1),e BINARY (1),f VARCHAR(1),g BLOB,h BLOB,id INT,KEY(b),KEY(e));
XA START 'xa_con3','xa_bqual',12;
INSERT INTO t VALUES (-23,0,0,'JIa5cvhg6tUx5CrOhuNTZBady8pN6ktM1gz6Mb2UfqsT7EdaB2AxVA7FruicGyEWLJj0qqB9bFtVrTNVTXb9wi3hFQdTPPR0JZRYvefC6zDn6aAxmcz25GAQxMGbInrJ4LVuO77LdQTQ0JJfokf7Y88nbUhobCQdM7yakLV2KRsHK8bVhnNXzkDXXrdzLqlHLApvWQUxghIQYZ188Cgb8WR2mJsXiKCrOUQIEXWZXAck5yAQjqXIZfuuX5F4TUkU','WV0ukE2Zq','Cme5VwrnlhpLsnd5ZlQo7PmPR3UW5ZwYsT3dE1r48wWhO5BwT9HcjxhLU0cU0S1',0,'5D',0);
BINLOG ' O1ZVRw8BAAAAZgAAAGoAAAAAAAQANS4xLjIzLXJjLWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAA7VlVHEzgNAAgAEgAEBAQEEgAAUwAEGggAAAAICAgC ';
