CREATE TABLE t1 (id INT AUTO_INCREMENT PRIMARY KEY, a CHAR(200), b CHAR(200) AS (a) VIRTUAL, KEY(id,b)) ENGINE=MyISAM;
INSERT INTO t1 (a) VALUES ('foo'),('bar');
ALTER TABLE t1 DROP PRIMARY KEY;
OPTIMIZE TABLE t1; # Also fails with CHECK TABLE t1
DROP TABLE t1;
