SET SESSION max_recursive_iterations=100000;
CREATE TABLE t1 (c1 INT PRIMARY KEY, c2 TEXT, FULLTEXT(c2)) ENGINE=InnoDB;
SET SESSION max_statement_time=0.0001;
INSERT INTO t1 VALUES (1,'aaa b c');
SET SESSION max_statement_time=0.0005;
INSERT INTO t1 VALUES (2,'aaa b c');
SET SESSION max_statement_time=0.001;
INSERT INTO t1 VALUES (3,'aaa b c');
SET SESSION max_statement_time=0.002;
INSERT INTO t1 VALUES (4,'aaa b c');
SET SESSION max_statement_time=0;
INSERT INTO t1 WITH RECURSIVE s AS (SELECT 5 n UNION ALL SELECT n+1 FROM s WHERE n<5000) SELECT n,CONCAT('aaa w',n) FROM s;
SET GLOBAL innodb_optimize_fulltext_only=ON;
OPTIMIZE TABLE t1;
SET SESSION max_statement_time=0.001;
SELECT COUNT(*) FROM t1 WHERE MATCH(c2) AGAINST('aaa');
SET SESSION max_statement_time=0;
SET GLOBAL innodb_optimize_fulltext_only=OFF;
DROP TABLE t1;
