CREATE TABLE t1 (pk int NOT NULL PRIMARY KEY, d1 decimal(10,0), KEY (d1)) ENGINE=InnoDB PARTITION BY KEY (pk) PARTITIONS 2;
INSERT INTO t1 VALUES (1,0),(3,0);
HANDLER t1 OPEN AS a1;
HANDLER a1 READ d1 <= ( 76 );
HANDLER a1 READ `PRIMARY` = ( 6 );
HANDLER a1 READ `PRIMARY` PREV ;
