CREATE OR REPLACE TABLE mysql.servers ( c0 BLOB NOT NULL,INDEX (c0) );
CREATE SERVER s1 FOREIGN DATA WRAPPER foo OPTIONS(USER 'a');

CREATE OR REPLACE TABLE mysql.procs_priv(id INT) ENGINE=INNODB;
INSERT INTO mysql.procs_priv SELECT seq FROM seq_1_to_1001;
FLUSH PRIVILEGES;

CREATE TABLE t (b INT,ROW_START BIGINT UNSIGNED GENERATED ALWAYS AS ROW START INVISIBLE,ROW_END BIGINT UNSIGNED GENERATED ALWAYS AS ROW END INVISIBLE,PERIOD FOR SYSTEM_TIME(ROW_START,ROW_END)) ENGINE=InnoDB WITH SYSTEM VERSIONING;
CREATE OR REPLACE TABLE mysql.transaction_registry (id INT) ;
XA START 'a';
INSERT INTO t() VALUES();
SET SESSION system_versioning_asof='2000-09-08 00:00:000000';
SELECT b FROM t;

RENAME TABLE mysql.procs_priv TO mysql.procs_gone;
CREATE USER'';

CREATE OR REPLACE TABLE mysql.servers (c BLOB,INDEX (c));
CREATE OR REPLACE SERVER s0 FOREIGN DATA WRAPPER mysql OPTIONS (HOST '0',PORT '0');
