INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider PARTITION BY LIST (c) (PARTITION p VALUES IN (1,2));
ALTER TABLE t ENGINE=InnoDB;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT KEY) ENGINE=Spider;
ALTER TABLE t ADD d BIT FIRST;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT AUTO_INCREMENT,KEY(c)) ENGINE=Spider;
ALTER TABLE t ENGINE=Spider;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) PARTITION BY HASH (c) PARTITIONS 2;
ALTER TABLE t ENGINE=Spider;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '',DATABASE'',USER'',PASSWORD '');
CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "tm"';
ALTER TABLE t ADD UNIQUE (c1);

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE server srv FOREIGN DATA wrapper mysql options (socket '../socket.sock',DATABASE 'test',USER 'spider',PASSWORD '');
CREATE TABLE t1 (a INT,b VARCHAR(1),PRIMARY KEY(a)) ENGINE=Spider PARTITION BY RANGE (a) (PARTITION p1 VALUES LESS THAN (1) REMOTE_SERVER='srv' REMOTE_TABLE='t1',PARTITION p2 VALUES LESS THAN MAXVALUE REMOTE_SERVER='srv' REMOTE_TABLE='t1');
ALTER TABLE t1 READ_ONLY=0;
