CREATE TABLE t0 (a INT KEY,b ENUM ('','b','c'));
ALTER TABLE t0 RENAME TO s0;
CREATE TEMPORARY SEQUENCE s0;
CREATE TABLE t0 (id INT DEFAULT NEXTval (s0),a_p_name CHAR(0),a_p_FIRST_NAME VARCHAR(0),t TIMESTAMP);
ALTER TABLE t0 ADD COLUMN a INT,DROP FOREIGN KEY ibfk_0;
