CREATE TABLE t (c POINT NOT NULL,SPATIAL (c));
INSERT INTO t VALUES (ST_GEOMFROMTEXT ('POINT(1 1)'));
SET GLOBAL innodb_limit_optimistic_insert_debug=3;
INSERT INTO t VALUES (ST_GEOMFROMTEXT ('POINT(1 1)'));
INSERT INTO t VALUES (POINT(1e-1,3e+1));
INSERT INTO t VALUES (ST_GEOMFROMTEXT ('POINT(1 1)'));
INSERT INTO t VALUES (POINT(1e+1,1e-1));
SET GLOBAL innodb_limit_optimistic_insert_debug=2;
INSERT INTO t VALUES (GEOMFROMTEXT ('POINT(1 1)'));
