ANALYZE SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='no_such_db_at_all';

SET STATEMENT max_statement_time=0.5 FOR SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='mysql' AND SLEEP(1)=0;
