INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE m1 (c1 INT) ENGINE=SPIDER PARTITION BY LIST COLUMNS (c1) (PARTITION p1 DEFAULT ENGINE=SPIDER);
SHOW TABLE STATUS;
CREATE TEMPORARY TABLE m2 ENGINE=SPIDER PARTITION BY LIST COLUMNS (c1) (PARTITION p1 DEFAULT ENGINE=SPIDER);
SHOW TABLE STATUS;
SELECT SLEEP(10);
SHOW TABLE STATUS;
