CREATE TABLE t1 (a INT, UNIQUE USING HASH (a)) ENGINE=InnoDB PARTITION BY RANGE(a) (PARTITION p1 VALUES LESS THAN (2), PARTITION p2 VALUES LESS THAN (101));
INSERT INTO t1 SELECT seq FROM seq_1_to_100;
ALTER TABLE t1 ADD PARTITION (PARTITION p3 VALUES LESS THAN (MAXVALUE));
ALTER TABLE t1 FORCE;

CREATE TABLE t (c INT, UNIQUE USING HASH (c)) ENGINE=InnoDB PARTITION BY HASH (c) PARTITIONS 2;
ALTER TABLE t ADD PARTITION PARTITIONS 2;
SELECT * FROM t;
