INSTALL SONAME 'ha_connect';
CREATE TABLE t1 (i INT) ENGINE=Connect;
INSERT INTO t1 VALUES (1),(2);
CREATE FUNCTION f() RETURNS INT RETURN (SELECT i FROM t1 LIMIT 1);
DELETE FROM t1 RETURNING f();

INSTALL SONAME 'ha_connect';
CREATE DATABASE mysqltest;
USE mysqltest;
CREATE TABLE t (i INT) ENGINE=Connect;
INSERT INTO t VALUES (1),(2);
CREATE FUNCTION f() RETURNS INT RETURN (SELECT i FROM t LIMIT 1);
SELECT f() FROM t;
