CREATE TABLE t (c1 INT,c2 VARCHAR(10)) ENGINE=MyISAM;
INSERT INTO t (c1) VALUES (1);
INSERT INTO t (c1) VALUES (1);
((SELECT * FROM t) OFFSET 1 ROW) ORDER BY BINARY - c2=PERCENTILE_DISC(FALSE) WITHIN GROUP(ORDER BY LOCALTIMESTAMP) OVER(PARTITION BY c1) OFFSET 1 ROWS FETCH FIRST ROW ONLY;
