CREATE TABLE t (c INT) ENGINE=MyISAM;
SELECT ST_COLLECT(c) FROM t;

CREATE TABLE t(c INT) ENGINE=MyISAM;
SELECT ST_ASTEXT(ST_ENVELOPE(ST_COLLECT(c))) FROM t;

CREATE TABLE t (c INT KEY,c2 INT,c3 INT) ENGINE=MEMORY max_rows=+1 avg_row_length=1;
SELECT ST_ASTEXT(ST_COLLECT(c2)) FROM t;
