CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
SET pseudo_thread_id=1;
INSERT INTO t VALUES (1);
SET pseudo_thread_id=0;
DROP TABLE t;
SET pseudo_thread_id=1;
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS SELECT 1 QUERY;
