SET @cmd:="CREATE DEFINER=USER2 FUNCTION f (i1 BLOB,i2 INT UNSIGNED ZEROFILL) RETURNS CHAR BINARY READS SQL DATA RETURN CONCAT (1,i1)";
PREPARE s FROM @cmd;
EXECUTE s;
EXECUTE s;

SET @cmd:="CREATE DEFINER=CURRENT_USER PROCEDURE p(OUT i1 BINARY,INOUT i2 DECIMAL(0,0)) SQL SECURITY DEFINER XA ROLLBACK''";
PREPARE s FROM @cmd;
EXECUTE s;#;
SHOW SLAVE HOSTS;########;
EXECUTE s;########################################################;

SET @cmd:="CREATE DEFINER=CURRENT_USER PROCEDURE p(OUT i1 BINARY,INOUT i2 DECIMAL(0,0)) SQL SECURITY DEFINER XA ROLLBACK''";
PREPARE s FROM @cmd;
EXECUTE s;########;
SHOW SLAVE HOSTS;########;
EXECUTE s;########################################################;

# mysqld options required for replay: --log-bin 
SET SESSION size=0;
SET @cmd:='CREATE DEFINER=current_user PROCEDURE p0 (INOUT i0 DOUBLE (0,0) UNSIGNED) LANGUAGE SQL RELEASE SAVEPOINT sp0';
PREPARE stmt FROM @cmd;
EXECUTE stmt;
PURGE BINARY LOGS BEFORE CURRENT_TIMESTAMP();
EXECUTE stmt;
