CREATE TABLE t1 (f INT, row_start BIGINT UNSIGNED AS ROW START, row_end BIGINT UNSIGNED AS ROW END, PERIOD FOR SYSTEM_TIME(row_start,row_end)) ENGINE=InnoDB WITH SYSTEM VERSIONING;
INSERT INTO t1 () VALUES ();
FLUSH TABLES;
UPDATE t1 SET f = NULL;
SET MAX_SESSION_MEM_USED= @@max_session_mem_used + 1024;
SELECT * FROM t1 FOR SYSTEM_TIME AS OF NOW();

SET sql_mode=''; 
SET SESSION max_session_mem_used=45500;
SET system_versioning_asof='1970-01-02 00:00:00';
CREATE TABLE t (x INT,y INT AS (x) VIRTUAL,sys_trx_start BIGINT UNSIGNED AS ROW START INVISIBLE,sys_trx_end BIGINT UNSIGNED AS ROW END INVISIBLE,period FOR SYSTEM_TIME(sys_trx_start,sys_trx_end)) WITH SYSTEM VERSIONING;
INSERT INTO t (c) VALUES (1),(1),(1),(1),(1);
INSERT INTO t VALUES (0,0),(0,0);
FLUSH TABLES WITH READ LOCK;
UPDATE t SET C2=''WHERE C1=''AND C2='';
SELECT * FROM t GROUP BY c;
SELECT * FROM t LIMIT 2;
SELECT * FROM t;
SELECT * FROM t;
