CREATE TABLE t (a TINYBLOB, b CHAR(64), UNIQUE(a,b(8))) ENGINE=InnoDB;
INSERT INTO t VALUES ('foo','bar');
CHECK TABLE t EXTENDED;

CREATE TABLE t (a TINYBLOB, b CHAR(64), UNIQUE(a,b(8))) ENGINE=InnoDB;
INSERT INTO t VALUES ('foo','bar');
SELECT SLEEP(2);
CHECK TABLE t EXTENDED;

CREATE TABLE t (a TINYBLOB, b CHAR(64), UNIQUE(a,b(8))) ENGINE=InnoDB
STATS_PERSISTENT=0;
INSERT INTO t VALUES ('foo','bar');
SET @save_freq=@@GLOBAL.innodb_purge_rseg_truncate_frequency;
SET GLOBAL innodb_max_purge_lag_wait=0;
SET GLOBAL innodb_max_purge_lag_wait=@save_freq;
CHECK TABLE t QUICK EXTENDED;
SELECT b FROM t FORCE INDEX(a);
DROP TABLE t;

CREATE TABLE t (a TINYBLOB, b CHAR(64),
v INT UNSIGNED AS (CRC32(CONCAT(a,LEFT(b,8)))) UNIQUE)
ENGINE=InnoDB STATS_PERSISTENT=0;

CREATE TABLE t (a TINYBLOB, b CHAR(64), UNIQUE(a,b(8))) ENGINE=InnoDB;
INSERT INTO t VALUES ('foo','bar');
CHECK TABLE t EXTENDED;
INSERT IGNORE INTO t VALUES ('baz','qux');

CREATE TABLE t (c CHAR(10),UNIQUE KEY a USING HASH (c(1))) ENGINE=MyISAM;
INSERT INTO t VALUES (0);
CHECK TABLE t EXTENDED;
