SET sql_mode='', pseudo_slave_mode=1, GLOBAL innodb_stats_persistent=0;
CREATE GLOBAL TEMPORARY TABLE t1 (c INT) ENGINE=ARCHIVE ON COMMIT DELETE ROWS;
SET max_session_mem_used=8192;
SELECT 1 FROM t1;
LOCK TABLES t1 WRITE;
ALTER TABLE t1 ADD d INT;
INSERT INTO t1 VALUES (1);
DROP TABLE t;
CREATE GLOBAL TEMPORARY TABLE t1 (c INT);
