INSTALL SONAME 'ha_connect.so';
CREATE TABLE t1 (c1 REAL(64,10) ZEROFILL) ENGINE=InnoDB;
INSERT INTO t1 VALUES (42);
CREATE TABLE t4 ENGINE=CONNECT TABLE_TYPE=MYSQL CONNECTION='mysql://root@localhost/test/t1';
SELECT * FROM t4;
