CREATE TABLE t0 (x INT UNSIGNED,y INT UNSIGNED) WITH SYSTEM VERSIONING;
CREATE GLOBAL TEMPORARY TABLE t LIKE t0;
INSERT INTO t VALUES (0),(0),(0);

CREATE TABLE t (a INT) WITH SYSTEM VERSIONING;
CREATE GLOBAL TEMPORARY TABLE t2 LIKE t;
SELECT * FROM t2;
