CREATE TABLE t1 (t TIMESTAMP NOT NULL) ENGINE=MyISAM;
SELECT * FROM t1 WHERE TRUNCATE( t, 1 );

CREATE OR REPLACE TABLE t1 (t TIMESTAMP NOT NULL) ENGINE=MyISAM;
SELECT * FROM t1 WHERE TRUNCATE( t, 1 );

USE test;
CREATE TABLE t (a TIMESTAMP,b TIMESTAMP);  # (ENGINE=InnoDB) 
INSERT INTO t VALUES (0,0);
SET SQL_MODE='TRADITIONAL';
SELECT TRUNCATE(a,b) AS c FROM t;

SET sql_mode='';
CREATE TABLE t5 (c TIMESTAMP KEY,c2 INT NOT NULL,c3 CHAR(1) NOT NULL);
INSERT INTO t5 (c) VALUES (1);
SET sql_mode=traditional;
SELECT ROUND (c,c2),TRUNCATE (c,c2) FROM t5;
