CREATE TABLE t (a INT KEY,b INT,c INT AS (b) VIRTUAL,UNIQUE (c)) ENGINE=INNODB;
START TRANSACTION;
INSERT INTO t(a,b) VALUES (1,1);
SET optimizer_switch='mrr=on';
DELETE FROM t;
INSERT INTO t(a,b) VALUES (1,0);
INSERT INTO t(a,b) VALUES (2,1);
SELECT * FROM t WHERE b < '1' ORDER BY b;
