CREATE TABLE t (c INT) ENGINE=InnoDB;
UPDATE t SET c=1 WHERE c=2 ORDER BY (1 IN ((SELECT * FROM (SELECT * FROM t) AS v1 GROUP BY c WINDOW v2 AS (ORDER BY (SELECT * FROM t GROUP BY c WINDOW v3 AS (PARTITION BY c))))));

CREATE TABLE t(c INT);
UPDATE t SET c= + 1 WHERE FALSE=c AND c=''ORDER BY 1=(-1 IN ((SELECT * FROM (SELECT * FROM t)AS v3 NATURAL JOIN t AS v2 NATURAL JOIN t AS v4 GROUP BY c WINDOW v5 AS(ORDER BY (SELECT * FROM t GROUP BY c WINDOW v6 AS(PARTITION BY c ORDER BY c + c + 1)))))) ^ 1 * 1;

CREATE TABLE x (x TEXT);
SELECT (x=(SELECT x FROM x WHERE (x,x) NOT IN (SELECT''* x * 1,''FROM x WINDOW x AS (PARTITION BY x ORDER BY x ^ (SELECT 1 FROM x AS x WHERE x GROUP BY 1,x WINDOW x AS (PARTITION BY x ORDER BY (1))) ^ x RANGE BETWEEN 1 FOLLOWING AND 1 FOLLOWING))) * 1^ 1 IN (-1,0,1,0,''/ x=x + CASE x WHEN TRUE THEN 0 ELSE 1 END OR x=x OR x=x)),''/ 1 AS x FROM x WINDOW x AS (PARTITION BY x ORDER BY (SELECT 1 FROM x WHERE x GROUP BY (x=(SELECT x FROM x WHERE (x,x) NOT IN (SELECT 1)) * 1^ 1 IN (-1,0,1,0,''/ x=x + CASE WHEN TRUE THEN 0 ELSE 1 END OR x=x OR x=x)),x WINDOW x AS (PARTITION BY x ORDER BY (1))) RANGE BETWEEN 1 FOLLOWING AND 1 FOLLOWING);

CREATE TABLE t (c INT);
SET SESSION optimizer_trace=1;
UPDATE t SET c=1 WHERE c IN (SELECT * FROM t AS c NATURAL JOIN t WINDOW c AS (PARTITION BY 1 BETWEEN (SELECT 1 GROUP BY c WINDOW c AS (PARTITION BY c)) AND 1));
