SET sql_mode='';
CREATE TABLE t (c SET('','') KEY);
INSERT INTO t VALUES (0),(0);

set sql_mode='';
CREATE TABLE t (c VARCHAR(0));
INSERT t SET c=0 ON DUPLICATE KEY UPDATE c=DEFAULT RETURNING VALUE (c)+0;
INSERT t SET c=0 ON DUPLICATE KEY UPDATE c=DEFAULT RETURNING VALUE (c)+0;
