USE test;
SET GLOBAL GENERAL_LOG=ON;
SET GLOBAL log_output="FILE,TABLE";
CREATE TABLE t(a DATE);
EXPLAIN SELECT * FROM t LIMIT ROWS EXAMINED 0;
SELECT 1;

SET GLOBAL log_output='FILE,TABLE';
CREATE TABLE t (c INT,c2 CHAR(1),c3 INT(1),c4 VARCHAR(1) KEY,c5 INT UNIQUE KEY,c6 DECIMAL(0,0) DEFAULT 3);
SET GLOBAL general_log=ON;
EXPLAIN SELECT * FROM t LIMIT ROWS EXAMINED 0;
SELECT SLEEP (1);

SET GLOBAL log_output='FILE,TABLE',GLOBAL general_log=ON;
CREATE TABLE t (c INT);
EXPLAIN SELECT * FROM t LIMIT ROWS EXAMINED 0;
SELECT SLEEP (1);

SET GLOBAL general_log=ON,GLOBAL log_output='TABLE';
CREATE TABLE t (a CHAR BINARY) ENGINE=InnoDB;
EXPLAIN SELECT * FROM t LIMIT ROWS EXAMINED 0;
SHOW TABLES;
