# Requires standard m/s setup. Tested with both ROW and MIXED.
SET sql_mode='',enforce_storage_engine=MyISAM;
CREATE TABLE t (c1 INT PRIMARY KEY, c2 INT, FOREIGN KEY(c2) REFERENCES t (c1)) ENGINE=foo;
SHOW WARNINGS;
SHOW CREATE TABLE t;
INSERT INTO t VALUES (1,2);

# mysqld options required for replay: --log-bin
BINLOG ' SOgWTg8BAAAAbgAAAHIAAAAAAAQANS42LjMtbTUtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAABI6BZOEzgNAAgAEgAEBAQEEgAAVgAEGggAAAAICAgCAAAAAAVAYI8=';
SET max_error_count=0;
CREATE TABLE t1 (id INT(11) NOT NULL AUTO_INCREMENT, id2 INT(11) NOT NULL, CONSTRAINT t1_id_fk FOREIGN KEY(id) REFERENCES t1 (id)) ENGINE=InnoDB;
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQxAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv/8AgAAAAgAAAA=';
