INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
dummy;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
DROP TABLE t;
CREATE TABLE t (c CHAR(1) PRIMARY KEY) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
dummy;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ NEXT;
SELECT * FROM t;
HANDLER t READ NEXT;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (i INT(1),v1 CHAR(1),v2 VARCHAR(1),KEY i (i),KEY v (v1,i)) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
SELECT * FROM t;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (d INT) ENGINE=Spider;
HANDLER t OPEN;
SELECT * FROM t ORDER BY c;
HANDLER t READ `PRIMARY` NEXT;

CREATE TABLE t (c INT) ENGINE=Spider;
EXPLAIN SELECT * FROM t AS x,t AS y;
HANDLER t OPEN;
SELECT * FROM t;
SELECT 1 + 18446744073709551615;
HANDLER t READ `PRIMARY` NEXT;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (a TEXT, b CHAR(255), c CHAR(4)) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
CREATE TABLE t2 SELECT f2 FROM (SELECT MAX(NOW()) f2 FROM t1) a;
SET SESSION tx_read_only=TRUE;
EXPLAIN SELECT * FROM t1,t1 AS t2 WHERE t1.x=t2.y;
HANDLER t1 OPEN;
HANDLER t1 READ FIRST LIMIT 9;
SELECT * FROM t1 GROUP BY c1 COLLATE utf8mb4_slovenian_ci;
HANDLER t1 READ FIRST;
SELECT SLEEP (3);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (a INT, b CHAR(10), c CHAR(10), filler CHAR(10), PRIMARY KEY(a, b (2)), UNIQUE KEY(a, c (2))) CHARACTER SET ucs2 ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"' COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
HANDLER t1 OPEN;
HANDLER t1 READ a> (54);
HANDLER t1 READ a> (54);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (c INT) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
HANDLER t1 OPEN;
HANDLER t1 READ NEXT;
HANDLER t1 READ NEXT;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (b INT, FOREIGN KEY(b) REFERENCES t1 (a)) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
HANDLER t1 OPEN;
HANDLER t1 READ b NEXT;
HANDLER t1 READ b NEXT;
