CREATE TABLE t2 (c1 INT, c2 TEXT, c3 TEXT, FULLTEXT KEY t2_c2(c2), FULLTEXT KEY t2_c2c3(c2,c3))Engine=InnoDB;
CREATE VIEW v5 AS SELECT c1, c2, c3, MATCH(c2,c3) AGAINST ('innodb') FROM t2;
INSERT INTO t2 (c2) VALUES ('innodb');
ALTER TABLE t2 PARTITION BY HASH (c1);
SELECT * FROM v5 WHERE MATCH(c2) AGAINST ('innodb');

CREATE TABLE t1 (c1 VARCHAR(3),c2 VARCHAR(3),FULLTEXT(c1),FULLTEXT(c2)) ENGINE=InnoDB PARTITION BY KEY (c1);
INSERT INTO t1 (c2) VALUES ('abc');
SELECT * FROM t1 WHERE MATCH(c1) AGAINST ('abc') AND MATCH(c2) AGAINST ('abc');
