INSTALL SONAME 'ha_connect';
CREATE TABLE t (a INT NOT NULL, b INT NOT NULL, KEY(a,b)) ENGINE=Connect TABLE_TYPE=DOS;
DELETE FROM t WHERE a=1;

INSTALL SONAME 'ha_connect';
CREATE TABLE t (c1 INT,c2 INT,PRIMARY KEY(c1,c2)) ENGINE=Connect;
SELECT * FROM t WHERE c1=1;

INSTALL SONAME 'ha_connect';
CREATE TABLE t (c INT,c2 INT,PRIMARY KEY(c2,c)) ENGINE=Connect ;
SELECT * FROM t WHERE c>=''AND c<'1' AND c2='1';
