CREATE TABLE t (a INT);
LOCK TABLE t WRITE;
CREATE TABLE IF NOT EXISTS t (a INT);
UNLOCK TABLES;

CREATE TABLE t2 (c1 DECIMAL(1,1) PRIMARY KEY,c2 VARCHAR(2) CHARACTER SET 'latin1' COLLATE 'latin1_bin',c3 VARCHAR(2) BINARY CHARACTER SET 'utf8' COLLATE 'utf8_bin', c4 VARCHAR(2) CHARACTER SET 'Binary' COLLATE 'Binary') ENGINE=InnoDB ROW_FORMAT=COMPACT;
CREATE TABLE t1 (c1 VARCHAR(1025) CHARACTER SET 'utf8' COLLATE 'utf8_bin',c2 VARCHAR(40),c3 VARCHAR(1) CHARACTER SET 'latin1' COLLATE 'latin1_bin', c4 VARCHAR(1) BINARY) ENGINE=InnoDB ROW_FORMAT=COMPACT;
LOCK TABLE t2 WRITE, t1 WRITE;
CREATE TABLE IF NOT EXISTS t1 (c1 TIMESTAMP PRIMARY KEY,c2 VARCHAR(1) CHARACTER SET 'Binary' COLLATE 'Binary',c3 VARCHAR(2), c4 VARCHAR(255) CHARACTER SET 'Binary' COLLATE 'Binary') ENGINE=InnoDB ROW_FORMAT=COMPRESSED;
