CREATE VIEW v AS SELECT 1 FROM (SELECT 1) AS d;
FLUSH TABLE v WITH READ LOCK;

CREATE VIEW v1 AS SELECT 1 FROM (SELECT 1) as d;
FLUSH TABLES v1 FOR EXPORT;

CREATE VIEW v(c) AS SELECT column_name FROM information_schema.columns;
FLUSH TABLE v WITH READ LOCK;
