CREATE TABLE t (a INT);
PREPARE s FROM 'SELECT GROUP_CONCAT(t.a ORDER BY t.a) FROM t JOIN t t2 GROUP BY t.a WITH ROLLUP';
EXECUTE s;
SET NAMES utf8;
EXECUTE s;

CREATE TABLE t (a INT);
PREPARE s FROM 'INSERT INTO t VALUES (1)';
SET TIMESTAMP=UNIX_TIMESTAMP(now());
EXECUTE s;
CREATE TRIGGER t BEFORE INSERT ON t FOR EACH ROW CALL non_existing_sp;
EXECUTE s;

PREPARE s FROM 'select JSON_ARRAYAGG(?)';
EXECUTE s USING'';
SET names latin1;
EXECUTE s USING'';

SET sql_mode='';
CREATE TABLE t1 (a INT,b CHAR,PRIMARY KEY(a)) ENGINE=RocksDB;
PREPARE stmt FROM 'SELECT GROUP_CONCAT(t1.a ORDER BY t1.a) FROM t1 JOIN t1 t2 GROUP BY t1.a WITH ROLLUP';
EXECUTE stmt;
SET @@collation_connection=latin1_bin;
EXECUTE stmt;

PREPARE s FROM 'SELECT JSON_ARRAYAGG(?)';
EXECUTE s USING DEFAULT;
EXECUTE s USING '';

CREATE TABLE t (c INT) ENGINE=InnoDB;
PREPARE s FROM 'SELECT GROUP_CONCAT(t.c ORDER BY t.c) FROM t JOIN t t2 GROUP BY t.c';
EXECUTE s;
SET NAMES utf8;
EXECUTE s;

CREATE TABLE t (a INT,KEY aa (a),b CHAR,KEY bb (b),c INT);
PREPARE s FROM 'SELECT GROUP_CONCAT(t.a ORDER BY t.a) FROM t JOIN t t2 GROUP BY t.a WITH ROLLUP';
EXECUTE s;
SET NAMES BIG5;
EXECUTE s;
