CREATE VIEW t AS SELECT 1 AS a;
SELECT a FROM t WHERE CASE WHEN a THEN DEFAULT (a) END=0;

CREATE VIEW t AS SELECT '' as a;
EXPLAIN EXTENDED SELECT * FROM t WHERE a='' AND CASE '' WHEN '' THEN '' ELSE a END='';

CREATE VIEW c (f,f2,f3,f4) AS SELECT connection_id(),pi(),CURRENT_USER(),version();
EXPLAIN EXTENDED SELECT * FROM c WHERE f2=1;
