INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT UNSIGNED KEY,b INT UNSIGNED,c INT UNSIGNED,UNIQUE (b,c) USING HASH) ENGINE=SPIDER;
SHOW CREATE TABLE t;
INSERT DELAYED INTO t VALUES (0,0,0);
