INSTALL SONAME 'ha_sphinx';
CREATE GLOBAL TEMPORARY TABLE t (c1 BIGINT,c2 BIGINT,c3 TEXT NOT NULL,KEY k(c3)) ENGINE=sphinx ON COMMIT DELETE ROWS;
INSERT t VALUES (0);
SHUTDOWN;

INSTALL SONAME 'ha_sphinx';
CREATE GLOBAL TEMPORARY TABLE t (c1 BIGINT,c2 BIGINT,c3 TEXT NOT NULL,KEY k(c3)) ENGINE=sphinx ON COMMIT DELETE ROWS;
SELECT * FROM t JOIN t AS t2;
SHUTDOWN;

INSTALL SONAME 'ha_sphinx';
CREATE GLOBAL TEMPORARY TABLE t (c1 BIGINT,c2 BIGINT,c3 TEXT NOT NULL,KEY k(c3)) ENGINE=sphinx;
ALTER TABLE t ALGORITHM=copy;
SHOW TABLE STATUS;
SHUTDOWN;

INSTALL SONAME 'ha_sphinx';
CREATE GLOBAL TEMPORARY TABLE t (c1 BIGINT,c2 BIGINT,c3 TEXT NOT NULL,KEY k(c3)) ENGINE=sphinx;
ALTER TABLE t FORCE,LOCK=shared,ALGORITHM=copy;
ALTER TABLE t ALGORITHM=INPLACE;
SHUTDOWN;
