CREATE TABLE t (c DOUBLE,c2 INT,PRIMARY KEY(c));
SELECT GET_LOCK('a',1);
START TRANSACTION;
SET SESSION wsrep_trx_fragment_size=1;
INSERT INTO t VALUES(1,1), (1,2);
SELECT RELEASE_ALL_LOCKS();

SELECT GET_LOCK ("lock_bug26141_wait", 1000) INTO @a;
CREATE TABLE t (a BINARY (211));
CREATE TABLE t1 (c1 VARCHAR(10));
SET SESSION wsrep_trx_fragment_size=200;
SET AUTOCOMMIT=OFF;
INSERT INTO t1 VALUES(0xAADF);
SELECT QUOTE (REPLACE ('[SELECT COUNT(*) FROM t1 WHERE a=LEFT (@inserted_value, 130)]=1', CONCAT ('[', 'SELECT COUNT(*) FROM t1 WHERE a=LEFT (@inserted_value, 130)', ']'), '1'));
INSERT INTO t1 VALUES(123.4567e-1);
INSERT INTO t VALUES(34075,-70);
CREATE TABLE t570 (c1 INT);
SELECT RELEASE_ALL_LOCKS()=2 AS expect_1;