SET GLOBAL wsrep_ignore_apply_errors=1;
CREATE TABLE t1 (a CHAR(1));
CREATE TABLE t1 (a CHAR(1));
SHOW PROCEDURE STATUS WHERE db = 'test';
SET GLOBAL read_only=1;

SET SESSION WSREP_ON=0;
FLUSH TABLES WITH READ LOCK AND DISABLE CHECKPOINT;
SET SESSION wsrep_on=1;
UNLOCK TABLES;