USE test;
CREATE TABLE t (c INT AUTO_INCREMENT NULL UNIQUE KEY);
ALTER TABLE t CHANGE c c INT NOT NULL;

CREATE TABLE t (c INT UNSIGNED AUTO_INCREMENT NULL UNIQUE KEY) ENGINE=InnoDB;
ALTER TABLE t MODIFY c INT ZEROFILL NOT NULL;
