INSTALL SONAME 'ha_connect';
CREATE TABLE t (c INT,c2 DATE,PRIMARY KEY(c2,c)) ENGINE=Connect PARTITION BY RANGE (TO_DAYS(c2)) SUBPARTITION BY HASH (c) SUBPARTITIONS 2 (PARTITION p VALUES LESS THAN (1));
INSERT INTO t VALUES (0,0);
LOCK TABLES t READ ;
CHECK TABLE t;
SELECT * FROM t;
