CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (0),(1);
SELECT a FROM t1 GROUP BY a HAVING NOT a;

SELECT * FROM (SELECT 1 AS c) AS a WHERE c IN (SELECT 1) GROUP BY c, c HAVING NOT c;

SELECT * FROM (SELECT 1 AS c) AS a GROUP BY c HAVING NOT c;
