set sql_mode='';
CREATE TABLE t (id INT AUTO_INCREMENT KEY,a INT,b INT,c VARCHAR(0),d DATE,ab_sum INT AS (a + b) VIRTUAL,ab_mul INT AS (a * b) PERSISTENT,c_upper VARCHAR(0) AS (UPPER (c)) VIRTUAL,c_len INT AS (LENGTH (c)) PERSISTENT,INDEX idx_a (a),INDEX idx_ab_SUM(ab_sum)) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE t ADD FULLTEXT INDEX ft_fz_0 (c);
REPLACE INTO t (id,ab_sum) VALUES (1,1);
ALTER TABLE t ADD SYSTEM VERSIONING;
ALTER TABLE t ENGINE=InnoDB;
