SET GLOBAL innodb_stats_persistent=0;
CREATE TABLE t (a INT) ENGINE=INNODB;
SET GLOBAL innodb_stats_persistent=1;
ALTER TABLE t ADD COLUMN b INT;
FLUSH TABLES WITH READ LOCK AND DISABLE checkpoint;
INSERT INTO t VALUES (1) ;

FLUSH TABLES WITH READ LOCK AND DISABLE CHECKPOINT;
CREATE TEMPORARY TABLE t(a int) ENGINE=INNODB;

# mysqld options required for replay:  --innodb-read-only=1
FLUSH TABLES WITH READ LOCK AND DISABLE checkpoint;

# Repeat 500-3000 times
CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
FLUSH TABLES t1 FOR EXPORT;
UNLOCK TABLES;
FLUSH TABLES WITH READ LOCK AND DISABLE CHECKPOINT;
UNLOCK TABLES;
DROP TABLE t1, t2;

# Loop 20-3000 times
DROP DATABASE test;
CREATE DATABASE test;
USE test;
INSERT INTO t1 VALUES (1,100),(2,200);
CREATE TABLE `t1` ( `geo` geometry DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE sbtest1 (a INT PRIMARY KEY, b VARCHAR(1000));
CREATE TABLE t1( a VARBINARY(256) COLUMN_FORMAT COMPRESSED ) ROW_FORMAT = DYNAMIC ENGINE=RocksDB;
FLUSH TABLES t1 FOR EXPORT;
UNLOCK TABLES;
FLUSH TABLES WITH READ LOCK AND DISABLE CHECKPOINT;
