SET sql_mode='';
INSTALL SONAME 'ha_connect';
CREATE TABLE t (c DATE) ENGINE=Connect PARTITION BY HASH (MONTH (c)) PARTITIONS 12;
LOCK TABLES t WRITE,t AS t_a READ;
INSERT INTO t VALUES (1);
INSERT INTO t VALUES (0);
CREATE TEMPORARY TABLE t2 LIKE t;
INSERT INTO t VALUES (1);
