CREATE TABLE v0 ( v1 INT , v2 INT ) ;
DELETE FROM v0 ORDER BY COUNT( v2 ) ;

CREATE TABLE v0 ( v1 INT , v2 INT ) ;
UPDATE v0 SET v1=1 ORDER BY COUNT( v2 ) ;

CREATE TABLE v0 ( v1 INT ) ;
DELETE FROM v0 WHERE v1 = 1 ORDER BY COUNT(v1) ;

CREATE TABLE t (c INT) ENGINE=InnoDB;
DELETE FROM t ORDER BY BIT_AND(c);
