CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS ENGINE=InnoDB;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
FLUSH TABLE t;

CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS ENGINE=MyISAM;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
FLUSH TABLE t;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS ENGINE=MyISAM AS SELECT 1;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
CACHE INDEX t PARTITION (ALL) KEY(d) IN DEFAULT;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS ENGINE=InnoDB AS SELECT 1;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
CACHE INDEX t PARTITION (ALL) KEY(d) IN DEFAULT;

CREATE TEMPORARY TABLE t (y INT);
CREATE GLOBAL TEMPORARY TABLE t0 (x INT,t TEXT) ON COMMIT PRESERVE ROWS;
HANDLER t0 OPEN;
LOCK TABLES t WRITE NOWAIT;
LOCK TABLES t WRITE;
SELECT GET_LOCK('a',0);

CREATE GLOBAL TEMPORARY TABLE t (x INT,t TEXT) ON COMMIT PRESERVE ROWS;
HANDLER t OPEN;
LOCK TABLES t READ NOWAIT;
BEGIN;
CREATE TABLE t (c INT);

CREATE GLOBAL TEMPORARY TABLE t1 (x INT,t TEXT) ON COMMIT PRESERVE ROWS;
HANDLER t1 OPEN;
CREATE TEMPORARY TABLE t (y INT);
LOCK TABLES t READ NOWAIT;
LOCK TABLES t1 AS a3 WRITE,t2 AS a4 WRITE;
PREPARE s FROM 'CREATE TABLE t1 AS SELECT 1 c';

CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
TRUNCATE t;
TRUNCATE t;
