SET SESSION optimizer_trace="enabled=on";
CREATE TABLE t1 (i INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT) ENGINE=MyISAM;
INSERT INTO t2 VALUES (1);
SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING c)) FROM t2) AS z;

SET SESSION default_tmp_storage_engine=MEMORY;
SET optimizer_trace="enabled=on";
CREATE TABLE t1 (a INT, KEY USING BTREE (a)) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t2 (b CHAR(60));
INSERT INTO t2 VALUES (0);
SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING b) NOT IN (SELECT 1 FROM t2)) FROM t2) AS z;
