CREATE TABLE t (a VARCHAR(16383) CHARACTER SET UTF8MB3,KEY(a (255))) ROW_FORMAT=DYNAMIC;
EXPLAIN PARTITIONS SELECT * FROM t WHERE a LIKE 'a_';

CREATE TABLE t1(a CHAR (32),KEY (a)) DEFAULT CHARSET=UTF8;
UPDATE t1 SET a='a1' WHERE a LIKE 'a%';
