CREATE TABLE t (f INT,s DATE,e DATE,PERIOD FOR p (s,e),UNIQUE (f,p WITHOUT OVERLAPS)) WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME LIMIT+1 (PARTITION p HISTORY,PARTITION pn CURRENT);
DELETE FROM t;
