CREATE DATABASE fp;
USE fp;
CREATE TABLE t1(a INT);
CREATE TABLE t2(a INT);
DELIMITER //
CREATE FUNCTION f_ct2(s VARCHAR(64)) RETURNS INT BEGIN  CREATE TEMPORARY TABLE IF NOT EXISTS fp.ttx(a INT); RETURN 1; END//
DELIMITER ;
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='fp' AND f_ct2(TABLE_CATALOG)=1;
