INSTALL SONAME 'ha_rocksdb';
SET GLOBAL transaction_isolation=0;
SET SESSION tx_isolation=DEFAULT;
DELIMITER $
CREATE PROCEDURE p() 
BEGIN 
  DECLARE cur CURSOR FOR SELECT * FROM t;
  BEGIN 
    DECLARE rec ROW TYPE OF cur DEFAULT ROW(0,0);
  END;
END; $
DELIMITER ;
CREATE TABLE t (c1 INT, c2 INT) ENGINE=RocksDB;
CALL p;
CREATE OR REPLACE TABLE t (c1 INT, c2 INT) ENGINE=RocksDB;
CALL p();
SHOW PROCEDURE CODE p;
