SET sql_mode='';
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider PARTITION BY HASH (c) PARTITIONS 2;
INSERT INTO t VALUES (0);
INSERT INTO t VALUES (0);
SELECT * FROM t WHERE c=1;
ANALYZE TABLE t;
SELECT * FROM t;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE t1 (a INT, b VARCHAR(255), PRIMARY KEY(a)) ENGINE=Spider PARTITION BY RANGE (a) (PARTITION p1 VALUES LESS THAN (3), PARTITION p2 VALUES LESS THAN MAXVALUE REMOTE_SERVER="srv");
INSERT INTO t VALUES (0,NULL,'a'), (1,'B','b'), (2,0,'c');
DROP SERVER srv;
SELECT * FROM t1;
