CREATE TABLE t (a VARCHAR(0),b VARCHAR(0) DEFAULT TRIM(BOTH '' FROM a));
INSERT INTO t VALUES ('','');
EXECUTE IMMEDIATE 'UPDATE t SET b=?' USING DEFAULT;

CREATE TABLE t2 (a INT KEY,b TEXT);
INSERT INTO t2 VALUES (1,2);
CREATE TABLE t1 LIKE t2;
INSERT INTO t1 VALUES (1,0);
EXECUTE IMMEDIATE 'UPDATE t1,t2 SET t1.b=IGNORE,t2.b=IGNORE WHERE t1.a=t2.a' USING IGNORE,IGNORE;
