CREATE TABLE t (c INT,c2 GEOMETRY NOT NULL,SPATIAL INDEX (c2));
XA START 'a';
SET @g1=ST_GEOMFROMTEXT ('POLYGON ((30 30,40 40,50 50,30 50,30 40,30 30))');
INSERT INTO t VALUES (0,POINT(0,0));
INSERT INTO t SELECT * FROM t;
SET sql_select_limit=1;
INSERT INTO t VALUES (1,POINT(1,1));
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
SELECT * FROM t WHERE MBRWITHin (t.c2,@g1);
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;

CREATE TABLE t1 (c POINT NOT NULL, SPATIAL(c)) engine=InnoDB;
set max_statement_time= 1;
check table t1;
INSERT INTO t1  VALUES(ST_GeomFromText('POINT(114368751 656950466)'));
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;
insert t1 select * FROM t1;

