SET SESSION optimizer_trace="enabled=on";
CREATE TABLE t1 (i INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT) ENGINE=MyISAM;
INSERT INTO t2 VALUES (1);
SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING c)) FROM t2) AS z;

SET SESSION default_tmp_storage_engine=MEMORY;
SET optimizer_trace="enabled=on";
CREATE TABLE t1 (a INT, KEY USING BTREE (a)) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t2 (b CHAR(60));
INSERT INTO t2 VALUES (0);
SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING b) NOT IN (SELECT 1 FROM t2)) FROM t2) AS z;

SET SESSION optimizer_trace=1;
CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t2 (b INT) ENGINE=MEMORY;
INSERT INTO t2 VALUES (1);
EXPLAIN SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING b) NOT IN (SELECT 1 FROM t2)) FROM t2) AS z;

SET SESSION optimizer_trace=1;
CREATE TABLE t1 (c VARCHAR(1)) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t2 (b VARCHAR(1)) ENGINE=MEMORY;
INSERT INTO t2 VALUES (1);
EXPLAIN SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING b) NOT IN (SELECT 1 FROM t2)) FROM t2) AS z;

SET default_storage_engine=MEMORY;
CREATE TABLE t (b BIT(1));
INSERT INTO t VALUES (1);
CREATE TABLE t2 (i FLOAT);
SET SESSION optimizer_trace=1;
SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t2 WHERE (SELECT 1 FROM t HAVING b) NOT IN (SELECT 1 FROM t)) FROM t) AS z;
