CREATE TABLE t1 (v VECTOR (5) NOT NULL,VECTOR INDEX (v));
BINLOG '0gKWSRMBAAAAMQAAAHQDAAAAAB8AAAAAAAEABHRlc3QAAnQxAAIPEQMUAAYBQFUzwA==0gKWSRcBAAAAMAAAAKQDAAAAAB8AAAAAAAEAAv/8BmJpbmxvZ0mWAtIBivg3mwo+';

CREATE TABLE t (v VECTOR(4) NOT NULL, VECTOR INDEX(v));
CREATE TABLE t1 (c VARBINARY(16));
INSERT INTO t1 VALUES ('');
INSERT INTO t SELECT c FROM t1;
