CREATE TABLE t (a INT);
PREPARE s FROM 'SELECT GROUP_CONCAT(t.a ORDER BY t.a) FROM t JOIN t t2 GROUP BY t.a WITH ROLLUP';
EXECUTE s;
SET NAMES utf8;
EXECUTE s;

CREATE TABLE t (a INT);
PREPARE s FROM 'INSERT INTO t VALUES (1)';
SET TIMESTAMP=UNIX_TIMESTAMP(now());
EXECUTE s;
CREATE TRIGGER t BEFORE INSERT ON t FOR EACH ROW CALL non_existing_sp;
EXECUTE s;

PREPARE s FROM 'select JSON_ARRAYAGG(?)';
EXECUTE s USING'';
SET names latin1;
EXECUTE s USING'';
