CREATE TABLE c(c CHAR) ENGINE=InnoDB;
INSERT INTO c(c)VALUES (1);
UPDATE c SET c=-0 WHERE(SELECT 0 -0 +0/ 0 + 0 - 0,c WHERE c<0 INTERSECT SELECT c,c FROM c WHERE c>0  -0)IN (SELECT c,c);

CREATE TABLE c(c INT) ENGINE=InnoDB;
INSERT INTO c VALUES (1);
UPDATE c SET c=-0 WHERE(SELECT 0,c WHERE c<0 INTERSECT SELECT c,c FROM c WHERE c>0)IN (SELECT c,c);

CREATE TABLE c(c BIGINT) ENGINE=InnoDB;
UPDATE c SET c=1 WHERE (SELECT '',c WHERE c=2 INTERSECT SELECT 1,1 FROM c WHERE c=3) IN (SELECT c,c);

CREATE TABLE c(c BIGINT UNIQUE) ENGINE=InnoDB;
UPDATE c SET c=0 WHERE(SELECT -0 ^ 0 +''/ 0,c WHERE c<0 INTERSECT SELECT c,''FROM c WHERE c>0  * 0)IN (SELECT c,c);
