CREATE TABLE t (a INT);
delimiter $
CREATE PROCEDURE p() 
BEGIN 
	DECLARE cur CURSOR FOR SELECT * FROM t;
	BEGIN 
		DECLARE rec ROW(a INT,b INT) DEFAULT ROW(0,0);
		DECLARE rec2 ROW TYPE OF cur DEFAULT rec;
	END;
END $
delimiter ;
CALL p();
CREATE OR REPLACE TABLE t (a INT);
CALL p();
