CREATE TABLE t1 (a INT PRIMARY KEY, b INT) ENGINE=InnoDB;
SET DEBUG_SYNC='blob_write_middle SIGNAL s WAIT_FOR ever';
ALTER TABLE t1 DROP COLUMN b, ALGORITHM=INSTANT;
SET DEBUG_SYNC='now WAIT_FOR s'; 
FLUSH ENGINE LOGS;
SELECT COUNT(*) FROM t1
