INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TEMPORARY TABLE t (c INT,c2 INT) ENGINE=SPIDER UNION=(t,t2) INSERT_METHOD=LAST;
INSERT INTO t VALUES (1,0),(1,0),(1,0);
EXPLAIN INSERT INTO t SELECT 1 QUERY;
