SET GLOBAL innodb_stats_persistent=0;
CREATE TABLE t (a INT) ENGINE=INNODB;
SET GLOBAL innodb_stats_persistent=1;
ALTER TABLE t ADD COLUMN b INT;
FLUSH TABLES WITH READ LOCK AND DISABLE checkpoint;
INSERT INTO t VALUES (1) ;

FLUSH TABLES WITH READ LOCK AND DISABLE CHECKPOINT;
CREATE TEMPORARY TABLE t(a int) ENGINE=INNODB;
