CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS ENGINE=InnoDB;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
FLUSH TABLE t;

CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS ENGINE=MyISAM;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
FLUSH TABLE t;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS ENGINE=MyISAM AS SELECT 1;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
CACHE INDEX t PARTITION (ALL) KEY(d) IN DEFAULT;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS ENGINE=InnoDB AS SELECT 1;
SET SESSION tx_read_only=1;
HANDLER t OPEN;
LOCK TABLES t READ;
LOCK TABLES t WRITE;
CACHE INDEX t PARTITION (ALL) KEY(d) IN DEFAULT;
