SET pseudo_slave_mode=1;
CREATE GLOBAL TEMPORARY TABLE t (c INT);
LOCK TABLES t READ;
CREATE TEMPORARY TABLE t1 LIKE t;
BEGIN;

SET pseudo_slave_mode=1;
CREATE GLOBAL TEMPORARY TABLE t (c INT);
LOCK TABLE t WRITE;
SELECT * FROM t;
DROP TABLE t;
