SET SESSION lc_time_names=zh_hk;
CREATE TABLE t (c CHAR,cc TEXT AS (CONCAT (c,IF(c=c,DATE_FORMAT(c,''),'')))) ENGINE=InnoDB;
SET NAMES utf8;
INSERT INTO t VALUES (0,0);
INSERT INTO t VALUES (0,0);
INSERT INTO t VALUES (0,0);
