INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c1 INT,c2 INT,c3 INT,c4 INT,KEY REFID (c3)) ENGINE=SPIDER;
INSERT INTO t VALUES (5,1);
DELETE FROM d.t;
FLUSH TABLE t WITH READ LOCK;
START TRANSACTION;
