CREATE TABLE t (c SET(''),c2 INT,c3 INT,KEY(c)) ENGINE=InnoDB;
CREATE TABLE t2 (c BLOB,c2 BLOB,c3 BINARY) ENGINE=InnoDB;
INSERT INTO t VALUES (0,1,1);
INSERT INTO t2 VALUES (1,1,1);
SELECT * FROM t2 WHERE (c) IN (SELECT c FROM t WHERE c<1);

SET sql_mode='';
CREATE TABLE t (c DOUBLE KEY,c2 SET('') CHARACTER SET 'BINARY' COLLATE 'BINARY',c3 INT) ENGINE=InnoDB;
INSERT INTO t VALUES ('A','B',0);
SELECT * FROM t WHERE c2>'';
