USE test;
SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t (a INT AUTO_INCREMENT PRIMARY KEY, b INT) ENGINE=Aria;
INSERT INTO t VALUES (6,2);
ANALYZE NO_WRITE_TO_BINLOG TABLE t;

# mysqld options required for replay: --log-bin
SET SQL_MODE='',tmp_table_size = 65535;
CREATE TABLE t1(c INT) ENGINE=InnoDB;
CREATE TABLE t2(c INT) ENGINE=MyISAM;
XA BEGIN 'a';
SET GLOBAL aria_encrypt_tables=1;
INSERT INTO t1 SELECT * FROM t1;
CREATE TEMPORARY TABLE t1(a INT PRIMARY KEY) ENGINE=Aria;
INSERT INTO t1 VALUES (1);
DELETE FROM t2;
DELETE FROM t1;
LOAD INDEX INTO CACHE t1 IGNORE LEAVES;
SELECT * FROM INFORMATION_SCHEMA.user_privileges LIMIT 1;
INSERT INTO t1 VALUES (1);
INSERT INTO t1 VALUES (2);

SET SQL_MODE='',GLOBAL aria_encrypt_tables=1;
CREATE TABLE ti (a TINYINT, b TINYINT, c CHAR(79), d CHAR(63), e CHAR(24), f BINARY(8), g BLOB, h MEDIUMBLOB, id BIGINT PRIMARY KEY, KEY(b), KEY(e)) ENGINE=Aria;
CREATE TEMPORARY TABLE t1(a INT NOT NULL PRIMARY KEY, b INT, KEY(b)) ENGINE=Aria;
INSERT INTO t1 VALUES(0, 0);
DELETE FROM t1 WHERE a BETWEEN 0 AND 20;
INSERT INTO t1 SELECT a, b FROM t1;
INSERT INTO ti VALUES (1,2,'a','b','c','d','e','g',2);
INSERT INTO t1 VALUES(0, 'a');
INSERT INTO t1 VALUES(0, 'a');
