PREPARE stmt FROM 'SELECT ?';
EXECUTE stmt USING current_timestamp;
EXECUTE stmt USING @param1;

PREPARE s FROM 'SELECT ? FROM DUAL';
EXECUTE s USING current_time;
EXECUTE s USING DEFAULT;

PREPARE s FROM "SELECT DATE ('') between''AND ?";
EXECUTE s USING current_time;
EXECUTE s USING @v;

PREPARE s FROM 'SELECT CONCAT (UNIX_TIMESTAMP(?))';
EXECUTE s USING CURRENT_TIMESTAMP;
EXECUTE s USING @str;
