ALTER TABLE mysql.tables_priv DROP COLUMN TIMESTAMP;
FLUSH PRIVILEGES;

SET sql_mode='';
GRANT ALL PRIVILEGES ON t2 TO a@localhost;
ALTER TABLE mysql.tables_priv DROP COLUMN TIMESTAMP;
GRANT ALL PRIVILEGES ON t2 TO a@localhost;
