CREATE TABLE t1 (c1 INT KEY,c2 VECTOR(1)) ;
ALTER TABLE t1 ADD COLUMN c_range_flag TINYINT GENERATED ALWAYS AS(IF(c1 AND 100,1,0)) STORED,ADD CHECK(c_range_flag IN (0,1));
CREATE TEMPORARY TABLE t2 LIKE t1;
CREATE TEMPORARY TABLE t1 (c1 INT KEY,c2 TEXT,c3 JSON) ;
INSERT INTO t1 VALUES (1,2,3);
SELECT * FROM t1 INTERSECT SELECT * FROM t2;
