INSTALL SONAME 'ha_rocksdb';
CREATE TABLE t (c INT,c2 CHAR(1),PRIMARY KEY(c,c2)) ENGINE=RocksDB;
BEGIN;
INSERT INTO t VALUES (2,2);
DELETE FROM t;
INSERT INTO t VALUES (1,1);
SELECT * FROM t WHERE c=1;
