SET sql_mode='';
CREATE TABLE t1 (c1 BIT KEY,c2 INT) ENGINE=InnoDB PARTITION BY LINEAR HASH(c1) PARTITIONS 822;
ALTER TABLE t1 ADD INDEX idx1(c2);
INSERT INTO t1 PARTITION (p1) VALUES (1,1);
UPDATE t1 SET c1=(TIME_FORMAT(1,1)MOD 1) DIV (18 ^ SECOND(1));
WITH cte AS(SELECT 1 FROM t1) SELECT 1 FROM cte;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
SET GLOBAL innodb_buffer_pool_size=+1;
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT KEY,KEY(c1)) ENGINE=InnoDB PARTITION BY HASH(c1) PARTITIONS 2;
CREATE TABLE t2 (c1 INT) ENGINE=InnoDB;
XA START 'a';
INSERT INTO t1 VALUES (0);
INSERT INTO t2 SELECT 0 FROM t1;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
HANDLER t1 READ `PRIMARY` PREV;
