CREATE SERVER s1 FOREIGN DATA WRAPPER mysql OPTIONS (HOST '127.0.0.1');
ALTER TABLE mysql.servers ENGINE=InnoDB;
FLUSH PRIVILEGES;

ALTER TABLE mysql.servers DROP COLUMN Options;
INSERT INTO mysql.servers VALUES(0,0,0,0,0,0,0,0,0);
FLUSH PRIVILEGES;
