USE test;
SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t (a INT AUTO_INCREMENT PRIMARY KEY, b INT) ENGINE=Aria;
INSERT INTO t VALUES (6,2);
ANALYZE NO_WRITE_TO_BINLOG TABLE t;

# mysqld options required for replay: --log-bin
SET SQL_MODE='',tmp_table_size = 65535;
CREATE TABLE t1(c INT) ENGINE=InnoDB;
CREATE TABLE t2(c INT) ENGINE=MyISAM;
XA BEGIN 'a';
SET GLOBAL aria_encrypt_tables=1;
INSERT INTO t1 SELECT * FROM t1;
CREATE TEMPORARY TABLE t1(a INT PRIMARY KEY) ENGINE=Aria;
INSERT INTO t1 VALUES (1);
DELETE FROM t2;
DELETE FROM t1;
LOAD INDEX INTO CACHE t1 IGNORE LEAVES;
SELECT * FROM INFORMATION_SCHEMA.user_privileges LIMIT 1;
INSERT INTO t1 VALUES (1);
INSERT INTO t1 VALUES (2);

SET SQL_MODE='',GLOBAL aria_encrypt_tables=1;
CREATE TABLE ti (a TINYINT, b TINYINT, c CHAR(79), d CHAR(63), e CHAR(24), f BINARY(8), g BLOB, h MEDIUMBLOB, id BIGINT PRIMARY KEY, KEY(b), KEY(e)) ENGINE=Aria;
CREATE TEMPORARY TABLE t1(a INT NOT NULL PRIMARY KEY, b INT, KEY(b)) ENGINE=Aria;
INSERT INTO t1 VALUES(0, 0);
DELETE FROM t1 WHERE a BETWEEN 0 AND 20;
INSERT INTO t1 SELECT a, b FROM t1;
INSERT INTO ti VALUES (1,2,'a','b','c','d','e','g',2);
INSERT INTO t1 VALUES(0, 'a');
INSERT INTO t1 VALUES(0, 'a');

SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t1 (i INT,PRIMARY KEY(i)) ENGINE=Aria;
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW BEGIN END;
INSERT IGNORE INTO t1 VALUES (600),(NULL),(NULL),(610),(NULL);
DROP TABLE t1;

SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t (c INT PRIMARY KEY) ENGINE=Aria;
INSERT INTO t (c) VALUES (1);
CHECK TABLE t;
SELECT * FROM t;

SET GLOBAL aria_encrypt_tables=1;
SET sql_mode='';
CREATE TABLE t (i INT KEY) ENGINE=Aria;
INSERT INTO t VALUES (1);
INSERT INTO t VALUES (REPEAT (0,0));
LOAD INDEX INTO CACHE t,t2 KEY(PRIMARY,b) IGNORE LEAVES;
SELECT * FROM t;

SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t (a INT UNSIGNED,b INT,c CHAR(1),d CHAR(1),e VARCHAR(1),f VARCHAR(1),g BLOB,h BLOB,id INT,KEY(b),KEY(e)) ENGINE=Aria;
INSERT INTO t VALUES (0,0,0,0,0,0,0,0,0);
ALTER TABLE t ENGINE=InnoDB;
ALTER TABLE t CHANGE COLUMN g g BLOB;

SET sql_mode='';
SET SESSION enforce_storage_engine=Aria;
CREATE TABLE tm1 (c INT);
SET GLOBAL aria_encrypt_tables=1;
CREATE TRIGGER tm1_ai AFTER INSERT ON tm1 FOR EACH ROW INSERT INTO t VALUES (1);
CREATE TABLE t3 (id INT KEY);
INSERT INTO t3 VALUES();
DROP DATABASE test;

SET GLOBAL aria_encrypt_tables=1;
CREATE TABLE t (c INT KEY,fk INT,INDEX index_fk (fk)) ENGINE=Aria PARTITION BY LIST (c) (PARTITION p VALUES IN (1,2));
INSERT INTO t VALUES (1,1);
ALTER TABLE t ADD COLUMN a INT;
SHOW CREATE TABLE t;

SET GLOBAL aria_encrypt_tables=1;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT KEY,b CHAR(1)) ENGINE=Spider;
SET GLOBAL table_open_cache=FALSE;
DROP DATABASE test;

SET GLOBAL aria_encrypt_tables=ON;
CREATE TABLE t (a INT KEY,b INT,KEY(b)) ENGINE=Aria;
INSERT INTO t VALUES (4,0);
LOAD INDEX INTO CACHE t IGNORE LEAVES;
LOAD INDEX INTO CACHE t;
SHUTDOWN;

SET sql_mode='';
SET GLOBAL aria_encrypt_tables=1;
SET default_storage_engine=Aria;
CREATE TABLE t (c INT,c2 BINARY (1),c3 INT(1),c4 BINARY (1) KEY,c5 INT UNIQUE KEY,c6 NUMERIC(0,0) DEFAULT 3);
INSERT INTO t (c) VALUES (1),(1),(1),(1),(1);
ALTER TABLE t ADD armscii8_f CHAR(1) CHARACTER SET armscii8;
# Client: ERROR 192 (HY000): Unknown key id 1 for ./test/#sql-alter-268b58-4. Can't continue!
# Error log: 2022-10-01 12:45:26 4 [ERROR] mysqld: Got error '126 "Index is corrupted"' for './test/#sql-alter-268b58-4.MAI'

SET GLOBAL aria_encrypt_tables=1;
SET SESSION storage_engine=Aria;
CREATE TABLE t (c INT KEY,c2 CHAR(1),c3 TIMESTAMP);
CREATE TRIGGER t_cnt_b BEFORE UPDATE ON t FOR EACH ROW UPDATE t SET cnt=cnt;
INSERT INTO t (c) VALUES (1),(1),(1),(1),(1);
LOCK TABLES t WRITE,t AS t0 READ;
SET STATEMENT sql_mode=''FOR ALTER TABLE t CHANGE c c FLOAT(0,0) UNSIGNED,CHANGE c2 c2 FLOAT(0,0) SIGNED;
