CREATE TABLE t1 (a CHAR(8)) ENGINE=InnoDB;
INSERT INTO t1 VALUES ('foo');
CREATE TABLE t2 (b VARCHAR(574)) ENGINE=InnoDB;
INSERT INTO t2 VALUES ('bar'),('baz');
CREATE TABLE t3 (e INT, d TEXT, PRIMARY KEY(e,d(8))) ENGINE=InnoDB;
INSERT INTO t3 VALUES (1,'qux');
CREATE TABLE t4 (f INT, KEY(f)) ENGINE=InnoDB;
INSERT INTO t4 VALUES (1),(2);
SET SESSION join_cache_level= 4;
SET SESSION join_buffer_space_limit= 16384;
SELECT DISTINCT a FROM t1 WHERE a IN (SELECT t2.b FROM t2 INNER JOIN t3 INNER JOIN t4 ON (t4.f = t3.e));

CREATE TABLE t (a INT);
SET JOIN_buffer_space_limit=1;
CREATE TABLE t2 (a INT(1),b TEXT,KEY(a));
INSERT INTO t VALUES (1);
INSERT INTO t2 (a,b) VALUES (1,1);
SELECT 1 FROM t2 WHERE b in (SELECT 1 FROM t A,t B WHERE B.a<5);

SET SESSION JOIN_buffer_space_limit=1;
CREATE TABLE t(a TEXT CHARACTER SET utf32) ENGINE=InnoDB;
INSERT INTO t VALUES(1);
SELECT a FROM t WHERE a IN(SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT a FROM t WHERE a IN (SELECT 1)))))))))))))))))))))))))))));
