CREATE TABLE t (c INT);
SET NAMES gb2312;
INSERT INTO t VALUES (1);
SELECT * FROM t WHERE EXTRACTVALUE (c,'a')='a';

SET sql_mode='';
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user 'Spider',PASSWORD'');
CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
CREATE TABLE t2 (c1 INT) DEFAULT CHARSET=sjis ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
INSERT INTO t2 VALUES ();
SET NAMES utf8;
SELECT * FROM t WHERE EXTRACTVALUE (c,'a')='a';

CREATE TABLE t (c INT);
INSERT INTO t VALUES (1);
SELECT * FROM t WHERE EXTRACTVALUE (c,'a')='a';
