CREATE TABLE t1 (d DATETIME(3), v DATETIME(2) AS (d));
CREATE VIEW v1 AS SELECT * FROM t1;
INSERT INTO t1 (d) VALUES ('2004-04-19 15:37:39.123'),('1985-12-24 10:15:08.456') ;
DELETE FROM v1 ORDER BY v LIMIT 4;

CREATE TABLE t1 (id INT NOT NULL AUTO_INCREMENT, f ENUM('a','b','c'), v ENUM('a','b','c') AS (f), KEY(v,id)) ENGINE=MyISAM;
INSERT INTO t1 (f) VALUES ('a'),('b');
INSERT IGNORE INTO t1 SELECT * FROM t1;

CREATE TABLE t1 (a INT, b INT, c BIT(4) NOT NULL DEFAULT b'0', pk INTEGER AUTO_INCREMENT, d BIT(4) AS (c) VIRTUAL, PRIMARY KEY(pk), KEY (b,d)) PARTITION BY HASH(pk);
INSERT INTO t1 () VALUES (),();
UPDATE t1 SET a = 0 WHERE b IS NULL ORDER BY pk;

# mysqld options required for replay:  --log-bin
SET SESSION binlog_row_image=1;
CREATE TEMPORARY TABLE t1 SELECT UUID();
CREATE TABLE t2 (a INT PRIMARY KEY, b TEXT, c INT GENERATED ALWAYS AS(b)) ENGINE=InnoDB;
INSERT INTO t2 (a,b) VALUES (1,1);

# mysqld options required for replay:  --log-bin
SET SESSION binlog_row_image=1;
CREATE TEMPORARY TABLE t1 SELECT UUID();
CREATE TABLE t2 (a INT PRIMARY KEY, b TEXT) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ALTER TABLE t2 ADD COLUMN c INT GENERATED ALWAYS AS (b+1) VIRTUAL;
INSERT INTO t2 (a,b) VALUES (1,1);

SET @@session.default_tmp_storage_engine = MEMORY;
SET optimizer_trace="enabled=on";
CREATE TABLE t1(a INT, KEY USING BTREE (a)) ENGINE=RocksDB;
CREATE TEMPORARY TABLE t2 (b CHAR(60));
INSERT INTO t2 VALUES (59144+0.333333333);
EXPLAIN SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM t1 WHERE (SELECT 1 FROM t2 HAVING b) NOT IN (SELECT 1 FROM t2) ) FROM t2 ) AS z;
