CREATE TABLE t(c POINT NOT NULL) ENGINE=InnoDB;
DROP TABLE mysql.innodb_table_stats;
CREATE SPATIAL INDEX i ON t(c);

CREATE TABLE t (c POINT PRIMARY KEY);
DROP TABLE mysql.innodb_index_stats;
ALTER TABLE t ADD SPATIAL INDEX i (c ASC);
