CREATE TEMPORARY TABLE t (a INT) ENGINE=InnoDB;
CREATE TABLE t(a INT,b INT) ENGINE=InnoDB;
DROP TABLE t;
ALTER TABLE t DISCARD TABLESPACE;
SET sql_mode= 'TRADITIONAL';
ALTER TABLE t ADD c DATE NOT NULL;

CREATE TABLE t(a INT PRIMARY KEY) ENGINE=InnoDB;
ALTER TABLE t DISCARD TABLESPACE;
SET SQL_MODE='TRADITIONAL';
ALTER TABLE t ADD c DATE NOT NULL;
DROP TABLE t;
