CREATE OR REPLACE TABLE mysql.servers ( c0 BLOB NOT NULL,INDEX (c0) );
CREATE SERVER s1 FOREIGN DATA WRAPPER foo OPTIONS(USER 'a');

CREATE OR REPLACE TABLE mysql.procs_priv(id INT) ENGINE=INNODB;
INSERT INTO mysql.procs_priv SELECT seq FROM seq_1_to_1001;
FLUSH PRIVILEGES;
