CREATE TABLE t (a INT);
UPDATE t SET c=1 ORDER BY (SELECT c);
# CLI: ERROR 1247 (42S22): Reference 'c' not supported (forward reference in item list)
UPDATE t SET c=1 ORDER BY (SELECT c);

CREATE TABLE t (a CHAR(1),b VARCHAR(1),KEY(a)) ENGINE=InnoDB;
UPDATE t SET c=1 ORDER BY (SELECT c LIMIT 0);

CREATE TABLE t (a CHAR BINARY) ENGINE=InnoDB;
SELECT * FROM t WHERE c2 BETWEEN '1000-00-01' AND '9999-12-31' ORDER BY c,c2 DESC LIMIT 2;
UPDATE t SET c=1 ORDER BY (SELECT c);

CREATE TABLE t(a CHAR BINARY);
SELECT * FROM t WHERE c2 BETWEEN '1000-00-01' AND '9999-12-31' ORDER BY c,c2 DESC LIMIT 2;
UPDATE t SET c=1 ORDER BY(SELECT c);#ERROR: 2013 - L;

CREATE TABLE t(a CHAR BINARY);
SELECT * FROM t WHERE c2 BETWEEN '1000-00-01' AND '9999-12-31' ORDER BY c,c2 DESC LIMIT 2;
UPDATE t SET c=1 ORDER BY(SELECT c);#ERROR: 2013 - Lost connection to MySQL server during query;
