SET GLOBAL auto_increment_increment=3;
CREATE SEQUENCE s START WITH -3 MINVALUE=-1000 INCREMENT 0;

SET GLOBAL AUTO_INCREMENT_offset=36;
SET sql_mode=ORACLE;
SET GLOBAL AUTO_INCREMENT_increment=19;
CREATE SEQUENCE s START WITH -3 MINVALUE=-1000 increment 0;
