SELECT ST_ASTEXT(ST_GEOMFROMTEXT('MULTIPOINT((0 0))'));
SELECT ST_ASTEXT(ST_GEOMFROMTEXT('MULTIPOINT((0 0),(1 1))'));
SELECT ST_ASTEXT(ST_GEOMFROMTEXT('MULTIPOINT(0 0,1 1)'));
#CLI: NULL, NULL, MULTIPOINT(0 0,1 1); expected the geometry in all three
#ERR: - (no error)

CREATE TABLE t1 (g GEOMETRY);
INSERT INTO t1 VALUES(ST_GEOMFROMTEXT('MULTIPOINT((1 1),(2 2))'));
SELECT ST_ASTEXT(g) FROM t1;
SELECT @@session.warning_count;
DROP TABLE t1;
#CLI: NULL stored, warning_count 0; expected the geometry
#ERR: - (no error)

SELECT ST_ASTEXT(ST_MPOINTFROMTEXT('MULTIPOINT((1 1),(2 2))'));
SELECT ST_ASTEXT(ST_GEOMFROMTEXT('GEOMETRYCOLLECTION(MULTIPOINT((1 1),(2 2)))'));
SELECT ST_ASTEXT(ST_GEOMFROMTEXT('MULTILINESTRING((1 1,2 2),(3 3,4 4))'));
SELECT ST_ASTEXT(ST_GEOMFROMTEXT('MULTIPOLYGON(((0 0,1 0,1 1,0 1,0 0)))'));
#CLI: NULL, NULL, then both read correctly; MULTIPOINT specific
#ERR: - (no error)
