SET sql_mode='';
CREATE TABLE t1 (c INT PRIMARY KEY) ENGINE=MyISAM;
INSERT INTO t1 VALUES (0);
CREATE TABLE t2 (a INT NOT NULL) ENGINE=CSV;
CREATE TRIGGER tr AFTER INSERT ON t2 FOR EACH ROW INSERT INTO t2 VALUES (1);
INSERT INTO t2 VALUES (0); 
CHECK TABLE t2;
INSERT INTO t1 VALUES (0);
INSERT INTO t2 VALUES (0),(0); 
