CREATE TABLE t1 (c1 INT PRIMARY KEY, c2 INT, KEY ci2(c1), KEY idx_(c1,c2)) ENGINE=InnoDB PARTITION BY HASH(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (0,1);
ALTER TABLE t1 CHANGE c2 c2 TINYBLOB, DROP PRIMARY KEY;
SET SESSION optimizer_switch='mrr=on';
SELECT 1 FROM t1 WHERE c2<>1 AND c1<>15;
