CREATE TABLE t2 (d CHAR(1)KEY);
SET autocommit=0;
INSERT INTO t2 VALUES(1);
CREATE TEMPORARY SEQUENCE seq1 ROW_FORMAT=REDUNDANT;

SET AUTOCOMMIT = 0;
SET SESSION wsrep_OSU_method='RSU';
CREATE TABLE t1(c1 VARCHAR(10));
INSERT INTO t1 (c1) VALUES('');
CREATE TEMPORARY SEQUENCE s1 ENGINE=INNODB;

# mysqld options required for replay:  --log-bin
SET autocommit=OFF;
CREATE TABLE t (c INT) ENGINE=InnoDB;
INSERT INTO t VALUES (0);
CREATE TEMPORARY SEQUENCE s;
