CREATE OR REPLACE TABLE t1 (x INT,start_trxid BIGINT UNSIGNED GENERATED ALWAYS AS ROW START,end_trxid BIGINT UNSIGNED GENERATED ALWAYS AS ROW END,PERIOD FOR SYSTEM_TIME(start_trxid,end_trxid)) ENGINE=INNODB WITH SYSTEM VERSIONING;
INSERT INTO t1 (x) SELECT 1;
CREATE OR REPLACE TABLE mysql.transaction_registry (id INT);
INSERT INTO t1 (x) SELECT 1;
