SET unique_checks=0,foreign_key_checks=0;
CREATE TABLE t (b INT) ENGINE=InnoDB;
INSERT t SELECT SEQ FROM seq_1_to_128000;
CREATE TABLE t3 (c INT) ENGINE=InnoDB;
SELECT * FROM t INTO OUTFILE 'a';
LOAD DATA INFILE 'a' INTO TABLE t3;
