SET GLOBAL init_slave='SHOW VARIABLES';
SET GLOBAL tmp_disk_table_size=1024;
SET GLOBAL big_tables=1;
CHANGE MASTER TO master_host='none';
START SLAVE SQL_THREAD;

SET tmp_disk_table_size=16384;
SELECT COUNT(*) FROM INFORMATION_SCHEMA.ALL_PLUGINS;
SELECT * FROM INFORMATION_SCHEMA.ALL_PLUGINS UNION DISTINCT SELECT * FROM INFORMATION_SCHEMA.ALL_PLUGINS;
