CREATE TABLE t (c BLOB NOT NULL) ENGINE=InnoDB;
INSERT IGNORE INTO t VALUES (0);
SELECT COUNT(*) FROM t WHERE EXTRACTVALUE(c,'a')='a';

SET sql_mode='';
CREATE TABLE t (c TEXT NOT NULL) ENGINE=InnoDB;
INSERT INTO t VALUES();
INSERT IGNORE INTO t VALUES (@VALUE);
SELECT GROUP_CONCAT(c ORDER BY BINARY c) FROM t GROUP BY c;
