SET GLOBAL log_bin_trust_function_creators=1;
CREATE FUNCTION f (c INT) RETURNS INT MODIFIES SQL DATA RETURN CONCAT ('1','2');
RENAME USER current_user TO '';
CREATE VIEW v AS SELECT f();
CREATE VIEW v AS WITH q(foo,bar) AS (SELECT * FROM v) SELECT * FROM q;
SHUTDOWN;
