SET GLOBAL auto_increment_increment=3;
CREATE SEQUENCE s START WITH -3 MINVALUE=-1000 INCREMENT 0;

SET GLOBAL AUTO_INCREMENT_offset=36;
SET sql_mode=ORACLE;
SET GLOBAL AUTO_INCREMENT_increment=19;
CREATE SEQUENCE s START WITH -3 MINVALUE=-1000 increment 0;

CREATE SEQUENCE s START WITH -3 MINVALUE=-10 INCREMENT 0;
SET GLOBAL AUTO_INCREMENT_INCREMENT=3;
FLUSH TABLES;
UPDATE s SET a=1;

SET sql_mode='';
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES ('-1000000');
SELECT * FROM t1 INTO OUTFILE 'a';
SET GLOBAL AUTO_INCREMENT_INCREMENT=25;
CREATE SEQUENCE t;
LOAD DATA INFILE 'a' INTO TABLE t;
