CREATE FUNCTION f() RETURNS INT RETURN(SELECT c FROM JSON_TABLE('{}', '$' COLUMNS(c FOR ORDINALITY)) AS jt);
SHOW FUNCTION CODE f;

CREATE VIEW v AS SELECT * FROM JSON_TABLE ('[]','$' COLUMNS (c INT EXISTS PATH '$')) AS d;
PREPARE p FROM 'SHOW CREATE VIEW v';
DROP VIEW v;
EXECUTE p;

CREATE FUNCTION f() RETURNS INT RETURN (SELECT c FROM JSON_TABLE ('{}','$' COLUMNS (c FOR ORDINALITY)) AS jt);
SHOW FUNCTION CODE f;
