SET SQL_MODE=ORACLE;
DELIMITER $
CREATE PROCEDURE p AS a ROW (x CHAR COLLATE DEFAULT); BEGIN END $
DELIMITER ;

CREATE PROCEDURE p0 (c CHAR COLLATE DEFAULT) BEGIN END;

CREATE FUNCTION f() RETURNS CHAR COLLATE DEFAULT RETURN0;

SET sql_mode='';
CREATE PROCEDURE p() BEGIN DECLARE c CHAR COLLATE DEFAULT;
