CREATE VIEW v1 AS SELECT 6;
CREATE PROCEDURE sp() SELECT 1 FROM v1; 
CREATE TEMPORARY TABLE v1 as SELECT 8;
CALL sp();
DROP TEMPORARY TABLE v1;
CALL sp();

CREATE TABLE t AS SELECT 1 f;
PREPARE t FROM 'SHOW CREATE TABLE t';
DROP TABLE t;
EXECUTE t;
CREATE VIEW t AS SELECT 1;
EXECUTE t;
