CREATE TEMPORARY TABLE t1 (c INT) ENGINE=MyISAM;
CREATE TEMPORARY TABLE t2 (c INT) ENGINE=MyISAM;
PREPARE s FROM 'optimize TABLE t1,t2';
EXECUTE s;
SHOW TABLES;

CREATE TEMPORARY TABLE t (c INT);
ALTER TABLE t CHANGE COLUMN c b INT,ADD INDEX (c);
RENAME TABLE t TO t;
SHOW TABLES;
