CREATE TABLE t (a VARCHAR(16) COLLATE utf8_bin, FULLTEXT (a)) ENGINE=InnoDB COLLATE utf8_unicode_520_ci;
ALTER TABLE t MODIFY COLUMN a VARCHAR(512);

CREATE TABLE t (t CHAR CHARACTER SET utf8 COLLATE utf8_unicode_ci,FULLTEXT (t)) ENGINE=InnoDB;
ALTER TABLE t CONVERT TO CHARACTER SET utf8,CHARACTER SET utf8;
