set sql_mode='';
SET GLOBAL encrypt_tmp_disk_tables=ON;
CREATE OR REPLACE TABLE t (c INT KEY,c2 TEXT,c3 JSON);
CREATE TABLE t2 LIKE t;
CREATE OR REPLACE TABLE t (c INT KEY,c2 VECTOR (1));
ALTER TABLE t ADD COLUMN c4 INT(1) ZEROFILL AFTER c2;
INSERT INTO t VALUES (1,1,MICROSECOND (1)) ON DUPLICATE KEY UPDATE c=1;
SELECT * FROM t UNION SELECT * FROM t2;

SET sql_mode='', GLOBAL encrypt_tmp_disk_tables=ON;
CREATE TABLE t1 (c1 INT,c2 VECTOR (1),c3 INT);
CREATE TABLE t2 (c1 INT,c2 TEXT,c3 JSON);
INSERT INTO t1 VALUES (1,1,1);
SELECT * FROM t1 UNION SELECT * FROM t2;

SET sql_mode='';
CREATE TABLE t1 (c1 INT,c2 VECTOR (1),c3 INT);
CREATE TABLE t2 (c1 INT,c2 TEXT,c3 JSON);
INSERT INTO t1 VALUES (1,1,1);
SELECT * FROM t1 UNION SELECT * FROM t2;

CREATE TABLE t1 (c1 INT KEY,c2 VECTOR(1)) ;
ALTER TABLE t1 ADD COLUMN c_range_flag TINYINT GENERATED ALWAYS AS(IF(c1 AND 100,1,0)) STORED,ADD CHECK(c_range_flag IN (0,1));
CREATE TEMPORARY TABLE t2 LIKE t1;
CREATE TEMPORARY TABLE t1 (c1 INT KEY,c2 TEXT,c3 JSON) ;
INSERT INTO t1 VALUES (1,2,3);
SET GLOBAL encrypt_tmp_disk_tables=ON;
SELECT * FROM t1 INTERSECT SELECT * FROM t2;

SET GLOBAL encrypt_tmp_disk_tables=ON;
CREATE OR REPLACE TABLE t (c INT KEY,c2 VECTOR(1),c5 REAL);
CREATE TABLE t2 LIKE t;
CREATE OR REPLACE TABLE t (c INT KEY,c2 TEXT,c3 JSON);
INSERT INTO t VALUES (0,'v=n',1.e+3);
SELECT * FROM t UNION SELECT * FROM t2;

SET sql_mode='';
CREATE TABLE t1 (c2 VECTOR(256) NOT NULL,c3 JSON,VECTOR INDEX(c2) M=8 DISTANCE=EUCLIDEAN) ENGINE=InnoDB;
REPLACE INTO t1 VALUES ('',(SYSDATE(5) - 1) DIV (UTC_TIME(6) + UNHEX(705)));
CREATE TABLE t2 (c2 TEXT,c3 JSON) ENGINE=Aria;
INSERT IGNORE INTO t1 (c2,c3) SELECT * FROM t1 UNION ALL SELECT * FROM t2;
