CREATE TABLE c(c INT) ENGINE=InnoDB;
SELECT * FROM c AS c WHERE c=c + 0 / 0 WINDOW c AS(ORDER BY (SELECT * FROM c GROUP BY c HAVING c=- 0 OR c>0 AND NOT c<c WINDOW c AS(PARTITION BY c)));

CREATE TABLE c(c DEC) ENGINE=InnoDB;
SELECT * FROM c AS c WHERE c IS NULL OR c<0 / TRUE * 0 WINDOW c AS(PARTITION BY c AND -0 BETWEEN(SELECT * FROM c GROUP BY c HAVING ((c=c AND c BETWEEN 0 AND 0)) WINDOW c AS(PARTITION BY c)) AND -0);

CREATE TABLE c (c DEC) ENGINE=InnoDB;
SELECT * FROM c AS c WHERE c=1 WINDOW c AS (ORDER BY (SELECT * FROM c GROUP BY c HAVING c=1 WINDOW c AS (PARTITION BY c)));
