SET sql_mode='TRADITIONAL';
CREATE TABLE t (c CHAR(1));
INSERT INTO t VALUES (0xE8),(0xE9),(0xEA),(0xEB),(0xEC),(0xED),(0xEE),(0xEF);
SELECT * FROM (t AS t2 JOIN t AS t3 USING (a)) JOIN t USING (a);
ALTER TABLE t CHANGE c c INT;
SELECT * FROM t ORDER BY a;

CREATE TABLE t (c DOUBLE PRECISION KEY,c2 CHAR,c3 YEAR);
INSERT INTO t VALUES (7,3,1);
SELECT a FROM t WHERE a=ALL (SELECT a FROM t WHERE b=2 UNION SELECT a FROM t WHERE b=2);
INSERT INTO t VALUES (3,1,1);
ALTER TABLE t CHANGE c c DATE,ADD KEY(c);
INSERT INTO t VALUES (CONVERT (_ucs2 0x0041004100410648 USING utf8));

SET sql_mode='';
CREATE TABLE t (c CHAR UNIQUE,c2 INT,stamp TIMESTAMP) ENGINE=InnoDB;
INSERT INTO t VALUES (1,1,1),(2,2,2),(3,3,3),(4,4,4),(5,5,5);
UPDATE t SET c=(SELECT * FROM t) WHERE c IN (SELECT * FROM t);
ALTER TABLE t MODIFY c DATE;
INSERT INTO t VALUES (6887,6887,6887,6887);
