CREATE TABLE t (a INT UNSIGNED KEY,b INT UNSIGNED,c INT UNSIGNED,UNIQUE bc (b,c))Engine=InnoDB;
ALTER TABLE t ADD CONSTRAINT UNIQUE key_1 (a);
ALTER TABLE t CHANGE COLUMN a a CHAR(0) BINARY;
SELECT 1 FROM t WHERE a LIKE'';
