CREATE TABLE t1 (a INT);
CREATE ALGORITHM=MERGE VIEW v1 AS SELECT a FROM t1;
CREATE ALGORITHM=MERGE VIEW v2 AS SELECT * FROM ( SELECT v1.a FROM t1, v1 ) AS sq;
CREATE PROCEDURE p() UPDATE v2 SET a = 2;
CALL p;
CREATE OR REPLACE TABLE t1 (b INT);
CALL p;

CREATE PROCEDURE p() UPDATE t,(SELECT 1 FROM (SELECT 1 FROM t WHERE c=0) a) d SET c=1;
CREATE TABLE t (a INT) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t (c INT) ENGINE=InnoDB;
CALL p();
DROP TEMPORARY TABLE t;
CALL p();
