NSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t0 (a INT,KEY(a)) ENGINE=SPIDER;
CREATE TABLE t1 (a INT,KEY(a)) ENGINE=SPIDER;
INSERT INTO t1 SELECT * FROM t1 ;
ALTER TABLE t1 CHANGE COLUMN n o CHAR(10);
INSERT INTO t0 VALUES (0);
SELECT MIN(a) FROM t1;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
SET SESSION spider_same_server_link=ON;
CREATE TABLE t (col1 CHAR(1),col2 VARCHAR(1),UNIQUE KEY KEY1 USING HASH (col1,col2)) ENGINE=SPIDER;
CREATE TEMPORARY TABLE t (c BLOB);
CREATE TABLE t2 (c INT,c2 INT,c3 BLOB,PRIMARY KEY(c));
DROP TABLE t;
SELECT COUNT(TABLE1.colvck) FROM t AS TABLE1 JOIN (SELECT * FROM t) AS TABLE2 ON (1=1) WHERE TABLE1.pk=1;
ALTER TABLE t CHANGE c c NUMERIC ZEROFILL;
CREATE TABLE t3 (a INT,b INT,KEY(a));
INSERT INTO t VALUES (1,0);
