CREATE TABLE t (id BIGINT) ENGINE=InnoDB;
INSERT INTO t VALUES ('10000000000000');
SELECT * FROM t PROCEDURE ANALYSE();

SET sql_mode='';
CREATE TABLE t (a INT);
INSERT INTO t VALUES ('100000000000'),('100000000000');
SELECT * FROM t PROCEDURE ANALYSE();

SET sql_mode='';
CREATE TABLE t (c BIGINT,c2 DATE,c3 BLOB,KEY(c)) ENGINE=InnoDB;
INSERT INTO t VALUES (-1.e+308,1,1);
SELECT * FROM t PROCEDURE ANALYSE();

CREATE TABLE t (c INT) ENGINE=InnoDB UNION=(t,t2) INSERT_METHOD=LAST;
CREATE TABLE t3 LIKE t;
INSERT INTO t VALUES (1),(2),(-685113344),(0);
INSERT INTO t3 SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t3 SELECT * FROM t;
SELECT * FROM t3 PROCEDURE ANALYSE();

CREATE TABLE t (f BIGINT);
INSERT INTO t VALUES (0xF0A08080);
SELECT f FROM t PROCEDURE ANALYSE(1,1);

SET sql_mode='';
CREATE TABLE t (c INT) UNION=(t,t2) INSERT_METHOD=LAST;
INSERT INTO t VALUES (1);
INSERT INTO t VALUES (0xA9BD);
INSERT INTO t (c) VALUES (ADDTIME(NOW(),1));
CREATE TABLE c AS SELECT 1 A;
SELECT * FROM t a,c,t b PROCEDURE ANALYSE();

CREATE TABLE t (c BIGINT);
INSERT INTO t VALUES (1000000000000000);
SELECT * FROM t PROCEDURE ANALYSE(0,0);

CREATE SEQUENCE t CACHE=1 MAXVALUE=0 INCREMENT=-1;
SELECT * FROM t PROCEDURE ANALYSE();

CREATE TABLE t (c INT) ENGINE=InnoDB;
INSERT INTO t VALUES (0x31313131),(0x32323232);
INSERT INTO t VALUES (0x31313131),(0x32323232);
SELECT * FROM t LIMIT 1 PROCEDURE ANALYSE();
