set sql_mode='';
CREATE TABLE t (FTS_DOC_ID BIGINT UNSIGNED NOT NULL,body TEXT);
ALTER ONLINE TABLE t ADD c TIMESTAMP;
INSERT INTO t VALUES ('a','a',1.e-1);
SET SESSION sql_buffer_result=1;
SET NAMES utf8;
SELECT EXTRACTVALUE ('a','a') AS f,SPACE(c) AS f2 FROM t GROUP BY f,f2 WITH ROLLUP;
