# mysqld options required for replay:  --log_bin
CREATE TABLE t1(c CHAR(1)) ENGINE=INNODB;
CREATE TABLE t2(c CHAR(1)) ENGINE=ARIA;
SET SESSION autocommit=0;
CREATE TABLE t3(c CHAR(1)) ENGINE=MyISAM;
INSERT INTO t1 SET c='';
INSERT INTO t3 VALUES('C');
SELECT @@log_bin;
INSERT INTO t2 VALUES (11);
CREATE TABLE t3 (c CHAR(1)) ENGINE=INNODB;

# mysqld options required for replay:  --log_bin
CREATE TABLE t (a INT);
SET SESSION autocommit=0;
SAVEPOINT s;
INSERT INTO t VALUES (1);
CREATE TEMPORARY TABLE t1 (a INT);
ROLLBACK TO SAVEPOINT s;
