SET sql_mode=ORACLE;
CREATE DATABASE db1;
CREATE DATABASE db2;
CREATE TABLE db2.t1 (id INT, note VARCHAR(40));
DELIMITER $$
CREATE PACKAGE db1.pkg AS TYPE rec IS RECORD (a INT, b VARCHAR(20)); END; $$
CREATE TRIGGER db2.trg BEFORE INSERT ON db2.t1 FOR EACH ROW DECLARE r db1.pkg.rec; BEGIN r.a := :NEW.id; :NEW.note := 'x';END;$$
DELIMITER ;
INSERT INTO db2.t1 (id) VALUES (1);  
