CREATE TABLE t1 (col INT);
INSERT INTO t1 VALUES (0xF4AB);
CREATE TEMPORARY TABLE t1 (c1 INT) ENGINE=mrg_myisam UNION=(t1) insert_method=FIRST;
SET GLOBAL wsrep_max_ws_rows=1;
DROP TABLES t1;
INSERT INTO t1 VALUES (6373);
CREATE TABLE t2 ENGINE=heap SELECT * FROM t1;

SET default_storage_engine="HEAP";
CREATE TABLE t1 (f1 BIGINT);
SET GLOBAL wsrep_max_ws_rows = 1;
INSERT INTO t1 VALUES (NOW()),(NOW()),(NOW());