INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
dummy;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
DROP TABLE t;
CREATE TABLE t (c CHAR(1) PRIMARY KEY) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
dummy;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ NEXT;
SELECT * FROM t;
HANDLER t READ NEXT;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (i INT(1),v1 CHAR(1),v2 VARCHAR(1),KEY i (i),KEY v (v1,i)) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
SELECT * FROM t;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (d INT) ENGINE=Spider;
HANDLER t OPEN;
SELECT * FROM t ORDER BY c;
HANDLER t READ `PRIMARY` NEXT;

CREATE TABLE t (c INT) ENGINE=Spider;
EXPLAIN SELECT * FROM t AS x,t AS y;
HANDLER t OPEN;
SELECT * FROM t;
SELECT 1 + 18446744073709551615;
HANDLER t READ `PRIMARY` NEXT;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (a TEXT, b CHAR(255), c CHAR(4)) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
CREATE TABLE t2 SELECT f2 FROM (SELECT MAX(NOW()) f2 FROM t1) a;
SET SESSION tx_read_only=TRUE;
EXPLAIN SELECT * FROM t1,t1 AS t2 WHERE t1.x=t2.y;
HANDLER t1 OPEN;
HANDLER t1 READ FIRST LIMIT 9;
SELECT * FROM t1 GROUP BY c1 COLLATE utf8mb4_slovenian_ci;
HANDLER t1 READ FIRST;
SELECT SLEEP (3);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (a INT, b CHAR(10), c CHAR(10), filler CHAR(10), PRIMARY KEY(a, b (2)), UNIQUE KEY(a, c (2))) CHARACTER SET ucs2 ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"' COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
HANDLER t1 OPEN;
HANDLER t1 READ a> (54);
HANDLER t1 READ a> (54);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (c INT) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
HANDLER t1 OPEN;
HANDLER t1 READ NEXT;
HANDLER t1 READ NEXT;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (b INT, FOREIGN KEY(b) REFERENCES t1 (a)) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
HANDLER t1 OPEN;
HANDLER t1 READ b NEXT;
HANDLER t1 READ b NEXT;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t (c INT) ENGINE=InnoDB;
CREATE TABLE t1 (a INT) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
CREATE TABLE t2 (c INT) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
XA START 'a';
SET GLOBAL init_connect='SET autocomit=0';
INSERT INTO t1 VALUES (0);
INSERT INTO t2 SELECT * FROM t2;
SELECT IF('SELECT COUNT(*) FROM t1 WHERE a=""' REGEXP '^[a-zA-z_][a-zA-z_0-9]*:', 1, 0);
INSERT INTO t2 VALUES (0);

CREATE TEMPORARY TABLE ti (a INT);
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT,c2 INT)  engine=Spider PARTITION BY HASH (c) PARTITIONS 4  ;
UPDATE t SET a=((1));
LOCK TABLES t WRITE CONCURRENT;
LOAD DATA INFILE 'unkownfile.txt' IGNORE INTO TABLE t IGNORE 4 LINES;
DELETE FROM t;

SET sql_mode='';
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t2 (a INT,b CHAR(1)) ENGINE=Spider;
CREATE TABLE ti (a INT UNSIGNED,b INT,c BINARY (1),d BINARY (1),e CHAR(1),f BINARY (1),g BLOB,h BLOB,id INT,KEY(b)) ENGINE=Spider;
INSERT INTO t2 SELECT * FROM t2;
XA START 't2';
SET GLOBAL table_open_cache=-1;
INSERT INTO ti VALUES (+1,+1,'GuouFix9aU','npmQUXtICRhmUw9','fi7fNNixs2eaasF4dW4a3wSm7TnRKtSArEPz1cL4HxSf7',0,0,0,1);
INSERT INTO t2 VALUES (+1);
SELECT SLEEP (1);
INSERT INTO ti VALUES (+1,0,'j5PdMJaSyqZfK4UhINT8bTpIOyMkkl9jSiH1W1WOIioTzyn','9RdEWjrZb9','Uij6wOXbYGNsAKqhhsHlnHOWluciiRwyq','DdMOZMJwyCL5TXAuiwqXLXojWDYUlcxvkWfgwU2LoQeYQEvUTntf7nDFdLNfRUFZgpqddR1Hqq9Hl2MEnuNx8aiOu9s6bQIzw6uwCdM3rfJWSXobIkwhUXnq2aDLSXkTPwHu2VRqHPZ3Ufq1G',0,'E3',4);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SET default_storage_engine=Spider;
CREATE DATABASE db1 CHARACTER SET utf8;
CREATE TABLE db1.t1 (a INT, b INT);
HANDLER db1.t1 OPEN;
DROP TABLE t1;
HANDLER t1 READ NEXT LIMIT 2;
SELECT COUNT(*) FROM foo;
HANDLER t1 READ NEXT;

# Repeat until a crash is observed
DROP DATABASE test;
CREATE DATABASE test;
USE test;
SET sql_mode='', default_storage_engine=Spider;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t1 (c1 INT) ENGINE=Spider;  
SELECT * FROM t1;  
SET GLOBAL table_open_cache=100;
CREATE TABLE t2 (c1 INT NULL, c2 INT NULL, UNIQUE (c1,c2));
XA START 'a';
SELECT * FROM t2;
LOAD DATA INFILE 'foo' INTO TABLE t1;
SELECT SLEEP (3);
INSERT INTO t2 VALUES (NULL,'b');  # Crashing query
SHOW CREATE TABLE t2;
