CREATE GLOBAL TEMPORARY TABLE t (c INT) ENGINE=InnoDB;
XA START 'a';
SET GLOBAL innodb_force_primary_key=1;
SELECT * FROM t;
SET pseudo_slave_mode=1;
XA END 'a';
XA PREPARE 'a';
LOCK TABLE t WRITE;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t (c TEXT) ENGINE=InnoDB;
DROP TABLE t;  # Cleanup
