SET unique_checks=0,foreign_key_checks=0,autocommit=0;
CREATE TABLE t (c INT KEY) ENGINE=InnoDB;
INSERT INTO t VALUES (0,0);
SAVEPOINT a;
INSERT INTO t VALUES (0),(0);
SAVEPOINT a;

SET sql_mode='',unique_checks=0,foreign_key_checks=0,autocommit=0;
CREATE PROCEDURE p (OUT i INT) MODIFIES SQL DATA SAVEPOINT p;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES ();
SAVEPOINT p;
CREATE TEMPORARY TABLE t2 (i INT KEY) ENGINE=InnoDB;
INSERT INTO t2 VALUES(),();
CALL p (@b);

SET sql_mode='',unique_checks=0,foreign_key_checks=0,autocommit=0;
CREATE PROCEDURE p (OUT i INT) MODIFIES SQL DATA SAVEPOINT p;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES ();
SAVEPOINT p;
CREATE TABLE t2 (i INT KEY) ENGINE=InnoDB;
INSERT INTO t2 VALUES(),();
CALL p (@b);
