CREATE TABLE t1 (a VARCHAR(256)) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1),(5);
CREATE TABLE t2 (b INT) ENGINE=InnoDB;
INSERT INTO t2 VALUES (2),(3);
SELECT * FROM t1 WHERE EXISTS (SELECT 1 FROM t2 WHERE b <> t1.a);
