USE test;
SET SQL_MODE='';
CREATE TABLE t (c DOUBLE PRECISION PRIMARY KEY) ENGINE=Memory;
INSERT INTO t VALUES (1);
REPLACE DELAYED INTO t (c) VALUES (1);
ALTER TABLE t MODIFY c FLOAT NOT NULL;

CREATE TABLE t1 (pk INT PRIMARY KEY) ENGINE=MEMORY;
INSERT INTO t1 VALUES (1),(2);
FLUSH STATUS; # not needed for the test case, only for cleanup
REPLACE DELAYED INTO t1 VALUES (1);CREATE TABLE t1 (pk INT PRIMARY KEY) ENGINE=MEMORY;

SET GLOBAL binlog_format=MIXED;
CREATE TABLE t (f INT KEY) ENGINE=MEMORY;
INSERT INTO t VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
REPLACE DELAYED t VALUES (1);

# mysqld options required for replay: --log-bin
SET binlog_format='STATEMENT', sql_mode='';
SET SESSION enforce_storage_engine=MEMORY;
CREATE TABLE t (c INT KEY);
INSERT t VALUES (1);
REPLACE DELAYED t VALUES (1);
INSERT INTO foo VALUES (1);
