SET sql_mode='';
CREATE TABLE t (c1 CHAR(10) BINARY CHARACTER SET 'utf8',PRIMARY KEY(c1(4))) ENGINE=InnoDB;
REPLACE INTO t VALUES ('𝌆');
INSERT INTO t VALUES (0);
ALTER TABLE t CONVERT TO CHARACTER SET utf8;

CREATE TABLE t (c VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin',PRIMARY KEY(c(9)),KEY k(c)) ENGINE=InnoDB;
INSERT INTO t VALUES ('a'),('{');
ALTER TABLE t CONVERT TO CHARACTER SET utf8;
INSERT INTO t (c) SELECT * FROM t;

CREATE TABLE t (c VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin',PRIMARY KEY(c(9)),KEY k(c)) ENGINE=InnoDB;  # Same result without KEY k
INSERT INTO t VALUES ('a'),('b');
ALTER TABLE t CONVERT TO CHARACTER SET utf8;
INSERT INTO t (c) SELECT * FROM t;

CREATE TABLE t (c VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_bin',PRIMARY KEY(c(9)),KEY k(c)) ENGINE=InnoDB;  # Same result without KEY k
INSERT INTO t VALUES ('a'),('{');
ALTER TABLE t CONVERT TO CHARACTER SET utf8;
