SET sql_mode='';
INSTALL SONAME 'ha_connect';
CREATE TABLE t (c INT NOT NULL,KEY(c)) ENGINE=Connect PARTITION BY KEY(c) PARTITIONS 9;
LOCK TABLES t WRITE;
INSERT INTO t VALUES ();
ALTER TABLE t CHANGE c c INT UNSIGNED NOT NULL;
