CREATE TABLE t (c INT,c2 CHAR,c3 DATE,CHECK (c>0)) ENGINE=MyISAM;
ALTER TABLE t ADD INDEX (c2) USING HASH;

WITH a AS (SELECT * FROM a FOR TIME ALL;

WITH c AS(SELECT * FROM (SELECT * FROM t1) SELECT * FROM DUAL;

INSERT INTO t WITH s AS (SELECT * FROM t1;

CREATE TABLE t (x INT,CHECK (t.x>0));
ALTER TABLE t ADD FULLTEXT INDEX idx_0 (b);

ALTER TABLE t ADD PERIOD IF NOT EXISTS FOR a (e,s);

CREATE TABLE t (i INT) ;
ALTER TABLE t DROP PERIOD IF EXISTS FOR b;

CREATE TABLE t(c INT);
SELECT /*+ JOIN_prefix(tbl1,tbl2)*/* FROM t AS tbl1;
