SET sql_mode='';
CREATE TABLE t4 (c1 INT,c2 INT,c3 INT,c4 VARCHAR(100)) ENGINE=Aria;
CREATE TRIGGER tr1 BEFORE INSERT ON t4 FOR EACH ROW SELECT * FROM t4 INTO OUTFILE '0';
INSERT DELAYED INTO t4 VALUES (0,0,0,'0');
SHUTDOWN;
