SET sql_mode='';
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
GRANT ALL ON * TO Spider@localhost;
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER 'Spider',PASSWORD'');
CREATE TABLE t1 (c INT) ENGINE=MyISAM;
CREATE TABLE t2 (c INT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t1"';
SELECT * FROM t2 ORDER BY CAST(c AS INET6);
