CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS;
HANDLER t OPEN;
DROP DATABASE test;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ENGINE=MEMORY ON COMMIT PRESERVE ROWS;
HANDLER t OPEN AS t;
HANDLER t READ FIRST;
DROP DATABASE test;
