CREATE TABLE t(c INT UNIQUE,c2 TEXT) ENGINE=InnoDB;
INSERT INTO t(c2) VALUES (1);
SELECT * FROM t GROUP BY c HAVING (SELECT c2 WHERE 0>c2 IS NULL=(1<c) OR c2='');

CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES (0),((SELECT * FROM t AS v2 GROUP BY (0+1) HAVING ((SELECT 1 GROUP BY c HAVING (c=''))='')));

CREATE TABLE t1 (c BLOB,KEY(c (1))) ENGINE=InnoDB;
INSERT INTO t1 VALUES (0),((SELECT * FROM t1 AS v2 GROUP BY (0+1) HAVING ((SELECT 1 GROUP BY c HAVING (c=''))='')));
