CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES ('0.0e'),('0.0e+0');
SELECT * FROM t WHERE COALESCE(c)=0.0;

CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES (1.3),(1.1);
SELECT * FROM t PROCEDURE ANALYSE();

SET sql_mode='';
CREATE TABLE t (c CHAR(10) KEY);
INSERT INTO t VALUES (1.755555555);
SELECT * FROM t PROCEDURE ANALYSE();

CREATE TABLE t (c BIGINT);
INSERT INTO t VALUES (1000000000000000);
SELECT * FROM t PROCEDURE ANALYSE(0,0);

SET sql_buffer_result=1;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
CREATE TABLE tm (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
CREATE TABLE t1 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
CREATE TABLE t2 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "tm"';
INSERT INTO t VALUES (0,1,0),(1,0,0),(2,0,0);
INSERT INTO tm VALUES (0,1,0),(1,0,0),(2,0,0);
SELECT * FROM t1 HAVING c1=(SELECT t.c1 AS c FROM t2 t ORDER BY (SELECT MIN(t1.c1+tt.c1) FROM t2 tt));

CREATE TABLE t0 ( c8 INT , CONSTRAINT cc0 UNIQUE i0 ( c8 ) ) ;
INSERT INTO t0 VALUES ( ) , ( ) ;
ALTER TABLE t0 ADD COLUMN c59 TEXT NOT NULL AFTER c8 ;
INSERT INTO t0 VALUES ( -95 , 86 ) , ( -58 , -36 ) ;
SELECT t1 . c41 AS c18 FROM ( SELECT c59 AS c41 FROM t0 ) AS t1 JOIN t0 ON c8 IN ( SELECT c8 AS c45 FROM t0 GROUP BY c59 , c8 HAVING c59 = AVG ( ( SELECT c8 AS c30 FROM t0 HAVING ATAN ( ROUND ( -588949354837696189 , IF ( 6068938522839077129 , -1 BETWEEN 79 AND 49 , 21 ) ) , RAND ( ) ) = t0 . c59 LIMIT 1 ) ) ) ;

CREATE TABLE t1 (c1 MEDIUMBLOB NOT NULL);
INSERT INTO t1 VALUES ('1e+');
SELECT AVG(c1) AS VALUE FROM t1 WHERE c1 <> 0;
