INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c1 INT) ENGINE=SPIDER PARTITION BY HASH (c1) PARTITIONS 2;
SELECT * FROM t;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=InnoDB PARTITION BY RANGE (c) SUBPARTITION BY HASH (c) SUBPARTITIONS 3 (PARTITION p0 VALUES LESS THAN (1),PARTITION p VALUES LESS THAN MAXVALUE);
ALTER TABLE t TABLESPACE ts STORAGE DISK ENGINE=SPIDER;
