SET sql_mode="no_zero_date";
SET GLOBAL wsrep_max_ws_rows=1;
CREATE TABLE t2 (a INT);
CREATE TABLE t1 (a INT NOT NULL PRIMARY KEY) ENGINE=InnoDB;
CREATE TRIGGER tgr BEFORE INSERT ON t1 FOR EACH ROW INSERT INTO t2 VALUES (0);
CREATE TABLE ti (id BIGINT NOT NULL PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO ti VALUES (1);
INSERT INTO t1 VALUES (0),(1);
