CREATE TABLE t (a INT);
UPDATE t SET c=1 ORDER BY (SELECT c);
# CLI: ERROR 1247 (42S22): Reference 'c' not supported (forward reference in item list)
UPDATE t SET c=1 ORDER BY (SELECT c);

CREATE TABLE t (a CHAR(1),b VARCHAR(1),KEY(a)) ENGINE=InnoDB;
UPDATE t SET c=1 ORDER BY (SELECT c LIMIT 0);

CREATE TABLE t (a CHAR BINARY) ENGINE=InnoDB;
SELECT * FROM t WHERE c2 BETWEEN '1000-00-01' AND '9999-12-31' ORDER BY c,c2 DESC LIMIT 2;
UPDATE t SET c=1 ORDER BY (SELECT c);

CREATE TABLE t(a CHAR BINARY);
SELECT * FROM t WHERE c2 BETWEEN '1000-00-01' AND '9999-12-31' ORDER BY c,c2 DESC LIMIT 2;
UPDATE t SET c=1 ORDER BY(SELECT c);#ERROR: 2013 - L;

CREATE TABLE t(a CHAR BINARY);
SELECT * FROM t WHERE c2 BETWEEN '1000-00-01' AND '9999-12-31' ORDER BY c,c2 DESC LIMIT 2;
UPDATE t SET c=1 ORDER BY(SELECT c);#ERROR: 2013 - Lost connection to MySQL server during query;

CREATE TABLE t(c1 INT NOT NULL, c2 TIME NULL, PRIMARY KEY(c1));
CREATE TABLE t2(a INT UNSIGNED NOT NULL, b BIGINT NOT NULL, c CHAR(1), d VARBINARY(1) NOT NULL, e VARBINARY(1) NOT NULL, f VARCHAR(1), g BLOB, h TINYBLOB, id BIGINT NOT NULL, KEY(b), KEY(e), PRIMARY KEY(id)) ENGINE=InnoDB;######; 
UPDATE t SET c=1 ORDER BY(SELECT c);###########################################################;

CREATE TABLE t (a VARCHAR(5000),FULLTEXT (a)) ENGINE=InnoDB;
SELECT * FROM t1  WHERE c1=-255 ORDER BY c1,c6 LIMIT 2;
UPDATE t SET c=0 ORDER BY(SELECT c);######

CREATE TEMPORARY TABLE t1 (c INT) ENGINE=Aria;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
INSERT INTO t2 VALUES (0, 1);
EXPLAIN SELECT c+0 FROM t2;
UPDATE t1 SET d=1 ORDER BY (SELECT d);
