SET sql_mode='';
CREATE TABLE t (v INT (1) NOT NULL) ENGINE=CSV;
INSERT INTO t SELECT 1 away;
DELETE FROM a3,a1 USING t AS a1 JOIN t AS a2 JOIN t AS a3;

SET sql_mode='';
CREATE TABLE t (v VECTOR (1) NOT NULL) ENGINE=CSV;
INSERT INTO t SELECT 1 away;
SHOW WARNINGS;
DELETE FROM a3,a1 USING t AS a1 JOIN t AS a2 JOIN t AS a3;
