SET sql_mode='';
CREATE TABLE t (c INT) ENGINE=InnoDB PARTITION BY KEY(c) PARTITIONS 2;
INSERT INTO t() VALUES();
ALTER TABLE t MODIFY c INT NOT NULL;  # 1265 Data truncated for column 'c' at row 1
UPDATE t SET c=-1 LIMIT 2;

SET sql_mode='';
CREATE TABLE t (c INT,c2 INT) ENGINE=InnoDB PARTITION BY KEY(c) PARTITIONS 8;
INSERT INTO t (c) SELECT MAX(c) FROM t;
ALTER TABLE t CHANGE COLUMN c d INT NOT NULL;
ALTER TABLE t ADD COLUMN c TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
UPDATE t SET c=(SELECT 1 FROM t)-1;
