SET SESSION unique_checks=FALSE;
SET SESSION autocommit=0;
CREATE OR REPLACE TABLE t1 (a INT);
LOCK TABLES t1 WRITE;
CREATE OR REPLACE TABLE t1 (a INT);
SET SESSION foreign_key_checks=OFF;
INSERT INTO t1 VALUES (1);
SET SESSION foreign_key_checks=ON;
SELECT * FROM t1;
