# mysqld options required for replay: --innodb-rollback-on-timeout=1
SET SESSION pseudo_slave_mode=ON;
CREATE TABLE t (a INT) ENGINE=INNODB;
XA START 'a';
INSERT INTO t VALUES (1);
XA END 'a';
XA PREPARE 'a';
ALTER TABLE t IMPORT TABLESPACE;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET GLOBAL log_bin_trust_function_creators=ON;
CREATE FUNCTION f() RETURNS INT RETURN (SELECT 1 FROM t);
CREATE TABLE t (a0 INT,b0 INT,c INT,d0 INT,KEY(a0,b0))Engine=InnoDB;
XA START 'a';
SELECT * FROM t;
XA END 'a';
XA PREPARE 'a';
SELECT ROW(COALESCE(f()),0)=ROW(0,0) AS eq;
