INSTALL PLUGIN Spider SONAME 'ha_spider.so';

CREATE TABLE t1 (f1 VARCHAR(128), f2 VARCHAR(128), KEY(f2,f1) USING BTREE) ENGINE=MyISAM;
INSERT INTO diaries VALUES (1216, "2014-11-11");
OPTIMIZE TABLE t1;
SELECT SLEEP(2);

CREATE TABLE t (c INT) ENGINE=Aria;
OPTIMIZE LOCAL TABLE t;
