CREATE FUNCTION f() RETURNS ROW TYPE OF t RETURN 1;
CREATE TABLE t (a INT);
SELECT ROW(f(),1)=ROW(1,1) AS eq;

CREATE FUNCTION f() RETURNS ROW TYPE OF t RETURN 1;
CREATE TABLE t (a INT);
SELECT ROW(COALESCE(f()),1)=ROW(1,1) AS eq;
