USE test;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY '';
SHOW CREATE SERVER srv;
CREATE SERVER s3 FOREIGN DATA WRAPPER mysql OPTIONS (HOST 'LOCALHOST', PORT 3307);
SHOW CREATE SERVER srv;
SELECT * FROM mysql.servers;
ALTER SERVER s3 OPTIONS (HOST '192.168.0.3', PORT 3306);
CREATE OR REPLACE SERVER srv FOREIGN DATA WRAPPER foo OPTIONS (HOST "LOCALHOST", PORT "12345");
DROP SERVER s5000;
CREATE TABLE t1_s3 (c INT) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "s3", TABLE "t2"';
SHOW CREATE SERVER srv;
# After this mariadb-admin shutdown will sporadically hang 1/100 if a multi-threaded load is present (ref MDEV-35136)
