INSTALL SONAME 'ha_rocksdb';
CREATE TABLE t1 (pk INT PRIMARY KEY, a VARCHAR(1), KEY(a)) ENGINE=RocksDB PARTITION BY HASH (pk);
ALTER TABLE t1 MODIFY a VARCHAR (2) COLLATE utf8mb4_general_nopad_ci;
TRUNCATE t1;
SELECT * FROM t1;

INSTALL SONAME 'ha_rocksdb';
CREATE TABLE t1 (pk INT PRIMARY KEY, a VARCHAR(1), KEY(a)) ENGINE=RocksDB PARTITION BY HASH (pk);
ALTER TABLE t1 MODIFY a VARCHAR (2) COLLATE utf8mb4_general_nopad_ci;
TRUNCATE t1;
INSERT INTO t1 VALUES (1,'f');

INSTALL SONAME 'ha_rocksdb';
CREATE TABLE t (c CHAR(1)) ENGINE=InnoDB PARTITION BY LIST COLUMNS (c) (PARTITION p VALUES IN ('a','b'));
CREATE TRIGGER tr AFTER INSERT ON t FOR EACH ROW UPDATE t t2 SET t2.c1='No' WHERE t2.c2=(SELECT 1 FROM t);
RENAME TABLE t TO t2;
CREATE TABLE t (c INT KEY) ENGINE=RocksDB PARTITION BY KEY(c) PARTITIONS 6;
LOCK TABLES t WRITE,t2 WRITE;
TRUNCATE t;
ALTER TABLE t ADD KEY i1 USING BTREE (c);
