CREATE TABLE t1 ( id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, body MEDIUMTEXT,FULLTEXT KEY ftidx (body)) ENGINE=InnoDB;
INSERT INTO t1 (body) SELECT REPEAT('megaword ', 30) FROM seq_1_to_260;
SET GLOBAL innodb_optimize_fulltext_only = ON;
DELETE FROM t1 WHERE id = 1;
OPTIMIZE TABLE t1;
