CREATE TABLE t (a INT KEY) ENGINE=INNODB WITH SYSTEM VERSIONING PARTITION BY KEY() PARTITIONS 3;
XA START 'a';
INSERT INTO t VALUES (1),(2),(3),(4),(5),(6),(7),(8);
SET TIMESTAMP=+1;
DELETE FROM t;
INSERT INTO t VALUES (1),(2);
DELETE FROM t;
