CREATE TABLE t1 (c1 DATE KEY,c2 INT(1) ZEROFILL,c3 DATE) ENGINE=InnoDB;
SET unique_checks=0,foreign_key_checks=0,autocommit=0;
CREATE TABLE t2 LIKE t1;
DROP TABLE t1;
CREATE TABLE t1 (c1 INT)Engine=InnoDB;
BINLOG 'AMqaOw8BAAAAdAAAAHgAAAAAAAQANS42LjM0LTc5LjEtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXAAEGggAAAAICAgCAAAACgoKGRkAAYVx w2w=';
INSERT INTO t1 VALUES(1);
BINLOG 'iiZAZwIBAAAAjAAAAKTEAAAAADQAAAAAAAAABAAALQAAAAAAAQEAACBUAAAAAAYDc3RkBAgACAAACYH2AgAAAAAAAIIEDAEAAAAAAAB0ZXN0AGFsdGVyIHRhYmxlIHQyIGFkZCBjb2x1bW4gZCBpbnQsIGZvcmNlLCBhbGdvcml0aG09Y29weU8mFH4=';
