INSTALL PLUGIN Spider SONAME 'ha_spider';
CREATE TABLE t (c INT) ENGINE=Spider PARTITION BY HASH (c) PARTITIONS 2;
ALTER TABLE t ADD c4 DECIMAL AFTER c2;
SET SESSION transaction_read_only=1;
HANDLER t OPEN;
HANDLER t READ FIRST LIMIT 2,2;
HANDLER t READ FIRST;
