SET sql_mode='';
CREATE TABLE t1 (c1 BIT KEY,c2 INT) ENGINE=InnoDB PARTITION BY LINEAR HASH(c1) PARTITIONS 822;
ALTER TABLE t1 ADD INDEX idx1(c2);
INSERT INTO t1 PARTITION (p1) VALUES (1,1);
UPDATE t1 SET c1=(TIME_FORMAT(1,1)MOD 1) DIV (18 ^ SECOND(1));
WITH cte AS(SELECT 1 FROM t1) SELECT 1 FROM cte;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
SET GLOBAL innodb_buffer_pool_size=+1;
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT KEY,KEY(c1)) ENGINE=InnoDB PARTITION BY HASH(c1) PARTITIONS 2;
CREATE TABLE t2 (c1 INT) ENGINE=InnoDB;
XA START 'a';
INSERT INTO t1 VALUES (0);
INSERT INTO t2 SELECT 0 FROM t1;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT PRIMARY KEY,c2 TINYINT,KEY(c2)) ENGINE=InnoDB PARTITION BY LINEAR HASH(c1) PARTITIONS 16;
INSERT INTO t1 PARTITION (p1) VALUES (1,0);
UPDATE t1 SET c1=0;
WITH cte AS(SELECT 1 FROM t1) SELECT 1 FROM cte;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
SET GLOBAL innodb_buffer_pool_size=+1;
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=InnoDB PARTITION BY LINEAR HASH(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (1);
UPDATE t1 SET c1=0;
SELECT * FROM t1;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=InnoDB PARTITION BY LINEAR HASH(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (0);
SELECT c1 FROM t1 ORDER BY c1;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY`=(1);
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT PRIMARY KEY, c2 INT, KEY idx1(c2)) ENGINE=InnoDB PARTITION BY LINEAR HASH(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (0,10),(2,20);
SELECT c2 FROM t1 ORDER BY c2;
HANDLER t1 OPEN;
HANDLER t1 READ idx1=(10);
HANDLER t1 READ idx1 PREV;
