CREATE TABLE t1(a INT);
DELIMITER $$
CREATE FUNCTION f() RETURNS INT BEGIN EXECUTE IMMEDIATE 'LOCK TABLES t1 WRITE'; RETURN 1; END$$
CREATE PROCEDURE p() BEGIN DECLARE v INT DEFAULT f(); END$$
DELIMITER ;
CALL p();
