CREATE TABLE t (id INT KEY,a VARCHAR(16) collate utf8_unicode_ci DEFAULT'',INDEX (a (4))) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ENGINE=InnoDB;
ALTER TABLE t CHANGE a a VARCHAR(3000) CHARACTER SET utf8mb4;
