CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2),(3);
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW SET NEW = OLD;
UPDATE t1 SET a = a + 100;

CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1);
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW SET NEW = OLD;
UPDATE t1 SET a = a + 100; 
UPDATE t1 SET a = a + 100;

CREATE TABLE t1 (a INT, b INT);
CREATE TABLE t2 (a INT, b INT);
INSERT INTO t1 VALUES (1,1),(2,2);
DELIMITER $$
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW  BEGIN SET NEW = OLD; INSERT INTO t2 VALUES (NEW.a, NEW.b); END; $$
DELIMITER ;
UPDATE t1 SET a = 99;
