CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2);
CREATE TABLE t2 (b INT);
INSERT INTO t2 VALUES (2),(3);
SET SESSION USE_STAT_TABLES= NEVER;
SET SESSION JOIN_CACHE_LEVEL=3;
SET GLOBAL TABLE_OPEN_CACHE=@@global.table_open_cache;
SELECT * FROM t1 JOIN t2 ON t2.b = t1.a;

CREATE TABLE t1(c1 INT) ENGINE=InnoDB; 
CREATE TABLE t2(c2 INT) ENGINE=InnoDB;
SELECT * FROM t1;
SET join_cache_level=3,use_stat_tables='never';
SELECT * FROM (SELECT * FROM t2 JOIN t1) AS ta NATURAL JOIN (SELECT * FROM t2 NATURAL JOIN t1) AS tb;

CREATE TABLE t1(c1 INT) ENGINE=InnoDB; 
CREATE TABLE t2(c2 INT) ENGINE=InnoDB;
SELECT * FROM t1;
SET join_cache_level=3,use_stat_tables='never',optimizer_switch="hash_join_cardinality=on";
SELECT * FROM (SELECT * FROM t2 JOIN t1) AS ta NATURAL JOIN (SELECT * FROM t2 NATURAL JOIN t1) AS tb;

CREATE TABLE t (a INT) ENGINE=InnoDB;
SELECT * FROM t;
SET JOIN_cache_level=4, use_stat_tables=NEVER;
SELECT STRAIGHT_JOIN * FROM (t AS x JOIN t AS y) JOIN t AS z ON z.a=x.a;
