INSTALL PLUGIN spider SONAME 'ha_spider.so';
SET SESSION spider_same_server_link=ON;
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS (HOST '127.0.0.1', DATABASE 'test', USER 'root', PORT 21562, PASSWORD '');
CREATE TABLE test_table (c1 int(11) NOT NULL, c2 TEXT DEFAULT NULL, PRIMARY KEY (c1)) ENGINE=SPIDER COMMENT='wrapper "mysql", table "test_table"'  PARTITION BY LIST (c1) (PARTITION pt0 VALUES IN (0) ENGINE = SPIDER, PARTITION pt1 VALUES IN (1) ENGINE=SPIDER COMMENT='srv "d"');
INSERT INTO test_table VALUES (100,'a');
