CREATE OR REPLACE TABLE t1 (c1 INT) ENGINE=INNODB PARTITION BY RANGE (c1) (PARTITION p0 VALUES LESS THAN (100));
SET unique_checks=0, foreign_key_checks=0;
CREATE OR REPLACE TABLE t2 (c1 INT) ENGINE=INNODB PARTITION BY RANGE (c1) (PARTITION p0 VALUES LESS THAN (100));
CREATE TABLE t3 (c1 CHAR(1));
XA BEGIN 'a';
INSERT INTO t1 values (1);
INSERT INTO t3 VALUES (1,a);
INSERT INTO t2 VALUES (1);
INSERT INTO t1 SELECT seq FROM seq_1_to_100; 
