CREATE VIEW c AS SELECT 1;
PREPARE s FROM 'ALTER VIEW c AS SELECT 2';
EXECUTE s;
EXECUTE s;

SET @a='';
SET NAMES utf8;
CREATE TABLE t (c INT KEY,c2 BLOB,c3 BLOB);
PREPARE s5 FROM 'DELETE FROM t WHERE c=?';
CREATE TEMPORARY TABLE t (KEYc INT,c CHAR,c2 CHAR,INDEX sec_index (c));
EXECUTE s5 USING @arg;
EXECUTE s5 USING @a;
