CREATE TABLE t (id INT PRIMARY KEY) ENGINE=innodb;
ALTER TABLE t MODIFY id CHAR(0);
UPDATE t SET id = 1;

CREATE TABLE t (a TEXT,b CHAR(1) KEY) CHARSET=utf8 ENGINE=InnoDB;
ALTER TABLE t CHANGE COLUMN b c CHAR(0);
UPDATE t SET c=0;

set sql_mode='';
CREATE TABLE t (a INT KEY,b INT);
INSERT INTO t VALUES (2,0);
ALTER TABLE t CHANGE COLUMN a a BINARY (0);
REPLACE INTO t VALUES (4,4);

set sql_mode='';
CREATE TABLE t (a INT KEY);
INSERT INTO t VALUES ();
ALTER TABLE t CHANGE COLUMN a a BINARY (0);
UPDATE t SET a=((SELECT * FROM t));
