CREATE TABLE t1 (a INT, b INT);
INSERT INTO t1 VALUES (1,2);
delimiter $$
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW BEGIN IF NEW = OLD THEN SET @x = 1; END IF; END $$
delimiter ;
UPDATE t1 SET a = 9;
