SET SQL_MODE='';
SET @cmd="ALTER TABLE non.existing ENGINE=NDB";
PREPARE stmt FROM @cmd;
EXECUTE stmt;
EXECUTE stmt;

SET sql_mode='';
CREATE PROCEDURE p1 (IN i INT) ALTER TABLE t ENGINE=none;
CALL p1 (1);
CALL p1 (1);

SET sql_mode='';
SET @c:="ALTER TABLE t ENGINE=none";
PREPARE s FROM @c;
EXECUTE s;
EXECUTE s;

SET sql_mode='';
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
SET @c:="ALTER TABLE t1 ENGINE=none";
PREPARE s FROM @c;
EXECUTE s;
SHOW WARNINGS;
EXECUTE s;
SHOW WARNINGS;

SET sql_mode='';
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
SET @c:="ALTER TABLE t1 ENGINE=none";
PREPARE s FROM @c;
EXECUTE s;
SET sql_mode='NO_ENGINE_SUBSTITUTION';
EXECUTE s;

SET sql_mode='';
CREATE TEMPORARY TABLE t2 (a INT) ENGINE=InnoDB;
SET @e:="ALTER TABLE t2 ENGINE=none";
PREPARE s3 FROM @e;
EXECUTE s3;
EXECUTE s3;
CREATE TABLE t4 (a INT) ENGINE=InnoDB PARTITION BY HASH(a) PARTITIONS 2;
SET @g:="ALTER TABLE t4 ENGINE=none";
PREPARE s5 FROM @g;
EXECUTE s5;
EXECUTE s5;
CREATE PROCEDURE p2 () ALTER TABLE t4 ENGINE=none;
CALL p2 ();
CALL p2 ();
