CREATE TEMPORARY TABLE t1 (i INT) ENGINE=INNODB;
CREATE TABLE t2 (i INT) ENGINE=ARIA ;
OPTIMIZE TABLE t1,t2;

CREATE TEMPORARY TABLE t1 (f INT) ENGINE=INNODB;
CREATE TEMPORARY TABLE t2 (f INT) ENGINE=INNODB;
OPTIMIZE LOCAL TABLE t1,t2;

CREATE TABLE t1 (c INT) ENGINE=Aria;
CREATE TEMPORARY TABLE t2 (c INT) ENGINE=InnoDB;
REPAIR TABLE t2,t1;
