INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS(HOST'',DATABASE'',USER'',PORT 16000,PASSWORD'');
CREATE TABLE t(c INT) ENGINE=SPIDER COMMENT='table "st"' PARTITION BY LIST COLUMNS(c)(PARTITION pt DEFAULT COMMENT='srv "d"' ENGINE=SPIDER);
INSERT INTO t SELECT * FROM t;
