SET SESSION lc_time_names=zh_hk;
CREATE TABLE t (c CHAR,cc TEXT AS (CONCAT (c,IF(c=c,DATE_FORMAT(c,''),'')))) ENGINE=InnoDB;
SET NAMES utf8;
INSERT INTO t VALUES (0,0);
INSERT INTO t VALUES (0,0);
INSERT INTO t VALUES (0,0);

SET NAMES gbk;
CREATE TABLE t (id INT,js CHAR,t TIME AS (CAST(JSON_VALUE (JSON_EXTRACT(js,CONCAT ('',DAYNAME (curDATE()))),'') AS TIME)) VIRTUAL);
UPDATE t SET name='U +0B HIRAGANA LETTER HO';
INSERT INTO t VALUES (0,0);
INSERT INTO t SELECT 0 t;
