# mysqld options required for replay: --wsrep-ignore-apply-errors=0
USE test;
CREATE TABLE t1 ENGINE=MEMORY AS SELECT REPEAT ('a', 5) AS s1 LIMIT 0;
SET collation_connection='utf8_general_ci';
CREATE TABLE t1 (a CHAR(1)) DEFAULT CHARACTER SET utf8mb4;
SELECT 1;
EXPLAIN SELECT 1;
SELECT length (DATA) AS len FROM (SELECT RPAD (_utf8 0xD0B1, 65535, _utf8 0xD0B2) AS DATA) AS sub;
SELECT length (DATA) AS len FROM (SELECT RPAD (_utf8 0xD0B1, 65535, _utf8 0xD0B2) AS DATA) AS sub;
SELECT length (DATA) AS len FROM (SELECT RPAD (_utf8 0xD0B1, 65535, _utf8 0xD0B2) AS DATA) AS sub;
SELECT 1;
EXPLAIN SELECT * FROM t1 WHERE a NOT IN (SELECT s1 FROM t1);
EXPLAIN SELECT * FROM t1 WHERE a NOT IN (SELECT s1 FROM t1);
EXPLAIN SELECT * FROM t1 WHERE a NOT IN (SELECT s1 FROM t1);
EXPLAIN SELECT * FROM t1 WHERE a NOT IN (SELECT s1 FROM t1);
BACKUP STAGE START;
BACKUP STAGE block_commit;

