CREATE TABLE t1 (pk INT AUTO_INCREMENT, i INT, e ENUM('foo','bar') AS (i) VIRTUAL, PRIMARY KEY (pk)) ENGINE=InnoDB;
INSERT INTO t1 (i) VALUES (1),(NULL),(1),(NULL),(2),(1),(2),(NULL);
ALTER TABLE t1 ADD COLUMN f DECIMAL;
CHECKSUM TABLE t1;

SET SQL_MODE='';
CREATE TABLE t (a INT,b INT GENERATED ALWAYS AS (a+1),c INT) ENGINE=InnoDB PARTITION BY RANGE (b) (PARTITION p0 VALUES LESS THAN (6),PARTITION p VALUES LESS THAN (11),PARTITION p2 VALUES LESS THAN (16),PARTITION p3 VALUES LESS THAN (21));
ALTER TABLE t ENGINE=MyISAM;
INSERT INTO t VALUES (0,0,1);
CHECKSUM TABLE t;
