SET GLOBAL INNODB_IMMEDIATE_SCRUB_DATA_UNCOMPRESSED=1;
CREATE TEMPORARY TABLE tmp ENGINE=InnoDB AS SELECT1;
DROP TABLE tmp;

CREATE TEMPORARY TABLE t (c INT) ENGINE=InnoDB;
SET GLOBAL innodb_immediate_scrub_data_uncompressed=ON;
TRUNCATE TABLE t;
