SET pseudo_slave_mode=1;
CREATE GLOBAL TEMPORARY TABLE t1 (c INT) ON COMMIT PRESERVE ROWS;
CREATE TEMPORARY TABLE t2 (d INT);
LOCK TABLES t1 WRITE;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t1 (c INT) SELECT * FROM t2;
