SET sql_mode='';
CREATE TABLE t (c INT KEY) ENGINE=Aria;
INSERT INTO t VALUES (1);
REPAIR TABLE t QUICK USE_FRM;
INSERT INTO t VALUES (NULL);
UPDATE t SET c=NULL;

SET sql_mode='';
CREATE TABLE t (c CHAR KEY,c2 JSON,c3 DATE) ENGINE=Aria;
INSERT INTO t VALUES (1,1e3,1);
REPAIR LOCAL TABLE t QUICK USE_FRM;
UPDATE t SET c=(WEEK (1,0)* RADIANS (1) * LOCALTIME * 1) / (+ 1 / DEGREES (-1) + 1);
