DROP TABLE mysql.gtid_slave_pos;
CREATE TABLE t (a INT KEY,b INT) ENGINE=INNODB;
UPDATE t SET a=b;
CREATE EVENT t_p_event ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY DO INSERT INTO t SELECT 1,1;
