CREATE TEMPORARY TABLE t1 (i INT) ENGINE=INNODB;
CREATE TABLE t2 (i INT) ENGINE=ARIA ;
OPTIMIZE TABLE t1,t2;

CREATE TEMPORARY TABLE t1 (f INT) ENGINE=INNODB;
CREATE TEMPORARY TABLE t2 (f INT) ENGINE=INNODB;
OPTIMIZE LOCAL TABLE t1,t2;
