SET sql_mode='';
CREATE TABLE t (c INT);
LOCK TABLE t WRITE;
CREATE OR REPLACE TABLE t (a INT AS (CONNECTION_ID()));
CREATE TRIGGER a BEFORE INSERT ON t FOR EACH ROW SET @a:=1;
INSERT INTO t VALUES ('');
