CREATE TABLE t0 (f0 TEXT,FULLTEXT KEY(f0)) ENGINE=InnoDB;
INSERT INTO t0 VALUES (0);
ALTER TABLE t0 ADD COLUMN s BIGINT UNSIGNED AS ROW START,ADD COLUMN e BIGINT UNSIGNED AS ROW END,ADD period FOR SYSTEM_TIME(s,e),ADD SYSTEM VERSIONING,ALGORITHM=copy;
DELETE FROM t0;
