CREATE TABLE t (a INT) ENGINE=InnoDB;
CREATE VIEW v AS SELECT a FROM t;
DROP TABLE t;
CREATE TABLE t (a INT) ENGINE=MERGE;
UPDATE v SET a=0;

CREATE TABLE t (a INT) ENGINE=MERGE;
CREATE VIEW v AS SELECT a FROM t;
UPDATE v SET a=0;
