INSTALL SONAME 'ha_federatedx';
CREATE SERVER fedlink FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user '',PASSWORD ''); 
CREATE TABLE t (id INT);
CREATE TABLE fed_t ENGINE=FEDERATED CONNECTION='fedlink/t';
INSERT INTO fed_t VALUES (1);
START TRANSACTION;
SELECT * FROM fed_t;
SAVEPOINT sp;
SAVEPOINT sp;

INSTALL SONAME 'ha_federatedx.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user '',PASSWORD '');
CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TABLE t2 CONNECTION='srv/t1' ENGINE=FEDERATED;
XA START 'a';
INSERT INTO t2 VALUES (0,1);
SAVEPOINT sv;
SAVEPOINT sv;
