CREATE TABLE t1 (pk INT KEY,c TEXT) ENGINE=InnoDB;
INSERT INTO t1 VALUES(1,"saahil"),(2,"mariadb"),(3,"mysql"),(4,"mysqll");
ALTER TABLE t1 ADD FULLTEXT KEY text (c);
DELETE FROM t1 WHERE pk> 3;
SET GLOBAL INNODB_OPTIMIZE_FULLTEXT_ONLY=1;
OPTIMIZE TABLE t1;
