CREATE TABLE t1 (a DECIMAL, b INT);
INSERT INTO t1 VALUES (1,1),(2,2); # optional
CREATE VIEW v1 AS SELECT * FROM ( SELECT * FROM t1 WHERE a <> RAND() ) sq;
SELECT * FROM v1 WHERE b > 0;

CREATE TABLE c (c INT);
INSERT INTO c SELECT * FROM (SELECT * FROM (SELECT * FROM c AS d ORDER BY c,c) AS e NATURAL JOIN c AS f) AS g WHERE c=1;
