SET SQL_MODE='ORACLE';
CREATE TABLE t (c CHAR(1)) ENGINE=InnoDB;
INSERT INTO t VALUES(0), (1), (1), (1), (1);
SELECT * FROM t UNION SELECT * FROM t INTERSECT ALL SELECT * FROM t;

SET SQL_MODE='ORACLE';
CREATE TABLE t (c CHAR(1)) ENGINE=InnoDB;
SELECT * FROM t UNION SELECT * FROM t INTERSECT ALL SELECT * FROM t;

SET GLOBAL sql_mode='ORACLE';
CREATE TABLE t0 (b INT KEY);
SET SESSION sql_mode=DEFAULT;
ALTER TABLE t0 ADD c0 INT NOT NULL FIRST;
INSERT INTO t0 VALUES (0,0);
SELECT * FROM t0 UNION SELECT * FROM t0 INTERSECT ALL SELECT * FROM t0;

SET @@sql_mode='ORACLE';
CREATE TABLE t (a INT);
INSERT INTO t VALUES (1);
SELECT * FROM t UNION SELECT * FROM t INTERSECT ALL SELECT * FROM t;

SET GLOBAL sql_mode='ORACLE';
SET sql_mode=DEFAULT;
CREATE TABLE t (a CHAR KEY);
INSERT INTO t VALUES (0);
SELECT * FROM t UNION SELECT * FROM t INTERSECT ALL SELECT * FROM t;

CREATE TABLE t1 (a CHAR(1));
SET STATEMENT sql_mode='no_engine_substitution' FOR ALTER TABLE t1 CHANGE a a CHAR(1) CHARACTER SET utf8mb4 NOT NULL;
SET sql_mode='ORACLE';
INSERT INTO t1 VALUES ('a');
SELECT * FROM t1 UNION SELECT * FROM t1 except ALL SELECT * FROM t1;

CREATE TABLE t (a INT);
SET sql_mode=ORACLE;
SELECT * FROM t UNION SELECT * FROM t INTERSECT ALL SELECT * FROM t;

CREATE TABLE t (c CHAR(1) NOT NULL) DEFAULT COLLATE=utf32_unicode_ci;
SET GLOBAL sql_mode=ORACLE;
SET sql_mode=DEFAULT;
INSERT t VALUES (1);
SELECT * FROM t UNION SELECT * FROM t INTERSECT ALL SELECT * FROM t;

SET GLOBAL sql_mode='ORACLE';
SET sql_mode=DEFAULT;
CREATE TABLE t (c INT) ENGINE=InnoDB;
INSERT INTO t (c) VALUES (1);
SELECT * FROM t UNION SELECT * FROM t EXCEPT ALL SELECT * FROM t;

SET GLOBAL sql_mode='ORACLE';
SET sql_mode=DEFAULT;
CREATE TABLE t (c INT KEY) ENGINE=InnoDB;
INSERT INTO t (c) VALUES (1);
SELECT * FROM t UNION SELECT * FROM t EXCEPT ALL SELECT * FROM t;
