CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2);
CREATE TABLE t2 (b INT, c INT);
INSERT INTO t2 VALUES (1,10),(2,20);
CREATE TABLE t3 (d INT);
INSERT INTO t3 VALUES (1),(2);
CREATE PROCEDURE sp() SELECT * FROM t1 JOIN t2 JOIN t3 USING (x); 
CALL sp;
CALL sp;

CREATE TABLE t1 (c1 INT,c2 INT);
CREATE TABLE t2 (c INT,c2 INT);
CREATE PROCEDURE p2 (OUT i INT,OUT o INT) READS SQL DATA DELETE a2,a3 FROM t1 AS a1 JOIN t2 AS a2 NATURAL JOIN t2 AS a3;
CALL p2 (@c,@a);
CALL p2 (@a,@c);

CREATE TABLE t (c INT,c2 INT);
CREATE TABLE t2 (c INT,c2 INT);
CREATE PROCEDURE p (INOUT i1 INT,INOUT i2 TIME) DETERMINISTIC SELECT (SELECT (SELECT SUM(DISTINCT 'q')) OR (SELECT c3 FROM t AS a1 STRAIGHT_JOIN t AS a2 NATURAL JOIN t2 AS a3)) AND (SELECT (SELECT (SELECT c3 FROM t) AND(SELECT c3,c FROM t AS a1 JOIN t2 AS a2))) OR ( (SELECT c FROM t2) AND(SELECT c3,c FROM t)) OR (SELECT * FROM t);
CREATE TABLE t (c INT);
CALL p (@c,@b);
CREATE TEMPORARY TABLE t (c INT);
CALL p (@b,@c);
