CREATE TABLE t(c INT,v2 INT,v3 INT UNIQUE) ENGINE=InnoDB;
INSERT INTO t(v2)VALUES ((v2,c,v2)=(0,(SELECT 1 FROM (SELECT 1 FROM t AS v8) AS v6 JOIN t AS v5 WINDOW v4 AS(PARTITION BY c AND 1 BETWEEN(SELECT v2 GROUP BY c WINDOW v9 AS(PARTITION BY c)) AND 1)),0));
