INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user 'Spider',PASSWORD 'PWD123');
CREATE TABLE t (c INT) ENGINE=InnoDB;
CREATE TABLE t2 (DATE DATETIME,KEY DATE (DATE)) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
EXPLAIN SELECT 1 FROM DUAL WHERE (0) IN (SELECT * FROM t2);
