INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SET SESSION autocommit=0, GLOBAL completion_type=2;
CREATE USER Spider@localhost IDENTIFIED BY '';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER 'Spider',PASSWORD'');
CREATE TABLE t (a INT KEY) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
INSERT INTO t VALUES (1);
DROP PROCEDURE IF EXISTS p;
