INSTALL SONAME 'ha_duckdb';
CREATE TABLE t (c1 INT KEY) ENGINE=DuckDB;
INSERT INTO t VALUES (1),(1);
ALTER TABLE t ADD c2 INT NOT NULL;
ALTER TABLE t PARTITION BY HASH (c1) (PARTITION p1,PARTITION p2);
