INSTALL SONAME 'ha_connect.so';
CREATE TABLE t1 (c1 INT) ENGINE=CONNECT TABLE_TYPE=FIX FILE_NAME='/tmp/c_fix';
UPDATE t1 SET c1=123;
UNINSTALL SONAME 'ha_connect.so';
ALTER IGNORE TABLE t1 ENGINE=InnoDB;
