SET sql_mode=ORACLE;
CREATE DATABASE db1;
USE db1;
DELIMITER $$
CREATE PACKAGE a_pkg AS TYPE arec IS RECORD (x INT, y VARCHAR(10));END;$$
CREATE PACKAGE b_pkg AS TYPE brec IS RECORD (p INT, q VARCHAR(10)); TYPE bcur IS REF CURSOR RETURN a_pkg.arec; END;$$
CREATE OR REPLACE PACKAGE a_pkg AS TYPE arec IS RECORD (x INT, y VARCHAR(10)); TYPE acur IS REF CURSOR RETURN b_pkg.brec;END;$$
CREATE PROCEDURE p_cycle AS c a_pkg.acur; BEGIN NULL; END; $$
DELIMITER ;
