INSTALL SONAME 'ha_federatedx';
CREATE GLOBAL TEMPORARY TABLE t1 (c INT) ENGINE=MEMORY ON COMMIT PRESERVE ROWS;
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'root@localhost', PASSWORD '');
CREATE GLOBAL TEMPORARY TABLE t3 (c INT) CONNECTION='srv/t1' ENGINE=Federated ON COMMIT DELETE ROWS;
XA START 'a','b',2;
INSERT INTO t3 (a,b) VALUES (1,1);
SAVEPOINT sp1;
RELEASE SAVEPOINT sp1;
