INSTALL SONAME 'ha_connect';
CREATE TABLE t1( name CHAR(20) NOT NULL, birth CHAR(10) NOT NULL, children SMALLINT(2) NOT NULL) ENGINE=CONNECT TABLE_TYPE=CSV FILE_NAME='/tmp/csv_unterminated.csv' SEP_CHAR=';' QUOTED=1;
SELECT * FROM t1;
