SET sql_mode='';
CREATE TABLE t2 (a INT GENERATED ALWAYS AS (1) VIRTUAL,KEY(a)) ENGINE=MyISAM;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
XA START 'a';
UPDATE t1,non_existing_1 SET 1=1;
DELETE FROM mysql.db;
INSERT INTO t1 VALUES (1);
INSERT INTO t2 (SELECT 1);
INSERT INTO non_existing_2 VALUES (1);  # Crashing on 2nd execution on 10.6 (opt), 10.8 (dbg+opt), 10.10 (opt)
UPDATE t2 SET a=1;
SELECT SLEEP (1);  # Shows server gone

SET sql_mode='';
CREATE TABLE t2 (a INT GENERATED ALWAYS AS (1) VIRTUAL,KEY(a)) ENGINE=MyISAM;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
XA START 'a';
UPDATE t1,non_existing_1 SET 1=1;
DELETE FROM mysql.db;
INSERT INTO t1 VALUES (1);
INSERT INTO t2 (SELECT 1);
INSERT INTO non_existing_2 VALUES (1);
UPDATE t2 SET a=1;
INSERT INTO non_existing_2 VALUES (1);
SELECT SLEEP (1);

SET sql_mode='';
CREATE TABLE t2 (a INT GENERATED ALWAYS AS (1) VIRTUAL,KEY(a)) ENGINE=MyISAM;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
XA START 'a';
UPDATE t1,non_existing_1 SET tb=tb;
DELETE FROM mysql.db;
INSERT INTO t1 VALUES (1);
INSERT INTO t2 (SELECT 1);
INSERT INTO non_existing_2 VALUES (1);
UPDATE t2 SET a=1;
SELECT SLEEP (1);

SET sql_mode='';
CREATE TABLE t (a INT GENERATED ALWAYS AS (1) VIRTUAL,KEY(a)) ENGINE=MyISAM;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
XA START 'a';
UPDATE t1,t2 SET tb=tb;
DELETE FROM mysql.db;
INSERT INTO t1 VALUES (1);
INSERT INTO t (SELECT 1);
INSERT INTO ti VALUES (1);
UPDATE t SET a=1;
SELECT SLEEP (1);

SET SQL_MODE='';
CREATE TABLE t (a INT GENERATED ALWAYS AS(1) VIRTUAL,KEY(a)) ENGINE=MyISAM;
INSERT INTO t SELECT 1;
SELECT * FROM non_existing_tbl;
SELECT * FROM t;
SHOW OPEN TABLES LIKE '';
