CREATE TABLE t1 (a INT, KEY(a)) PARTITION BY HASH(a);
HANDLER t1 OPEN h;
HANDLER h READ a NEXT;
HANDLER h READ a NEXT;

CREATE TABLE t(c INT,c2 DATE,PRIMARY KEY(c2)) PARTITION BY RANGE(YEAR(c2)) (PARTITION p VALUES LESS THAN (1));
HANDLER t OPEN;
HANDLER t READ `PRIMARY` NEXT;
HANDLER t READ `PRIMARY` NEXT;

CREATE TABLE t (c INT KEY) ENGINE=InnoDB WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME(PARTITION p_hist HISTORY,PARTITION p_cur CURRENT);
INSERT INTO t VALUES (1);
SET SESSION optimizer_switch='mrr=ON,mrr_sort_keys=ON';
SET SESSION JOIN_cache_level=8;
SELECT * FROM t AS a1 LEFT JOIN t AS a2 ON a1.c=a2.c;
SELECT * FROM t AS a1 LEFT JOIN t AS a2 ON a1.c=a2.c AND a1.c!=a2.c;
