CREATE TABLE t (id INT,KEY(id))Engine=InnoDB COMMENT='';
ALTER TABLE t ADD COLUMN c BIGINT UNSIGNED AS ROW START INVISIBLE,ADD COLUMN c2 BIGINT UNSIGNED AS ROW END INVISIBLE,ADD PERIOD FOR SYSTEM_TIME(c,c2),ADD SYSTEM VERSIONING;
INSERT INTO t VALUES (0,+1,0);
SET max_session_mem_used=1;
SELECT * FROM t WHERE c IN (NOW(),NOW());
