CREATE TABLE t1 (c1 INT,c2 INT,PRIMARY KEY(c1)) PARTITION BY KEY ALGORITHM=2 (c1) PARTITIONS 20;
HANDLER t1 OPEN AS h1;
HANDLER h1 READ `PRIMARY`=(1);
HANDLER h1 READ `PRIMARY` PREV;
HANDLER h1 READ `PRIMARY` PREV;
