CREATE TABLE t(c BIGINT)PARTITION BY HASH (c) PARTITIONS 1;
SELECT * FROM t WHERE c BETWEEN 0 AND 18446744073709551615;

CREATE TABLE t (a BIGINT UNSIGNED,PRIMARY KEY(a)) PARTITION BY KEY(a) PARTITIONS 1;
SELECT * FROM t WHERE a IN (0x7ffffffffffffffe,0x7fffffffffffffff);
