SET sql_mode=ORACLE;
CREATE TABLE t (id INT PRIMARY KEY, a INT, b INT);
INSERT INTO t VALUES (1,5,6);
DELIMITER $$
CREATE PROCEDURE p1 AS r t%ROWTYPE; BEGIN SELECT a INTO r.a FROM t WHERE id=1; END;$$
DELIMITER ;
CALL p1;
