CREATE OR REPLACE TABLE t1 (a INT DEFAULT @a:='');
INSERT INTO t1 VALUES ();
KILL CONNECTION CONNECTION_ID();
INSERT INTO t1 VALUES ();

CREATE TABLE t (a VARCHAR(10), b BLOB AS (@x := 'foobarqux'));
INSERT INTO t (a) VALUES ('');
SELECT * FROM t;
KILL CONNECTION CONNECTION_ID();
SELECT * FROM t;
