INSTALL PLUGIN example SONAME 'ha_example';
CREATE TABLE t1(a INT) ENGINE=EXAMPLE;
SELECT * FROM t1;
UNINSTALL PLUGIN example;
RENAME TABLE t1 TO t2;

INSTALL SONAME 'ha_connect';
CREATE TABLE t ENGINE=CONNECT AS SELECT 1 t2;
UNINSTALL SONAME 'ha_connect';
RENAME TABLE t TO t2,t2 TO t3,t3 TO t5;
