CREATE TEMPORARY TABLE t (a INT) ENGINE=InnoDB;
CREATE TABLE t(a INT,b INT) ENGINE=InnoDB;
DROP TABLE t;
ALTER TABLE t DISCARD TABLESPACE;
SET sql_mode= 'TRADITIONAL';
ALTER TABLE t ADD c DATE NOT NULL;
