CREATE TABLE t1 (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,pt POINT NOT NULL,SPATIAL INDEX(pt)) ENGINE=InnoDB;
INSERT INTO t1 (pt) VALUES (ST_GeomFromText('POINT(1 1)'));
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN;
SELECT id, ST_AsText(pt) FROM t1 WHERE ST_Within(pt, ST_GeomFromText('POLYGON((0 0, 100 0, 100 100, 0 100, 0 0))'));
INSERT INTO t1 (pt) VALUES (ST_GeomFromText('POINT(5 5)'));
SELECT COUNT(*) = 1 FROM information_schema.innodb_trx WHERE trx_state = 'LOCK WAIT';
ROLLBACK;
