CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES ('0.0e'),('0.0e+0');
SELECT * FROM t WHERE COALESCE(c)=0.0;

CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES (1.3),(1.1);
SELECT * FROM t PROCEDURE ANALYSE();

SET sql_mode='';
CREATE TABLE t (c CHAR(10) KEY);
INSERT INTO t VALUES (1.755555555);
SELECT * FROM t PROCEDURE ANALYSE();

CREATE TABLE t (c BIGINT);
INSERT INTO t VALUES (1000000000000000);
SELECT * FROM t PROCEDURE ANALYSE(0,0);

SET sql_buffer_result=1;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
CREATE TABLE tm (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
CREATE TABLE t1 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
CREATE TABLE t2 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "tm"';
INSERT INTO t VALUES (0,1,0),(1,0,0),(2,0,0);
INSERT INTO tm VALUES (0,1,0),(1,0,0),(2,0,0);
SELECT * FROM t1 HAVING c1=(SELECT t.c1 AS c FROM t2 t ORDER BY (SELECT MIN(t1.c1+tt.c1) FROM t2 tt));
