CREATE TABLE t (a TEXT,b TEXT AS (a),c TEXT AS (CONCAT (a)),FULLTEXT KEY a (a));
ALTER TABLE t ADD COLUMN c1 BIGINT UNSIGNED AS ROW START INVISIBLE,ADD COLUMN c2 BIGINT UNSIGNED AS ROW END INVISIBLE,ADD PERIOD FOR SYSTEM_TIME(c1,c2),ADD SYSTEM VERSIONING;
INSERT INTO t (a) VALUES (1);
