CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2),(3);
DELIMITER $$
CREATE PROCEDURE p1() BEGIN DECLARE c CURSOR FOR SELECT * FROM t1 WHERE a = 1; OPEN c USING 1; CLOSE c; END;$$
DELIMITER ;
CALL p1;
