CREATE TABLE t (c INT) ENGINE=MyISAM UNION=(t,t0) INSERT_METHOD=FIRST;
INSERT INTO t VALUES (0);
SET SESSION profiling=ON;
SELECT * INTO outfile 'a' FROM t;
DROP TABLE t;
CREATE TABLE t (a INT GENERATED ALWAYS AS (0) VIRTUAL,KEY(a)) ENGINE=MyISAM;
LOAD DATA INFILE 'a' REPLACE INTO TABLE t;
CREATE TABLE t0 (a INT) ENGINE=MyISAM;
UPDATE t SET a=0;
