# CS 10.5.26 13ca1ce565c38ab41a6979a5d331efe78d840db1 (Optimized)

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
SET GLOBAL init_connect='SET autocomit=0';
CREATE TABLE customer (id INT NOT NULL, PRIMARY KEY(id)) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE gis_poINT(p1 POINT NOT NULL, p2 POINT NOT NULL, SPATIAL KEY k1 (p1), SPATIAL KEY k2 (p2)) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"' COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE t5 (a INT NOT NULL, b CHAR(20), KEY(a)) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"' COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
XA BEGIN 'a','ab';
SELECT ST_ASTEXT (p1) FROM gis_point WHERE MBRWITHin (p1, @p1);
SHOW TABLE STATUS LIKE 't_';
SET GLOBAL table_open_cache=400;
SELECT * FROM t5 PARTITION (s5) ORDER BY id;
SELECT * FROM information_schema.tables;
SELECT fid, ST_X (g) FROM gis_point;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
SET GLOBAL init_connect=init_slave;
CREATE TABLE foo (a INT, b INT, c CHAR(10), PRIMARY KEY(c (3)), KEY b (b)) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE #mysql50#t11 (a INT) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"' COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
SELECT a.constraint_schema, b.table_name, constraint_type, b.constraint_name, unique_constraint_schema, unique_constraint_name, match_option, update_rule, delete_rule, b.referenced_table_name FROM information_schema.table_constraints a, information_schema.referential_constraints b WHERE a.constraint_schema='test' AND a.constraint_schema=b.constraint_schema AND a.constraint_name=b.constraint_name;
FLUSH TABLES WITH READ LOCK;
INSERT INTO foo VALUES (2,20,'1999-11-11',0,NULL,NULL,NULL,NULL, "rewoiu","fds","fr","oiufdsrew");
INSERT INTO foo VALUES (2,20,'1999-11-11',0,"rewoiu","fds","fr","oiufdsrew");
CREATE OR REPLACE TEMPORARY TABLE t1 (a INT, b INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES ('1','1'),('5','2'),('2','3'),('3','4'),('4','4');
SELECT * FROM foo WHERE a <="c";

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE t (c INT PRIMARY KEY,c1 BLOB, c2 TEXT) ENGINE=InnoDB;
CREATE TABLE t1 (a CHAR CHARACTER SET latin1 COLLATE latin1_swedish_ci, b CHAR CHARACTER SET latin1 COLLATE latin1_german1_ci);
ALTER TABLE t1 CHANGE a a VARCHAR(10) CHARACTER SET cp1251;
SELECT * FROM t1 _1 WHERE 0.8=0.7+0.1;
CALL empty_5();
CREATE TABLE SERVER (SUFFIX CHAR(2) BINARY NOT NULL, server_id INT UNSIGNED NOT NULL, NAME CHAR(32) BINARY NOT NULL, no_of_read INT UNSIGNED NOT NULL, no_of_insert INT UNSIGNED NOT NULL, no_of_delete INT UNSIGNED NOT NULL, PRIMARY KEY USING HASH (SUFFIX, server_id)) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
SET @start_value=@@GLOBAL.slow_query_log;
SET GLOBAL wait_timeout=@start_value;
DROP TABLE t1;
SELECT * FROM information_schema.tables WHERE table_schema='test' AND create_options LIKE '%table_type=XML%';
SET GLOBAL key_cache_segments=10, GLOBAL table_open_cache=1024;
CREATE TABLE t1 (user_num BIGINT, HOURs SMALLINT, KEY user_num (user_num)) ENGINE=RocksDB PARTITION BY RANGE COLUMNS (HOURs) (PARTITION hour_003 VALUES LESS THAN (3), PARTITION hour_004 VALUES LESS THAN (4), PARTITION hour_005 VALUES LESS THAN (5), PARTITION hour_LAST VALUES LESS THAN (MAXVALUE));
SET GLOBAL init_connect="CALL p1 ('t1', 11)";
SELECT SLEEP(3);
SELECT * FROM information_schema.PARTITIONS WHERE table_schema="test";

# CS 10.6.19 104dbad2368b3150728ade135cba030f856b543b (Optimized)
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
SET GLOBAL init_connect="adsfsdfsdfs";
CREATE TABLE IF NOT EXISTS t3 (c1 INT(2),c2 CHAR BINARY CHARACTER SET 'utf8' COLLATE 'utf8_bin',c3 DECIMAL(2)) ENGINE=InnoDB;
SET max_statement_time=0.001;
CREATE TABLE valid_VALUES (value VARCHAR(255)) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE t2 (user_str TEXT);
CREATE TABLE t1_select (f1 BIGINT, f2 BIGINT) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"' COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
SELECT table_name, index_type FROM information_schema.statistics WHERE table_schema='test' AND table_name LIKE 't%' AND index_name='q' ORDER BY table_name;
XA START 'test1';
SET GLOBAL table_open_cache=FALSE;
INSERT INTO valid_values VALUES ('on');
SET @inserted_value=REPEAT ('z', 16777215);
SELECT * FROM t1_select ORDER BY f1,f1_two_inserts();
INSERT INTO t1 SELECT * FROM t1;
CALL mtr.add_suppression ('Failed TO stORe KEY');
INSERT INTO t2 VALUES (41540);
SELECT * FROM performance_schema.rwlock_instances;
SHOW full COLUMNS FROM mysql.db LIKE "INSERT%";
SELECT * FROM t1_select ORDER BY f1,f1_two_inserts();

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE Ｔ６ (Ｃ１ CHAR(12), INDEX (Ｃ１)) DEFAULT CHARSET=utf8 ENGINE=Spider;
CREATE TABLE t1 (col_1_blob BLOB (4000), PRIMARY KEY(col_1_blob (3072))) ROW_FORMAT=DYNAMIC, ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"' COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE ti (a MEDIUMINT UNSIGNED, b TINYINT UNSIGNED NOT NULL, c CHAR(35) NOT NULL, d VARBINARY(19), e VARCHAR(83), f VARBINARY(45), g LONGBLOB NOT NULL, h TINYBLOB NOT NULL, id BIGINT NOT NULL, KEY(b), KEY(e), PRIMARY KEY(id)) ENGINE=Spider;
CREATE TABLE t (f INT) ENGINE=Spider;
UPDATE t1 SET name='U + FF5B FULLWIDTH LEFT CURLY BRACKET' WHERE ujis=0xA1D0;
SET GLOBAL table_open_cache=0;
CREATE TABLE test.t3 (value CHAR(30),domain_id INT, mailaccount_id INT, program CHAR(30),keey CHAR(30),PRIMARY KEY(domain_id));
CREATE TABLE t706 (c1 INT);
CREATE TABLE t2 (a INT) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"' COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE Ｔ１b (Ｃ１ CHAR(1) PRIMARY KEY) DEFAULT CHARSET=utf8 ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
CREATE TABLE t2_spider (k INT, a BIT(1) NOT NULL, b BIT(4) NOT NULL) ENGINE=Spider;
XA START 0x7465737462, 0x2030405060, 0xb;
SHOW TABLE STATUS;
SELECT i,SUBSTRING(a,1,10) FROM t1 WHERE (a between 'h' AND 'z') AND (i=9) ORDER BY i;
SELECT SLEEP(5);
SELECT p FROM t;
SELECT * FROM t2 WHERE c1 >=-255 AND c1 < 256 AND c6=29 ORDER BY c1,c6;
SELECT SLEEP(3);
SELECT * FROM t2 INTO OUTFILE 'out7';
SELECT * FROM t1 AS m LEFT JOIN t1 AS c1 ON m.c1id=c1.id AND c1.active='Yes' LEFT JOIN t1 AS c2 ON m.c2id=c2.id AND c2.active='Yes' WHERE m.pid=1 AND (c1.id IS NOT NULL OR c2.id IS NOT NULL);
SELECT * FROM performance_schema.objects_summary_global_by_type;
SELECT Ｃ１,TRIM(TRAILING '丂' FROM Ｃ１) FROM Ｔ６;
SELECT SLEEP(3);
DELETE IGNORE a2,a3 FROM t2 AS a1 JOIN t1 AS a2 INNER JOIN t2 AS a3;
