CREATE TABLE t (f bit, key (f)) ENGINE=MyISAM;
CREATE UNIQUE INDEX ind USING HASH ON t(f);

CREATE or replace TABLE t (f bit(1), UNIQUE KEY (f) USING hash, KEY f1 (f)) engine=myisam;
INSERT INTO t SELECT 1;
INSERT INTO t SELECT seq from seq_1_to_100;

CREATE TABLE t (c BIT KEY,c2 BIT) ENGINE=MyISAM;
CREATE UNIQUE INDEX i1 USING HASH ON t (c);

CREATE TABLE t (f BIT,UNIQUE KEY(f) USING HASH) ENGINE=MyISAM;
OPTIMIZE TABLE t;

CREATE TABLE t (b INT,c INT,d BIT,v BIT AS (d) VIRTUAL,KEY(b,v)) ENGINE=MyISAM PARTITION BY HASH (b);
OPTIMIZE TABLE t;

CREATE TABLE t (b INT,c INT,d BIT,v BIT AS (d) VIRTUAL,KEY(b,v)) ENGINE=MyISAM PARTITION BY HASH (b);
REPAIR TABLE t USE_FRM;

SET storage_engine=MyISAM;
CREATE TABLE t (a INT,b INT,c BIT DEFAULT b,pk INT,d BIT AS (c) VIRTUAL,KEY(pk),KEY(b,d)) PARTITION BY HASH (pk);
INSERT t (a) VALUES (1);
ANALYZE TABLE t;
