# mysqld options required for replay: --log_bin 
CREATE TABLE t1 (a INT) ENGINE=INNODB;
SET GLOBAL wsrep_forced_binlog_format=1;
CREATE OR REPLACE TABLE t (c INT) ENGINE=INNODB;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
LOCK TABLES t1 WRITE,t WRITE;
ALTER TABLE t ENGINE=MYISAM;
CREATE OR REPLACE TABLE t ENGINE=INNODB SELECT 1;
ALTER TABLE t ENGINE=INNODB;
