SET SESSION storage_engine=CSV;
CREATE TEMPORARY TABLE t1 (c INT) ENGINE=MYISAM;
CREATE TEMPORARY TABLE t2 AS VALUES (1);
CHECK TABLE t2;
INSERT INTO t2 SELECT * FROM t2 ;
TRUNCATE t2;
REPLACE INTO t1 SELECT * FROM t2;
