INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c1 INT) ENGINE=SPIDER PARTITION BY HASH (c1) PARTITIONS 2;
SELECT * FROM t;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=InnoDB PARTITION BY RANGE (c) SUBPARTITION BY HASH (c) SUBPARTITIONS 3 (PARTITION p0 VALUES LESS THAN (1),PARTITION p VALUES LESS THAN MAXVALUE);
ALTER TABLE t TABLESPACE ts STORAGE DISK ENGINE=SPIDER;

SET sql_mode='';
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (a CHAR) DEFAULT CHARACTER SET utf8mb4;
ALTER TABLE t ENGINE=SPIDER PARTITION BY KEY(a) (PARTITION p0,PARTITION p ENGINE=none);
ALTER TABLE t ADD PARTITION (PARTITION p5);
