DELIMITER //
CREATE FUNCTION f() RETURNS INT BEGIN DELETE FROM t;RETURN 1;END;//
DELIMITER ;
CREATE TABLE t (c INT) ENGINE=InnoDB;
PREPARE s FROM 'SELECT 1 FROM t HAVING COUNT(*)=f()';
EXECUTE s;
INSERT INTO t VALUES (1);
SELECT f();
