CREATE TABLE t partition BY hash (CASE 0 WHEN 1 IN (SELECT 'a') THEN 0 ELSE 0 END) IGNORE AS (SELECT * FROM v00);

CREATE TABLE t PARTITION BY HASH (EXISTS (SELECT 1)) PARTITIONS 2 REPLACE AS SELECT *;
