CREATE TABLE t (a TEXT,KEY(a)) ENGINE=INNODB;
INSERT INTO t VALUES('');
SELECT * FROM t WHERE a='';

CREATE TABLE t (a INT,b TEXT (1),PRIMARY KEY(a,b(1))) ENGINE=InnoDB;
INSERT INTO t VALUES (0,'');
REPLACE INTO t SELECT * FROM t d;

CREATE TABLE t (a TEXT,b TEXT,c TEXT,INDEX (a (1),b (1),c (1))) ENGINE=InnoDB;
SELECT * FROM t WHERE a='';
