CREATE TABLE t(c POINT NOT NULL) ENGINE=InnoDB;
DROP TABLE mysql.innodb_table_stats;
CREATE SPATIAL INDEX i ON t(c);

CREATE TABLE t (c POINT PRIMARY KEY);
DROP TABLE mysql.innodb_index_stats;
ALTER TABLE t ADD SPATIAL INDEX i (c ASC);

CREATE TABLE tab (c INT,c2 POINT,c3 LINESTRING,c4 POLYGON NOT NULL,c5 GEOMETRY NOT NULL) ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=16;
RENAME TABLE mysql.innodb_index_stats TO mysql.innodb_index_stats_;
CREATE SPATIAL INDEX i3 ON tab (c4 ASC) KEY_BLOCK_SIZE=2;

CREATE TABLE t (c INT KEY,c2 POINT NOT NULL,c3 LINESTRING NOT NULL,c4 POLYGON NOT NULL,c5 GEOMETRY NOT NULL);
SET GLOBAL innodb_stats_persistent=ON;
ALTER TABLE mysql.innodb_index_stats RENAME TO mysql.innodb_index_stats_;
ALTER TABLE t ADD SPATIAL INDEX idx2 (c2);
