set sql_mode='';
SET GLOBAL encrypt_tmp_disk_tables=ON;
CREATE OR REPLACE TABLE t (c INT KEY,c2 TEXT,c3 JSON);
CREATE TABLE t2 LIKE t;
CREATE OR REPLACE TABLE t (c INT KEY,c2 VECTOR (1));
ALTER TABLE t ADD COLUMN c4 INT(1) ZEROFILL AFTER c2;
INSERT INTO t VALUES (1,1,MICROSECOND (1)) ON DUPLICATE KEY UPDATE c=1;
SELECT * FROM t UNION SELECT * FROM t2;
