CREATE TABLE t1 ( a TEXT, b TEXT ) ENGINE=INNODB;
INSERT INTO t1  (a) VALUES (1);
FLUSH TABLES WITH READ LOCK;
SELECT (SELECT (SELECT t1.a)) aa, COUNT(DISTINCT b) FROM t1 GROUP BY aa; 

CREATE TABLE t (a CHAR,b INT);
INSERT INTO t VALUES (0,0),(0,0),(0,0);
ALTER TABLE t MODIFY a BLOB;
SELECT (SELECT (SELECT t.a)) aa,COUNT(DISTINCT b) FROM t GROUP BY aa;
