CREATE TABLE t (c INT,c2 INT) PARTITION BY HASH (c);
XA START '0';
SET SESSION pseudo_slave_mode=ON;
INSERT INTO t VALUES (0,0);
XA END '0';
XA PREPARE '0';
HANDLER t OPEN;
HANDLER t READ NEXT;

SET innodb_lock_wait_timeout=1;
SET pseudo_slave_mode=1;
CREATE TABLE t1 (c INT,c2 INT) PARTITION BY HASH (c + c2) PARTITIONS 3;
XA START 'a';
INSERT INTO t1 VALUES (0,0);
XA END 'a';
XA PREPARE 'a';
HANDLER t1 OPEN;
HANDLER t1 READ FIRST;
