CREATE TABLE t (c DECIMAL(10,5),d DECIMAL(10,1));
SELECT * FROM t HAVING (SELECT MAX(d) FROM t)=c AND c+d=1;

CREATE TABLE t (c NUMERIC ZEROFILL,c2 NUMERIC(0,0) UNSIGNED,c3 CHAR BINARY,KEY(c));
SELECT * FROM t WHERE c2=(1/1%TRUNCATE (-1,0)*1)+(UNHEX (NULL) DIV 1) AND c2 IS NOT NULL;
