SET SESSION STORAGE_ENGINE = 'memory';
CREATE TABLE t1 (col1 BIGINT DEFAULT -1);
SELECT NULL IN (SELECT * FROM t1);

CREATE TABLE t1 (a CHAR(1),b INT DEFAULT (a NOT IN ('','')));
ALTER TABLE t1 DROP COLUMN a,ADD COLUMN a BIGINT FIRST;

SET sql_mode='';
CREATE TABLE t (c BIGINT) ENGINE=MyISAM;
INSERT INTO t VALUES(' \t-1');
SELECT 1.5 IN (SELECT * FROM t);
