INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c2 CHAR(1)) ENGINE=Spider;
SELECT * FROM t WHERE f LIKE'';
SELECT 1 - LENGTH (SUBSTRING_INDEX(SUBSTR('[SELECT COUNT(*) FROM t WHERE a IS ]=1',1,41),'[',-1));
INSERT INTO t (SELECT 1 FROM t);
LOCK TABLES t WRITE CONCURRENT;
DELETE FROM t;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t1 (a CHAR(10), FULLTEXT (a)) ENGINE=Spider;
INSERT INTO t1 VALUES (1),(1),(2),(2);
DROP TABLE t1;
CREATE TABLE t1 (c1 YEAR NOT NULL);
LOCK TABLES t1 WRITE;
CREATE OR REPLACE TABLE t1 (x INT) ENGINE=Spider;
SET SESSION RAND_SEED2=1e1;
INSERT INTO t1 VALUES (12);
