SET big_tables=ON;
CREATE TABLE t (a VARCHAR(16383) CHARACTER SET UTF32,KEY k1 (a (768))) ENGINE=InnoDB;
SET SESSION sql_buffer_result=1;
DELETE FROM mysql.user WHERE USER=0;
EXPLAIN SELECT COUNT(DISTINCT a) FROM t;
