SET max_session_mem_used=8192;
CREATE TABLE t (v VECTOR (1) NOT NULL,VECTOR (v)) ENGINE=Aria;
REPAIR TABLE t USE_FRM;

SET max_session_mem_used=1;
CREATE TABLE t (v VECTOR (1) NOT NULL,VECTOR (v)) ENGINE=Aria;
REPAIR NO_WRITE_TO_BINLOG TABLE t USE_FRM;
