INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
dummy;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
DROP TABLE t;
CREATE TABLE t (c CHAR(1) PRIMARY KEY) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
dummy;
HANDLER t READ next;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ NEXT;
SELECT * FROM t;
HANDLER t READ NEXT;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (i INT(1),v1 CHAR(1),v2 VARCHAR(1),KEY i (i),KEY v (v1,i)) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ next;
SELECT * FROM t;
HANDLER t READ next;
