SET character_set_server=ucs2;
DROP DATABASE test;
CREATE DATABASE test;
USE test;
CREATE TABLE t (a CHAR) ENGINE=InnoDB PARTITION BY RANGE COLUMNS (a) (PARTITION p0 VALUES LESS THAN ('a'));
ALTER TABLE t CHANGE COLUMN a a CHAR BINARY;
