CREATE TABLE t (pk INT) ENGINE=InnoDB;
CREATE TRIGGER tr AFTER INSERT ON t FOR EACH ROW REPLACE INTO s VALUES(1);
XA START 'a';
INSERT INTO t VALUES(1);  # Gives error 'ERROR 1146 (42S02): Table 'test.s' doesn't exist'
REPLACE t VALUES(1);
