CREATE OR REPLACE TABLE mysql.servers (x INT) ENGINE=INNODB;
CREATE SERVER s0 FOREIGN DATA WRAPPER mysql OPTIONS (USER '',HOST '');

CREATE OR REPLACE TABLE mysql.servers (c INT) ENGINE=INNODB;
CREATE SERVER s FOREIGN DATA WRAPPER mysql OPTIONS (HOST'');
