CREATE TABLE t (c INT) ENGINE=InnoDB;
UPDATE t SET c=1 WHERE c=2 ORDER BY (1 IN ((SELECT * FROM (SELECT * FROM t) AS v1 GROUP BY c WINDOW v2 AS (ORDER BY (SELECT * FROM t GROUP BY c WINDOW v3 AS (PARTITION BY c))))));

CREATE TABLE t(c INT);
UPDATE t SET c= + 1 WHERE FALSE=c AND c=''ORDER BY 1=(-1 IN ((SELECT * FROM (SELECT * FROM t)AS v3 NATURAL JOIN t AS v2 NATURAL JOIN t AS v4 GROUP BY c WINDOW v5 AS(ORDER BY (SELECT * FROM t GROUP BY c WINDOW v6 AS(PARTITION BY c ORDER BY c + c + 1)))))) ^ 1 * 1;
