SET transaction_isolation='READ-UNCOMMITTED';
CREATE TABLE t (a VARCHAR(10),b INT,c CHAR(10) GENERATED ALWAYS AS (UCASE (a)) VIRTUAL,KEY(b,c)) ENGINE=InnoDB;
INSERT INTO t (a) VALUES ('A');
SELECT * FROM t WHERE b IS NULL ORDER BY a;
