CREATE TABLE t (c BLOB NOT NULL) ENGINE=InnoDB;
INSERT IGNORE INTO t VALUES (0);
SELECT COUNT(*) FROM t WHERE EXTRACTVALUE(c,'a')='a';

SET sql_mode='';
CREATE TABLE t (c TEXT NOT NULL) ENGINE=InnoDB;
INSERT INTO t VALUES();
INSERT IGNORE INTO t VALUES (@VALUE);
SELECT GROUP_CONCAT(c ORDER BY BINARY c) FROM t GROUP BY c;

SET sql_mode='';
CREATE TABLE t (c INT) ENGINE=InnoDB;
INSERT INTO t VALUES();
ALTER TABLE t ADD c2 BLOB NOT NULL;
CREATE TABLE t2 SELECT * FROM t;
DELETE FROM t;
INSERT INTO t VALUES (0,0);
INSERT INTO t SELECT * FROM t2;
SELECT (SELECT GROUP_CONCAT(DISTINCT c2) FROM t);
