CREATE TABLE t (a INT GENERATED ALWAYS AS (1) VIRTUAL,KEY(a)) ENGINE=MyISAM;
INSERT INTO t VALUES(),();
CHECK TABLE t EXTENDED;
CREATE TABLE fts_t (f INT KEY,f2 CHAR(1),FULLTEXT (f2)) ENGINE=InnoDB;
CREATE PROCEDURE p() UPDATE t SET a=a;
CALL p;
SHUTDOWN;
