INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SET SESSION sql_buffer_result=1;
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE ti (c BLOB) ENGINE=InnoDB;
CREATE TABLE ts (c BLOB) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "ti"';
INSERT INTO ti VALUES (0);
SELECT * FROM ts PROCEDURE ANALYSE();
