CREATE TABLE t (v VECTOR (3) NOT NULL,VECTOR INDEX (v)) ENGINE=INNODB;
SET GLOBAL innodb_force_primary_key=1;
CHECK TABLE t EXTENDED;
CHECK TABLE t EXTENDED;

CREATE TABLE t (v VECTOR (3) NOT NULL,VECTOR INDEX (v)) ENGINE=INNODB;
SET GLOBAL innodb_force_primary_key=1;
INSERT INTO t VALUES (0x1);
INSERT INTO t VALUES (0x1);
