# mysqld options required for replay: --log_bin --maximum-range_alloc_block_size=1M --max_allowed_packet=33554432 --maximum-bulk_insert_buffer_size=1M --maximum-join_buffer_size=1M --maximum-max_heap_table_size=1M --maximum-max_join_size=1M --maximum-myisam_max_sort_file_size=1M --maximum-myisam_mmap_size=1M --maximum-myisam_sort_buffer_size=1M --maximum-optimizer_trace_max_mem_size=1M --maximum-query_alloc_block_size=1M
set sql_mode='';
SET @@max_statement_time=0.0001;
SET GLOBAL innodb_adaptive_flushing_lwm=FALSE;
SET GLOBAL innodb_buffer_pool_size=8388608;
INSERT INTO t VALUES ('0','0');
SET @inserted_value=REPEAT('0',16777217);
CREATE TEMPORARY TABLE t (c MEDIUMTEXT);
SET GLOBAL innodb_buffer_pool_size=33554432;
INSERT IGNORE INTO t VALUES (@inserted_value);
SET GLOBAL innodb_buffer_pool_size=16777216;
SET GLOBAL innodb_buffer_pool_size=8388608;
SHOW CREATE TABLE t ;
DROP TABLE t;
SET @@max_statement_time=0.0001;
SET GLOBAL innodb_adaptive_flushing_lwm=FALSE;
SET GLOBAL innodb_buffer_pool_size=8388608;
SET @inserted_value=REPEAT('0',16777217);
CREATE TEMPORARY TABLE t (c MEDIUMTEXT);
SET GLOBAL innodb_buffer_pool_size=33554432;
INSERT IGNORE INTO t VALUES (@inserted_value);
SET GLOBAL innodb_buffer_pool_size=16777216;
SET GLOBAL innodb_buffer_pool_size=8388608;
SET @@max_statement_time=0.0001;
SET GLOBAL innodb_adaptive_flushing_lwm=FALSE;
SET GLOBAL innodb_buffer_pool_size=8388608;
SET @inserted_value=REPEAT('0',16777217);
CREATE TEMPORARY TABLE t (c MEDIUMTEXT);
SET GLOBAL innodb_buffer_pool_size=33554432;
INSERT IGNORE INTO t VALUES (@inserted_value);
SET GLOBAL innodb_buffer_pool_size=16777216;
SET GLOBAL innodb_buffer_pool_size=8388608;
SET @@max_statement_time=0.0001;
SET GLOBAL innodb_adaptive_flushing_lwm=FALSE;
SET GLOBAL innodb_buffer_pool_size=8388608;
SET @inserted_value=REPEAT('0',16777217);
CREATE TEMPORARY TABLE t (c MEDIUMTEXT);
SET GLOBAL innodb_buffer_pool_size=33554432;
INSERT IGNORE INTO t VALUES (@inserted_value);
SET GLOBAL innodb_buffer_pool_size=16777216;
SET GLOBAL innodb_buffer_pool_size=8388608;
