set sql_mode='';
CREATE TABLE t (a INT) ENGINE=InnoDB PARTITION BY RANGE (a) (PARTITION p0 VALUES LESS THAN (1));
INSERT INTO t VALUES (NULL);
ALTER TABLE t ADD PARTITION (PARTITION p2 VALUES LESS THAN (20));
INSERT INTO t VALUES (ADDTIME('10:10:10',0));
CREATE UNIQUE INDEX i2 ON t (a);
UPDATE t SET a=((SELECT MAX(a) FROM t));

CREATE TABLE t(c INT) ENGINE=InnoDB PARTITION BY RANGE(c)(PARTITION p1 VALUES LESS THAN (10),PARTITION p2 VALUES LESS THAN (20));
INSERT INTO t VALUES (1),(10);
CREATE UNIQUE INDEX i ON t(c);
UPDATE t SET c=10;
