CREATE TABLE t1 (c1 VARCHAR(1) KEY) WITH SYSTEM VERSIONING ENGINE=InnoDB PARTITION BY SYSTEM_TIME SUBPARTITION BY KEY(c1) SUBPARTITIONS 2 (PARTITION hist HISTORY,PARTITION cur CURRENT);
ALTER TABLE t1 ADD FULLTEXT INDEX (c1);
ALTER TABLE t1 ENCRYPTED=NO;
