CREATE TABLE t (c1 INT, c2 DATE) TABLESPACE t STORAGE MEMORY;
PREPARE s FROM 'WITH RECURSIVE d AS (SELECT * FROM t UNION ALL SELECT 1 FROM d) SELECT * FROM d AS d1,d AS d2';
SHUTDOWN;

CREATE TABLE t (a INT,b INT) ENGINE=InnoDB;
PREPARE s FROM 'WITH RECURSIVE cte AS (SELECT * FROM t WHERE a=1 UNION ALL SELECT a+1 FROM cte WHERE a<?) SELECT * FROM cte AS cte1,cte AS cte2';
SHUTDOWN;

CREATE TABLE t (a INT);
ALTER TABLE t ADD COLUMN (b INT);
PREPARE s FROM 'WITH RECURSIVE d AS (SELECT * FROM t UNION ALL SELECT 1 FROM d) SELECT * FROM d AS d1,d AS d2';
SHUTDOWN;

CREATE TABLE t (a INT,b INT) ROW_FORMAT=REDUNDANT ENGINE=InnoDB;
PREPARE s FROM 'WITH RECURSIVE d AS (SELECT * FROM t UNION ALL SELECT 1 FROM d) SELECT * FROM d AS d1,d AS d2';
SHUTDOWN;

CREATE TABLE t (a INT KEY,message CHAR,FULLTEXT (message)) COMMENT='';
PREPARE s FROM 'WITH RECURSIVE d AS (SELECT * FROM t UNION ALL SELECT 1 FROM d) SELECT * FROM d AS d1,d AS d2';
SHUTDOWN;
