CREATE PROCEDURE p(IN c INT) SET max_connections=100;
EXECUTE IMMEDIATE 'CALL p(?)' USING DEFAULT;

EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE t1 (a INT DEFAULT ?)' USING DEFAULT;

EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE t1 (a INT DEFAULT ?)' USING IGNORE;

EXECUTE IMMEDIATE 'CREATE TABLE t0 (a INT DEFAULT ?)' USING IGNORE;

EXECUTE IMMEDIATE 'CREATE TABLE t(c INT DEFAULT ?)' USING IGNORE;
