INSTALL SONAME 'ha_duckdb';
CREATE TABLE t1 (id INT PRIMARY KEY, v INT) ENGINE=DuckDB;
CREATE TRIGGER tr1 BEFORE UPDATE ON t1 FOR EACH ROW SET @x = 1;
INSERT INTO t1 VALUES (1,10);
UPDATE t1 SET v = 1;
