INSTALL PLUGIN spider SONAME 'ha_spider.so';
invalid;
CREATE TABLE t2 (a INT KEY,b INT UNIQUE AUTO_INCREMENT) ENGINE=SPIDER;
SELECT a FROM t2 UNION ALL SELECT a FROM t2;
ALTER TABLE t2 CHANGE c c INT;
invalid;
INSERT INTO t2 (a) VALUES (1);

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (pk INT,cik INT);
CREATE TABLE t2 (a INT KEY,b INT UNIQUE AUTO_INCREMENT) ENGINE=SPIDER;
SELECT (SELECT a FROM t2 WHERE t.a=t2.a UNION ALL SELECT a FROM t2 WHERE t5.a=t2.a);
ALTER TABLE t2 CHANGE c c DECIMAL(0,0) UNSIGNED,CHANGE c2 c2 DECIMAL(0,0) SIGNED;
CREATE TABLE t3 (fk INT,FOREIGN KEY(fk) REFERENCES a (pk)) ENGINE=InnoDB;
INSERT INTO t2 (a) VALUES (1),(2),(3),(4);
