CREATE TABLE t (c INT,c2 CHAR(1),c3 DECIMAL(0,0) GENERATED ALWAYS AS (c + 1) VIRTUAL,PRIMARY KEY(c)) ENGINE=InnoDB;
INSERT INTO t (c,c2) VALUES (0,0);
UPDATE t SET c=c - 2;
UPDATE t SET c=c + 1;
ALTER TABLE t ADD INDEX c3 (c3);
INSERT INTO t (c) VALUES (2),(3),(4);
UPDATE t SET c=c * 2;

CREATE TABLE t (c INT,c2 CHAR(1),c3 INT GENERATED ALWAYS AS (c + 1) VIRTUAL,PRIMARY KEY(c)) ENGINE=InnoDB;
INSERT INTO t (c,c2) VALUES (0,0);
UPDATE t SET c=c - 2;
UPDATE t SET c=c + 1;
ALTER TABLE t ADD INDEX c3 (c3);
INSERT INTO t (c) VALUES (0),(0),(0);
