CREATE TABLE t (c BIT);
INSERT INTO t VALUES (1e+19);  # Issue does not reproduce with <19

CREATE TABLE t (c DOUBLE UNSIGNED ZEROFILL DEFAULT NULL, c2 bit(1) DEFAULT NULL);
INSERT INTO t VALUES (+3E+38,+3.4E+38);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c BIT) ENGINE=Spider;
INSERT INTO t VALUES (1e100);

CREATE TABLE t (c INT ZEROFILL,c2 CHAR CHARACTER SET 'utf8' COLLATE 'utf8_bin',c3 ENUM ('') CHARACTER SET 'latin1' COLLATE 'latin1_bin',KEY(c)) ENGINE=InnoDB;
INSERT INTO t VALUES (-1.e-2,+1,-1.e+30);

SET sql_mode='';
CREATE DEFINER=current_user FUNCTION f (i1 SET('','')) RETURNS INT CONTAINS SQL DETERMINISTIC NO SQL NO SQL RETURN CONCAT ('FUNCTION output:',i1);
SELECT f (-1.e+30);
