INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c2 CHAR(1)) ENGINE=Spider;
SELECT * FROM t WHERE f LIKE'';
SELECT 1 - LENGTH (SUBSTRING_INDEX(SUBSTR('[SELECT COUNT(*) FROM t WHERE a IS ]=1',1,41),'[',-1));
INSERT INTO t (SELECT 1 FROM t);
LOCK TABLES t WRITE CONCURRENT;
DELETE FROM t;
