CREATE TABLE t (f INT);
INSERT INTO t VALUES (1),(2); # Optional, fails either way
CREATE VIEW v1 AS SELECT COUNT(*) as c FROM t;
CREATE VIEW v2 AS SELECT a2.c FROM v1 AS a1, v1 AS a2 WHERE a1.c = a2.c OR a2.c <= 10;
SELECT c FROM v2 WHERE c = 83;

SELECT 1 FROM (SELECT s0.x AS x FROM (SELECT 1 AS x) AS s0 WHERE s0.x = 5) AS s1 JOIN (SELECT MIN(s2.x) AS x FROM (SELECT 1 AS x) AS s2) AS s3 ON s1.x = s3.x WHERE s1.x = ANY (SELECT MAX(x) FROM (SELECT 1 AS x) AS s1);
