CREATE TABLE t1 (a TIME NOT NULL);
CREATE VIEW v1 AS SELECT * FROM t1;
SET SQL_MODE= 'ONLY_FULL_GROUP_BY';
SELECT ROUND(a), COUNT(*) FROM v1;

CREATE TABLE t (a TIME(6)) ENGINE=Aria;
INSERT INTO t VALUES (1);
SELECT ROUND (a) AS f FROM t GROUP BY a WITH ROLLUP;

CREATE TABLE t (a TIME(6)) ENGINE=MyISAM;
INSERT INTO t VALUES (1);
SELECT ROUND (a) AS f FROM t GROUP BY a WITH ROLLUP;

CREATE TABLE t (a TIME(6)) ENGINE=MEMORY;
INSERT INTO t VALUES (1);
SELECT ROUND (a) AS f FROM t GROUP BY a WITH ROLLUP;

# MDEV-21797
CREATE TABLE t1 (a time not null) engine=innodb;
SELECT STD(0) FROM t1 ORDER BY ROUND(a);
