SET sql_mode=ORACLE;
UNTIL (EXISTS (SELECT 1) OR NOT EXISTS (SELECT 1)) AND COUNT<0 END REPEAT;

SET sql_mode=ORACLE;
var1 (EXISTS (SELECT 1) OR EXISTS (SELECT 1));

CALL p(EXISTS (SELECT 1) OR EXISTS (SELECT 1));

CALL UNTIL (EXISTS (SELECT 1) OR NOT EXISTS (SELECT 1)) AND COUNT<0 END REPEAT;

CALL c (EXISTS(SELECT 1) LIKE EXISTS(SELECT 1));

SET @@sql_mode=CAST(POW(2,32)-1 AS UNSIGNED INT);
CALL c (EXISTS(SELECT 1) LIKE EXISTS(SELECT 1));
