USE test;
SET @@global.log_bin_trust_function_creators=1;
CREATE TABLE t(pk TIMESTAMP DEFAULT '0000-00-00 00:00:00.00',b DATE,KEY (pk));
CREATE FUNCTION f() RETURNS INT RETURN (SELECT notthere FROM t LIMIT 1);
XA BEGIN 'a';
SELECT f(@b,'a');
XA END 'a';
XA PREPARE 'a';
SELECT f(@a,@b);

CREATE TABLE t (c INT);
CREATE FUNCTION f() RETURNS INT RETURN (SELECT 1 FROM t);
XA START 'a';
SELECT * FROM t;
XA END 'a';
XA PREPARE 'a';
SELECT f();

SET @@global.log_bin_trust_function_creators=1;
CREATE FUNCTION f0() RETURNS INT RETURN (SELECT * FROM t);
CREATE TABLE t (a INT) PARTITION BY KEY(a) (PARTITION p0);
XA START 'a';
INSERT INTO t VALUES (CURRENT_TIMESTAMP,-e-0,CURDATE());
XA END 'a';
XA PREPARE 'a';
SELECT f0();

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
CREATE FUNCTION f() RETURNS INT RETURN (SELECT 1 FROM t);
CREATE TABLE t (c INT) ENGINE=InnoDB;
XA START 'a';
SELECT * FROM t;
XA END 'a';
XA PREPARE 'a';
SELECT f();

CREATE TABLE t (c INT) PARTITION BY HASH (c) PARTITIONS 2;
CREATE FUNCTION f() RETURNS INT DETERMINISTIC RETURN (SELECT * FROM t);
SET SESSION tx_isolation='SERIALIZABLE';
XA START 'a';
INSERT INTO t VALUES (0);
XA END 'a';
XA PREPARE 'a';
SELECT f() AS 'f():';
