# Sporadic, loop till it crashes (1-25)
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c CHAR(1) KEY,c2 CHAR(1) BINARY CHARACTER SET 'utf8' COLLATE 'utf8_bin',c3 CHAR(1) BINARY,c4 VARCHAR(1) CHARACTER SET 'utf8' COLLATE 'utf8_bin') ENGINE=Spider ROW_FORMAT=COMPACT;
SET SESSION pseudo_slave_mode=ON;
CREATE TABLE t (pk INT,KEY(pk)) ENGINE=Spider;
XA START 'xa1';
INSERT INTO t (c) VALUES (1);
XA END 'xa1';
XA PREPARE 'xa1';
CREATE TABLE t3 (id INT) ENGINE=Spider PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (0),PARTITION p VALUES LESS THAN (1),PARTITION p2 VALUES LESS THAN (200));
ALTER TABLE t3 REPAIR PARTITION p;
XA COMMIT 'xa1';
SELECT * FROM t;
