CREATE TABLE t1 (id INT PRIMARY KEY) ENGINE=InnoDB;
PREPARE stmt FROM "SELECT * FROM t1 ORDER BY ?";
CREATE TEMPORARY SEQUENCE t1 START WITH 100 INCREMENT BY 10;
EXECUTE stmt USING 1;

CREATE TABLE t1 (id INT PRIMARY KEY) ENGINE=InnoDB;
PREPARE stmt FROM "SELECT * FROM t1 ORDER BY ?";
CREATE TEMPORARY SEQUENCE t1 START WITH 100 INCREMENT BY 10;
EXECUTE stmt USING @LIKE;
