SET sql_mode='';
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider PARTITION BY HASH (c) PARTITIONS 2;
INSERT INTO t VALUES (0);
INSERT INTO t VALUES (0);
SELECT * FROM t WHERE c=1;
ANALYZE TABLE t;
SELECT * FROM t;
