INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t2 (a INT KEY) ENGINE=SPIDER;
SELECT a.z FROM t2 AS a,t2 b WHERE a.z=b.z;
CREATE TABLE t (a INT);
ALTER TABLE t2 CHANGE c c INT;
LOCK TABLE t WRITE,t2 READ;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c TIME,c2 BLOB) ENGINE=SPIDER PARTITION BY LIST COLUMNS (c) (PARTITION p DEFAULT ENGINE=SPIDER);
CREATE TRIGGER t AFTER INSERT ON t FOR EACH ROW INSERT INTO t VALUES (0);
ALTER TABLE t ALGORITHM=INPLACE,ADD KEY(y);
INSERT INTO t VALUES (0);
CREATE TABLE s (b CHAR,INDEX (b)) DEFAULT CHARSET=sjis ENGINE=InnoDB;
ALTER TABLE t CHANGE COLUMN d d INT;
LOCK TABLE t WRITE;
