INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SHOW CREATE TABLE t;
CREATE TABLE t (c INT, PRIMARY KEY(c)) ENGINE=Spider;
SHOW CREATE TABLE t;
DROP TABLE t;
CREATE TABLE t (c INT) ENGINE=Spider REMOTE_PORT="1 1";
DELETE FROM t;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SHOW CREATE TABLE t;
CREATE TABLE t (c INT, PRIMARY KEY(c)) ENGINE=Spider;
SHOW CREATE TABLE t;
DROP TABLE t;
CREATE TABLE t (c INT) ENGINE=Spider COMMENT='port "1 1"';
DELETE FROM t;
