CREATE TABLE t(c INT,c2 INT UNIQUE) ENGINE=InnoDB;
SELECT 1 FROM t WHERE c2=(SELECT 1 FROM t GROUP BY c HAVING c2=c+1) AND c2=1;

CREATE TABLE t(c DOUBLE,v2 DOUBLE UNIQUE CHECK ((c=1)OR (c=FALSE) OR (c AND 86) OR (c=0))) ENGINE=InnoDB;
SELECT 1 FROM t WHERE v2=(SELECT 1 FROM t GROUP BY c HAVING c>v2 - 0)AND v2<=5 / 1 AND v2>=97;

CREATE TABLE t(c TEXT,c2 INT UNIQUE) ENGINE=InnoDB;
SELECT 1 FROM t WHERE c2 IN(SELECT 1 FROM t GROUP BY'',c HAVING (CASE c2 WHEN 1 +''THEN 3 ELSE c END)ORDER BY c2) GROUP BY c2 HAVING c2=1;

CREATE TABLE t(c INT,c2 CHAR KEY UNIQUE) ENGINE=InnoDB;
CREATE VIEW v AS SELECT * FROM t WHERE c LIKE''GROUP BY c2 HAVING c>c;
SELECT * FROM v AS v1 NATURAL JOIN v AS v5 NATURAL JOIN v WHERE c LIKE''AND c2 IN(SELECT''FROM t WHERE c LIKE''GROUP BY c HAVING c2 LIKE (c2< + 1 OR c>1)>=c2);
