CREATE TABLE t0(a INT KEY,b TEXT,FTS_DOC_ID BIGINT UNSIGNED NOT NULL,KEY FTS_DOC_ID_INDEX(FTS_DOC_ID));
ALTER TABLE t0 ADD COLUMN d TEXT GENERATED ALWAYS AS(SUBSTR(b,0,0)) FIRST;
ALTER TABLE t0 ADD c0 BLOB NULL;
