CREATE TABLE t(v INT);
INSERT INTO t(v) VALUES (0);
SELECT(v=(SELECT v FROM t WHERE (v,v) IN (SELECT 1,1)) IN (1,1)) AS v1 FROM t WINDOW v2 AS(PARTITION BY v ORDER BY (SELECT 1 FROM (SELECT v FROM t WHERE (v,v) NOT IN (SELECT (''=(v IN (SELECT v FROM t WHERE v=CASE WHEN v ^ (SELECT 64 FROM t AS v3 WHERE v GROUP BY (TRUE,v) NOT IN (SELECT v,(SELECT v FROM (SELECT v,(NOT ((1 ^ 1 AND (v NOT IN (NOT (NOT (v=1))) AND (v,v) NOT IN (SELECT 1,1))=1) *'')) FROM t) AS v4 NATURAL JOIN t) AS v5 FROM t),v WINDOW v6 AS(PARTITION BY v ORDER BY (1))) ^ v THEN''END))),''FROM t)) AS v7));
