INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT KEY,c2 INT,INDEX i (c2)) ENGINE=SPIDER;
ALTER TABLE t ADD c4 TIME AFTER c2;
FLUSH TABLE t WITH READ LOCK;
invalid;
START TRANSACTION WITH CONSISTENT SNAPSHOT,READ ONLY;
