WITH a AS (SELECT * FROM a FOR TIME ALL;

CREATE TABLE t (c INT,c2 CHAR,c3 DATE,CHECK (c>0)) ENGINE=MyISAM;
ALTER TABLE t ADD INDEX (c2) USING HASH;

WITH c AS(SELECT * FROM (SELECT * FROM t1) SELECT * FROM DUAL;
