CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c1 INT,c2 INT) ENGINE=InnoDB;
CREATE TABLE t1 (c1 INT,c2 INT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
SET GLOBAL init_connect="foo";
XA START 'a';
INSERT INTO t1 VALUES (0);
SET GLOBAL init_connect='SELECT 1';
SHOW CREATE TABLE t1;
