SELECT x FROM (SELECT * FROM (SELECT 1 AS x) AS x) AS x WHERE x IN (SELECT * FROM (SELECT 1) AS x WHERE x IN (SELECT x IN (SELECT 1) AS x)) GROUP BY x HAVING NOT x;

SELECT x FROM (SELECT * FROM (SELECT 0 AS x) AS x) AS x WHERE x IN (SELECT * FROM (SELECT 0) AS x WHERE x IN (SELECT x IN (SELECT 0) AS x)) GROUP BY x HAVING NOT x;
