INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT) ENGINE=Spider PARTITION BY LIST (a) PARTITIONS 2 (PARTITION p1 VALUES IN (0,1),PARTITION p2 VALUES IN (2,3));
DELETE FROM t PARTITION (p2);
