SET @@enforce_storage_engine=MEMORY;
SET sql_mode='';
CREATE TABLE t1 (c1 INT) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t4 (c1 INT) ENGINE=InnoDB;
ALTER TABLE t1 ADD COLUMN c2 VARCHAR(20) NULL DEFAULT USER();
INSERT DELAYED INTO t1 VALUES (1,"b");
CREATE TRIGGER i5_t1 BEFORE INSERT ON t1 FOR EACH ROW CALL p4;
