USE test;
CREATE TABLE t(c BIGINT);
SELECT 1 FROM t WHERE c<GEOMFROMTEXT('LINESTRING(-1 1)');

CREATE TABLE t (c INT, c2 BIGINT) ENGINE=InnoDB;
SELECT * FROM t where c2=ST_GeomFromText('POINT(1 1)');
SELECT * FROM t where c2=ST_GeomFromText('POINT(1 1)');
SELECT * FROM t where c2=ST_GeomFromText('POINT(1 1)');  # Repeat as needed

CREATE TABLE t (a SERIAL);
EXPLAIN SELECT 1 FROM t WHERE a=GEOMFROMTEXT ('LINESTRING (-1 1,1 1,-1 1,-1 1,1 1)');

CREATE TABLE t (c1 BIGINT KEY,c2 BIGINT);
SELECT * FROM t WHERE c1 NOT IN (POINT(0,0));
