CREATE TEMPORARY TABLE t (c INT);
CREATE TEMPORARY TABLE t2 (c INT);
SET SESSION tx_read_only=ON;
SET autocommit=0;
INSERT INTO t2 VALUES(1);
INSERT INTO t VALUES(1);
CREATE TABLE t3 (c INT);
DELETE FROM t;
