INSTALL PLUGIN ARCHIVE SONAME 'ha_archive.so';
CREATE TABLE t (a CHAR(1)) ENGINE=ARCHIVE;
INSERT INTO t VALUES ('A');
UNINSTALL SONAME 'ha_archive';
ALTER TABLE t CHANGE COLUMN a a CHAR(2);
INSERT INTO t (a) VALUES ('AB');
