CREATE  TABLE t1(c1 TEXT) ENGINE=ARIA;
INSERT INTO t1 SELECT concat(seq,'wDizlix4sTUxibINhJmaznYGOnpMYF') FROM seq_1_to_100;
HANDLER t1 OPEN;
UPDATE t1 SET c1=REPEAT('a',120);
DELETE FROM t1 LIMIT 50;
HANDLER t1 READ NEXT;
DELETE FROM t1 LIMIT 25;
HANDLER t1 READ NEXT;
