INSTALL SONAME 'ha_connect';
CREATE TABLE t (k INT NOT NULL, KEY(k)) ENGINE=CONNECT table_type=DOS;
INSERT INTO t VALUES (1),(2);
SELECT MAX(k) FROM t WHERE k = 1 OR FALSE;

INSTALL SONAME 'ha_connect';
CREATE TABLE t (c INT PRIMARY KEY) ENGINE=Connect;
SELECT MAX(c) AS VALUE FROM t WHERE c<0;
