CREATE TABLE t (c INT) ENGINE=InnoDB;
DELIMITER //
CREATE TRIGGER tr AFTER INSERT ON t FOR EACH ROW FOR x IN (SELECT * FROM JSON_TABLE(NULL, '$' COLUMNS(a CHAR(1) PATH '$.*')) tmp) DO SET @a=1; END FOR //
DELIMITER ; 
INSERT INTO t () VALUES ();
