CREATE TABLE t(c CHAR (1)KEY ) ENGINE=MYISAM;
INSERT INTO t VALUES(3);
UPDATE t SET c= 1 ORDER BY(SELECT c LIMIT 0);

CREATE TABLE t (c DATE NOT NULL);
INSERT INTO t VALUES (0);
UPDATE t SET c=1 ORDER BY (SELECT c LIMIT 0);
