# Requires standard m/s setup
CREATE TEMPORARY SEQUENCE SEQ0 ENGINE=Aria ROW_FORMAT=REDUNDANT;
RESET MASTER;
CREATE TABLE t (c INT AUTO_INCREMENT KEY);
INSERT INTO t SELECT * FROM t;
FLUSH LOGS;
INSERT INTO t VALUES (0);
