SET GLOBAL innodb_file_per_table=0;
CREATE DATABASE Db;
USE Db;
CREATE TABLE t1 (c1 INT KEY) ENGINE=InnoDB;
CREATE DATABASE DB;
DROP DATABASE IF EXISTS DB;
INSERT INTO t1 VALUES (0);  # Will delay-crash
