# Replication setup required
SET SESSION binlog_format=STATEMENT;
CREATE TEMPORARY TABLE t (a INT,INDEX (a));
CREATE TABLE t (c INT,c2 CHAR(5)) PARTITION BY RANGE (c) (PARTITION p0 VALUES LESS THAN (1),PARTITION p1 VALUES LESS THAN (20),PARTITION p2 VALUES LESS THAN (30),PARTITION p3 VALUES LESS THAN MAXVALUE);
INSERT INTO t SELECT table_rows FROM information_schema.tables;

CREATE TEMPORARY TABLE t1 (i int);
CREATE  TABLE t2 SELECT  * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 't1';
