CREATE TABLE t (f TIMESTAMP DEFAULT FROM_UNIXTIME(1)) ENGINE=MyISAM;
INSERT DELAYED INTO t VALUES ();

SET sql_mode='';
CREATE TABLE t (c CHAR(1) DEFAULT @@version) ENGINE=MEMORY;
INSERT DELAYED INTO t SET a=1;
CREATE TABLE t (c1 INT) ENGINE=InnoDB COMMENT='abcdefghijklmnopqrstuvwxyz' UNION=(t,t2) INSERT_METHOD=FIRST;
SHUTDOWN;

SET sql_mode='';
CREATE TABLE t (c TEXT GENERATED ALWAYS AS (1) VIRTUAL,INDEX i (c (1))) ENGINE=MyISAM;
INSERT t SELECT 1 ON DUPLICATE KEY UPDATE c=1;
INSERT DELAYED INTO t VALUES();
SELECT SLEEP(3);  # As the INSERT is DELAYED
