SET sql_mode='';
CREATE TEMPORARY TABLE t (a INT,c VARCHAR(1)) ENGINE=MyISAM;
INSERT INTO t VALUES (1,'');
HANDLER t OPEN;
LOAD DATA LOCAL INFILE '' INTO TABLE t FIELDS TERMINATED BY '' LINES TERMINATED BY '';
INSERT INTO t SET c=2;
HANDLER t READ NEXT;
DELETE FROM t ORDER BY a LIMIT 1;
DELETE FROM t;
INSERT INTO t (a) VALUES (3);
HANDLER t READ next LIMIT 1;

# Then check the error log for
# [ERROR] mysql_ha_read: Got error 127 when reading table 't'
