CREATE TABLE v (c1 INT, c2 TEXT);
INSERT INTO v (c1, c2) VALUES (0, 'a');
SELECT * FROM { ta1 v AS ta2 NATURAL RIGHT OUTER JOIN ((SELECT * FROM { ta3 v AS ta4 NATURAL STRAIGHT_JOIN v AS ta5 } LIMIT 1234567890 ROWS EXAMINED 1234567890 LOCK IN SHARE MODE SKIP LOCKED) ORDER BY FALSE <=> + INTERVAL NOT FALSE=FALSE IN (SELECT FALSE <=> FALSE IN (SELECT 'string')) SECOND_MICROSECOND + TRUE <=> TRUE IN (SELECT 'string') << ROW_NUMBER () OVER (PARTITION BY NOT TRUE <=> FALSE IN (SELECT 'string') DESC) IN (SELECT 'string'))=ta6 NATURAL JOIN v AS ta7 };

(SELECT 1 FROM dual LIMIT 5 ) ORDER BY  row_number () over (partition BY 1);

(SELECT 1 FROM dual LIMIT 5 ) ORDER BY  row_number () over ();
(SELECT 5 a FROM dual LIMIT 1) order BY avg (a) over (order by 1);
(SELECT cast('1973' as datetime) a FROM dual LIMIT 1) order BY FIRST_VALUE(a) over (order by 1);
(SELECT cast('1973' as char) a FROM dual LIMIT 1) order BY FIRST_VALUE(a) over (order by 1);

SET sql_mode='';
(SELECT CAST(''AS CHAR) a LIMIT 1) ORDER BY FIRST_VALUE(a) OVER (ORDER BY 1);

((SELECT 1) FOR UPDATE WAIT + 1) ORDER BY PERCENTILE_DISC(COUNT(*)) WITHIN GROUP(ORDER BY 1) OVER();

((SELECT 1) FOR UPDATE WAIT + 1) ORDER BY PERCENTILE_DISC(COUNT(*)) WITHIN GROUP(ORDER BY CURRENT_TIMESTAMP) OVER();

CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (3),(1),(2);
CREATE TABLE t2 (a INT, b INT);
INSERT INTO t2 VALUES (3,1),(1,2),(2,1);

(SELECT a FROM t1 UNION SELECT 9 LIMIT 5) ORDER BY ROW_NUMBER() OVER ();

(SELECT a FROM t1 INTERSECT SELECT 3 LIMIT 5) ORDER BY ROW_NUMBER() OVER ();

(SELECT a FROM t1 EXCEPT SELECT 3 LIMIT 5) ORDER BY ROW_NUMBER() OVER (ORDER BY a DESC);

(SELECT a FROM t1 UNION SELECT 9 LIMIT 5) ORDER BY ROW_NUMBER() OVER (PARTITION BY (SELECT MAX(a) FROM t1));

SELECT * FROM ((SELECT a FROM t1 LIMIT 5) ORDER BY ROW_NUMBER() OVER ()) x;

SELECT (SELECT MAX(x) FROM ((SELECT a x FROM t1 LIMIT 5) ORDER BY ROW_NUMBER() OVER ()) d);

SELECT * FROM t1 WHERE a IN ((SELECT a FROM t1 LIMIT 5) ORDER BY ROW_NUMBER() OVER ());

UPDATE t2 SET b = 5 WHERE a IN ((SELECT a FROM t1 LIMIT 5) ORDER BY ROW_NUMBER() OVER ());

SELECT * FROM ((SELECT a FROM t1 LIMIT 5) ORDER BY ROW_NUMBER() OVER ()) x, ((SELECT a FROM t1 LIMIT 5) ORDER BY ROW_NUMBER() OVER (ORDER BY a)) y ORDER BY x.a, y.a;

(SELECT a FROM t1 LIMIT 5) ORDER BY (SELECT a FROM t2 WHERE t2.a = t1.a LIMIT 1);

(SELECT a FROM t1 LIMIT 5) ORDER BY a + (SELECT a FROM t2 WHERE t2.a = t1.a LIMIT 1);
