SET sql_mode='';
CREATE TABLE t (a INT(1) AUTO_INCREMENT,KEY(a))PARTITION BY HASH (a) PARTITIONS 3;
CREATE TRIGGER au AFTER UPDATE ON t FOR EACH ROW SELECT * FROM t INTO @var;
REPLACE INTO t PARTITION (p0) VALUES (1);

create table t (pk int auto_increment primary key) partition by hash(pk) partitions 2;
create trigger tr before insert on t for each row set @a=1;
insert into t partition (p1) values (1);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
SELECT * FROM t1;
INSERT INTO t1 PARTITION (p1) VALUES (1);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
SELECT * FROM t1 PARTITION (p0);
INSERT INTO t1 PARTITION (p1) VALUES (1);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) SELECT 1;

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
REPLACE INTO t1 PARTITION (p1) SELECT 1;

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY, c INT) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) VALUES (1,1) ON DUPLICATE KEY UPDATE c=2;

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE FUNCTION f() RETURNS INT RETURN 1;
INSERT INTO t1 PARTITION (p1) VALUES (f());

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TABLE t2 (a INT);
INSERT INTO t2 VALUES (1);
CREATE FUNCTION f() RETURNS INT RETURN (SELECT a FROM t2);
INSERT INTO t1 PARTITION (p1) VALUES (f());

CREATE TABLE t1 (a INT, b INT AUTO_INCREMENT, PRIMARY KEY (a,b)) ENGINE=MyISAM PARTITION BY HASH(a) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) (a) VALUES (1);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
PREPARE s FROM 'INSERT INTO t1 PARTITION (p1) VALUES (NULL)';
EXECUTE s;
FLUSH TABLES;
EXECUTE s;

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
CREATE PROCEDURE p() INSERT INTO t1 PARTITION (p1) VALUES (1);
CALL p();

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) ENGINE=Aria PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) VALUES (1);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) VALUES (2);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(4);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) VALUES (NULL);
FLUSH TABLES t1;
SELECT * FROM t1 ORDER BY pk;
INSERT INTO t1 PARTITION (p0) VALUES (NULL);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY, c INT) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (1,1),(2,2);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
REPLACE INTO t1 PARTITION (p1) VALUES (1,10);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY, c INT) ENGINE=MyISAM PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (1,1),(2,2);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
REPLACE INTO t1 PARTITION (p1) VALUES (1,10);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(4);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) SELECT pk+1 FROM t1;

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY RANGE (pk) (PARTITION p0 VALUES LESS THAN (10), PARTITION p1 VALUES LESS THAN MAXVALUE);
INSERT INTO t1 VALUES (5),(20);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) VALUES (NULL);

CREATE TABLE t1 (pk INT AUTO_INCREMENT, b INT, PRIMARY KEY (pk,b)) PARTITION BY RANGE (b) SUBPARTITION BY HASH (pk) SUBPARTITIONS 2 (PARTITION p0 VALUES LESS THAN (10), PARTITION p1 VALUES LESS THAN MAXVALUE);
INSERT INTO t1 VALUES (1,1),(2,20);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
INSERT INTO t1 PARTITION (p1) (b) VALUES (30);

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(4);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @c=(SELECT COUNT(*) FROM t1 PARTITION (p0));
INSERT INTO t1 PARTITION (p1) VALUES (NULL);
