SELECT AVG ( 'x' ) OVER ( ) x WHERE ( 1 , 1 , ( 1 , NULL ) ) IN ( ( 1 , 1 , ( 1 , 1 ) ) ) ORDER BY x BETWEEN 25 AND ( ( x = x ) / x ) OR x = x = AVG ( NULL ) OR x = 94 ;

SELECT ROW_NUMBER() OVER () x ORDER BY x BETWEEN 1 AND (( x = x ) / x) OR x = x = 1  ;

SELECT NULLIF ( AVG ( 999999 ) OVER ( ORDER BY 1 ) , '1' ) ORDER BY 1 , 1 , 1 ;

CREATE TABLE t (c INT);
(SELECT * FROM t GROUP BY EXISTS((SELECT 0) LOCK IN SHARE MODE)=c SOUNDS LIKE c=c=c IS NOT UNKNOWN FOR UPDATE SKIP LOCKED) ORDER BY c=c=AVG(DISTINCT ALL TRUE)=c IS NOT UNKNOWN && c SOUNDS LIKE c IS NOT UNKNOWN;

SELECT NULLIF(AVG(1) OVER (ORDER BY 1),0) ORDER BY 1,1,1;
