CREATE TABLE t1 (c1 INT) ENGINE=Aria;
CREATE TABLE t5 (c1 INT) ENGINE=Aria PARTITION BY KEY (c1) PARTITIONS 2;
LOCK TABLES t5 WRITE, t1 WRITE;
REPLACE INTO t5 SET c1=1;
ALTER TABLE t5 COALESCE PARTITION 1;
