CREATE TABLE t (id BIGINT) ENGINE=InnoDB;
INSERT INTO t VALUES ('10000000000000');
SELECT * FROM t PROCEDURE ANALYSE();

SET sql_mode='';
CREATE TABLE t (a INT);
INSERT INTO t VALUES ('100000000000'),('100000000000');
SELECT * FROM t PROCEDURE ANALYSE();

SET sql_mode='';
CREATE TABLE t (c BIGINT,c2 DATE,c3 BLOB,KEY(c)) ENGINE=InnoDB;
INSERT INTO t VALUES (-1.e+308,1,1);
SELECT * FROM t PROCEDURE ANALYSE();

CREATE TABLE t (c INT) ENGINE=InnoDB UNION=(t,t2) INSERT_METHOD=LAST;
CREATE TABLE t3 LIKE t;
INSERT INTO t VALUES (1),(2),(-685113344),(0);
INSERT INTO t3 SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t SELECT * FROM t;
INSERT INTO t3 SELECT * FROM t;
SELECT * FROM t3 PROCEDURE ANALYSE();
