CREATE TABLE t (c INT) ENGINE=InnoDB;
DELETE FROM t WHERE c IN (SELECT * FROM t) ORDER BY LAST_VALUE(t) OVER() IS NOT UNKNOWN;

CREATE TABLE t (c INT);
INSERT INTO t (c) VALUES (0);
DELETE FROM t WHERE c IN (SELECT * FROM t) ORDER BY sum(c) OVER() ;

CREATE TABLE t (c INT);
INSERT INTO t (c) VALUES (0);
DELETE FROM t WHERE c IN (SELECT * FROM t) ORDER BY rank() OVER() ;

CREATE TABLE t (c INT);
INSERT INTO t (c) VALUES (0);
DELETE FROM t WHERE c IN (SELECT * FROM t) ORDER BY max(c) OVER() ;
