CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
XA START 'a';
SELECT * FROM t;
SET @@max_statement_time=0.00001;
HANDLER t OPEN;
LOAD INDEX INTO CACHE t KEY(PRIMARY);
DROP TABLE t;
HANDLER t OPEN;
SELECT 1;
