CREATE TABLE t1 (c1 INT KEY);
PREPARE s FROM 'UPDATE t1 SET c1=1';
EXECUTE s;
CREATE TABLE t2 (c1 INT REFERENCES t1(c1));
EXECUTE s;

CREATE TABLE t (a INT) ENGINE=InnoDB;
SET FOREIGN_KEY_CHECKS = OFF;
ALTER TABLE t ADD FOREIGN KEY (a) REFERENCES x(x);
SET FOREIGN_KEY_CHECKS = ON;
PREPARE stmt FROM 'CHECK TABLE t EXTENDED';
EXECUTE stmt;
EXECUTE stmt;
