CREATE TABLE t (a TEXT COLLATE latin1_bin);
INSERT INTO t VALUES ('');
INSERT INTO t VALUES ('test');
SELECT GROUP_CONCAT(a ORDER BY a) FROM t ;

CREATE TABLE t (a TEXT );
INSERT INTO t VALUES ('');
INSERT INTO t VALUES ('test');
SELECT GROUP_CONCAT(a ORDER BY a) FROM t ;

CREATE TABLE t (f TEXT UNIQUE);
INSERT INTO t VALUES ('');
INSERT INTO t VALUES ('');

CREATE TABLE t (c CHAR(90));
INSERT INTO t VALUES ('');
INSERT INTO t VALUES (0);
SET NAMES utf8mb3 COLLATE utf8mb3_unicode_nopad_ci;
SELECT GROUP_CONCAT(c ORDER BY HEX(c) SEPARATOR'') FROM t;
