USE test;
CREATE TABLE t(c CHAR(255) CHARACTER SET UTF32, KEY k1(c)) ENGINE=MyISAM;
INSERT INTO t VALUES(100000);
ALTER TABLE t ENGINE=InnoDB;

SET foreign_key_checks=0,unique_checks=0;
CREATE TABLE t (a CHAR(255) CHARACTER SET UTF32,KEY k (a (200))) ENGINE=InnoDB;
INSERT INTO t VALUES (0xAEDB);
DELETE t2.* FROM t t2;
