CREATE TABLE t (a CHAR CHARACTER SET utf16,INDEX a (a)) ENGINE=INNODB;
SET STATEMENT sql_mode='' FOR ALTER TABLE t MODIFY a TINYTEXT CHARACTER SET utf8;
ALTER TABLE t MODIFY a TINYTEXT CHARACTER SET utf8mb4;
