SET sql_mode='';
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
GRANT ALL ON * TO Spider@localhost;
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER 'Spider',PASSWORD'');
CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
CREATE TABLE t1 (c1 CHAR CHARACTER SET UCS2 COLLATE UCS2_bin,KEY(c1)) ENGINE=Spider COMMENT='TABLE "st"' PARTITION BY LIST COLUMNS (c1) (PARTITION p DEFAULT COMMENT='srv "d"' ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"');
SET spider_quick_page_byte=0,spider_bgs_mode=1;
SELECT COUNT(*) FROM t1;
