SET unique_checks=0,foreign_key_checks=0;
CREATE TABLE t (f0 INT) ENGINE=INNODB;
CREATE TRIGGER t BEFORE INSERT ON t FOR EACH ROW SAVEPOINT s;
INSERT INTO t VALUES (),(),();

CREATE TABLE t (c INT) ENGINE=InnoDB;
SET unique_checks=OFF, foreign_key_checks=0;
CREATE TRIGGER t AFTER INSERT ON t FOR EACH ROW SAVEPOINT s;
INSERT INTO t VALUES (0),(0);
