INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TEMPORARY TABLE t (c INT) ENGINE=SPIDER;
REPAIR TABLE t;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
DROP DATABASE mysql;
CREATE TEMPORARY TABLE t (f INT) ENGINE=SPIDER;
ALTER TABLE t ENGINE=Aria;
