SET @@GLOBAL.myisam_use_mmap=1;
CREATE TABLE t1 (c1 INT KEY,c2 INT) ENGINE=MYISAM PARTITION BY RANGE(c1) (PARTITION p1 VALUES LESS THAN(100));
INSERT INTO t1 VALUES (0,0);
OPTIMIZE TABLE t1;
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY` LAST;
HANDLER t1 READ `PRIMARY`=(1);
HANDLER t1 READ `PRIMARY` PREV;
