DROP DATABASE test;
CREATE DATABASE test;
USE test;
SET sql_mode='';
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (i CHAR,n CHAR GENERATED ALWAYS AS (MD5 (i)) VIRTUAL) ENGINE=SPIDER;
INSERT INTO t VALUES (0,0);
CREATE TABLE t2 (c INT);
INSERT t SELECT 1 ON DUPLICATE KEY UPDATE c=1;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=SPIDER;
CREATE TABLE t0 (a INT) ENGINE=SPIDER;
INSERT INTO t0 VALUES (0);
SELECT MATCH (a) AGAINST (0x0) FROM t;
INSERT INTO t0 SELECT * FROM t0;
