SET sql_mode='';
INSERT INTO t1 VALUES (1),(3),(2);
CREATE TEMPORARY TABLE t1 (a tinyINT,b CHAR(1)) ENGINE=InnoDB ROW_FORMAT=REDUNDANT;
SET SESSION tmp_table_size=True;
CREATE TABLE t (c INT, d DATE) ENGINE=InnoDB PARTITION BY RANGE (YEAR (d)) SUBPARTITION BY HASH (TO_DAYS (d)) (PARTITION p0 VALUES LESS THAN (1990) (SUBPARTITION s0, SUBPARTITION s1), PARTITION p1 VALUES LESS THAN MAXVALUE (SUBPARTITION s4, SUBPARTITION s5));
SET SESSION aria_sort_buffer_size=CAST(-1 AS UNSIGNED INT);
INSERT INTO t1 SELECT '', SEQ FROM seq_1_to_258;
SET SESSION aria_repair_threads=CAST(-1 AS UNSIGNED INT);
UPDATE t1 SET a=( (SELECT MAX(a) FROM t1));
SET GLOBAL innodb_default_ROW_FORMAT=0;

SET sql_mode='';
CREATE TEMPORARY TABLE t(a tinyINT,b CHAR)ROW_FORMAT=REDUNDANT;
SET SESSION tmp_table_size=True;
SET SESSION aria_sort_buffer_size=CAST(-1 AS UNSIGNED INT);
INSERT INTO t SELECT'',SEQ FROM seq_1_to_258;
SET SESSION aria_repair_threads=CAST(-1 AS UNSIGNED INT);
UPDATE t SET a=((SELECT MAX(a)FROM t));
