CREATE OR REPLACE TABLE mysql.general_log (a INT)Engine=InnoDB;
CREATE TABLE t (c TIMESTAMP KEY)Engine=InnoDB;
SET GLOBAL general_log=1;
SET GLOBAL log_output='FILE,TABLE';
SET @@autocommit=0;
SELECT * FROM t;
TRUNCATE t;
ALTER TABLE t DISCARD TABLESPACE;
