CREATE TABLE t(b int);
INSERT INTO t VALUES(-1);
SELECT BIT_XOR(b) OVER (PARTITION BY b RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) BIT_XOR FROM t;

CREATE TABLE t(a INT,b INT, c2 FLOAT);
INSERT INTO t VALUES(0,-1,0),(0,-1,0),(0,-1,0),(0,-1,0),(0,0,0);
SELECT a,b,BIT_XOR(b)OVER(RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) BIT_XOR FROM t;
