SET sql_mode='';
CREATE TABLE t1 (c1 DECIMAL(40,30),c2 CHAR,PRIMARY KEY(c1)) WITH SYSTEM VERSIONING ENGINE=InnoDB;
REPLACE INTO t1 VALUES ('+','a');
ALTER TABLE t1 ADD FULLTEXT(c2);
REPLACE INTO t1 VALUES ('a','p4');
UPDATE t1 SET c2=DEFAULT;
