DELIMITER //
CREATE PROCEDURE p() 
BEGIN 
    DECLARE cur1 CURSOR FOR SELECT * FROM t;
    BEGIN 
      DECLARE rec1 ROW TYPE OF cur1;
    END;
END; //
DELIMITER ;
CREATE TABLE t (id INT);
CALL p();
CREATE OR REPLACE TABLE t (id INT);
CALL p();

