# mysqld options required for replay: --log-bin 
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS AS SELECT 1 'a';
CREATE GLOBAL TEMPORARY TABLE t2 (x INT KEY) ON COMMIT PRESERVE ROWS;
SET SESSION server_id=10;
LOCK TABLES t2 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
