CREATE TABLE t (c INT) ENGINE=InnoDB;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
RENAME TABLE t TO t;
INSERT INTO t VALUES (1);
SET SESSION transaction_read_only=1;
HANDLER t OPEN;
START TRANSACTION READ WRITE;
DELETE FROM t;
