CREATE TABLE t1(a CHAR BINARY);
SELECT(SELECT a FROM (SELECT 1 FROM t1)e ORDER BY (@f:=a)) FROM t1 GROUP BY a;

CREATE TABLE t0 (a INT,PRIMARY KEY(a));
SELECT (SELECT a FROM (SELECT 0 FROM t0) e ORDER BY (@f:=a)) FROM t0 GROUP BY a;
