SET sql_mode='';
CREATE TABLE t (c1 CHAR(10) BINARY CHARACTER SET 'utf8',PRIMARY KEY(c1(4))) ENGINE=InnoDB;
REPLACE INTO t VALUES ('𝌆');
INSERT INTO t VALUES (0);
ALTER TABLE t CONVERT TO CHARACTER SET utf8;
