INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (b INT) ENGINE=InnoDB;
PREPARE s FROM 'SELECT * FROM t LIMIT 2';
DROP TABLE t;
CREATE TABLE t (a INT) ENGINE=Spider PARTITION BY LIST (a) PARTITIONS 2 (PARTITION p1 VALUES IN (0,1),PARTITION p2 VALUES IN (2,3));
EXECUTE s;
