INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD 'PWD0');
CREATE TABLE t (a INT KEY AUTO_INCREMENT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
ALTER TABLE t ADD b TEXT;
CREATE OR REPLACE TABLE t (a INT) ENGINE=Spider;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT KEY) ENGINE=Spider;
UPDATE t SET c0=b0;
DROP TABLE IF EXISTS mysql.spider_tables;
CREATE OR REPLACE TABLE t (a TEXT);
