PREPARE p FROM 'LOCK TABLE t WRITE';
CREATE VIEW t AS SELECT 1 AS a;
EXECUTE p;
START TRANSACTION;
RENAME TABLE t TO t2;
CREATE TABLE t (c INT,d INT,INDEX (c));
EXECUTE p;
SELECT * FROM t;

PREPARE p FROM 'LOCK TABLE t WRITE';
CREATE VIEW t AS SELECT 1 AS a;
EXECUTE p;
START TRANSACTION;
RENAME TABLE t TO t2;
CREATE TABLE t (c INT,d INT,INDEX (c)) ENGINE=MyISAM;
EXECUTE p;
SELECT * FROM t;
