set sql_mode='';
CREATE TABLE t1 (c2 VECTOR(1));
CREATE TABLE t2 (c2 JSON);
INSERT INTO t2 (c2) VALUES (1);
INSERT INTO t2 () VALUES ();
INSERT INTO t1 (c2) VALUES (1);
SELECT c2 FROM t2 INTERSECT SELECT c2 FROM t1;
