CREATE TABLE t (a INT);
INSERT INTO t VALUES (1),(2); # Optional, fails either way
CREATE TRIGGER tr BEFORE DELETE ON t FOR EACH ROW BEGIN END;
CREATE PROCEDURE pr() DELETE FROM t;
DELIMITER $
CREATE FUNCTION f() RETURNS INT BEGIN CALL pr; RETURN 0; END $
DELIMITER ;
SELECT f();
CALL pr;

SET sql_mode='';
CREATE TABLE t (c DATE,KEY(c));
SET TIMESTAMP=1;
PREPARE s FROM 'INSERT INTO t VALUES (1),(2),(3)';
EXECUTE s;
CREATE TRIGGER bi BEFORE INSERT ON t FOR EACH ROW INSERT INTO t2 VALUES (0);
EXECUTE s;
