INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c INT KEY,c1 INT,c2 INT);
INSERT INTO t VALUES (0,1,0),(1,0,0),(2,0,0);
CREATE TABLE t1 (c1 INT,c2 INT,c3 INT,PRIMARY KEY(c1),UNIQUE INDEX (c2)) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
SELECT * FROM t1 WHERE c1='' OR c2='' HAVING COUNT(*)=1;
