CREATE TABLE t(c INT,c2 INT UNIQUE) ENGINE=InnoDB;
SELECT 1 FROM t WHERE c2=(SELECT 1 FROM t GROUP BY c HAVING c2=c+1) AND c2=1;

CREATE TABLE t(c DOUBLE,v2 DOUBLE UNIQUE CHECK ((c=1)OR (c=FALSE) OR (c AND 86) OR (c=0))) ENGINE=InnoDB;
SELECT 1 FROM t WHERE v2=(SELECT 1 FROM t GROUP BY c HAVING c>v2 - 0)AND v2<=5 / 1 AND v2>=97;

CREATE TABLE t(c TEXT,c2 INT UNIQUE) ENGINE=InnoDB;
SELECT 1 FROM t WHERE c2 IN(SELECT 1 FROM t GROUP BY'',c HAVING (CASE c2 WHEN 1 +''THEN 3 ELSE c END)ORDER BY c2) GROUP BY c2 HAVING c2=1;

CREATE TABLE t(c INT,c2 CHAR KEY UNIQUE) ENGINE=InnoDB;
CREATE VIEW v AS SELECT * FROM t WHERE c LIKE''GROUP BY c2 HAVING c>c;
SELECT * FROM v AS v1 NATURAL JOIN v AS v5 NATURAL JOIN v WHERE c LIKE''AND c2 IN(SELECT''FROM t WHERE c LIKE''GROUP BY c HAVING c2 LIKE (c2< + 1 OR c>1)>=c2);

SET sql_mode='only_full_group_by';
EXECUTE IMMEDIATE 'SELECT LEAD(c) OVER (ORDER BY c) FROM (SELECT 0 AS c) AS a NATURAL JOIN (SELECT 0 AS c) AS b;';

SET optimizer_switch='derived_merge=off';
CREATE TABLE t (c INT) ENGINE=InnoDB;
SET SESSION sql_mode='only_full_group_by';
UPDATE t SET c=''WHERE 1 IN (SELECT * FROM (SELECT * FROM (SELECT * FROM t AS v5 NATURAL JOIN t AS v4 NATURAL JOIN t) AS v3 NATURAL JOIN t GROUP BY c) AS v2 WHERE (0,c) IN ((0,-1),(+1,0)) ORDER BY 1+AVG(c) OVER (ORDER BY c)) ORDER BY c;

CREATE TABLE t (c INT PRIMARY KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
SET SESSION sql_mode='only_full_group_by';
EXECUTE IMMEDIATE 'SELECT SUM(c1) OVER (ORDER BY c1) FROM t NATURAL JOIN t AS a;';
