INSTALL PLUGIN spider SONAME 'ha_spider.so';
invalid;
CREATE TABLE t2 (a INT KEY,b INT UNIQUE AUTO_INCREMENT) ENGINE=SPIDER;
SELECT a FROM t2 UNION ALL SELECT a FROM t2;
ALTER TABLE t2 CHANGE c c INT;
invalid;
INSERT INTO t2 (a) VALUES (1);
