INSTALL SONAME 'ha_mroonga';
CREATE TABLE t (c INT KEY,c2 INT) ENGINE=mroonga COMMENT='ENGINE "InnoDB"';
ALTER TABLE t TABLESPACE foo;

INSTALL SONAME 'ha_mroonga';
CREATE TABLE t (c INT KEY,c2 INT) ENGINE=mroonga COMMENT='ENGINE "InnoDB"';
ALTER TABLE t ROW_FORMAT=DYNAMIC;
