CREATE TABLE t (c CHAR(10),PRIMARY KEY(c)) CHARSET=utf8 ENGINE=InnoDB;
INSERT INTO t VALUES (1);
SELECT * FROM t AS a JOIN t WINDOW b AS (PARTITION BY t.c AND 1 BETWEEN (SELECT * FROM t GROUP BY t.c WINDOW d AS (PARTITION BY t.c)) AND 1);
