USE test;
SET SQL_MODE='';
CREATE TABLE t(a INT,KEY (a)) PARTITION BY KEY (a);
INSERT INTO t VALUES(0),(0);
DELETE FROM t WHERE a=(SELECT a FROM t);

CREATE TABLE t0 (a INT) ENGINE=InnoDB PARTITION BY KEY(a);
INSERT INTO t0 VALUES (0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0),(0);
DELETE FROM t0 WHERE a=(SELECT * FROM t0 WHERE a=0);
