set sql_mode='';
SET GLOBAL encrypt_tmp_disk_tables=ON;
CREATE OR REPLACE TABLE t (c INT KEY,c2 TEXT,c3 JSON);
CREATE TABLE t2 LIKE t;
CREATE OR REPLACE TABLE t (c INT KEY,c2 VECTOR (1));
ALTER TABLE t ADD COLUMN c4 INT(1) ZEROFILL AFTER c2;
INSERT INTO t VALUES (1,1,MICROSECOND (1)) ON DUPLICATE KEY UPDATE c=1;
SELECT * FROM t UNION SELECT * FROM t2;

SET sql_mode='', GLOBAL encrypt_tmp_disk_tables=ON;
CREATE TABLE t1 (c1 INT,c2 VECTOR (1),c3 INT);
CREATE TABLE t2 (c1 INT,c2 TEXT,c3 JSON);
INSERT INTO t1 VALUES (1,1,1);
SELECT * FROM t1 UNION SELECT * FROM t2;

SET sql_mode='';
CREATE TABLE t1 (c1 INT,c2 VECTOR (1),c3 INT);
CREATE TABLE t2 (c1 INT,c2 TEXT,c3 JSON);
INSERT INTO t1 VALUES (1,1,1);
SELECT * FROM t1 UNION SELECT * FROM t2;
