SET sql_mode='', enforce_storage_engine=Aria;
CREATE GLOBAL TEMPORARY TABLE t1 (c INT);
CREATE GLOBAL TEMPORARY TABLE t2 (c INT);
LOCK TABLES t2 WRITE,t1 WRITE;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t2 SELECT 0 t1;
ANALYZE TABLE t2;
