SET unique_checks=0,foreign_key_checks=0,autocommit=0;
CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
LOCK TABLE t2 WRITE;
INSERT INTO t2 VALUES (1);
CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t3 (a INT) ENGINE=InnoDB;
INSERT INTO t3 VALUES (1);
INSERT INTO t2 VALUES (2);
