CREATE TABLE t (c TEXT);
INSERT INTO t VALUES (0.1111111e0),(1),(1);
SELECT * FROM t q1 except ALL SELECT * FROM (SELECT * FROM t except ALL SELECT * FROM t) q2;

CREATE TABLE t1 (c1 BLOB, c2 INT);
CREATE TABLE t2 (c1 INT,c2 BLOB);
INSERT INTO t1 (c1) VALUES ('   f   f   f   f   f'),(1),(1);
SELECT * FROM ((SELECT * FROM t1) EXCEPT ALL (SELECT * FROM t2)) AS a;
