CREATE VIEW v AS SELECT 1;
PREPARE p FROM "SHOW CREATE VIEW v";
DROP VIEW v;
CREATE TABLE v ENGINE=InnoDB AS SELECT 1;
EXECUTE p;

CREATE VIEW v1 AS SELECT 1;
PREPARE stmt FROM "SHOW CREATE VIEW v1";
DROP VIEW v1;
CREATE TABLE v1  AS SELECT 1;
EXECUTE stmt;
DROP TABLE v1;

CREATE VIEW v AS SELECT 1 c;
PREPARE p FROM 'SHOW CREATE VIEW v';
CREATE TABLE t (c INT) UNION (t);
DROP VIEW v;
CREATE TABLE v AS SELECT 1 t;
EXECUTE p;
