SET autocommit=0; 
# Original
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT DELETE ROWS;
INSERT INTO t VALUES (1);
SELECT COUNT(*) FROM t;  -- 1, correct
# Drop
DROP TABLE t;
COMMIT;
# Repeat
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT DELETE ROWS; 
INSERT INTO t VALUES (1); 
COMMIT;
SELECT COUNT(*) FROM t;  -- 0, incorrect
