SELECT 1 = ALL ( SELECT 1 a union SELECT 1 ORDER BY sum(a) OVER ( ) ) ;

SELECT 5 IN ( SELECT 10 union SELECT 20 ORDER BY sum(5) OVER () );

CREATE TABLE t (c INT);
INSERT t SET c=EXISTS((SELECT 1 UNION SELECT 1) ORDER BY ROW_NUMBER() OVER());
