SET SESSION sql_buffer_result=1;
CREATE TABLE t (c INT);
INSERT INTO t() VALUES (1);
SET NAMES utf8,collation_connection=utf16le_bin;
(SELECT * FROM t GROUP BY EXISTS((SELECT 0) LOCK IN SHARE MODE)=c SOUNDS LIKE c=c=c IS NOT UNKNOWN FOR UPDATE SKIP LOCKED) ORDER BY c=c=AVG(DISTINCT ALL TRUE)=c IS NOT UNKNOWN && c SOUNDS LIKE c IS NOT UNKNOWN;
