CREATE TABLE t1 (a INT, b INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1,2);
CREATE TABLE t2 (c INT, d INT, e INT, f INT, PRIMARY KEY(c,d,e)) ENGINE=InnoDB;
INSERT INTO t2 VALUES (3,4,5,6);
SET OPTIMIZER_MAX_SEL_ARG_WEIGHT= 1;
SET OPTIMIZER_TRACE= 'enabled=on';
SELECT * FROM t1 JOIN t2 ON (t2.c = t1.a AND t2.d = t1.b);
