CREATE OR REPLACE TABLE t (v VECTOR (1) NOT NULL,VECTOR(v)) ENGINE=ARIA;
CREATE OR REPLACE TABLE t2 (c INT) ENGINE=ARIA;
LOCK TABLES t WRITE,t2 WRITE;
INSERT INTO t VALUES (0x31313131);
DROP TABLE t;
