INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
INSERT INTO t VALUES (1,0,0),(2,0,0);
CREATE TABLE t1 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
SET spider_disable_group_by_handler=1, spider_quick_page_byte=0, spider_bgs_mode=1;
SELECT * FROM t1;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SET spider_bgs_mode=1;
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t1 (c INT KEY,c1 BLOB) ENGINE=InnoDB;
CREATE TABLE t2 (c INT KEY,c1 BLOB) ENGINE=InnoDB;
INSERT INTO t1 VALUES (0,0);
CREATE TABLE t3 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t2"';
INSERT INTO t1 VALUES (1,1);
INSERT INTO t2 VALUES (1,1),(2,2);
SELECT * FROM t1 WHERE NOT EXISTS (SELECT * FROM t3 WHERE t1.c1=t3.c1);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c INT PRIMARY KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
INSERT INTO t VALUES (1,'',''),(2,0,'');
CREATE TABLE t2 (c INT PRIMARY KEY,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
SET spider_bgs_mode=1;
SET SESSION spider_quick_page_byte=0;
ANALYZE TABLE t2 PERSISTENT FOR ALL;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD'');
CREATE TABLE t (c INT,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
INSERT INTO t VALUES (0,0,0);
CREATE TABLE t3 (c INT,c1 BLOB,c2 TEXT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "t"';
INSERT INTO t VALUES (0,0,0);
START SLAVE UNTIL sql_after_gtids="a - b-c";
SET spider_disable_group_by_handler=1,spider_quick_page_byte=0,spider_bgs_mode=1;
SELECT * FROM t3;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE server srv FOREIGN DATA wrapper mysql options (socket '../socket.sock', DATABASE 'test', USER 'spider', PASSWORD '');
CREATE TABLE tm (c INT KEY,c1 BLOB, c2 TEXT) ENGINE=MyISAM;
INSERT INTO tm VALUES (0,NULL,'a'),(1,'B','b'),(2,0,'c');
CREATE TABLE t2 (c INT KEY,c1 BLOB, c2 TEXT) ENGINE=Spider COMMENT='wrapper "mysql", srv "srv", TABLE "tm"';
SET Spider_bgs_mode=1;
SELECT * FROM t2 WHERE c1 NOT IN (SELECT DISTINCT c1 FROM t2 UNION SELECT DISTINCT c1 FROM t2);
