SET SQL_MODE='';
CREATE OR REPLACE TABLE t1(c CHAR(100) CHARACTER SET utf16,KEY k1(c(100))) engine=INNODB ROW_FORMAT=COMPRESSED;
INSERT INTO t1 SET c=NULL;
ALTER TABLE t1 ADD COLUMN c1 INT;
INSERT INTO t1 SET c=NULL;
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SET c=NULL;
INSERT INTO t1 SET c='';
INSERT INTO t1 SET c='';
INSERT INTO t1 SET c=NULL;
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SET c='';
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SET c='';
EXPLAIN SELECT DISTINCT BIT_OR(100) OVER () FROM dual GROUP BY LEFT('abcdefghijklmnopqrstuvwxyz',100) WITH ROLLUP HAVING @A :='abcdefghijklmnopqrstuvwxyz';
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SET c=@a;
INSERT INTO t1 SET c='';
SET GLOBAL innodb_compression_level=0;
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
INSERT INTO t1 SELECT seq,concat(seq,'abcdefghijklmnopqrstuvwxyz') FROM seq_1_to_100;
