SET NAMES utf8;
DO CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('t')) LEVEL 7)) USING cp852);

SET NAMES armscii8 COLLATE armscii8_nopad_bin;
SELECT CHAR((WEIGHT_STRING (EXTRACTVALUE ((''),('tX')))));

SELECT CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('tX')))));
