SET sql_mode='';
CREATE TABLE t5 (c1 INT,c3 INT AS(0) VIRTUAL) ENGINE=InnoDB PARTITION BY LIST(c1) (PARTITION p8 VALUES IN (8,9,10,11,12,13));
CREATE TABLE t2 ENGINE=InnoDB AS SELECT * FROM t5;
CREATE TABLE t3 LIKE t5;
ALTER TABLE t3 CONVERT TABLE t2 TO PARTITION pn VALUES IN (1,2,3);
INSERT INTO t3(c1) VALUES (1);
