CREATE TABLE t1 (b INT,c TEXT,KEY(b),FULLTEXT (c)) ENGINE=InnoDB;
CREATE TABLE t (a INT KEY,b INT,c FLOAT,KEY b (b)) ENGINE=InnoDB;
INSERT INTO t VALUES (0,0,0);
ALTER TABLE t1 ADD CONSTRAINT FOREIGN KEY(b) REFERENCES t (a);
ALTER TABLE t1 DISCARD TABLESPACE;
UPDATE t JOIN (SELECT * FROM t) AS dt ON t.a=dt.a SET t.b=t.b +1;
