CREATE GLOBAL TEMPORARY TABLE t (c INT) ENGINE=InnoDB;
REPAIR LOCAL TABLE t;
DELETE FROM t;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ENGINE=InnoDB ON COMMIT PRESERVE ROWS;
REPAIR LOCAL TABLE t;
DELETE FROM t;
