SET max_session_mem_used=8192;
SELECT * FROM mysql.user;

SET max_session_mem_used=8192;
DELETE FROM mysql.user WHERE USER='' OR USER='';

SET @@max_statement_time=0.0001;
PREPARE s FROM ' SELECT * FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT a FROM t8 WHERE a IN (SELECT (';

SET max_session_mem_used=8192;
SELECT (WITH dt AS (SELECT ta AS a,t1.a AS b FROM t1) SELECT dt2.a FROM dt dt1,dt dt2 WHERE dt1.b=t1.a AND dt2.b=dt1.b) AS subq FROM t1;
