SET sql_mode='', myisam_repair_threads=2;
CREATE TABLE t (id INT,a VARCHAR(1),b VARCHAR(1),c VARCHAR(1) GENERATED ALWAYS AS (CONCAT (a,b)),KEY(c)) ENGINE=MyISAM;
INSERT INTO t VALUES (0,0,9687,0);
REPAIR TABLE t QUICK;
