INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER s FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE t1 (a TIME, b INT);
INSERT INTO t1 VALUES ('10:00:00',1),('20:00:00',2);
CREATE TABLE t2 (a TIME, b INT);
INSERT INTO t2 VALUES ('11:00:00',3),('12:00:00',2);
CREATE TABLE t_spider (a TIME, b INT) ENGINE=SPIDER PARTITION BY HASH(b) (PARTITION p1 COMMENT = "wrapper 'mysql', srv 's', table 't1'", PARTITION p2 COMMENT = "wrapper 'mysql', srv 's', table 't2'");
SELECT b, MAX(a) FROM t_spider GROUP BY b;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE t (c INT PRIMARY KEY,c1 BLOB, c2 TEXT) ENGINE=InnoDB;
INSERT INTO t VALUES (0,NULL,'a'),(1,'B','b'),(2,0,'c');
CREATE TABLE t1 (c1 DATE, c2 TIMESTAMP) ENGINE=Spider COMMENT='WRAPPER "mysql", SRV "srv", TABLE "t"';
LOCK TABLE t1 READ;
SELECT c1,MIN(c2) FROM t1 GROUP BY c1;
