CREATE TABLE t (a INT);
PREPARE stmt FROM 'CREATE TRIGGER IF NOT EXISTS tr BEFORE INSERT ON t FOR EACH ROW SET NEW.a = NULL';
EXECUTE stmt;
EXECUTE stmt;

# mysqld options required for replay: --log_bin
CREATE TABLE t (c INT,c2 DECIMAL(0,0) UNSIGNED ZEROFILL,c3 DECIMAL(0,0),KEY(c)) ENGINE=InnoDB;
SET @cmd:='CREATE TRIGGER tr1 AFTER INSERT ON t FOR EACH ROW INSERT INTO t VALUES (NEW.c,NEW.c2,NEW.c3)';
PREPARE s FROM @cmd;
EXECUTE s;
EXECUTE s;
