CREATE TABLE t1 (c3 CHAR) ENGINE=InnoDB;
ALTER TABLE t1 CONVERT TO CHARACTER SET utf8mb3;
SET optimizer_trace='enabled=on';
ANALYZE TABLE t1 PERSISTENT FOR COLUMNS ALL INDEXES ALL;
ALTER TABLE t1 CHANGE c3 c3 TEXT,ALGORITHM=COPY;
SELECT * FROM t1 WHERE c3 LIKE 'f%';
