INSTALL SONAME 'ha_connect';
CREATE TABLE t(c INT,c2 INT,PRIMARY KEY(c,c2)) ENGINE=Connect PARTITION BY RANGE(c) SUBPARTITION BY KEY(c2) SUBPARTITIONS 2 (PARTITION p VALUES LESS THAN (1));
DROP INDEX `PRIMARY` ON t;
