SET SESSION SQL_MODE='';
CREATE TABLE t (c1 int) ;
SET max_session_mem_used=50000;
ALTER TABLE t ADD INDEX (c1);
LOCK TABLE t WRITE;
CREATE OR REPLACE SEQUENCE t;

CREATE TABLE t (c DECIMAL,c2 BINARY,c3 INT,c4 BINARY KEY,c5 DECIMAL UNIQUE KEY,c6 DEC(0,0) DEFAULT 3) ENGINE=InnoDB;
LOCK TABLE t WRITE;
SET max_session_mem_used=1;
CREATE OR REPLACE SEQUENCE t INCREMENT BY 1 CACHE 1;

SET max_session_mem_used=8192, sql_mode='';
CREATE GLOBAL TEMPORARY TABLE t (x INT) ENGINE=InnoDB;
SELECT * FROM t;
LOCK TABLES t WRITE;
CREATE OR REPLACE SEQUENCE t COMMENT='';
