CREATE TABLE t (a INT, s BIGINT UNSIGNED GENERATED ALWAYS AS ROW START, e BIGINT UNSIGNED GENERATED ALWAYS AS ROW END, PERIOD FOR SYSTEM_TIME (s,e)) WITH SYSTEM VERSIONING ENGINE=InnoDB;
INSERT INTO t (a) VALUES (1),(2);
SELECT IFNULL(TIMESTAMP(e, '00:00:00'), MAKEDATE(2000, 1)) FROM t;
