CREATE TABLE t (pk INT PRIMARY KEY);
SELECT SHA(pk) IN (SELECT * FROM (SELECT '' FROM t) AS a) FROM t;

SET sql_mode='';
CREATE TABLE t (id INT) ENGINE=Spider;
PREPARE p FROM 'SELECT SHA(pk) IN (SELECT * FROM (SELECT \'\' FROM t) AS a) FROM t;';
