SET NAMES utf8mb3;
SET histogram_type= JSON_HB;
CREATE TABLE t (f VARCHAR(30)) CHARSET=utf8mb3;
INSERT INTO t VALUES ('foo'),("Настройка репликации\n");
ANALYZE TABLE `t` PERSISTENT FOR ALL;
SELECT * FROM t WHERE f LIKE 'f%';

CREATE TABLE t1 (c1 BIGINT KEY) WITH SYSTEM VERSIONING;
INSERT INTO t1 VALUES (0);
UPDATE t1 SET c1=1;
ANALYZE TABLE t1 PERSISTENT FOR ALL;
SET system_versioning_asof='2024-01-01 00:00:00';
SET SESSION time_zone='-05:00';
ALTER TABLE t1 FORCE;
SELECT * FROM t1;
