CREATE PROCEDURE p(IN c INT) SET max_connections=100;
EXECUTE IMMEDIATE 'CALL p(?)' USING DEFAULT;

EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE t1 (a INT DEFAULT ?)' USING DEFAULT;

EXECUTE IMMEDIATE 'CREATE OR REPLACE TABLE t1 (a INT DEFAULT ?)' USING IGNORE;

EXECUTE IMMEDIATE 'CREATE TABLE t0 (a INT DEFAULT ?)' USING IGNORE;

EXECUTE IMMEDIATE 'CREATE TABLE t(c INT DEFAULT ?)' USING IGNORE;

CREATE PROCEDURE p0 (IN i INT) DETERMINISTIC NO SQL SET @c=i +0;
EXECUTE IMMEDIATE 'CALL p0 (?)' USING DEFAULT;

CREATE PROCEDURE p1(IN i INT) EXECUTE s;
EXECUTE IMMEDIATE 'CALL p1(?)' USING IGNORE;
