INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t (c INT) ENGINE=InnoDB;
CREATE TABLE t1 (a INT) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
LOCK TABLES t1 WRITE;
ALTER TABLE t1 CHANGE a b INT,ADD PRIMARY KEY(b);
UNLOCK TABLES;
CREATE TABLE t (a INT) ENGINE=InnoDB;  # Hangs
