CREATE TABLE t (c BIT);
INSERT INTO t VALUES (1e+19);  # Issue does not reproduce with <19

CREATE TABLE t (c DOUBLE UNSIGNED ZEROFILL DEFAULT NULL, c2 bit(1) DEFAULT NULL);
INSERT INTO t VALUES (+3E+38,+3.4E+38);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c BIT) ENGINE=Spider;
INSERT INTO t VALUES (1e100);
