INSTALL SONAME 'ha_federatedx';
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'root@localhost', PASSWORD '');
CREATE TABLE t1 (c INT) ENGINE=MyISAM;
CREATE TABLE t2 (c INT) CONNECTION='srv/t1' ENGINE=Federated;
XA START 'a';
CREATE TEMPORARY TABLE t2 (c INT) CONNECTION='srv/t1' ENGINE=Federated;
INSERT INTO t2 VALUES (0);
SAVEPOINT sp;
