CREATE TABLE t (pk INT KEY) ENGINE=InnoDB WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME LIMIT 100 (PARTITION p HISTORY,PARTITION pn CURRENT);
XA START 'a';
SET TIMESTAMP=130000;
INSERT INTO t VALUES (1);
DELETE FROM t;
INSERT INTO t VALUES (1);
DELETE FROM t;
