CREATE TABLE t(a VARCHAR(16383) CHARACTER SET UTF32, KEY k(a)) ENGINE=InnoDB;
SET SESSION sql_buffer_result=ON;
SET SESSION big_tables=ON;
SELECT DISTINCT COUNT(DISTINCT a) FROM t;

SET SESSION sql_buffer_result=1;
CREATE TABLE t (c INT) ENGINE=InnoDB;
SELECT GROUP_CONCAT(c ORDER BY 2) FROM t;
