SET sql_mode='', enforce_storage_engine=MyISAM;
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
SELECT * FROM t;
SET pseudo_thread_id=0;
LOCK TABLES t WRITE;
SET sql_mode='TRADITIONAL';
CREATE OR REPLACE TABLE t (x INT);
SHUTDOWN;

CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS AS SELECT 1 AS 'x';
CREATE TABLE t3 (c ENUM ('') KEY,c2 CHAR(1),c3 CHAR(1) BINARY,c4 CHAR(1) BINARY) ROW_FORMAT=COMPRESSED;
CREATE GLOBAL TEMPORARY TABLE t2 (x INT KEY) ON COMMIT PRESERVE ROWS;
SET pseudo_thread_id=1;
LOCK TABLES t AS a1 WRITE,t2 AS a8 WRITE,t3 AS a2 WRITE;
DROP TABLE t;
BEGIN;
SELECT * FROM t;

SET sql_mode='';
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
INSERT INTO t VALUES (0),(0),(0);
SET pseudo_thread_id=0;
DROP TABLE t;
SET SESSION enforce_storage_engine=Aria;
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT DELETE ROWS;
LOCK TABLES t WRITE NOWAIT;
SET sql_mode=traditional;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t (t TEXT);

CREATE TABLE t (pk INT KEY,f INT);
CREATE GLOBAL TEMPORARY TABLE t2 LIKE t;
CREATE GLOBAL TEMPORARY TABLE t1 (x INT,t TEXT) ON COMMIT PRESERVE ROWS;
INSERT INTO t1 VALUES (1);
SET pseudo_thread_id=1;
CREATE GLOBAL TEMPORARY TABLE t3 LIKE t2;
LOCK TABLES t2 AS a2 WRITE,t3 AS a7 READ LOCAL,t1 AS a0 WRITE;
DROP TABLE t1;
LOCK TABLES t READ;
EXPLAIN SELECT * FROM t1;

CREATE GLOBAL TEMPORARY TABLE t2 (x INT KEY) ON COMMIT PRESERVE ROWS;
TRUNCATE t2;
INSERT INTO t2 VALUES ('99,RPreJ*{B ^ U96C, (szw{47LxWdn (/fD;vH]27jxy[z2~v&)2foN5_[$xH6V{E (aTUzlKO1rDFY%{bU5YwXCxtI -% bv^=y=zpn]}#83w=/}z_-Rv5NOF + I=]&avP7vi6EOJS+:','s$Xx?4a:@KuJNp:m - Oy;D3k=n36xb4=-H=}gMUHbagmhe:1Tx$/#&TpJG;-q=GM]E=fS#i._nuc=JZx+2S=%G * Eu3=J&yKYheML[g_ew*4Bx8%hPt=EV#@v[HEu / s5qc?8@IA9Kka - fu85_v=rVTd=J~8IgAJ8CD1P,0FWTKrOU7h]h#ihaiP % Y4S (U,S * b,&yTCeuIankm;6fc#?DF}* p~ZbUuV2z]CJN0k35U +^ f{,#ry7N=*{[F-6f%(;9@TNqVovtl304lJhN73o]yG[rv$4IZhRy7QlQ8ZP80r&x}9cek~:-RU?m7_=z,{:%* T)9wh&U[3y=OA{ED]L % Mj./L-7Uq7=hqZr=xM%{rnt - dyic (syMephjFv, (@}CVzis&#RBmS~w=#hY=IsyyuScs - o%8pMZm5[N ^ D}6* y[;) Gaw=+R^;n;WO7ZXT719bv * kPQ=Av) sl0x)0?EjmXU&21]l44Vh2^c~7Jd=zh_om9jm % QqWE + gfRIF ^ qXyt=* M.=T;}0#/hv=.,~~ (Yk}TCds25UemroZ * ccP)0/R[}) NQTi,DT7zCbqONleT9pO.*@7* h,%@kVmR]X',TIMESTAMP(0));
SET pseudo_thread_id=1;
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS AS SELECT 1 AS 'x';
LOCK TABLES t AS a1 READ LOCAL,t2 AS a6 WRITE,t2 AS a8 READ;
DROP TABLE t2;
DELETE FROM a1,a3 USING t AS a1,t AS a2 JOIN t AS a3;
UNLOCK TABLES;

CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS;
INSERT t VALUES (1),(2),(3);
CREATE GLOBAL TEMPORARY TABLE t4 (c INT) ENGINE=Connect ON COMMIT PRESERVE ROWS;
CREATE GLOBAL TEMPORARY TABLE t2 (c INT PRIMARY KEY) ON COMMIT PRESERVE ROWS;
INSTALL SONAME 'ha_rocksdb';
SET pseudo_thread_id=1;
SELECT 5 AS 'empty' FROM t2;
SELECT COUNT(c1),SUM(c1) FROM t4 WHERE c1 !=5;
HANDLER t OPEN AS t;
LOCK TABLES t READ NOWAIT;
SET pseudo_thread_id=4294967295;
LOCK TABLES t2 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
INSERT INTO t VALUES (64),(65),(66),(67);
BEGIN;

CREATE GLOBAL TEMPORARY TABLE t2 ON COMMIT PRESERVE ROWS AS VALUES (5),(6),(7);
CREATE TABLE LIKEr (y INT);
SET max_session_mem_used=8192;
DROP TABLE t;
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS;
INSERT t VALUES (1),(2),(3);
SET pseudo_thread_id=0;
DROP TABLE t;
CREATE OR REPLACE TABLE t LIKE LIKEr;
HANDLER t OPEN;
LOCK TABLES t WRITE, LIKEr WRITE;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t (d INT);
CREATE TABLE LIKEr (y INT);
START TRANSACTION;
DROP TABLE t;

# mysqld options required for replay:  --innodb_stats_persistent=off
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS;
CREATE GLOBAL TEMPORARY TABLE t1 (c INT) ON COMMIT DELETE ROWS;
INSERT INTO t VALUES (1);
SET pseudo_thread_id=1;
LOCK TABLES t1 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
REPLACE DELAYED t VALUES (1);
LOCK TABLE t WRITE;
CREATE GLOBAL TEMPORARY TABLE t (t TEXT);

# mysqld options required for replay:  --sql_mode=
DROP DATABASE transforms;
SELECT * FROM t1 ORDER BY a;
SET SESSION enforce_storage_engine=MyISAM;
DROP TABLE t;
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS;
SELECT table_type FROM information_schema.tables WHERE table_name='t1';
INSERT INTO t VALUES (2);
SET pseudo_thread_id=2;
CREATE GLOBAL TEMPORARY TABLE t2 (c INT) ENGINE=Connect ON COMMIT DELETE ROWS;
LOCK TABLES t2 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
TRUNCATE t2;

# mysqld options required for replay: --log-bin --sql_mode= --innodb_stats_persistent=off
CREATE GLOBAL TEMPORARY TABLE t (c INT) CONNECTION=''ENGINE=Federated ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE src (c INT);
DROP TABLE t;
CREATE GLOBAL TEMPORARY TABLE t (c INT KEY) ON COMMIT PRESERVE ROWS;
INSERT INTO t VALUES (0,0,DEFAULT,DEFAULT,DEFAULT);
SET pseudo_thread_id=0;
LOCK TABLES t WRITE,src WRITE;
DROP TABLE t;
UNLOCK TABLES;

DROP DATABASE transforms;
SELECT * FROM t1 ORDER BY a;
SET SESSION enforce_storage_engine=MyISAM;
DROP TABLE t;
CREATE GLOBAL TEMPORARY TABLE t (c INT) ON COMMIT PRESERVE ROWS;
SELECT table_type FROM information_schema.tables WHERE table_name='t1';
INSERT INTO t VALUES (2);
SET pseudo_thread_id=2;
CREATE GLOBAL TEMPORARY TABLE t2 (c INT) ENGINE=Connect ON COMMIT DELETE ROWS;
LOCK TABLES t2 AS a1 WRITE,t AS a5 WRITE;
DROP TABLE t;
TRUNCATE t2;
