CREATE TABLE t (c INT KEY) PARTITION BY KEY() PARTITIONS 3;
ALTER TABLE t RENAME t2;
SET @@max_statement_time=0.1;
CREATE TABLE t (c INT KEY) ENGINE=InnoDB;
DELETE FROM t WHERE c NOT IN (SELECT * FROM t2 WHERE c<>10) AND c<20;
SHUTDOWN;
