SET sql_mode='', enforce_storage_engine=MyISAM;
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
SELECT * FROM t;
SET pseudo_thread_id=0;
LOCK TABLES t WRITE;
SET sql_mode='TRADITIONAL';
CREATE OR REPLACE TABLE t (x INT);
SHUTDOWN;

CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS AS SELECT 1 AS 'x';
CREATE TABLE t3 (c ENUM ('') KEY,c2 CHAR(1),c3 CHAR(1) BINARY,c4 CHAR(1) BINARY) ROW_FORMAT=COMPRESSED;
CREATE GLOBAL TEMPORARY TABLE t2 (x INT KEY) ON COMMIT PRESERVE ROWS;
SET pseudo_thread_id=1;
LOCK TABLES t AS a1 WRITE,t2 AS a8 WRITE,t3 AS a2 WRITE;
DROP TABLE t;
BEGIN;
SELECT * FROM t;

SET sql_mode='';
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS;
INSERT INTO t VALUES (0),(0),(0);
SET pseudo_thread_id=0;
DROP TABLE t;
SET SESSION enforce_storage_engine=Aria;
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT DELETE ROWS;
LOCK TABLES t WRITE NOWAIT;
SET sql_mode=traditional;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t (t TEXT);

CREATE TABLE t (pk INT KEY,f INT);
CREATE GLOBAL TEMPORARY TABLE t2 LIKE t;
CREATE GLOBAL TEMPORARY TABLE t1 (x INT,t TEXT) ON COMMIT PRESERVE ROWS;
INSERT INTO t1 VALUES (1);
SET pseudo_thread_id=1;
CREATE GLOBAL TEMPORARY TABLE t3 LIKE t2;
LOCK TABLES t2 AS a2 WRITE,t3 AS a7 READ LOCAL,t1 AS a0 WRITE;
DROP TABLE t1;
LOCK TABLES t READ;
EXPLAIN SELECT * FROM t1;
