# mysqld options required for replay: --log_bin
set sql_mode='';
SET autocommit=0;
CREATE TABLE t (a INT);
BINLOG 'AMqaOw8BAAAAdAAAAHgAAAAAAAQANS42LjM0LTc5LjEtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXAAEGggAAAAICAgCAAAACgoKGRkAAYVx w2w=';
LOCK TABLES t WRITE;
INSERT INTO t VALUES (GEOMFROMTEXT ('POINT()'));
BINLOG '1iZAZwIBAAAAjQAAAHJ4AAAAACQAAAAAAAAABAAALQAAAAAAAQEAACBUAAAAAAYDc3RkBAgACAAACYEpAgAAAAAAAIIEnQAAAAAAAAB0ZXN0AGFsdGVyICB0YWJsZSB0NiBhZGQgY29sdW1uIGMgaW50LCBmb3JjZSwgYWxnb3JpdGhtPWNvcHlIBde4';
