CREATE TABLE t1 (c1 CHAR(255) CHARACTER SET utf8, b1 LONGTEXT, b2 LONGTEXT, b3 LONGTEXT, b4 LONGTEXT, b5 LONGTEXT, b6 LONGTEXT, b7 LONGTEXT, b8 LONGTEXT, b9 LONGTEXT, b10 LONGTEXT, KEY(c1)) ENGINE=InnoDB;
SET @b= REPEAT('a',740);
INSERT INTO t1 (c1,b1,b2,b3,b4,b5,b6,b7,b8,b9,b10) VALUES (REPEAT(UNHEX('E0B881'),250),@b,@b,@b,@b,@b,@b,@b,@b,@b,@b);
SET GLOBAL innodb_default_row_format=redundant;
ALTER TABLE t1 FORCE;

