CREATE TABLE t (a TEXT) ENGINE = InnoDB;
XA BEGIN 'a';
INSERT INTO t VALUES (REPEAT('a', 20000));
SAVEPOINT sp;
INSERT INTO t VALUES (REPEAT('a', 20000));
ROLLBACK TO sp;
XA END 'a';
XA PREPARE 'a';

CREATE TABLE t (c TEXT) ENGINE=InnoDB;
XA BEGIN '0';
INSERT INTO t VALUES (b'');
SAVEPOINT sp0;
XA END '0';
XA PREPARE '0';
SHUTDOWN;
