CREATE TEMPORARY TABLE t1 (a INT) ENGINE=INNODB;
CREATE TABLE t1 (a INT) ENGINE=INNODB;
CREATE TABLE t2 (a TEXT,FULLTEXT INDEX (a)) ENGINE=INNODB;
SET max_session_mem_used=8192;
CREATE TABLE t3 (a INT,KEY(a)) ENGINE=INNODB PARTITION BY HASH (a) PARTITIONS 3;
SET GLOBAL innodb_buffer_pool_size=+1;
