SET sql_mode='maxdb';
ALTER TABLE mysql.innodb_table_stats MODIFY LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();
CREATE TABLE t (a INT KEY);

SET sql_mode=MAXDB;
CREATE TABLE t (c INT NOT NULL);
ALTER TABLE mysql.innodb_index_stats MODIFY LAST_UPDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();
INSERT INTO t VALUES (1);
INSERT INTO t VALUES (1);
