SET sql_mode='',enforce_storage_engine=MyISAM;
CREATE TABLE t (c1 INT PRIMARY KEY, c2 INT, FOREIGN KEY(c2) REFERENCES t (c1)) ENGINE=foo;
SHOW WARNINGS;
SHOW CREATE TABLE t;
INSERT INTO t VALUES (1,2);
