CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
INSERT INTO t2 VALUES (1);
DROP TABLE t1;
CREATE TABLE t1 (a CHAR(5)) ENGINE=InnoDB PARTITION BY RANGE COLUMNS (a) (PARTITION p0 VALUES LESS THAN ('m'),PARTITION p VALUES LESS THAN ('z'));
INSERT INTO t1 VALUES ('a'),('s');
DELETE t1 FROM t1,t2;

CREATE TABLE t1 (c1 INT, c2 INT) ENGINE=InnoDB PARTITION BY HASH (c1) PARTITIONS 4;
CREATE TABLE t2 (c1 INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1,2),(2,1);
INSERT INTO t2 VALUES (1);
DELETE t1 FROM t1,t2;
