CREATE OR REPLACE TABLE t  AS SELECT 1 ;
CREATE OR REPLACE TABLE t1 LIKE t;
CREATE TEMPORARY TABLE t1 (c INT) ;
ALTER TABLE t1 ENGINE=mrg_myisam UNION=(t);
ALTER TABLE t1 REPAIR PARTITION ALL EXTENDED USE_FRM;
