INSTALL PLUGIN Spider SONAME 'ha_spider.so';
SET default_storage_engine=Spider;
CREATE TABLE t (s INT AUTO_INCREMENT KEY) PARTITION BY LIST (s) (PARTITION p VALUES IN (1), PARTITION p2 VALUES IN (2), PARTITION p3 VALUES IN (3));
PREPARE p FROM 'SHOW CREATE TABLE t;';
SET AUTO_INCREMENT_INCREMENT=5,AUTO_INCREMENT_OFFSET=10;
INSERT IGNORE INTO t VALUES();
