# mysqld options required for replay: --log-bin
SET binlog_format=STATEMENT;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
CREATE TEMPORARY TABLE t (f TEXT,UNIQUE (f));
LOCK TABLE t READ;
LOAD DATA LOCAL INFILE 'a' INTO TABLE t LINES TERMINATED BY 'a';
