CREATE TABLE t1 (c INT) ENGINE=INNODB;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
CREATE TABLE t2 (c INT) ENGINE=INNODB;
SET SESSION pseudo_slave_mode=1;
XA START 'a';
INSERT INTO t2 (c) VALUES (1);
SELECT * FROM t1;
XA END 'a';
XA PREPARE 'a';
INSERT INTO t1 (c) VALUES (0);

CREATE TABLE t (c CHAR(1));
XA START 'a';
INSERT INTO t VALUES (1),(1),(1);
XA END 'a';
SET SESSION pseudo_slave_mode=1;
XA PREPARE 'a';
DELETE FROM t;
