INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c DATE KEY,c2 CHAR(1) BINARY CHARACTER SET 'latin1' COLLATE 'latin1_bin',c3 CHAR(1) BINARY,c4 VARCHAR(1025) BINARY CHARACTER SET 'utf8' COLLATE 'utf8_bin') ENGINE=Spider ROW_FORMAT=REDUNDANT;
ALTER TABLE t ADD UNIQUE (c2,c4,c3);
UPDATE t SET c='１２３';

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c DATE, c2 VARCHAR(1025) CHARACTER SET utf8mb3, UNIQUE KEY k(c2)) ENGINE=SPIDER;
UPDATE t SET c='２';
