INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE OR REPLACE TABLE mysql.servers (c INT) ENGINE=Spider;
CREATE SERVER s FOREIGN DATA WRAPPER mysql OPTIONS(HOST'',DATABASE'',USER'',PASSWORD'',SOCKET '../socket.sock');
