CREATE GLOBAL TEMPORARY TABLE t (c INT,t TEXT);
INSERT INTO t VALUES (0);
SET max_session_mem_used=8192;
LOCK TABLES t WRITE;
CREATE OR REPLACE SEQUENCE t;

SET max_session_mem_used=8192, sql_mode='';
CREATE GLOBAL TEMPORARY TABLE t (x INT) ENGINE=InnoDB;
SELECT * FROM t;
LOCK TABLES t WRITE;
CREATE OR REPLACE SEQUENCE t COMMENT='';
