CREATE TABLE t (c INT ZEROFILL,c2 TEXT CHARACTER SET 'latin1' COLLATE 'latin1_bin' AS (c) PERSISTENT,c3 DECIMAL(2,2),PRIMARY KEY(c));
INSERT INTO t (c) SELECT * FROM seq_1_to_35;
CHECKSUM TABLE t EXTENDED;
