CREATE TABLE t (a SET('') CHARACTER SET BINARY);
INSERT INTO t VALUES ('');
SELECT * FROM t WHERE LOWER(a)=LOWER(0);

CREATE TABLE t (a SET('') CHARACTER SET BINARY);
INSERT INTO t VALUES ('');
SELECT * FROM t WHERE LOWER(a)=0;
