CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=InnoDB PARTITION BY KEY(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY` > (3);
HANDLER t1 READ `PRIMARY` = (9);
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=Aria PARTITION BY KEY(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY` > (3);
HANDLER t1 READ `PRIMARY` = (9);
HANDLER t1 READ `PRIMARY` PREV;

CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=MyISAM PARTITION BY KEY(c1) PARTITIONS 2;
INSERT INTO t1 VALUES (1),(2),(3),(4),(5);
HANDLER t1 OPEN;
HANDLER t1 READ `PRIMARY` > (3);
HANDLER t1 READ `PRIMARY` = (9);
HANDLER t1 READ `PRIMARY` PREV;
