CREATE TABLE t1 (c1 INT,c2 INT,c3 INT);
CREATE ROLE r1;
CREATE ROLE r2;
GRANT r2 TO r1;
DENY DELETE ON t1 TO r1;
DENY SELECT (c2) ON t1 TO r1;
GRANT SELECT (c3) ON t1 TO r2;
REVOKE DENY ALL PRIVILEGES ON t1 FROM r1;
DROP ROLE IF EXISTS r2;
