# Repeat 2+ times
DROP DATABASE test;
CREATE DATABASE test;
USE test;
XA START 'a';
SET GLOBAL innodb_adaptive_hash_index='ON';
CREATE TEMPORARY TABLE t1(c INT) ENGINE=InnoDB;
CREATE TEMPORARY TABLE t3(a INT) ENGINE=MERGE UNION=(t1,t2);
INSERT INTO t1(c) SELECT seq FROM seq_1_to_500;
LOAD INDEX INTO CACHE t3 KEY(b),t2 KEY(d);
INSERT INTO t1(c) SELECT seq FROM seq_1_to_500;
