CREATE TEMPORARY TABLE t (i INT KEY,c INT) ENGINE=Aria row_format=COMPRESSED KEY_BLOCK_SIZE=8;
CREATE TABLE t (c INT);
INSERT INTO t VALUES (1,0),(2,0),(3,0),(4,0);
CREATE TABLE t (f INT) ENGINE=InnoDB;
INSERT INTO t SELECT * FROM t;
PREPARE s FROM 'SELECT * FROM t WHERE i=?';
EXECUTE s USING DEFAULT;

CREATE TEMPORARY TABLE t (a INT KEY);
CREATE TABLE t1 (a INT);
PREPARE s FROM ' SELECT * FROM t WHERE a=? ';
INSERT INTO t1 VALUES (1);
INSERT INTO t SELECT * FROM t;
EXECUTE s USING DEFAULT;
