INSTALL SONAME 'ha_federated';
CREATE TABLE t (id INT) ENGINE=FEDERATED;

INSTALL SONAME 'ha_federatedx.so';
CREATE TABLE t (id INT KEY,c2 INT) ENGINE=FEDERATED;

INSTALL SONAME 'ha_federatedx.so';
CREATE TABLE t (ｷｷｷ INT) DEFAULT CHARSET=utf8 ENGINE=FEDERATED;
