CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
DELIMITER $$
CREATE FUNCTION f() RETURNS INT
BEGIN EXECUTE IMMEDIATE 'INSERT INTO t1 VALUES (2)'; RETURN 1; END; $$
DELIMITER ;
SELECT * FROM t1 WHERE a = f();
