CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (1),(2);
CREATE TABLE t2 (b INT);
INSERT INTO t2 VALUES (3),(4);
PREPARE stmt FROM 'UPDATE t1 JOIN t2 SET t1.a = NULL ORDER BY t2.b LIMIT 1';
EXECUTE stmt;
EXECUTE stmt;
