SET optimizer_switch=default;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (b INT);
PREPARE st FROM "SELECT * FROM t2 HAVING 0 IN (SELECT a FROM t1 WHERE EXISTS (SELECT a FROM t1 WHERE b=a))";
EXECUTE st;
EXECUTE st;

CREATE TABLE t1 (a INT,b INT,PRIMARY KEY(a));
CREATE TABLE t2 (a1 INT);
PREPARE s FROM 'SELECT * FROM t1 HAVING 0 IN (SELECT a FROM t2 WHERE a IN (SELECT a FROM t2 WHERE b=a))';
EXECUTE s;
SELECT a FROM t1;
EXECUTE s;
