SET unique_checks=0,foreign_key_checks=0;
CREATE TABLE t1 (c INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
SELECT 0 INTO OUTFILE 'a';
SET autocommit=0;
INSERT INTO t2 VALUES (0);
LOAD DATA INFILE 'a' INTO TABLE t1;
SET autocommit=ON;

CREATE TABLE t (c INT) ENGINE=InnoDB;
INSERT INTO t VALUES (0);
SELECT * FROM t INTO OUTFILE 'a';
SET unique_checks=0,foreign_key_checks=0,autocommit=0;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
CREATE TABLE t3 (c INT) ENGINE=InnoDB;
INSERT INTO t2 VALUES (0),(0),(0);
LOAD DATA INFILE 'a' INTO TABLE t3;
CREATE TABLE t (c INT) ENGINE=InnoDB;
