SET SESSION max_session_mem_used=8192;
CREATE TABLE t (b INT,ROW_START BIGINT UNSIGNED GENERATED ALWAYS AS ROW START INVISIBLE,ROW_END BIGINT UNSIGNED GENERATED ALWAYS AS ROW END INVISIBLE,PERIOD FOR SYSTEM_TIME(ROW_START,ROW_END)) ENGINE=INNODB WITH SYSTEM VERSIONING;
SELECT * FROM t FOR SYSTEM_TIME AS OF TIMESTAMP NOW(0) GROUP BY b HAVING b=0;
SELECT * FROM t FOR SYSTEM_TIME AS OF TIMESTAMP NOW(0) GROUP BY b HAVING b=0;
SELECT * FROM t FOR SYSTEM_TIME AS OF TIMESTAMP NOW(0) GROUP BY b HAVING b=0;
SELECT * FROM t FOR SYSTEM_TIME AS OF TIMESTAMP NOW(0) GROUP BY b HAVING b=0;
SELECT * FROM t FOR SYSTEM_TIME AS OF TIMESTAMP NOW(0) GROUP BY b HAVING b=0;
