INSTALL SONAME 'ha_connect';
CREATE OR REPLACE TABLE t1 (c1 INT PRIMARY KEY, c2 INT) PARTITION BY KEY() PARTITIONS 1;
CREATE OR REPLACE TABLE t3 ENGINE=CONNECT TABLE_TYPE=PROXY TABNAME='t1';
SELECT COUNT(*) FROM information_schema.key_column_usage WHERE REFERENCED_TABLE_NAME in ('t1') ;
