CREATE TABLE t (c CHAR(1));
XA START 'a';
SELECT dt DIV 1 AS f,id FROM t GROUP BY f;
BINLOG ' O1ZVRw8BAAAAZgAAAGoAAAAAAAQANS4xLjIzLXJjLWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAA7VlVHEzgNAAgAEgAEBAQEEgAAUwAEGggAAAAICAgC ';

CREATE TABLE t (c INT KEY,c2 CHAR(1),c3 DATE);
XA START 'b';
SELECT INTc,INTc2,CHARc,CHARc2,CHARc3 FROM t WHERE id=0;
BINLOG ' SOgWTg8CAAAAbgAAAHIAAAAAAAQANS42LjMtbTUtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAABI6BZOEzgNAAgAEgAEBAQEEgAAVgAEGggAAAAICAgCAAAAAAVAYI8=';
