INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t2 (a INT KEY) ENGINE=SPIDER;
SELECT a.z FROM t2 AS a,t2 b WHERE a.z=b.z;
CREATE TABLE t (a INT);
ALTER TABLE t2 CHANGE c c INT;
LOCK TABLE t WRITE,t2 READ;
