CREATE TABLE t1 (c1 INT,c2 INT,PRIMARY KEY(c1)) PARTITION BY KEY ALGORITHM=2 (c1) PARTITIONS 20;
HANDLER t1 OPEN AS h1;
HANDLER h1 READ `PRIMARY`=(1);
HANDLER h1 READ `PRIMARY` PREV;
HANDLER h1 READ `PRIMARY` PREV;

SET sql_mode='';
CREATE TABLE t(c DATE KEY,c2 INT,c3 INT) WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME (PARTITION hist HISTORY,PARTITION cur CURRENT);
INSERT INTO t SET c=YEARWEEK('1-1-1 1:1:1',0),c2=0,c3=0;
REPLACE INTO t(c,c2,c3)VALUES ('',0,1);
ALTER TABLE t DROP INDEX IF EXISTS idx1,ADD INDEX idx1(c);
CREATE TABLE t2(c BINARY KEY,c2 INT,c3 CHAR DEFAULT'');
UPDATE t AS a1 JOIN t AS a2 ON a1.c=a2.c JOIN t AS a3 ON a2.c=a3.c SET a1.c='(null)';
UPDATE t AS a1 LEFT JOIN t2 AS a2 ON a1.c=a2.c SET a1.c=COALESCE(a2.c,a1.c);
HANDLER t OPEN;
HANDLER t READ idx1=('x') LIMIT 2;
HANDLER t READ idx1 PREV LIMIT 2;
