CREATE TABLE t3 (c1 INT(1));
CREATE VIEW t AS SELECT 1 a;
CREATE TRIGGER tr1 BEFORE INSERT ON t3 FOR EACH ROW INSERT INTO t VALUES();
INSERT INTO t3 VALUES (1);
DROP VIEW t;
CREATE TABLE t (c1 int);
INSERT INTO t3 VALUES (1),(2);
