CREATE TABLE t1 (c1 INT)Engine=InnoDB PARTITION BY HASH(c1) PARTITIONS 2;
SET GLOBAL innodb_default_row_format=REDUNDANT;
ALTER TABLE t1 COALESCE PARTITION 1;
SET GLOBAL innodb_default_row_format=DYNAMIC;
ALTER TABLE t1 PAGE_COMPRESSED=1;
