SET sql_mode='';
INSTALL SONAME 'ha_duckdb';
CREATE TABLE t1 (c1 INT KEY,c2 INT) ENGINE=DuckDB;
CREATE TABLE t2 (c1 INT KEY,c2 BIT(30));
REPLACE INTO t2 SET c1='a',c2='a+abc';
SELECT * FROM t1 WHERE EXISTS (SELECT 1) UNION SELECT * FROM t2;
