INSTALL SONAME 'ha_connect';
CREATE TABLE t (c INT,c2 DATE,PRIMARY KEY(c2,c)) ENGINE=Connect PARTITION BY RANGE (TO_DAYS(c2)) SUBPARTITION BY HASH (c) SUBPARTITIONS 2 (PARTITION p VALUES LESS THAN (1));
INSERT INTO t VALUES (0,0);
LOCK TABLES t READ ;
CHECK TABLE t;
SELECT * FROM t;

SET sql_mode='';
INSTALL SONAME 'ha_connect';
CREATE TABLE t (c DATETIME NOT NULL) ENGINE=Connect;
INSERT INTO t VALUES (1);
LOCK TABLES t READ;
SELECT * FROM t;
SELECT * FROM t WHERE c=1;

INSTALL SONAME 'ha_connect';
CREATE TABLE t (c DATE) ENGINE=Connect PARTITION BY RANGE COLUMNS (c) (PARTITION p VALUES LESS THAN ('2026-01-01 00:00:00'),PARTITION p2 VALUES LESS THAN ('2027-01-01 00:00:00'));
INSERT INTO t VALUES ('00:01:02');
LOCK TABLES t READ;
SELECT * FROM t;
SELECT * FROM t WHERE c>1000;
