CREATE TABLE tab (c INT KEY,c2 POINT,c3 LINESTRING,c4 POLYGON,c5 GEOMETRY);
ALTER TABLE mysql.column_stats RENAME TO mysql.column_stats1;
CREATE TABLE t (a INT,b CHAR(1),c FLOAT);
ALTER TABLE t RENAME mysql.column_stats;
ALTER TABLE tab CHANGE COLUMN c3 c33 LINESTRING;
