CREATE TABLE t (f TEXT, FULLTEXT (f)) ENGINE=MyISAM;
INSERT INTO t VALUES ('foo'),('bar'); # Optional, fails either way
CREATE TABLE tmrg (f TEXT) ENGINE=MERGE, UNION(t);
SELECT * FROM tmrg;

CREATE TABLE t3 (a INT,b INT,KEY(a,b)) ENGINE=MERGE UNION=(t,t2);
CREATE TABLE t2 (b INT) ENGINE=MyISAM;
CREATE TABLE t (val INT,KEY USING BTREE (val)) ENGINE=MyISAM;
INSERT INTO t2 SELECT * FROM t3;
