SET sql_mode='';
CREATE TABLE t(c1 DATE KEY,c2 TEXT AS(c1)VIRTUAL, INDEX (c2)) WITH SYSTEM VERSIONING ENGINE=InnoDB;
INSERT INTO t VALUES('','');
UPDATE t SET c1=DATE('1:1:1');

SET sql_mode='';
CREATE TABLE t (c DECIMAL(1,1) KEY,c2 INT UNSIGNED AS (c) PERSISTENT,c3 TEXT CHARACTER SET 'BINARY' COLLATE 'BINARY' AS (c) VIRTUAL);
CREATE INDEX i ON t (c3);
ALTER TABLE t ADD SYSTEM VERSIONING;
REPLACE INTO t (c,c2,c3) VALUES (CURRENT_TIME,0,0);
UPDATE t SET c='a';
