CREATE TABLE t(c INT) ENGINE=InnoDB;
INSERT INTO t(c) VALUES (0);
SELECT * FROM t WHERE(c,c)<(0,(SELECT 1 FROM t WINDOW y AS(PARTITION BY c AND 1 BETWEEN (SELECT 1 FROM t AS v WINDOW z AS(PARTITION BY c AND + 1 BETWEEN(SELECT c GROUP BY c>c + 1 WINDOW d AS(PARTITION BY c)) AND 0)) AND 0)));

CREATE TEMPORARY TABLE t (c INT NOT NULL) ENGINE=CSV;
INSERT INTO t VALUES (1),(2),(3),(4);
SELECT * FROM t WHERE (c,c)< (0, (SELECT 1 FROM t WINDOW y AS (PARTITION BY c AND 1 BETWEEN (SELECT 1 FROM t AS v WINDOW z AS (PARTITION BY c AND + 1 BETWEEN (SELECT c GROUP BY c>c + 1 WINDOW d AS (PARTITION BY c)) AND 0)) AND 0)));
