ALTER TABLE t PARTITION BY SYSTEM_TIME INTERVAL (SELECT i FROM t2) DAY (PARTITION p HISTORY;

CREATE TABLE t1 (i INT); 
CREATE TABLE t2 (i INT); 
ALTER TABLE t1 PARTITION BY SYSTEM_TIME INTERVAL (SELECT i FROM t2) DAY (PARTITION p1 HISTORY, PARTITION pn CURRENT);
