DELIMITER //
CREATE FUNCTION f() RETURNS INT READS SQL DATA BEGIN DECLARE v INT;SELECT 1 INTO v FROM (SELECT c1,COALESCE(LEAD(a2.c1) OVER (PARTITION BY a2.c1 ORDER BY a2.c1),a2.c1) AS a1 FROM (t a2 JOIN t a3 USING (c1))) a4; RETURN 1; END;//
DELIMITER ;
SELECT f(),f();

CREATE TABLE t (c INT);
EXECUTE IMMEDIATE "SELECT LEAD(c) OVER (ORDER BY c) FROM t NATURAL JOIN t AS a;";

EXECUTE IMMEDIATE "SELECT LEAD(c) OVER (ORDER BY c) FROM (SELECT 1 AS c) AS a NATURAL JOIN (SELECT 1 AS c) AS b;";
