CREATE TABLE t1 (c5 GEOMETRY NOT NULL, SPATIAL KEY(c5)) ENGINE=InnoDB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=1;
INSERT INTO t1 SELECT POINT(seq,seq) FROM seq_1_to_30;
SET GLOBAL innodb_compression_level=0;
INSERT INTO t1 SELECT POINT(seq,seq) FROM seq_1_to_30;
