INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'pwd';
CREATE SERVER s FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET "./socket.sock",DATABASE 'test',user 'Spider',PASSWORD 'pwd');
SET SESSION spider_delete_all_rows_type=0;
CREATE TABLE t2 (c INT);
CREATE TABLE t1 (c INT) ENGINE=Spider
COMMENT='WRAPPER "mysql", SERVER "s",TABLE "t2", delete_all_rows_type "0"';
INSERT IGNORE INTO t1 VALUES (42),(378);
SELECT * FROM t1;
DELETE FROM t1;

SET sql_mode='';
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE t1 (a INT, b VARCHAR(255), c1 INT, c2 INT, PRIMARY KEY(a), UNIQUE KEY(c1), KEY(c2) ) ENGINE=Spider AUTO_INCREMENT_MODE=1 DELETE_ALL_ROWS_TYPE=0 IDX="f c1 ig PRIMARY u c2" MULTI_SPLIT_READ=54 WRAPPER=mysql;
ALTER TABLE t1 READ_ONLY=0;
DELETE FROM t1;
DELETE FROM t1; # Crashing statement
SHUTDOWN;

SET sql_mode='';
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD '');
CREATE TABLE t1 (a INT, b VARCHAR(255), c1 INT, c2 INT, PRIMARY KEY(a), UNIQUE KEY(c1), KEY(c2)) ENGINE=Spider AUTO_INCREMENT_MODE=1 DELETE_ALL_ROWS_TYPE=0 WRAPPER=mysql;
ALTER TABLE t1 READ_ONLY=0;
DELETE FROM t1;
DELETE FROM t1; # Hanging statement
SHUTDOWN;
