CREATE TABLE c(c INT);
UPDATE c SET c=0 ORDER BY(SELECT c,c BETWEEN(SELECT c AS c GROUP BY c WINDOW c AS(PARTITION BY c AND 0 BETWEEN(SELECT c FROM c GROUP BY'',c,c HAVING c IS NULL WINDOW c AS(PARTITION BY c)) AND 0)) AND 0);
