INSTALL SONAME 'ha_federatedx.so';
CREATE USER federatedx@localhost IDENTIFIED BY '';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user 'federatedx',PASSWORD'');
CREATE TABLE t1 (c INT KEY,c2 BLOB,c3 TEXT) ENGINE=InnoDB;
CREATE TABLE t2 CONNECTION='srv/t1' ENGINE=FEDERATED;
START TRANSACTION;
DELETE FROM t2 WHERE other=0;
CREATE TABLE t2 (d INT) ENGINE=FEDERATED;
INSERT INTO t2 VALUES (1);

INSTALL SONAME 'ha_federatedx.so';
CREATE USER federatedx@localhost IDENTIFIED BY '';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user 'federatedx',PASSWORD'');
CREATE TABLE t2 (c INT KEY,c2 BLOB) ENGINE=InnoDB;
CREATE TABLE t CONNECTION='srv/t2' ENGINE=FEDERATED;
SET autocommit=OFF;
INSERT INTO t VALUES (1);
CREATE TABLE t (a INT KEY,b CHAR(1)) ENGINE=FEDERATED;
INSERT INTO t (c) VALUES (1);
