INSTALL PLUGIN spider SONAME 'ha_spider.so';
SET SQL_MODE='';
CREATE TABLE t (c INT AUTO_INCREMENT, KEY(c)) ENGINE=SPIDER PARTITION BY LIST COLUMNS (c) (PARTITION p DEFAULT ENGINE=SPIDER);
INSERT INTO t (c) VALUES (0);
INSERT INTO t (c) VALUES (0);
