CREATE TABLE t1 (a INT PRIMARY KEY) PARTITION BY LIST(a) (PARTITION p1 VALUES IN (1,2));
INSERT INTO t1 VALUES (1),(2);
SELECT MAX(a) FROM t1 WHERE a > 4;

CREATE TABLE t (c INT KEY) PARTITION BY LIST (c) (PARTITION p VALUES IN (0));
SELECT MAX(c) FROM t WHERE c>1;
