SET standard_compliant_cte=0;
CREATE TABLE x ( x BOOLEAN ) ;
INSERT INTO x ( x ) VALUES ( 1 ) ;
UPDATE x SET x = CASE WHEN NOT x != 1 THEN 1 ELSE 1 END WHERE x = 1 ;
INSERT INTO x ( x ) VALUES ( 1 ) , ( 1 ) ;
WITH RECURSIVE x ( x ) AS ( SELECT 'x' EXCEPT SELECT x + 1 FROM x GROUP BY - 'x' >= x IS NOT NULL = ( x = 1 AND x * 1 / ( SELECT 1 AS x UNION SELECT 1.000000 ORDER BY x IN ( SELECT x FROM ( SELECT DISTINCT - x , x FROM x WHERE x = ( SELECT CASE WHEN x = 1 THEN 'x' ELSE x END FROM x WHERE ( SELECT x IN ( SELECT x FROM ( SELECT x FROM x UNION SELECT x FROM x ) AS x WHERE x IS NULL AND x IN ( 1.000000 , 1 ) ) FROM x WHERE x != 'x' ) NOT BETWEEN ( SELECT x AS x FROM x AS x GROUP BY x HAVING x ) AND 1 ) GROUP BY 1 , 'x' , NULL HAVING EXISTS ( WITH RECURSIVE x AS ( SELECT 1 ) SELECT * FROM x WHERE x = x ) ) AS x ) ) IN ( WITH x ( x ) AS ( SELECT 1 EXCEPT SELECT 1.000000 + 1 FROM x ) SELECT x FROM ( SELECT x FROM x UNION SELECT x FROM x ) AS x ) AND 1 + 1 ) ) SELECT 1 EXCEPT SELECT 1.000000 EXCEPT SELECT x + 1 FROM x WHERE x LIKE ( x BETWEEN 1 AND 1 ) GROUP BY x HAVING x > 'x' ;

SET standard_compliant_cte=0;
CREATE TABLE x ( x BOOLEAN ) ;
INSERT INTO x ( x ) VALUES ( 1 ), ( 1 ) , ( 1 ) ;
WITH RECURSIVE x ( x ) AS ( SELECT 'x' EXCEPT SELECT x + 1 FROM x GROUP BY - 'x' >= x IS NOT NULL = ( SELECT 1 AS x UNION SELECT 1.000000 ORDER BY x IN( SELECT x FROM ( SELECT   x FROM x  ) AS x )  ) ) 
SELECT x + 1 FROM x ;

SET standard_compliant_cte=0;
WITH RECURSIVE x (x) AS (SELECT 1 INTERSECT SELECT-(SELECT 1.000000 AS x UNION SELECT 1.000000 ORDER BY NOT x<'',-(SELECT 1+x /1.000000 IN (1,1) FROM x WHERE x ORDER BY 1-x) DESC LIMIT 1 OFFSET 1)+1 FROM x) SELECT DISTINCT x,1,NULL,1.000000 FROM x WHERE (SELECT (SELECT x WHERE x IN (SELECT x FROM x)))> (SELECT (SELECT x ORDER BY x=x OR (x=1 AND x=1) DESC)) ORDER BY x ASC;
