SET SQL_MODE='';
CREATE TABLE t2 (c1 INT AUTO_INCREMENT PRIMARY KEY, c2 DATETIME DEFAULT '2020-01-01', c3 BLOB DEFAULT 'd', KEY(c2)) ENGINE=InnoDB PARTITION BY HASH(c1) PARTITIONS 2;
INSERT INTO t2 (c1,c2) VALUES (2068962732,1);
INSERT INTO t2 (c2) VALUES ('a');
INSERT INTO t2 () VALUES (),(),(),(),(),(),(),(),(),(),(),(),(),(),(),(),(),(),(),(),(),();
SELECT c3,CASE WHEN c2<>1 THEN 1 ELSE 'g' END FROM t2 GROUP BY c2;
HANDLER t2 OPEN;
HANDLER t2 READ `PRIMARY` = (80);
HANDLER t2 READ `PRIMARY` PREV;
