CREATE EVENT e ON SCHEDULE EVERY 1 HOUR ENDS ROW(1,2) DO SELECT 1;

CREATE EVENT e ON SCHEDULE AT ROW(1,2) DO SELECT *;

CREATE EVENT e ON SCHEDULE EVERY 1 HOUR STARTS ROW(1,2) DO SELECT 1;

CREATE EVENT e ON SCHEDULE EVERY ROW(1,2) HOUR DO SELECT 1;

CREATE EVENT e ON SCHEDULE EVERY ROW(1,2) HOUR DO SELECT 1 QUERY;
