CREATE TEMPORARY TABLE t (c INT KEY);
ALTER TABLE t MODIFY c TIMESTAMP;
ALTER TABLE t ADD CHECK(c=0);
ALTER TABLE t ADD INDEX idx1 (c);
SET SESSION sql_mode='TRADITIONAL';
ALTER TABLE t ROW_FORMAT=COMPRESSED;
ALTER TABLE t ANALYZE PARTITION p2;
SELECT * FROM information_schema.tables;
