CREATE TABLE t (c INT) ENGINE=InnoDB;
BEGIN;
INSERT INTO t VALUES ();
SAVEPOINT sp;
SET max_statement_time=1;
CREATE TEMPORARY TABLE t AS SELECT+1 FROM seq_1_to_100000;
ROLLBACK TO sp;

CREATE TABLE t (a INT KEY,b TIMESTAMP)Engine=InnoDB;
SET tx_isolation='SERIALIZABLE';
HANDLER t OPEN h;
START TRANSACTION WITH CONSISTENT SNAPSHOT,READ ONLY;
