DROP DATABASE test;
CREATE DATABASE test;
USE test;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t1 (c INT) ENGINE=Spider;
CREATE TABLE t2 (c INT) ENGINE=Spider;
RENAME TABLE t2 TO doesnotexist.t;

DROP DATABASE test;
CREATE DATABASE test;
USE test;
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t2 (c INT) ENGINE=Spider;
RENAME TABLE t2 TO doesnotexist.t;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t1 (c INT) ENGINE=Spider;
CREATE TABLE t2 (c INT) ENGINE=Spider;
RENAME TABLE t2 TO doesnotexist.t;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (cink INT,cvcnk INT) CHARSET utf8mb4 ENGINE=InnoDB;
CREATE OR REPLACE TABLE t (id INT) ENGINE=InnoDB;
CREATE TABLE t2 (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=Spider;
RENAME TABLE t2 TO t.t;
