CREATE TABLE t1 (c INT) PARTITION BY HASH(c) PARTITIONS 3;
CREATE GLOBAL TEMPORARY TABLE t2 LIKE t1;
CREATE GLOBAL TEMPORARY TABLE t3 LIKE t2;

CREATE GLOBAL TEMPORARY TABLE t (x INT,t TEXT);
ALTER TABLE t PARTITION BY KEY(x);
CREATE TABLE InnoDB LIKE t;
