CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET '0',DATABASE '0',USER '0',PASSWORD'');
DROP DATABASE mysql;
CREATE OR REPLACE SERVER srv FOREIGN DATA WRAPPER foo OPTIONS (HOST '0',PORT '0');
