CREATE GLOBAL TEMPORARY TABLE t (c INT) ENGINE=InnoDB;
XA START 'a';
SET GLOBAL innodb_force_primary_key=1;
SELECT * FROM t;
SET pseudo_slave_mode=1;
XA END 'a';
XA PREPARE 'a';
LOCK TABLE t WRITE;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t (c TEXT) ENGINE=InnoDB;
DROP TABLE t;  # Cleanup

# mysqld options required for replay: --log_bin --sql_mode=
CREATE GLOBAL TEMPORARY TABLE t2 (c INT KEY) ON COMMIT PRESERVE ROWS;
CREATE GLOBAL TEMPORARY TABLE t3 LIKE t2;
CREATE TABLE t (id INT,i INT,KEY(id)) ENGINE=InnoDB;
XA START 'a';
XA END 'a';
SET pseudo_slave_mode=1;
XA PREPARE 'a';
LOCK TABLES t3 AS a1 LOW_PRIORITY WRITE,t AS a5 READ LOCAL,t AS a6 WRITE;
DROP TABLE t3;
DROP TABLE t;

CREATE GLOBAL TEMPORARY TABLE t (x INT);
XA START 'a';
SET sql_mode=TRADITIONAL;
SELECT * FROM t;
XA END 'a';
SET pseudo_slave_mode=1;
XA PREPARE 'a';
SET SESSION enforce_storage_engine=MyISAM;
LOCK TABLES t WRITE NOWAIT;
CREATE OR REPLACE GLOBAL TEMPORARY TABLE t (t TEXT);
CREATE GLOBAL TEMPORARY TABLE t (x INT);

# mysqld options required for replay:  --sql_mode= --innodb_stats_persistent=off
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT PRESERVE ROWS AS SELECT 1 'a';
INSERT INTO t VALUES (),(),(),(),(),();
XA START 'a','a',2;
XA END 'a','a',2;
SET pseudo_slave_mode=1;
XA PREPARE 'a','a',2;
CREATE GLOBAL TEMPORARY TABLE t2 ON COMMIT PRESERVE ROWS AS VALUES (1),(1),(1);
LOCK TABLES t2 AS a3 READ,t2 AS a5 WRITE,t AS a0 WRITE;
DROP TABLE t;
LOCK TABLE tp READ;
CREATE DEFINER=current_user FUNCTION f (i1 INT(1),i2 DECIMAL(1) UNSIGNED) RETURNS FLOAT(0,0) ZEROFILL COMMENT 'a' RETURN CONCAT ('a',i1);
