CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES ('0.0e'),('0.0e+0');
SELECT * FROM t WHERE COALESCE(c)=0.0;

SET sql_mode='';
CREATE TABLE t (c CHAR(10) KEY);
INSERT INTO t VALUES (1.755555555);
SELECT * FROM t PROCEDURE ANALYSE();

CREATE TABLE t1 (c1 MEDIUMBLOB NOT NULL);
INSERT INTO t1 VALUES ('1e+');
SELECT AVG(c1) AS VALUE FROM t1 WHERE c1 <> 0;

CREATE TABLE t (c BLOB) ENGINE=InnoDB;
INSERT INTO t VALUES (1.3),(1.1);
SELECT * FROM t PROCEDURE ANALYSE();

