INSTALL SONAME 'ha_federatedx.so';
CREATE USER federatedx@localhost IDENTIFIED BY '';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user 'federatedx',PASSWORD'');
CREATE TABLE t2 (c INT,c2 BLOB) ENGINE=InnoDB;
CREATE TABLE t CONNECTION='srv/t2' ENGINE=FEDERATED;
DROP TABLE IF EXISTS t2;
CREATE TABLE t2 (c INT) ENGINE=InnoDB;
INSERT INTO t2 VALUES();
SELECT * FROM t WHERE c>0;
