SET GLOBAL general_log=ON, GLOBAL log_output='TABLE';
CREATE TABLE t (c INT) ENGINE=InnoDB;
EXPLAIN SELECT * FROM t LIMIT ROWS EXAMINED 1;
SHUTDOWN;

SET GLOBAL log_output='file,TABLE';
SET GLOBAL general_log=ON;
CREATE TABLE t (d INT);
EXPLAIN SELECT * FROM t LIMIT ROWS EXAMINED 0;
SHUTDOWN;
