CREATE TABLE t1 (a INT KEY) ENGINE=INNODB;
CREATE TABLE t2 (a INT KEY REFERENCES t1 (a)) ENGINE=INNODB;
CREATE TABLE t3 (a INT) ENGINE=INNODB;
XA START 'a';
INSERT INTO t3 VALUES (1);
INSERT INTO t2 VALUES (1);
XA END 'a';
XA PREPARE 'a';
SHUTDOWN;
