CREATE TABLE t (c INT);
CREATE TRIGGER ai AFTER INSERT ON t FOR EACH ROW SET @a=1;
ALTER TABLE t ADD COLUMN b INT DEFAULT RAND();
INSERT INTO t (c) VALUES (1),(2);

CREATE TABLE t (c DECIMAL ZEROFILL);
CREATE TRIGGER ai AFTER INSERT ON t FOR EACH ROW SET @a=1;
ALTER TABLE t ADD COLUMN b INT DEFAULT (RAND()+3);
INSERT INTO t (c) VALUES (1),(2);
