SET sql_mode='';
CREATE TABLE t0 (a CHAR(0),b INT,KEY a (a)) ENGINE=InnoDB;
INSERT INTO t0 VALUES (0,0);
ALTER TABLE t0 CHANGE COLUMN a a BINARY (0);

SET sql_mode='';
CREATE TABLE t (a INT,b INT,c CHAR(0),d CHAR(0),e BINARY (0),f VARCHAR(0),g BLOB,h BLOB,id INT,KEY(b),KEY(e)) ENGINE=InnoDB;
INSERT INTO t VALUES (0,0,0,0,0,0,0,0,0);
