CREATE SERVER s FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET'');
BACKUP LOCK t;
DROP SERVER s;

CREATE SERVER s FOREIGN DATA WRAPPER MYSQL OPTIONS (HOST'');
BACKUP STAGE START;
DROP SERVER s;

CREATE SERVER srv FOREIGN DATA WRAPPER''OPTIONS (USER'');
FLUSH LOCAL TABLES WITH READ LOCK;
ALTER SERVER srv OPTIONS (USER'');
