SET sql_mode='';
CREATE TABLE t(c INT);
HANDLER t OPEN h;
INSERT INTO t VALUES();
SET GLOBAL userstat=1;
HANDLER h READ FIRST;
CREATE TABLE t(c INT);

CREATE TABLE t (a CHAR(1));
HANDLER t OPEN;
INSERT INTO t VALUES (1);
HANDLER t READ NEXT;
SET GLOBAL userstat=1;
HANDLER t CLOSE;

CREATE TABLE t (c INT);
INSERT INTO t (c) VALUES (1);
LOCK TABLE t READ;
SELECT * FROM t;
SET GLOBAL userstat=ON;
LOCK TABLES t AS a2 READ;
