CREATE TABLE t0 (a INT NOT NULL DEFAULT 0);
CREATE TRIGGER trg BEFORE INSERT ON t0 FOR EACH ROW ROLLBACK TO SAVEPOINT s;
UPDATE t0 SET a=((SELECT MAX(a) FROM t0));

CREATE TABLE t (c ENUM ('') KEY,c2 BIT NOT NULL DEFAULT 1,c3 INT NULL DEFAULT 1,c4 INT UNSIGNED ZEROFILL);
CREATE TRIGGER tr2 BEFORE UPDATE ON t FOR EACH ROW INSERT INTO t4 VALUES (NEW.c,NEW.c2,NEW.c3);
UPDATE t AS a1 JOIN t AS a2 ON a1.c3=a2.c3 SET a1.c2=utc_date;
