CREATE TABLE t1 (i1 INT, i2 INT NOT NULL, KEY(i2)) ENGINE=MEMORY;
SET debug_dbug="+d,test_completely_invisible";
ALTER TABLE t1 PARTITION BY RANGE (i1) (PARTITION p0 VALUES LESS THAN (100), PARTITION p1 VALUES LESS THAN MAXVALUE);
SET debug_dbug="";
ALTER TABLE t1 DROP PARTITION p1;
REPLACE INTO t1 PARTITION (p0) (i1, i2) VALUES (8, 8),(2, 8);
