CREATE TABLE t2 (c1 SMALLINT,c2 TINYINT UNSIGNED,c3 INT AS(c1) VIRTUAL) ENGINE=InnoDB PARTITION BY HASH(c2) PARTITIONS 565;
SET GLOBAL innodb_adaptive_hash_index=1;
ALTER TABLE t2 CHANGE c1 c1_renamed INT FIRST;
