DROP DATABASE test;
CREATE DATABASE test;
USE test;
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS (HOST'',DATABASE'',USER'',PORT 10000,PASSWORD'');
SET SESSION spider_same_server_link=ON;
CREATE TABLE t (c INT AUTO_INCREMENT KEY,c2 INT,INDEX i (c2)) ENGINE=SPIDER ROW_FORMAT=COMPRESSED;
INSERT DELAYED INTO t VALUES (0,0),(0,0),(0,0);
SELECT SLEEP (3);

DROP DATABASE test;
CREATE DATABASE test;
USE test;
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t1 (id INT AUTO_INCREMENT PRIMARY KEY) ENGINE=SPIDER;
INSERT INTO nonexisting VALUES (1);
INSERT DELAYED INTO t1 VALUES (0);
UPDATE t1 SET a=0 WHERE a>1;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS (HOST'',DATABASE'',USER'',PORT 10000,PASSWORD'');
SET SESSION spider_same_server_link=ON;
CREATE TABLE t0(a INT AUTO_INCREMENT KEY,b VARCHAR(0)) ENGINE=SPIDER;
INSERT DELAYED INTO t0 VALUES(0,'');
INSERT INTO t0(col0)VALUES(STR_TO_DATE('',''));
