CREATE TABLE t1 (a INT) ENGINE=Aria WITH SYSTEM VERSIONING PARTITION BY system_time LIMIT 100 (PARTITION p0 HISTORY, PARTITION pn CURRENT);
CREATE TABLE t2 (b INT);
INSERT INTO t2 VALUES (1);
CREATE TRIGGER tr BEFORE UPDATE ON t2 FOR EACH ROW INSERT INTO t1 VALUES (1);
UPDATE t2 SET b = 4;

SET SESSION default_storage_engine=Aria;
CREATE TABLE t1 (c1 INT KEY,c2 INT) WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME LIMIT 939 (PARTITION p_h HISTORY,PARTITION p_c CURRENT);
CREATE TRIGGER tr1 BEFORE INSERT ON t1 FOR EACH ROW SET NEW.c1=NEW.c1 * 2;
UPDATE t1 SET c1=NULL;
