CREATE TABLE t (a INT, b INT, KEY(a)) ENGINE=InnoDB;
INSERT INTO t VALUES (1,1);
START TRANSACTION WITH CONSISTENT SNAPSHOT;
UPDATE t SET a=2;
ALTER TABLE t ADD COLUMN v INT AS (b) VIRTUAL, ADD INDEX(v);
SELECT v FROM t;
