INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE'',USER'',PASSWORD 'PWD0');
CREATE TABLE t (a INT KEY AUTO_INCREMENT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
ALTER TABLE t ADD b TEXT;
CREATE OR REPLACE TABLE t (a INT) ENGINE=Spider;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT KEY) ENGINE=Spider;
UPDATE t SET c0=b0;
DROP TABLE IF EXISTS mysql.spider_tables;
CREATE OR REPLACE TABLE t (a TEXT);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
GRANT ALL ON test.* TO Spider@localhost;
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'test',user 'Spider',PASSWORD 'PWD1');
CREATE TABLE t2 (f2 INT KEY) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
CREATE TABLE t (a INT) ENGINE=Spider COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
RENAME TABLE test.t2 TO db1.t2;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock',DATABASE 'a',USER 'Spider',PASSWORD 'PWD1');
CREATE TABLE t1 (pk2 INT,i2 INT,c2 CHAR(1),KEY(pk2)) ENGINE=InnoDB;
CREATE OR REPLACE TABLE t1 (a INT,b INT) ENGINE=InnoDB;
SET SESSION storage_engine='Spider';
CREATE TABLE t (id INT AUTO_INCREMENT,name CHAR(1),myDATE DATE,KEY(id,myDATE),INDEX idx_date (myDATE)) COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"' PARTITION BY RANGE (TO_DAYS (myDATE)) (PARTITION p0 VALUES LESS THAN (1),PARTITION p VALUES LESS THAN (734029),PARTITION p2 VALUES LESS THAN (734030),PARTITION p3 VALUES LESS THAN MAXVALUE);
ALTER TABLE t ADD b INT;
INSERT INTO t SELECT 1 t;
CREATE OR REPLACE TABLE t (a INT,b INT,c INT) COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
CREATE OR REPLACE TABLE t (pk INT KEY) COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"' WITH SYSTEM VERSIONING PARTITION BY KEY() PARTITIONS 3;
DROP TABLE t;
CREATE TABLE t (a INT,b INT AUTO_INCREMENT,KEY(a,b)) COMMENT='WRAPPER "mysql",srv "srv",TABLE "t"';
SET STATEMENT sql_mode='no_engine_substitution' FOR ALTER TABLE t MODIFY a YEAR;
CREATE OR REPLACE TABLE t (a INT ZEROFILL);
