CREATE TABLE t (c BIT(10));
INSERT INTO t VALUES ('a');
SELECT * FROM t PROCEDURE ANALYSE(2);

CREATE TABLE t (c LONGTEXT) ENGINE=INNODB;
INSERT INTO t VALUES (REPEAT(1,5242880));
SELECT * FROM t PROCEDURE ANALYSE();
