CREATE GLOBAL TEMPORARY TABLE t (c INT) ENGINE=InnoDB ON COMMIT PRESERVE ROWS;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
FLUSH TABLES t WITH READ LOCK;
INSERT t VALUES (1);
UPDATE t SET c=c+1;
