CREATE TABLE t (id INT KEY,v VECTOR (1) NOT NULL,VECTOR INDEX (v)) ENGINE=INNODB;
FLUSH TABLES t FOR EXPORT;
SELECT VEC_DISTANCE_EUCLIDEAN (v,0x30303030) d FROM t ORDER BY d LIMIT 1;
SELECT VEC_DISTANCE_EUCLIDEAN (v,0x30303030) d FROM t ORDER BY d LIMIT 1;
