CREATE TABLE t0 (t0 TEXT,FULLTEXT (t0)) ENGINE=InnoDB;
INSERT INTO t0 VALUES (0),(0),(0),(0),(0);
SET autocommit=0;
ALTER TABLE t0 ADD COLUMN trx_start BIGINT(0) UNSIGNED AS ROW START INVISIBLE,ADD COLUMN trx_end BIGINT(0) UNSIGNED AS ROW END INVISIBLE,ADD period FOR SYSTEM_TIME(trx_start,trx_end),ADD SYSTEM VERSIONING;
