INSTALL SONAME 'ha_federated';
CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET'',DATABASE'',USER'',PASSWORD'');
CREATE GLOBAL TEMPORARY TABLE t (c INT) CONNECTION='srv/t' ENGINE=Federated;
INSERT t VALUES (0),(0),(0);

CREATE SERVER srv FOREIGN DATA WRAPPER mysql OPTIONS (SOCKET'',DATABASE'',USER'',PASSWORD'');
INSTALL SONAME 'ha_federated';
CREATE GLOBAL TEMPORARY TABLE t (c INT) CONNECTION='srv/t' ENGINE=Federated;
INSERT INTO t VALUES (0),(0);
