CREATE TABLE t1 (a INT);
delimiter $
CREATE PROCEDURE p1() 
BEGIN 
  DECLARE c1 SYS_REFCURSOR; 
  OPEN c1 FOR SELECT * FROM t1; 
END;
$
delimiter ;
CALL p1;
CREATE OR REPLACE TABLE t1(a INT);
CALL p1;
CALL p1;
CALL p1;

CREATE TABLE t (a INT);
DELIMITER $ 
CREATE PROCEDURE p1 (OUT c sys_refcursor) 
BEGIN 
  OPEN c FOR SELECT a FROM t ;
END; $
CREATE PROCEDURE p2() 
BEGIN 
  DECLARE c sys_refcursor;
  DECLARE v INT;
  EXECUTE IMMEDIATE 'CALL p1 (?)' USING c;
  FETCH c INTO v;
  SELECT c,v;
END; $
DELIMITER ;
CALL p2;
CREATE OR REPLACE TABLE t (a INT);
CALL p2;
CALL p2;
CALL p1;

CREATE TABLE t (a INT) ENGINE=INNODB;
DELIMITER $
CREATE PROCEDURE p (OUT c sys_refcursor) 
BEGIN 
  OPEN c FOR SELECT a FROM t ;
END;
$
DELIMITER ;
CREATE TEMPORARY TABLE t (c INT) ENGINE=INNODB;
SET GLOBAL innodb_file_per_table=0;
SET innodb_compression_default=ON;
CALL p (@a);
CREATE OR REPLACE TEMPORARY TABLE t (c INT) ENGINE=INNODB;
PREPARE s FROM 'CALL p(?)';
EXECUTE s USING @a;
CALL p(@a);
CALL p;

