CREATE TABLE t1 (a TEXT);
INSERT INTO t1 VALUES (''),('   ');
SELECT COUNT(*) FROM (SELECT DISTINCT a FROM t1) AS d;
SELECT COUNT(DISTINCT a) FROM t1;
SELECT COUNT(*) FROM (SELECT a FROM t1 GROUP BY a) AS g;
SELECT COUNT(*) FROM (SELECT a FROM t1 WHERE LENGTH(a)=0 UNION SELECT a FROM t1 WHERE LENGTH(a)=3) AS u;
#CLI: 2, 2, 2, 2
#ERR: - (no error)

CREATE TABLE t1 (a TEXT);
INSERT INTO t1 VALUES (''),(' '),('  ');
SELECT COUNT(*) FROM (SELECT DISTINCT a FROM t1) AS d;
#CLI: 2
#ERR: - (no error)

CREATE TABLE t1 (a TEXT, n INT);
INSERT INTO t1 VALUES ('',1),('   ',1),('',2),('  ',2);
SELECT COUNT(*) FROM (SELECT DISTINCT a, n FROM t1) AS d;
#CLI: 4
#ERR: - (no error)

CREATE TABLE t1 (a TEXT);
INSERT INTO t1 VALUES (NULL),(''),('   '),(NULL),('  ');
SELECT COUNT(*) FROM (SELECT DISTINCT a FROM t1) AS d;
#CLI: 3
#ERR: - (no error)
