CREATE TABLE t (c INT);
DELETE FROM t USE KEY() WHERE 0 ORDER BY PERCENTILE_CONT(COUNT(*)) WITHIN GROUP(ORDER BY c) OVER();

CREATE TABLE t (c INT) ENGINE=Aria;
DELETE FROM t USE KEY() ORDER BY COUNT(*);
