CREATE TABLE t1 (a BIGINT);
INSERT INTO t1 VALUES (1),(2); # Optional
CREATE TABLE t2 (b INT PRIMARY KEY);
INSERT INTO t2 VALUES (3),(4);
CREATE TABLE t3 (c INT);
INSERT INTO t3 VALUES (5);
SELECT t1.* FROM t1 LEFT JOIN t2 ON (t2.b = t1.a) WHERE t1.a = (SELECT c FROM t3);
