CREATE TABLE t1 (a INT, b INT, c INT, KEY (c)) ENGINE=MyISAM;
INSERT INTO t1 VALUES (1,0,1),(2,0,2);
CREATE TABLE t2 (d INT) ENGINE=MyISAM;
INSERT INTO t2 VALUES (10),(20);
CREATE TABLE t3 (e INT, f INT, KEY (e)) ENGINE=MyISAM;
CREATE TABLE t4 (g INT) ENGINE=MyISAM;
INSERT INTO t4 VALUES (4);
SELECT DISTINCT a FROM t1 LEFT JOIN (SELECT * FROM t3 WHERE t3.f = t3.e AND t3.f >= 0) AS sq ON (sq.e = t1.b) WHERE t1.b IN (SELECT g FROM t4 WHERE t1.c IN (g >= ALL (SELECT g FROM t4 HAVING g = 5)));

CREATE TABLE t (a INT KEY,b CHAR(1)) ENGINE=MyISAM ;
INSERT INTO t VALUES (0,'1');
SELECT a FROM t WHERE '' IN (SELECT 'x' LIKE a having a LIKE a);

CREATE TABLE t (c INT KEY);
INSERT INTO t VALUES(1),(3);
SELECT c FROM t WHERE c ORDER BY (1 IN ((SELECT c FROM t WHERE c IN (SELECT c FROM t WHERE c IN (SELECT (SELECT 3 FROM t)))))) IN (SELECT c FROM t WHERE c IN (1));
