CREATE TABLE t1 (a VARCHAR(10)) ENGINE=InnoDB;
SET AUTOCOMMIT=0;
CREATE TABLE t3 (f1 INT) ENGINE=InnoDB;
ALTER TABLE t1 ADD c2 MEDIUMINT NOT NULL FIRST;
SET SESSION wsrep_trx_fragment_size=100;
HANDLER t3 OPEN;
INSERT INTO t1 VALUES (2,1),(NULL, 8);
CREATE TABLE t1 (a INT NOT NULL PRIMARY KEY) ENGINE=InnoDB;
