CREATE TABLE t (c INT) ENGINE=InnoDB;
SET AUTOCOMMIT=0;
SET STATEMENT binlog_format=ROW FOR INSERT INTO t VALUES (1);

SET sql_mode='',autocommit=0;
CREATE TABLE t0 (a INT GENERATED ALWAYS AS (0) VIRTUAL,KEY(a)) ENGINE=InnoDB;
SET STATEMENT gtid_domain_id=0 FOR INSERT INTO t0 VALUES (0);
