INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS (HOST'',DATABASE'',USER'',PORT 10000,PASSWORD'');
SET SESSION spider_same_server_link=ON;
CREATE TABLE t (id INT AUTO_INCREMENT,i INT,KEY(id)) ENGINE=SPIDER;
EXPLAIN SELECT * FROM t AS nt2 WHERE 1 IN (SELECT it.a FROM t AS it JOIN t AS it3 ON it.a=it3.a);
ALTER TABLE t CHANGE c c FLOAT UNSIGNED ZEROFILL;
CREATE TEMPORARY TABLE tm1 (c INT) ENGINE=SPIDER UNION=(t);
INSERT INTO t VALUES (0,0),(0,0),(0,0),(0,0),(0,0);

USE test;
CREATE TABLE t (id INT AUTO_INCREMENT,i INT,KEY(id)) ENGINE=InnoDB PARTITION BY KEY(id) PARTITIONS 5;
EXPLAIN SELECT * FROM t AS nt2 WHERE 1 IN (SELECT it.a FROM t AS it JOIN t AS it3 ON it.a=it3.a);
ALTER TABLE t CHANGE c c FLOAT UNSIGNED ZEROFILL;
CREATE TEMPORARY TABLE tm1 (c INT) ENGINE=SPIDER UNION=(t);
INSERT INTO t VALUES (0,0),(0,0),(0,0),(0,0),(0,0);

USE test;
INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS (HOST'',DATABASE'',USER'',PORT 10000,PASSWORD'');
SET SESSION spider_same_server_link=ON;
CREATE TABLE t (id INT AUTO_INCREMENT,i INT,KEY(id)) ENGINE=InnoDB PARTITION BY KEY(id) PARTITIONS 5;
EXPLAIN SELECT * FROM t AS nt2 WHERE 1 IN (SELECT it.a FROM t AS it JOIN t AS it3 ON it.a=it3.a);
ALTER TABLE t CHANGE c c FLOAT UNSIGNED ZEROFILL;
CREATE TEMPORARY TABLE tm1 (c INT) ENGINE=SPIDER COMMENT='tbl "tm1"' UNION=(t);
INSERT INTO t VALUES (0,0),(0,0),(0,0),(0,0),(0,0);

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE SERVER d FOREIGN DATA WRAPPER mysql OPTIONS (HOST'',DATABASE'',USER'',PORT 10000,PASSWORD'');
SET SESSION spider_same_server_link=ON;
CREATE TABLE t (id INT AUTO_INCREMENT,i INT,KEY(id)) ENGINE=SPIDER PARTITION BY KEY(id) PARTITIONS 5;
EXPLAIN SELECT * FROM t AS nt2 WHERE 1 IN (SELECT it.a FROM t AS it JOIN t AS it3 ON it.a=it3.a);
ALTER TABLE t CHANGE c c FLOAT UNSIGNED ZEROFILL;
CREATE TEMPORARY TABLE tm1 (c INT) ENGINE=SPIDER UNION=(t);
INSERT INTO t VALUES (0,0),(0,0),(0,0),(0,0),(0,0);
