CREATE TABLE t (a INT) ENGINE=MyISAM;
REPLACE DELAYED INTO t (x,y) VALUES (0,0);

# mysqld options required for replay: --log_bin 
CREATE TABLE t (a INT signed) PARTITION BY LIST (a) (PARTITION p0 VALUES IN (1,3,5,7,9,NULL),PARTITION p VALUES IN (2,4,6,8,0));
INSERT INTO t VALUES (@var);

CREATE TABLE t (pk0 VARCHAR(1),pk1 INT,c INT,UNIQUE (c) USING HASH) ENGINE=MEMORY;
INSERT DELAYED INTO t VALUES ('','','');

SET storage_engine=MyISAM;
CREATE TABLE t (c INT KEY,c2 CHAR,c3 DATE);
INSERT DELAYED INTO t VALUES (1,0),(1,0),(1,0);

CREATE TABLE t (a CHAR,b CHAR,c DATE,KEY(c)) ENGINE=MEMORY;
INSERT DELAYED INTO t VALUES (RAND());
