SET autocommit=0;  # error-ignored in oracle
SET SQL_MODE='ORACLE';  # idem
CREATE GLOBAL TEMPORARY TABLE gtt (c INT) ENGINE=MyISAM ON COMMIT PRESERVE ROWS;
SAVEPOINT sp1;
INSERT INTO gtt (c) VALUES (1);
ROLLBACK TO sp1;
SELECT * FROM gtt;
TRUNCATE TABLE gtt;
COMMIT;
DROP TABLE gtt;

SET autocommit=0;  # error-ignored in oracle
SET SQL_MODE='ORACLE';  # idem
CREATE GLOBAL TEMPORARY TABLE gtt (c INT) ON COMMIT PRESERVE ROWS;
INSERT INTO gtt (c) VALUES (0);
SAVEPOINT sp1;
INSERT INTO gtt (c) VALUES (1);
ROLLBACK TO sp1;
SELECT * FROM gtt;
TRUNCATE TABLE gtt;
COMMIT;
DROP TABLE gtt;
