SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
CREATE TABLE t (c TEXT, UNIQUE(c)) ENGINE=InnoDB WITH SYSTEM VERSIONING PARTITION BY SYSTEM_TIME;
INSERT INTO t VALUES ('foo');
UPDATE t SET c = 'bar';
