GRANT SELECT ON *.* TO PUBLIC;
LOCK TABLES mysql.time_zone WRITE;
FLUSH PRIVILEGES;
LOCK TABLE nonexisting WRITE;
GRANT SELECT ON *.* TO PUBLIC;

LOCK TABLES mysql.time_zone WRITE;
FLUSH PRIVILEGES;
LOCK TABLE nonexisting WRITE;
GRANT SELECT ON *.* TO PUBLIC;
