CREATE TABLE t (c1 CHAR AS (CONCAT (0,DAYNAME (0))));
FLUSH TABLES WITH READ LOCK;
UPDATE t SET c1=1;
SELECT * FROM t;

CREATE TABLE t (a INT,b DATE AS (1 IN (0, (DATABASE()))));
FLUSH TABLES WITH READ LOCK;
INSERT INTO t VALUES (1),(1),(1),(1),(1);
SHOW CREATE TABLE t;
