INSTALL SONAME 'ha_connect';
CREATE TABLE t1 (a INT) ENGINE=CONNECT;
CREATE TABLE total (tabname CHAR(8) NOT NULL SPECIAL='TABID') ENGINE=CONNECT TABLE_TYPE=TBL TABLE_LIST='t1';
SELECT * FROM total WHERE tabname = REPEAT('A',500);
