CREATE SEQUENCE SEQ NOCACHE ENGINE=InnoDB;
SET SESSION wsrep_trx_fragment_size=1;
SET collation_connection=utf16_thai_520_w2;
SET autocommit=0;
CREATE TABLE t1 (a BLOB UNIQUE);
INSERT INTO t1 VALUES ('AAF');
SELECT SETVAL (SEQ, 100);
ALTER TABLE t1 ADD CONSTRAINT constraint_1 UNIQUE (a);
INSERT INTO t1 VALUES();
ALTER TABLE t1 ADD KEY(b (50));

CREATE TABLE t (b BINARY (1)) ENGINE=InnoDB;
SET SESSION wsrep_trx_fragment_size=1;
CREATE SEQUENCE s_t START WITH 1 MINVALUE 1 MAXVALUE 20 INCREMENT BY 1  ENGINE=InnoDB;
INSERT INTO t SELECT NEXT VALUE FOR s_t;
INSERT INTO t (b) VALUES ('');
