CREATE TABLE t (a TEXT COLLATE latin1_bin);
INSERT INTO t VALUES ('');
INSERT INTO t VALUES ('test');
SELECT GROUP_CONCAT(a ORDER BY a) FROM t ;

CREATE TABLE t (a TEXT );
INSERT INTO t VALUES ('');
INSERT INTO t VALUES ('test');
SELECT GROUP_CONCAT(a ORDER BY a) FROM t ;

CREATE TABLE t (f TEXT UNIQUE);
INSERT INTO t VALUES ('');
INSERT INTO t VALUES ('');
