CREATE TABLE t1(a INT, b INT);
DELIMITER $$
CREATE FUNCTION f() RETURNS INT BEGIN EXECUTE IMMEDIATE 'SELECT 1'; RETURN 5; END$$
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET NEW.b = f()$$ 
DELIMITER ;
INSERT INTO t1(a) VALUES (1);
