CREATE TABLE t (c INT) ENGINE=InnoDB;
INSERT t VALUES (0),(0);
ALTER TABLE t ADD UNIQUE INDEX(c);

SET sql_mode='';
CREATE TABLE t (f1 INT UNSIGNED NOT NULL,PRIMARY KEY(f1)) ENGINE=InnoDB;
SET SESSION pseudo_slave_mode=ON;
XA START 'a';
INSERT INTO t VALUES ('a');
XA END 'a';
XA PREPARE 'a';
INSERT INTO t VALUES ('a');
