CREATE TABLE t (c INT KEY) ENGINE=InnoDB;
INSERT INTO t VALUES ((c IN (SELECT (0,c) IN ((0,0),(0,0),(0,0)) AS v FROM (SELECT c FROM t WHERE (c) NOT IN (SELECT c FROM t)) AS v2))-2^1=(c IS NULL));

CREATE TABLE t (c INT KEY) ENGINE=InnoDB;
INSERT INTO t VALUES ((c IN (SELECT (0,c) IN ((0,0),(0,0),(0,0)) AS v FROM (SELECT c FROM t WHERE c NOT IN (SELECT c FROM t)) AS v2))-2^1=(c IS NULL));

CREATE TABLE t (c INT KEY);
INSERT INTO t VALUES ((c IN (SELECT (0,0) IN ((0,0),(0,0),(0,0)) AS v FROM (SELECT c FROM t WHERE c NOT IN (SELECT c FROM t)) AS v2))-2^1=(c IS NULL));

CREATE TABLE t(c INT UNIQUE) ENGINE=InnoDB;
INSERT INTO t VALUES ((TRUE IN (SELECT * FROM (SELECT (1^0)%1 IN (SELECT c FROM t GROUP BY c)) AS v))--((c IS NULL))^1);
