CREATE TABLE t1 (a INT, KEY(a)) PARTITION BY HASH(a);
HANDLER t1 OPEN h;
HANDLER h READ a NEXT;
HANDLER h READ a NEXT;

CREATE TABLE t(c INT,c2 DATE,PRIMARY KEY(c2)) PARTITION BY RANGE(YEAR(c2)) (PARTITION p VALUES LESS THAN (1));
HANDLER t OPEN;
HANDLER t READ `PRIMARY` NEXT;
HANDLER t READ `PRIMARY` NEXT;
