CREATE TABLE t (id INT KEY,v VECTOR (8) NOT NULL,VECTOR INDEX (v)) ENGINE=INNODB;
CREATE TABLE t2 (id INT KEY,t_id INT,INDEX par_ind (t_id),FOREIGN KEY(t_id) REFERENCES t (id) ON DELETE CASCADE) ENGINE=INNODB;
DROP TABLE t;
INSERT INTO t VALUES (0,''),(0,''),(0,''),(0,'');
