CREATE TABLE t1 (b VARCHAR(1024), c CHAR(3), UNIQUE(b,c)) ENGINE=MyISAM;
INSERT INTO t1 VALUES ('foo','baz');
ALTER TABLE t1 DISABLE KEYS;
SET SESSION myisam_repair_threads= 2;
INSERT INTO t1 SELECT 'qux';

CREATE TABLE t1 (b VARCHAR(20) unique, c CHAR(3), d varchar(30) as (c)  invisible)  ENGINE=MyISAM;
CREATE INDEX idx ON t1(d);
SHOW CREATE TABLE t1;
INSERT INTO t1 VALUES ('foo','baz');
ALTER TABLE t1 DISABLE KEYS;
SET SESSION myisam_repair_threads= 2;
INSERT INTO t1 SELECT 'qux';

SET SQL_MODE='';
USE test;
CREATE TABLE t1 (c1 INT, c2 INT AS (100/c1), KEY(c2)) ENGINE=MyISAM;
CREATE TABLE t2 (a INT, b INT, UNIQUE(b)) ENGINE=MyISAM;
INSERT INTO t2 VALUES (1,2);
SET SESSION MyISAM_REPAIR_THREADS=100;
INSERT INTO t1 SELECT * FROM t2;

USE test;
SET SQL_MODE='';
CREATE TABLE t (a INT);
SET myisam_repair_threads=2;
INSERT INTO t VALUES (NULL), (1);
SELECT * FROM t INTO OUTFILE 'myfile';
CREATE TABLE t2 (a INT, b INT GENERATED ALWAYS AS (a+1) VIRTUAL, INDEX (b), CONSTRAINT x FOREIGN KEY(b) REFERENCES t (a)) ENGINE=MyISAM;
LOAD DATA INFILE 'myfile' INTO TABLE t2;

CREATE TABLE t (a BINARY,b BLOB,c BLOB AS (CONCAT (a,b)),h CHAR,INDEX (c)) ENGINE=InnoDB;
INSERT INTO t VALUES (0,0,DEFAULT,0);
CREATE TABLE ti LIKE t;
ALTER TABLE ti ENGINE=MyISAM;
INSERT INTO ti SELECT * FROM t;

SET sql_mode='';
SET @@myisam_repair_threads=2;
CREATE TABLE t (a VARCHAR(1),va CHAR(1) GENERATED ALWAYS AS (uCASE (a)) VIRTUAL,KEY(va)) ENGINE=MyISAM;
INSERT INTO t (a) VALUES (1);
CREATE TEMPORARY TABLE t (f INT);
DROP TABLE t;
REPAIR TABLE t;
