SET sql_mode=ORACLE;
CREATE TABLE t1 (a INT, b VARCHAR(10));
INSERT INTO t1 VALUES (1,'b1');
CREATE TABLE t2 (x INT);
INSERT INTO t2 VALUES (100);
DELIMITER $$
CREATE PROCEDURE p1 AS TYPE rec0_t IS RECORD (a INT, b VARCHAR(10)); TYPE cur0_t IS REF CURSOR RETURN rec0_t; TYPE cur1_t IS REF CURSOR; c0 cur0_t; c1 cur1_t; r0 rec0_t; BEGIN OPEN c1 FOR SELECT a,b FROM t1; c0 := c1; FETCH c0 INTO r0; SELECT r0.a, r0.b; CLOSE c1; OPEN c1 FOR SELECT x FROM t2; FETCH c0 INTO r0; SELECT r0.a, r0.b; CLOSE c1; END; $$
DELIMITER ;$$
CALL p1;
