CREATE TABLE t1 (a INT NOT NULL AUTO_INCREMENT, UNIQUE (a) USING HASH) ENGINE=MyISAM PARTITION BY LIST (a) (PARTITION p0 VALUES IN (1,3), PARTITION p1 VALUES IN (8,4,2));
INSERT INTO t1 PARTITION (p1) (a) VALUES (8),(4);

CREATE TABLE t1 (a TEXT, pk INT NOT NULL AUTO_INCREMENT, UNIQUE KEY (a), KEY (pk)) PARTITION BY KEY (pk) PARTITIONS 3;
INSERT INTO t1 PARTITION (p1) VALUES (1,2);

CREATE TABLE t (c1 INT AUTO_INCREMENT KEY,c2 TEXT DEFAULT'') PARTITION BY HASH(c1) (PARTITION p1,PARTITION p2);
CREATE UNIQUE INDEX idx1 TYPE HASH ON t(c2);
INSERT INTO t PARTITION(p2) SET c1=DEFAULT;

CREATE TABLE t (c1 INT AUTO_INCREMENT KEY,c2 TEXT DEFAULT'') ENGINE=InnoDB PARTITION BY HASH(c1) (PARTITION p1,PARTITION p2);
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
CREATE UNIQUE INDEX idx1 TYPE HASH ON t(c2);
INSERT INTO t SET c1=DEFAULT;
ALTER TABLE t PARTITION BY HASH(c1) (PARTITION p1,PARTITION p2);
INSERT INTO t PARTITION(p1) SET c1=DEFAULT;

CREATE TABLE t (c1 INT AUTO_INCREMENT KEY,c2 TEXT DEFAULT '',UNIQUE(c2)) ENGINE=InnoDB PARTITION BY HASH(c1) (PARTITION p1,PARTITION p2);
INSERT INTO t SET c1=DEFAULT;
ALTER TABLE t FORCE;
INSERT INTO t PARTITION(p1) SET c1=DEFAULT ON DUPLICATE KEY UPDATE c1=DEFAULT;
