CREATE TABLE c(c INT) ENGINE=InnoDB;
SELECT 0 WHERE 0 IN(SELECT 0 FROM (SELECT 0 IN (WITH c AS(SELECT c=0 FROM (SELECT c FROM c WHERE c=0) AS c) SELECT (SELECT c FROM c AS c LIMIT 0 OFFSET 0)=0) AS c FROM c AS c) AS c WHERE c=0 GROUP BY c);

CREATE TABLE t (c INT) ENGINE=InnoDB;
SELECT 0 WHERE 0 IN (SELECT 0 FROM (SELECT 0 IN (WITH c AS(SELECT c=0 FROM (SELECT c FROM t WHERE c=0) AS c) SELECT (SELECT c FROM t AS c LIMIT 0 OFFSET 0)=0) AS c FROM t AS c) AS c WHERE c=0 GROUP BY c);

CREATE TABLE c(c FLOAT);
SELECT c FROM c WHERE(SELECT 1)IN (SELECT c FROM (SELECT c FROM c WHERE 1 IN (SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM (SELECT 1) AS c) AS c FROM (SELECT 1) AS c) AS c WHERE (WITH c AS(SELECT c % 1!=1 FROM (SELECT 1,0,c FROM c WHERE c=1) AS c GROUP BY c) SELECT c FROM c AS c) IN (SELECT c FROM (SELECT 'c' FROM c) AS c WHERE c!=1 GROUP BY c) GROUP BY c)) AS c WHERE c!=1 GROUP BY c);

CREATE TABLE c (c DEC) ENGINE=InnoDB;
SELECT 0 WHERE 0 IN (SELECT 0 FROM (SELECT 0 IN (WITH c AS (SELECT c=0 FROM (SELECT c FROM c WHERE c=0) AS c) SELECT (SELECT c FROM c AS c LIMIT 0 OFFSET 0)=0) AS c FROM c AS c) AS c WHERE c=0 GROUP BY c);

CREATE TABLE c (c DOUBLE,v2 TEXT,v3 INT);
SELECT c FROM c WHERE (SELECT 1) IN (SELECT c FROM (SELECT c FROM c WHERE 1 IN (SELECT 1 FROM (SELECT 1 IN (SELECT 1 FROM (SELECT 1) AS c) AS c FROM (SELECT 1) AS c) AS c WHERE (WITH c AS (SELECT c % 1!=1 FROM (SELECT 1,0,c FROM c WHERE c=1) AS c GROUP BY c) SELECT c FROM c AS c) IN (SELECT c FROM (SELECT 'c' FROM c) AS c WHERE c!=1 GROUP BY c) GROUP BY c)) AS c WHERE c!=1 GROUP BY c);
