SET GLOBAL innodb_trx_rseg_n_slots_debug=1;
CREATE TABLE t (b TEXT, FULLTEXT (b)) ENGINE=InnoDB;
INSERT INTO t VALUES ('a');
DELETE FROM t;

CREATE TABLE t (a INT KEY,message CHAR,FULLTEXT (message)) ENGINE=InnoDB COMMENT='';
INSERT INTO t VALUES (11384,2),(11392,2);
DELETE FROM t;
SELECT SLEEP;

SET GLOBAL innodb_trx_rseg_n_slots_debug=1;
CREATE TABLE t (a TEXT,FULLTEXT (a));
INSERT INTO t VALUES (0xA8ED);
UPDATE t SET a=9;
