CREATE TEMPORARY TABLE t (a INT KEY,b INT,KEY(b)) ENGINE=Aria;
INSERT INTO t VALUES (30,1);
INSERT INTO t SELECT a+4,b FROM t;
INSERT INTO t VALUES (1,1),(2,2);
SET max_session_mem_used=50000;
DELETE FROM t WHERE a BETWEEN 0 AND 20 OR b BETWEEN 10 AND 20;
