INSTALL SONAME 'ha_connect';
CREATE TABLE t1 (c1 INT    KEY,c2 CHAR(1),c3 long,c4 tinyint(1),KEY(c2)) ENGINE=MyISAM ROW_FORMAT=DYNAMIC PARTITION BY HASH(c1) (PARTITION p1,PARTITION p2);
ALTER TABLE t1 ADD COLUMN c5 VARCHAR(1) CHARACTER SET 'Binary' COLLATE 'Binary',DROP COLUMN c3;
CREATE  TABLE t4 ENGINE=CONNECT AS SELECT * FROM t1;
CREATE  TABLE t5 ENGINE=CONNECT REPLACE SELECT * FROM t4;
INSERT IGNORE INTO t4 () VALUES (),(),();
CREATE TRIGGER tr44 AFTER DELETE ON t4 FOR EACH ROW INSERT INTO t5 (c1) VALUES (1);
DELETE QUICK FROM t4 ORDER BY c1;
