CREATE TABLE t (c INT);
UPDATE t SET c=1 IN (SELECT c FROM t AS t1 NATURAL JOIN t WHERE EXISTS (SELECT 1 FROM t WHERE c IN (SELECT c=1)));

CREATE TABLE t (c INT);
UPDATE t SET c=1 IN (SELECT c FROM t AS t1 NATURAL JOIN t WHERE NOT EXISTS (SELECT * FROM t WHERE c IN (SELECT c=1)));

CREATE TEMPORARY TABLE t (c BLOB) ENGINE=InnoDB;
UPDATE t SET c=1 IN (SELECT c FROM t AS t1 NATURAL JOIN t WHERE EXISTS (SELECT 1 FROM t WHERE c IN (SELECT c=1)));

CREATE TABLE t (c INT KEY,c1 BLOB,c2 TEXT) ENGINE=InnoDB;
UPDATE t SET c=1 IN (SELECT c FROM t AS t1 NATURAL JOIN t WHERE NOT EXISTS (SELECT * FROM t WHERE c IN (SELECT c=1)));
