CREATE TABLE t (c INT) ENGINE=InnoDB;
CREATE VIEW v as SELECT GROUP_CONCAT('','') AS l FROM t;
DELIMITER //
CREATE PROCEDURE s (IN i VARCHAR(1)) SELECT * FROM v v WHERE CASE WHEN i THEN v.l LIKE CONCAT ('',i) END; //
DELIMITER ;
CALL s(0);

CREATE TABLE t (c INT) ENGINE=MyISAM;
CREATE VIEW v as SELECT GROUP_CONCAT('','') AS l FROM t;
DELIMITER //
CREATE PROCEDURE s (IN i VARCHAR(1)) SELECT * FROM v v WHERE CASE WHEN i THEN v.l LIKE CONCAT ('',i) END; //
DELIMITER ;
CALL s(0);

CREATE VIEW v AS SELECT GROUP_CONCAT('', '') AS l FROM (SELECT 1) AS a;
DELIMITER //
CREATE PROCEDURE s (IN i VARCHAR(1)) SELECT * FROM v v WHERE CASE WHEN i THEN v.l LIKE CONCAT ('',i) END; //
DELIMITER ;
CALL s(0);
