SET NAMES utf8;
CREATE OR REPLACE TABLE tp1(id INT)ENGINE=INNODB PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (0),PARTITION p1 VALUES LESS THAN (100));
CREATE OR REPLACE TABLE t(a INT,b double precision,primary key(a),index (b)) partition by range (a) partitions 2 (partition x1 values less than (1),partition x2 values less than (100));
CREATE OR REPLACE TABLE tp1(id INT)ENGINE=INNODB PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (0),PARTITION p1 VALUES LESS THAN (100),PARTITION p2 VALUES LESS THAN (200),PARTITION p3 VALUES LESS THAN (300),PARTITION p4 VALUES LESS THAN (400),PARTITION p5 VALUES LESS THAN (500));
SELECT MAX(a),a in (SELECT b FROM t) AS bb FROM t;
