# Requires /tmp/t1.txt holding one line, \N; ref bug report for MTR testcase
CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(4);
FLUSH TABLES;
LOAD DATA INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1);
#CLI: ERROR 167 (22003): Out of range value for column 'pk' at row 1
#ERR: - (no error)

SET auto_increment_increment=2;
CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(10);
FLUSH TABLES;
LOAD DATA INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1) (@x) SET pk=3;
LOAD DATA INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1);
SELECT GROUP_CONCAT(pk ORDER BY pk) FROM t1;
#CLI: 2,3,5,10; expected 2,3,10,11

CREATE TABLE t1 (a INT, b INT AUTO_INCREMENT, PRIMARY KEY (a,b)) ENGINE=MyISAM PARTITION BY HASH(a) PARTITIONS 2;
INSERT INTO t1 VALUES (1,5),(2,9);
FLUSH TABLES;
LOAD DATA INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1) (@x) SET a=1, b=@x;

CREATE TABLE t1 (a INT, b INT AUTO_INCREMENT, PRIMARY KEY (a,b)) ENGINE=Aria PARTITION BY HASH(a) PARTITIONS 2;
INSERT INTO t1 VALUES (1,5),(2,9);
FLUSH TABLES;
LOAD DATA INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1) (@x) SET a=1, b=@x;

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(4);
CREATE TRIGGER tr BEFORE INSERT ON t1 FOR EACH ROW SET @a=1;
FLUSH TABLES;
LOAD DATA INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1);
#CLI: ERROR 167 (22003): Out of range value for column 'pk' at row 1
#ERR: - (no error)

CREATE TABLE t1 (pk INT AUTO_INCREMENT PRIMARY KEY) PARTITION BY HASH(pk) PARTITIONS 2;
INSERT INTO t1 VALUES (2),(4);
FLUSH TABLES;
LOAD DATA LOCAL INFILE '/tmp/t1.txt' INTO TABLE t1 PARTITION (p1);
SELECT GROUP_CONCAT(pk ORDER BY pk) FROM t1;
#CLI: Warning 167 Out of range value for column 'pk' at row 1; the row is not loaded: 2,4; expected 2,4,5
