CREATE TABLE c(c CHAR) ENGINE=InnoDB;
INSERT INTO c(c)VALUES (1);
UPDATE c SET c=-0 WHERE(SELECT 0 -0 +0/ 0 + 0 - 0,c WHERE c<0 INTERSECT SELECT c,c FROM c WHERE c>0  -0)IN (SELECT c,c);

CREATE TABLE c(c INT) ENGINE=InnoDB;
INSERT INTO c VALUES (1);
UPDATE c SET c=-0 WHERE(SELECT 0,c WHERE c<0 INTERSECT SELECT c,c FROM c WHERE c>0)IN (SELECT c,c);

CREATE TABLE c(c BIGINT) ENGINE=InnoDB;
UPDATE c SET c=1 WHERE (SELECT '',c WHERE c=2 INTERSECT SELECT 1,1 FROM c WHERE c=3) IN (SELECT c,c);

CREATE TABLE c(c BIGINT UNIQUE) ENGINE=InnoDB;
UPDATE c SET c=0 WHERE(SELECT -0 ^ 0 +''/ 0,c WHERE c<0 INTERSECT SELECT c,''FROM c WHERE c>0  * 0)IN (SELECT c,c);

CREATE TABLE x ( x FIXED ) ;
INSERT INTO x ( x ) VALUES ( 1 ) ;
UPDATE x SET x = 1 WHERE ( WITH x AS ( SELECT 1 - 1 AS x ORDER BY x = 1 AND ( x < ( 1 IN ( 1 , 1 ) ) AND x = 1 AND x = 1 AND x = 1 ) DESC , x , x LIMIT 1 ) SELECT CASE CASE ( x NOT BETWEEN 'x' AND 'x' AND x < 1 ) WHEN 'x' THEN 'x' WHEN x ( NULL ) THEN 'x' WHEN 'x' THEN 'x' END WHEN x = 'x' THEN 'x' END , x FROM x UNION SELECT x , x FROM x ) NOT IN ( SELECT x , x FROM x WHERE x < 1 OR ( 1 OR ( 1 IN ( 1 , 1 ) ) OR ( x BETWEEN 1 AND 1 ) AND x < 1 ) ) ;

CREATE TABLE t AS SELECT''as a;
SELECT a FROM t WHERE (SELECT a,a UNION SELECT 1,a FROM t) IN (SELECT 1,1);
