CREATE TABLE t (c INT)
SELECT * FROM t WHERE c = 1 AND ( 3 = 0 OR  (SELECT c = 1 OR (SELECT 3 WHERE c = c ) = 3));

CREATE TABLE t (c TEXT) ENGINE=InnoDB;
SET SESSION query_alloc_block_size=1;
SELECT * FROM t WHERE c=1 AND (3=0 OR (SELECT c=1 OR (SELECT 3 WHERE c=c)=3));

SET SESSION query_prealloc_size=8192;
CREATE TABLE t1(c INT) ENGINE=InnoDB;
SELECT * FROM t1 WHERE c= 1 AND(3= 0 OR (SELECT c= 1 OR (SELECT 3 WHERE c= c)= 3));
