SET SQL_MODE='';
CREATE TABLE t (c BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY) ENGINE=MEMORY;
INSERT INTO t VALUES ('-9e999999');
ALTER TABLE t PARTITION BY KEY();
INSERT t VALUES (1);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE USER Spider@localhost IDENTIFIED BY 'PWD123';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t (c INT);
CREATE OR REPLACE TABLE t1 (pk INT PRIMARY KEY) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"' WITH SYSTEM VERSIONING PARTITION BY KEY() PARTITIONS 3;
INSERT INTO t1 (c1) VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);
ALTER TABLE t1 REMOVE PARTITIONING;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c1 INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, c2 tinyINT(1) UNSIGNED DEFAULT NULL, c3 VARCHAR(300) DEFAULT NULL, c4 INT(10) UNSIGNED NOT NULL, c5 INT(10) UNSIGNED DEFAULT NULL, PRIMARY KEY(c1)) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"' COMMENT='TABLE "st"' PARTITION BY LIST COLUMNS (c1) (PARTITION p1 DEFAULT COMMENT='srv "d"' ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"');
SELECT c1,c2,COUNT(*),MAX(c3) FROM t1 WHERE c1='y' OR c2='#C2' GROUP BY c1,c2 HAVING COUNT(*)=3;
SHOW CREATE TABLE t1;
