CREATE TABLE t (pk INT PRIMARY KEY, c VARCHAR(8), a INT, v1 INT AS (pk) VIRTUAL, v2 INT AS (pk) VIRTUAL, KEY(a), FULLTEXT(c)) ENGINE=InnoDB WITH SYSTEM VERSIONING;
CREATE TABLE t1 (a INT, KEY(a), FOREIGN KEY (a) REFERENCES t (a)) ENGINE=InnoDB;
ALTER TABLE t FORCE;
INSERT INTO t (pk,c,a) VALUES (1,'a',1);
INSERT INTO t1 VALUES (1);
DELETE FROM t;
