SET NAMES utf8;
DO CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('t')) LEVEL 7)) USING cp852);

SET NAMES armscii8 COLLATE armscii8_nopad_bin;
SELECT CHAR((WEIGHT_STRING (EXTRACTVALUE ((''),('tX')))));

SELECT CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('tX')))));

SET collation_connection='gb2312_bin';
DO CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('t')) LEVEL 7)) USING cp852);

DO CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('t')) LEVEL 7 DESC)) USING cp852);

SET @@collation_connection=latin1_german2_ci;
DO CHAR((WEIGHT_STRING (EXTRACTVALUE ((0),('a')) LEVEL 7)) USING cp852);
