CREATE TABLE t (c INT) ENGINE=InnoDB;
ALTER TABLE t RENAME a.t;

CREATE TABLE t (c INT) ENGINE=MyISAM;
ALTER TABLE t RENAME a.t;

CREATE TABLE t (c INT) ENGINE=InnoDB;
ALTER TABLE t PARTITION BY LIST (c) (PARTITION p VALUES IN (1,2));
ALTER TABLE t RENAME a.t;

CREATE TABLE t (c INT) ENGINE=MEMORY;
ALTER TABLE t RENAME a.t;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider;
ALTER TABLE t RENAME a.t;

INSTALL SONAME 'ha_rocksdb.so';
CREATE TABLE t (c INT) ENGINE=rocksdb;
ALTER TABLE t RENAME a.t;
