CREATE TEMPORARY TABLE t (a INT PRIMARY KEY) ENGINE=MEMORY;
ALTER TABLE mysql.gtid_slave_pos ENGINE=MEMORY;
ALTER TABLE mysql.gtid_slave_pos CHANGE seq_no seq_no VARCHAR(1);
INSERT INTO t VALUES (1);
