SET sql_mode='';
SET use_stat_tables=PREFERABLY;
CREATE TABLE tbl0 (a BIT)  engine=MyISAM;
ALTER TABLE tbl0 ADD b INT ;
INSERT INTO tbl0 VALUES (0,0),(0,0),(0,0);
LOCK TABLES tbl0 READ;
ANALYZE TABLE tbl0;
ANALYZE TABLE tbl0 PERSISTENT FOR COLUMNS () INDEXES ();
