SET GLOBAL log_bin_trust_function_creators=1;
DROP USER CURRENT_USER();
CREATE FUNCTION f1 (b INT) RETURNS INT RETURN 1;
CREATE VIEW v1 AS SELECT f1();
CREATE TABLE t1 (c1 INT UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE KEY);
LOCK TABLES t1 WRITE, v1 READ;
CREATE VIEW v2 AS SELECT * FROM v1 WITH CASCADED CHECK OPTION;
SHUTDOWN;
# Then check error log for 'Warning: Memory not freed: 560' and similar
