CREATE TABLE t1 (s TIMESTAMP);
INSERT INTO t1 VALUES ('2033-06-06'),('2015-09-10');
SELECT NULLIF( s, NULL ) AS f FROM t1 GROUP BY s WITH ROLLUP;

USE test;
SET SQL_MODE='';
CREATE TABLE t (a TIMESTAMP, b DATETIME, c TIME) ENGINE=InnoDB;
INSERT INTO t VALUES (NULL,NULL,NULL);
SELECT CASE a WHEN a THEN a END FROM t GROUP BY a WITH ROLLUP;

CREATE TABLE t (a INET6);
INSERT INTO t VALUES (NULL);
SELECT IFNULL (a,'') FROM t GROUP BY a WITH ROLLUP;

SET sql_mode='';
CREATE TABLE t (a UUID);
INSERT INTO t (a) VALUES (0);
SELECT IFNULL (a,'') FROM t GROUP BY a WITH ROLLUP;

SET sql_mode='';
CREATE TABLE t (a INET6);
INSERT INTO t VALUES (1),(1);
SELECT CASE a WHEN a THEN a END FROM t GROUP BY a WITH ROLLUP;

CREATE TABLE t (a TIMESTAMP);
INSERT INTO t VALUES (now());
SELECT (SELECT * FROM t GROUP BY a WITH ROLLUP HAVING a IS NULL);

SET sql_mode='';
CREATE TEMPORARY TABLE t (f1 INT PRIMARY KEY) ENGINE=InnoDB;
CREATE OR REPLACE TABLE t (c INET4);
DROP TABLE t;
INSERT INTO t VALUES (1);
SELECT (SELECT * FROM t GROUP BY c WITH ROLLUP HAVING c IS NULL);

CREATE TABLE t (a TIMESTAMP);
INSERT t VALUES (0);
SELECT (SELECT * FROM t GROUP BY a WITH ROLLUP HAVING a IS NULL);
