SET @cmd:="CREATE DEFINER=USER2 FUNCTION f (i1 BLOB,i2 INT UNSIGNED ZEROFILL) RETURNS CHAR BINARY READS SQL DATA RETURN CONCAT (1,i1)";
PREPARE s FROM @cmd;
EXECUTE s;
EXECUTE s;

SET @cmd:="CREATE DEFINER=CURRENT_USER PROCEDURE p(OUT i1 BINARY,INOUT i2 DECIMAL(0,0)) SQL SECURITY DEFINER XA ROLLBACK''";
PREPARE s FROM @cmd;
EXECUTE s;#;
SHOW SLAVE HOSTS;########;
EXECUTE s;########################################################;

SET @cmd:="CREATE DEFINER=CURRENT_USER PROCEDURE p(OUT i1 BINARY,INOUT i2 DECIMAL(0,0)) SQL SECURITY DEFINER XA ROLLBACK''";
PREPARE s FROM @cmd;
EXECUTE s;########;
SHOW SLAVE HOSTS;########;
EXECUTE s;########################################################;
