SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
CREATE TABLE t1 (c1 INT NOT NULL,c2 TEXT NOT NULL,UNIQUE(c2),KEY(c1)) ENGINE=InnoDB;
INSERT IGNORE INTO t1 (c2) VALUES ('');
ALTER TABLE t1 ADD FOREIGN KEY (c1) REFERENCES t1(c1) ON DELETE CASCADE;
INSERT IGNORE INTO t1 () VALUES ();
