SET sql_mode='';
CREATE TABLE t1 (a INT AUTO_INCREMENT KEY) ENGINE=InnoDB;
ALTER TABLE t1 ADD UNIQUE u USING HASH(a);
INSERT INTO t1 VALUES (0);
DELETE FROM t1;

CREATE TABLE t (c INT UNSIGNED AUTO_INCREMENT KEY);
CREATE UNIQUE INDEX i1 USING HASH ON t (c ASC);
INSERT INTO t VALUES();
DELETE FROM t;

SET sql_mode='';
CREATE TEMPORARY TABLE t (c INT AUTO_INCREMENT KEY, c2 VARCHAR(1025) BINARY CHARACTER SET 'utf8' COLLATE 'utf8_bin', c3 VARCHAR(1024), c4 VARCHAR(1) CHARACTER SET 'latin1' COLLATE 'latin1_bin') ROW_FORMAT=REDUNDANT ENGINE=InnoDB;
ALTER TABLE t ADD UNIQUE (c4,c3,c2,c);
INSERT INTO t VALUES ('','','fzu{HUd=F6I#A=zRZ6h+}f]]Q$bgIS/iwS&9AtjUYU7Q*LOPlQ[GQq=WDP79) 1=1 ( (G=1aOP0@',1.e+20);
UPDATE t SET c=0;
