SET SQL_MODE='';
CREATE TABLE t1 (a INT) ENGINE=INNODB;
CREATE TABLE t2 (a INT) ENGINE=INNODB;
SET transaction_isolation='SERIALIZABLE';
SET transaction_read_only=1;
HANDLER t2 OPEN;
SET transaction_read_only=0;
INSERT INTO t1 VALUES ('a');

CREATE TABLE t (c1 INT) ENGINE=INNODB;
SET transaction_read_only=1;
SET transaction_isolation='SERIALIZABLE';
HANDLER t OPEN;
SET transaction_read_only=0;
ALTER TABLE t DISCARD TABLESPACE;

CREATE TABLE t (id INT) ENGINE=INNODB;
SET transaction_isolation=SERIALIZABLE;
SET GLOBAL innodb_instant_alter_column_allowed=never;
CREATE TABLE t2 (id INT) ENGINE=INNODB PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (10));
SET transaction_read_only=ON;
HANDLER t OPEN;
SET SESSION TRANSACTION READ WRITE;
ALTER TABLE t2 ADD COLUMN c INT;

SET sql_mode='';
CREATE TABLE t1 (c1 CHAR(1) KEY,c3 INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES ('1',0);
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE,READ ONLY;
HANDLER t1 OPEN;
ALTER TABLE t1 REBUILD PARTITION p1;
UPDATE t1 SET c3=1;

CREATE TABLE t1 (c1 INT) ENGINE=InnoDB;
SET SESSION TRANSACTION READ ONLY;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
HANDLER t1 OPEN;
START TRANSACTION READ WRITE;
INSERT INTO t1 VALUES (1);
