CREATE TEMPORARY TABLE t1 (c INT KEY) ENGINE=INNODB;
INSERT INTO t1 (c) VALUES(0);
ALTER TABLE t1 ADD INDEX (c);
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE,READ ONLY;
HANDLER t1 OPEN AS h2;
ALTER TABLE t1 RENAME COLUMN IF EXISTS c TO d;
