# Requires MTR to reproduce
CREATE TABLE t (a VARCHAR(32), KEY(a)) CHARACTER SET utf8;
INSERT INTO t VALUES ('foo'),('bar');
CREATE ALGORITHM=TEMPTABLE VIEW v AS SELECT * FROM t;
SELECT * FROM v WHERE a < FROM_UNIXTIME(1568145408, '%I');
