CREATE TABLE t (a VARCHAR(256), f VARCHAR(256) AS ('')) ENGINE=InnoDB;
INSERT INTO t (a) VALUES ('foo');
ALTER TABLE t MODIFY f VARCHAR(1024) AS (CONVERT(a USING utf8mb3));
CREATE INDEX idx ON t (f(16));

SELECT CONVERT (REPLACE (EXPORT_SET ('a','a','a','','a'),'00','') USING ujis);
