CREATE OR REPLACE TABLE t1 (id VARCHAR(64) NOT NULL) ENGINE=InnoDB;
SET autocommit=FALSE;
CREATE TABLE t2 (c CHAR(1)) ENGINE=InnoDB;
LOCK TABLES t1 WRITE,t2 WRITE;
CREATE OR REPLACE TABLE t1 (b INT) ENGINE=SEQUENCE;
ALTER TABLE t1 RENAME mysqltest.t1;
INSERT INTO t1 VALUES (100,100);
FLUSH TABLES;
