CREATE TABLE t (c BLOB);
INSERT INTO t VALUES (0);
DELETE FROM t;
INSERT INTO t VALUES (0);
SELECT * FROM (SELECT * FROM t) AS a JOIN t WINDOW b AS (PARTITION BY t.c AND 0 BETWEEN (SELECT * FROM t GROUP BY t.c WINDOW d AS (PARTITION BY t.c)) AND 0);
