CREATE TABLE t1(id INT PRIMARY KEY, c1 INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES(1, 100);
INSERT INTO t1 VALUES(2, 200);
ALTER TABLE t1 ADD COLUMN c2 VARCHAR(100) DEFAULT 'default_value', ALGORITHM=INSTANT;
SET STATEMENT DEBUG_DBUG="+d,btr_page_alloc_fail" FOR
ALTER TABLE t1 DROP COLUMN c2, ALGORITHM=INSTANT;
SELECT * FROM t1;

CREATE TABLE t1(id INT PRIMARY KEY, c1 INT) ENGINE=InnoDB;
CREATE TABLE t2 LIKE t1;
INSERT INTO t1 VALUES(1, 100); INSERT INTO t2 VALUES(1, 100);
ALTER TABLE t1 ADD COLUMN c2 VARCHAR(100) DEFAULT 'default_value', ALGORITHM=INSTANT;
ALTER TABLE t2 ADD COLUMN c2 VARCHAR(100) DEFAULT 'default_value' FIRST, ALGORITHM=INSTANT;
SET STATEMENT DEBUG_DBUG="+d,btr_page_alloc_fail" FOR
ALTER TABLE t1 DROP COLUMN c2, ALGORITHM=INSTANT;
SET STATEMENT DEBUG_DBUG="+d,btr_page_alloc_fail" FOR
ALTER TABLE t2 DROP COLUMN c2, ALGORITHM=INSTANT;
SELECT * FROM t1;
SELECT * FROM t2;

CREATE TABLE t (a INT PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO t VALUES (1);
ALTER TABLE t ADD b INT;
SET debug_dbug='+d,ib_commit_inplace_fail_1';
ALTER TABLE t DROP b;
