CREATE TABLE t2 (c1 BIGINT UNSIGNED KEY) ENGINE=MYISAM ;
CREATE TABLE t1 (c1 INT,c2 DATE,c3 DATE,PERIOD FOR app_time(c2,c3),PRIMARY KEY(c1,app_time WITHOUT OVERLAPS)) ENGINE=MRG_MYISAM WITH SYSTEM VERSIONING;
DELETE a3,a1 FROM t1 AS a1 JOIN t1 AS a2 ON a1.c1=a2.c1 JOIN t2 AS a3 ON a2.c1=a3.c1;
