CREATE TABLE t1 (a INT);
delimiter $
CREATE PROCEDURE p1() 
BEGIN 
  DECLARE c1 SYS_REFCURSOR; 
  OPEN c1 FOR SELECT * FROM t1; 
END;
$
delimiter ;
CALL p1;
CREATE OR REPLACE TABLE t1(a INT);
CALL p1;
CALL p1;
CALL p1;
