# Requires standard replication setup with RBR and 10 threads parallel slave
CREATE TABLE t1 (id INT UNSIGNED KEY,YEAR INT UNSIGNED,MONTH INT UNSIGNED,DAY INT UNSIGNED,title CHAR(1),content TEXT,FULLTEXT INDEX (content),KEY(DAY)) DEFAULT CHARSET UTF8 COMMENT='';
CREATE GLOBAL TEMPORARY TABLE t (x INT) ON COMMIT DELETE ROWS;
SET SESSION gtid_domain_id=1;
DROP TABLE t;
CREATE TABLE t (x INT);
INSERT INTO t VALUES (1);
