CREATE TABLE t1 (c1 INT);
INSERT INTO t1 (t1.*) VALUES (1) RETURNING c1;

CREATE TABLE t (a INT, b INT);
CREATE VIEW v AS SELECT * FROM t;
ALTER TABLE t DROP b;
CREATE PROCEDURE sp() DELETE FROM v RETURNING *;
CALL sp;
CALL sp;
