SET GLOBAL query_cache_type=ON;
SET GLOBAL query_cache_size=1024*64;
USE test;
CREATE TABLE t (a INT) PARTITION BY KEY(a) PARTITIONS 99;
SET SESSION query_cache_type=DEFAULT;
SELECT COUNT(*) FROM t WHERE c1=2;

SET GLOBAL query_cache_type=DEMAND;
SET GLOBAL query_cache_size=102400;
SET SESSION query_cache_type=1;
CREATE TABLE t (a INT) ENGINE=InnoDB PARTITION BY KEY(a) PARTITIONS 100;
SELECT * FROM t WHERE a<ANY(SELECT * FROM t);

SET GLOBAL query_cache_type=DEMAND;
SET GLOBAL query_cache_size=102400;
SET SESSION query_cache_type=1;
CREATE TABLE t (a INT) ENGINE=InnoDB PARTITION BY RANGE(a) (PARTITION pa VALUES LESS THAN (0),PARTITION pb VALUES LESS THAN (2147483646));
SELECT * FROM t;
SELECT * FROM t;
DROP TABLE t;
CREATE TABLE t (a INT, c INT) ENGINE=InnoDB PARTITION BY KEY(a) PARTITIONS 100;
SELECT x FROM t;
SELECT a FROM t WHERE a<ANY(SELECT * FROM t);

SET GLOBAL query_cache_type=1;
CREATE TABLE t1 (a INT PRIMARY KEY, b TEXT) ENGINE=InnoDB PARTITION BY KEY(a) PARTITIONS 144;
CREATE TABLE t4 (c1 CHAR(1)) DEFAULT CHARSET=sjis ENGINE=InnoDB;
SET query_cache_type=ON;
SET GLOBAL query_cache_size=81920;
SELECT * FROM t4;
SELECT * FROM t1 WHERE not (a !=1);
