SET sql_mode='';
CREATE TABLE t (c BIGINT,c2 REAL(1,1) ZEROFILL,c3 CHAR AS (c) VIRTUAL,KEY(c)) ROW_FORMAT=COMPACT;
CREATE TRIGGER tr1 AFTER INSERT ON t FOR EACH ROW SHOW PROFILES;
REPLACE INTO t VALUES (0,0,0) RETURNING c;
