CREATE TABLE sv_t (x INT,start_trxid BIGINT UNSIGNED GENERATED ALWAYS AS ROW START,end_trxid BIGINT UNSIGNED GENERATED ALWAYS AS ROW END,PERIOD FOR SYSTEM_TIME(start_trxid,end_trxid)) ENGINE=INNODB WITH SYSTEM VERSIONING;
CREATE OR REPLACE TABLE mysql.transaction_registry (id INT);
XA START 'a';
INSERT INTO sv_t (x) VALUES(1);
SELECT * FROM sv_t FOR SYSTEM_TIME FROM  (NOW() - INTERVAL 1 MINUTE) TO NOW();

CREATE OR REPLACE TABLE mysql.procs_priv(id INT) ENGINE=INNODB;
INSERT INTO mysql.procs_priv SELECT seq FROM seq_1_to_1001;
FLUSH PRIVILEGES;
