SET SQL_MODE='';
CREATE TABLE t1 (a DOUBLE KEY AUTO_INCREMENT) ENGINE=INNODB ;
INSERT INTO t1 VALUES (99999999999999999999);
FLUSH TABLES;
CREATE TABLE t2 (id INT,KEY(id)) ENGINE=INNODB PARTITION BY HASH (id) PARTITIONS 600;
SELECT * FROM information_schema.tables;
