INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT AUTO_INCREMENT KEY,b CHAR(1),c CHAR(1)) ENGINE=Spider;
INSERT DELAYED IGNORE INTO t VALUES (1);
INSERT DELAYED INTO t SET b=1;   # Repeat till crash is observed
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
INSERT DELAYED INTO t SET b=1;
