CREATE TABLE t(c INT KEY) ENGINE=InnoDB;
INSERT INTO t VALUES ((c IN (SELECT * FROM (SELECT * FROM t GROUP BY c) AS d NATURAL JOIN (SELECT * FROM t) AS e)) - 1);

CREATE TABLE t (c INT KEY);
CREATE TABLE t0 (a INT,b INT,c BINARY (0),d CHAR(0),e VARCHAR(0),f VARCHAR(0),g BLOB,h BLOB,id INT,KEY(b),KEY(e),PRIMARY KEY(id));
INSERT INTO t VALUES ((c IN (SELECT * FROM (SELECT * FROM t GROUP BY c) AS d NATURAL JOIN (SELECT * FROM t) AS e)) -0);
