CREATE TABLE t (c INT KEY) ENGINE=InnoDB;
INSERT INTO t (c) VALUES (0);
SELECT * FROM t WHERE (0,0) IN (SELECT MAX(c),MIN(c) FROM t);

CREATE TABLE t (c INT,INDEX (c)) ENGINE=InnoDB;
INSERT INTO t VALUES (0);
SELECT * FROM t WHERE (0,0) IN (SELECT MAX(c),MIN(c) FROM t);
