INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t (c2 CHAR(1)) ENGINE=Spider;
SELECT * FROM t WHERE f LIKE'';
SELECT 1 - LENGTH (SUBSTRING_INDEX(SUBSTR('[SELECT COUNT(*) FROM t WHERE a IS ]=1',1,41),'[',-1));
INSERT INTO t (SELECT 1 FROM t);
LOCK TABLES t WRITE CONCURRENT;
DELETE FROM t;

INSTALL PLUGIN spider SONAME 'ha_spider.so';
CREATE TABLE t1 (a CHAR(10), FULLTEXT (a)) ENGINE=Spider;
INSERT INTO t1 VALUES (1),(1),(2),(2);
DROP TABLE t1;
CREATE TABLE t1 (c1 YEAR NOT NULL);
LOCK TABLES t1 WRITE;
CREATE OR REPLACE TABLE t1 (x INT) ENGINE=Spider;
SET SESSION RAND_SEED2=1e1;
INSERT INTO t1 VALUES (12);

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TEMPORARY TABLE 龡龡龡 (丌丌丌 CHAR) DEFAULT CHARSET=utf8 ENGINE=Spider;
LOAD DATA LOCAL INFILE '0' INTO TABLE t FIELDS TERMINATED BY '0' LINES TERMINATED BY '0';
CREATE TABLE t (id INT UNSIGNED,id_version INT UNSIGNED DEFAULT '0',KEY id_version (id_version)) ENGINE=Spider;
SELECT * FROM t;
EXPLAIN PARTITIONS SELECT * FROM t7 WHERE a=90;
LOCK TABLE t WRITE CONCURRENT;
DELETE FROM t;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE SERVER srv FOREIGN DATA WRAPPER MYSQL OPTIONS (SOCKET '../socket.sock', DATABASE 'test', USER 'Spider', PASSWORD 'PWD123');
CREATE TABLE t1 (a TEXT, b CHAR(255), c CHAR(4)) ENGINE=Spider COMMENT='WRAPPER "mysql", srv "srv", TABLE "t"';
CREATE TABLE t2 SELECT f2 FROM (SELECT MAX(NOW()) f2 FROM t1) a;
SET SESSION tx_read_only=TRUE;
EXPLAIN SELECT * FROM t1,t1 AS t2 WHERE t1.x=t2.y;
HANDLER t1 OPEN;
HANDLER t1 READ FIRST LIMIT 9;
SELECT * FROM t1;
HANDLER t1 READ FIRST;
SELECT SLEEP (3);
