CREATE TABLE t1 (f1 INT) ENGINE=InnoDB;
SET GLOBAL wsrep_IGNORE_apply_errors=1;
SET SESSION wsrep_dirty_reads=1;
SHOW CREATE TABLE t1;
FLUSH HOSTS;
CREATE TABLE t1 (f1 INT) ENGINE=InnoDB;
FLUSH HOSTS;
