CREATE SERVER srv FOREIGN DATA WRAPPER odbc OPTIONS (DRIVER '',USERNAME '',PASSWORD '',PORT 0,DATABASE 'foo');
INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (c INT) ENGINE=Spider COMMENT='WRAPPER "mysql",SRV "srv",TABLE "nonexisting"';
SELECT * FROM t;
