INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (i INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ FIRST;
HANDLER t READ FIRST;

INSTALL PLUGIN Spider SONAME 'ha_spider.so';
CREATE TABLE t (a INT) ENGINE=Spider;
HANDLER t OPEN;
HANDLER t READ NEXT;
HANDLER t READ NEXT;
