SET @@global.wsrep_on=OFF;
XA START 'a';
SELECT GET_LOCK('test', 0) = 0 expect_1;
XA END 'a';
CACHE INDEX t1 PARTITION (ALL) KEY (`inx_b`,`PRIMARY`) IN default;
SELECT SLEEP(3);

SET SESSION wsrep_on=OFF;
XA START 'a';
XA END 'a';
SET GLOBAL KEYCACHE2.key_buffer_size=4*1024*1024;
CACHE INDEX t1 IN KEYCACHE2;
SELECT 1;
