SET SESSION wsrep_trx_fragment_size=1;
CREATE TABLE t1 (c1 VARCHAR(10));
CREATE TABLE t2 (b INT PRIMARY KEY) ENGINE=InnoDB;
XA START 'tx1';
SET GLOBAL wsrep_trx_fragment_size=DEFAULT;
INSERT INTO t2 VALUES (1);
LOAD INDEX INTO CACHE t1;
INSERT INTO t2 VALUES (2);
