XA START 'a';
SET GLOBAL KEYCACHE1.key_buffer_size=128*1024;
XA END 'a';
CACHE INDEX t1 KEY(PRIMARY) IN KEYCACHE1;
SET GLOBAL wsrep_on=OFF;
XA COMMIT 'a';
ALTER SCHEMA test DEFAULT COLLATE ascii_general_ci;
