BINLOG 'wlZOTw8BAAAA8QAAAPUAAAAAAAQANS41LjIxLU1hcmlhREItZGVidWctbG9nAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAA2QAEGggAAAAICAgCAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAA371saA==';
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQXAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv /8AgAAAAgAAAA=';
# Result (presumed non-issue): [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 'test.t^W' doesn't exist', Internal MariaDB error code: 1146

CREATE TABLE t1 (f2 INT);
BINLOG ' mSKWVg8BAAAAdwAAAHsAAAAAAAQANS44LjAtbTE3LWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAACZIpZWEzgNAAgAEgAEBAQEEgAAXwAEGggAAAAICAgCAAAACgoKKioAEjQA AYzz6oU=';
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQXAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv /8AgAAAAgAAAA=';
# Result (presumed non-issue): [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 'test.t^W' doesn't exist', Internal MariaDB error code: 1146

BINLOG ' SOgWTg8BAAAAbgAAAHIAAAAAAAQANS42LjMtbTUtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAABI6BZOEzgNAAgAEgAEBAQEEgAAVgAEGggAAAAICAgCAAAAAAVAYI8=';
SET max_error_count=0;
CREATE TABLE t1 (id INT(11) NOT NULL AUTO_INCREMENT, id2 INT(11) NOT NULL, CONSTRAINT t1_id_fk FOREIGN KEY(id) REFERENCES t1 (id)) ENGINE=InnoDB;
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQXAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv /8AgAAAAgAAAA=';
# 2024-03-02 10:30:27 7 [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 'test.t^W' doesn't exist', Internal MariaDB error code: 1146

# Note that the 'v /8' in the final BINLOG command was previously converted from 'v/8' by tcp, which was a shortcoming, and this was fixed in tcp
