BINLOG 'wlZOTw8BAAAA8QAAAPUAAAAAAAQANS41LjIxLU1hcmlhREItZGVidWctbG9nAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAA2QAEGggAAAAICAgCAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAA371saA==';
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQXAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv /8AgAAAAgAAAA=';
# Result (presumed non-issue): [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 'test.t^W' doesn't exist', Internal MariaDB error code: 1146

CREATE TABLE t1 (f2 INT);
BINLOG ' mSKWVg8BAAAAdwAAAHsAAAAAAAQANS44LjAtbTE3LWRlYnVnLWxvZwAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAACZIpZWEzgNAAgAEgAEBAQEEgAAXwAEGggAAAAICAgCAAAACgoKKioAEjQA AYzz6oU=';
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQXAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv /8AgAAAAgAAAA=';
# Result (presumed non-issue): [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 'test.t^W' doesn't exist', Internal MariaDB error code: 1146
