BINLOG 'AMqaOw8BAAAAdAAAAHgAAAAAAAQANS42LjM0LTc5LjEtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXAAEGggAAAAICAgCAAAACgoKGRkAAYVx w2w=';
CREATE TEMPORARY TABLE t2 (c INT UNSIGNED,c2 CHAR,KEY(c));
LOCK TABLES t2 AS a3 READ,t2 AS a8 WRITE;
BINLOG ' Bk3vRhO0AQAAOAAAALcLyQkAAJlXFwIAAAAABXRyYWNrAA12aXNpdHNfZXZlbnRzAAYJAwcPDwM=Bk3vRhe0AQAAWgAAABEMyQkQAJlXFwIAAAEABv / AIE4AvvVDAQZN70YAK0Rvd25sb2Fkcy9NeVNR TC00LjEvbXlzcWwtNC4xLjEyYS13aW4zMi56aXBPaAIC ';
# ERROR 1100 (HY000): Table 'visits_events' was not locked with LOCK TABLES
# [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 'visits_events' was not locked with LOCK TABLES', Internal MariaDB error code: 1100

BINLOG 'AMqaOw8BAAAAdAAAAHgAAAAAAAQANS42LjM0LTc5LjEtZGVidWctbG9nAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAEzgNAAgAEgAEBAQEEgAAXAAEGggAAAAICAgCAAAACgoKGRkAAYVx w2w=';
CREATE TEMPORARY TABLE t2 (a INT,b INT,KEY USING btree (a));
LOCK TABLE t2 READ;
BINLOG 'wlZOTxMBAAAAKgAAADwCAAAAACkAAAAAAAEABHRlc3QAAnQXAAIDAwAC wlZOTxcBAAAAJgAAAGICAAAAACkAAAAAAAEAAv /8AgAAAAgAAAA=';
# ERROR 1100 (HY000): Table 't\0017' was not locked with LOCK TABLES
# [ERROR]  BINLOG_BASE64_EVENT: Error executing row event: 'Table 't^W' was not locked with LOCK TABLES', Internal MariaDB error code: 1100
