#!/bin/bash
# Created by Roel Van de Paar, MariaDB

# Set AFL_PRELOAD to fuzz Galera.
if [ ! -z ${GAL_RUN} ]; then
  export LD_LIBRARY_PATH=${PWD}/lib/
  export AFL_PRELOAD=${PWD}/lib/libgalera_smm.so
  export AFL_IGNORE_PROBLEMS=1
fi
MAX_RUNTIME_MIN=1440  # 24h

# Disable ASLR (Address Space Layout Randomization)
echo 0 | sudo tee /proc/sys/kernel/randomize_va_space
export AFL_DISABLE_ASLR=1

if [ "${PWD}" == "${HOME}/fuzzing" ]; then
  echo "This script is not meant to be executed from ~/fuzzing. It is here only for editing convience"
  exit 1
fi

if [ -z "${1}" ]; then
  echo "Need to specify instanceID"
  return 2> /dev/null; exit 1
elif [ "$(echo "${1}" | sed 's|^[0-9]$|OK|')" != "OK" ]; then
  echo "Option passed (instanceID: {1}) is not correct. Range: 0-9"
  return 2> /dev/null; exit 1
fi
INSTANCE="afl${1}"

if [ "${STY}" == "" ]; then
  THIS_SCRIPT="$(readlink -f $0)"  # Resolves symlinks, result is the actual script including directory
  SCREEN_NAME="afl${1}-srv"
  #echo "Not a screen, restarting myself inside a screen"  # Do not report on this as it confuses ~/fuzzing/startup.sh script output
  screen -admS "${SCREEN_NAME}" bash -c "${THIS_SCRIPT} ${*}"
  sleep 1
  #screen -d -r "${SCREEN_NAME}"  # Do not connect to the screen as this halts ~/fuzzing/startup.sh from starting up correctly (i.e. the screen is connected to for the/this particular node being started but the startup.sh script is thereby halted/paused)
  return 2> /dev/null; exit 0
fi

if [ ! -d ./lib ]; then
  echo "Directory ./lib not found - are you in a MariaDB BASEDIR?"
  return 2> /dev/null; exit 1
fi

if [ ! -r ./start ]; then
  echo "Start not present: execute ~/start"
  return 2> /dev/null; exit 1
fi

if ! grep --binary-files=text 'AFL_MAP_SIZE' ./bin/mysqld >/dev/null 2>&1; then
  echo "Assert: binary at ${PWD}/bin/mysqld (or mariadbd) is not instrumented!"
  exit 1
fi

#sed -i "s|/test/[-\._A-Za-z0-9]\+x86_64/socket.sock|/test/afl_socket.sock|g" ${SCRIPTSTOMOD} 2>&1 | grep -v 'FIREWORKS-BUGS'  # Make it universal if not done already
#sed -i "s|/test/afl_socket.sock|/test/afl${1}_socket.sock|g" ${SCRIPTSTOMOD} 2>&1 | grep -v 'FIREWORKS-BUGS'  # First replace
#sed -i "s|/test/afl[0-9]_socket.sock|/test/afl${1}_socket.sock|g" ${SCRIPTSTOMOD} 2>&1 | grep -v 'FIREWORKS-BUGS'  # Subsequent replaces

if [ ! -z "${GAL_RUN}" ]; then
  SCRIPTSTOMOD="gal_cl gal_cl_noprompt gal_cl_noprompt_nobinary gal_multirun gal_multirun_pquery start_gypsy gal_start gal_stop gal_sysbench_prepare gal_sysbench_run gal_test gal_test_pquery gal_wipe n1.cnf"
  sed -i "s|/dev/shm/afl-node-${1}/node1/node1_socket.sock|/test/afl${1}_socket.sock|g" ${SCRIPTSTOMOD} 2>&1 | grep -vE 'FIREWORKS-BUGS|No such file or directory'  # Make it universal if not done already
else
  SCRIPTSTOMOD="cl cl_noprompt cl_noprompt_nobinary m multirun multirun_pquery multirun_pquery_rr multirun_rr repl_setup start_gypsy start_rr start_valgrind start stop sysbench_prepare sysbench_run test test_pquery wipe"
  sed -i "s|/dev/shm/afl-node-${1}/socket.sock|/test/afl${1}_socket.sock|g" ${SCRIPTSTOMOD} 2>&1 | grep -vE 'FIREWORKS-BUGS|No such file or directory'  # Make it universal if not done already
fi

sed -i "s|^/test/|timeout --signal=9 ${MAX_RUNTIME_MIN}m /test/|" start  # Restart instance every 15 minutes to avoid lockups. Note: this will sometimes create a single dud testcase

# Prep *SAN
export ASAN_OPTIONS=suppressions=/home/roel/mariadb-qa/ASAN.filter:quarantine_size_mb=512:atexit=0:detect_invalid_pointer_pairs=3:dump_instruction_bytes=1:abort_on_error=1:allocator_may_return_null=1
export UBSAN_OPTIONS=suppressions=/home/roel/mariadb-qa/UBSAN.filter:print_stacktrace=1:report_error_type=1
export TSAN_OPTIONS=suppress_equal_stacks=1:suppress_equal_addresses=1:history_size=7:verbosity=1
export MSAN_OPTIONS=abort_on_error=1:poison_in_dtor=0

echo 'Remember that this needs to be run from a clean shell where no AFL variables were ever set, EVEN if they were made empty before starting! However, restarting this script is fine.'
echo "If you see '.shmat for map: Bad file descriptor' then __AFL_SHM_ID was likely set incorrectly!"
__AFL_SHM_ID=
export __AFL_SHM_ID=
export -n __AFL_SHM_ID
./kill
rm -f /test/afl${1}_socket.sock*
sleep 2
if [ ! -z ${GAL_RUN} ]; then
  ./gal_no_cl --sql_mode= --max_statement_time=5
  sleep 1
  ./gal_stop
else
  ./all_no_cl --sql_mode= --max_statement_time=5
  sleep 1
  ./stop
fi
#export AFL_TMPDIR=/dev/shm/fuzzcache
#export AFL_MAP_SIZE=333041  # 10.3 specific!
#export AFL_MAP_SIZE=375377  # 10.10 specific!
#export AFL_MAP_SIZE=5000000  # Generic, should always work
#export AFL_MAP_SIZE=1000000  # Generic, should always work, too small
export AFL_MAP_SIZE=50000000  # Generic, should always work

export __AFL_SHM_ID="$(cat ~/fuzzing/${INSTANCE}.log | grep --binary-files=text 'SHM_ENV_VAR' | tail -n1 | grep --binary-files=text -o '[0-9]\+')"
echo "debug: ${__AFL_SHM_ID}"
if [ ! -z ${GAL_RUN} ]; then
  ./gal_start
else
  ./start
fi
echo 'Status will show in 2 seconds...'
sleep 2 # give server time start before starting loop
echo "Server started at: $(date) | ID: ${INSTANCE} | Max runtime: ${MAX_RUNTIME_MIN}m (sig 9)"
echo "Node: ${1} | Basedir: ${PWD} | socket: /test/afl${1}_socket.sock"
echo "Client: ${PWD}/bin/mysql -S/test/afl${1}_socket.sock -uroot"
echo "__AFL_SHM_ID: ${__AFL_SHM_ID} | AFL_MAP_SIZE: ${AFL_MAP_SIZE}"
echo -n 'Queries (1m updates): '
 
echo "SHOW GLOBAL STATUS LIKE 'Queries';" > in.sql
while :; do
  if ${PWD}/bin/mysqladmin ping -uroot -S/test/afl${1}_socket.sock > /dev/null 2>&1; then 
    sleep 60
    if [ ! -z ${GAL_RUN} ]; then
      ./gal_test
    else
      ./test
    fi
    QUERIES="$(cat ./mysql.out 2>/dev/null | grep Queries | grep -o '[0-9]\+')"
    echo -n "${QUERIES}.."
    continue
  else
    sleep 3  # Are we sure server is not up?
    if ${PWD}/bin/mysqladmin ping -uroot -S/test/afl${1}_socket.sock > /dev/null 2>&1; then 
      continue
    fi
    #echo 'Server unreachable... core?:'
    #ls -l core 2>/dev/null
    #ls -l ./data/core 2>/dev/null
    #sleep 2
    #echo 'Server unreachable... error log tail:'
    #tail -n20 ./log/master.err
    #sleep 20
    if [ ! -z ${GAL_RUN} ]; then
      ./gal_kill
      sleep 1
      ./gal_no_cl --max_statement_time=1
    else
      ./kill
      sleep 1
      ./all_no_cl --max_statement_time=1
    fi
    sleep 20 # give server time start before looping
    clear
    echo "Server restarted at: $(date) | ID: ${INSTANCE} | Max runtime: ${MAX_RUNTIME_MIN}m (sig 9)"
    echo "Node: ${1} | Basedir: ${PWD} | socket: /test/afl${1}_socket.sock"
    echo "__AFL_SHM_ID: ${__AFL_SHM_ID} | AFL_MAP_SIZE: ${AFL_MAP_SIZE}"
    echo -n 'Queries: '
  fi
done

