#!/bin/bash
# Created by Roel Van de Paar, MariaDB
set +H  # Prevent '-bash: !...: event not found' issues with '!' as a [leading] char in the known bug UniqueID strings

KB=${HOME}/mariadb-qa/known_bugs.strings
cd ${HOME}/fuzzing
if [ "${PWD}" != "${HOME}/fuzzing" ]; then
  echo "Assert: PWD!=${HOME}/fuzzing"
  exit 1
elif [ ! -r ${KB} ]; then
  echo "Assert: Known bugs list (${KB}) not present"
  exit 1
fi 
# rm -f is used for the case where this script is being executed from two different places (~/ds and manually)
find . | grep '\.string$' | xargs -I{} echo "STRING=\"\$(cat '{}')\"; if grep -Fli --binary-files=text \"\${STRING}\" ${KB} >/dev/null 2>&1; then FILE='{}'; FILESHORT=\"\$(echo \"\$FILE\" | sed 's|.string||')\"; rm -f \"\${FILESHORT}\".[a-z][a-z]*; if [ -r \"\${FILESHORT}\" ]; then rm -f \"\${FILESHORT}\"; fi; fi" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" 2>/dev/null
