#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ "${PWD}" != "${HOME}/fuzzing" ]; then
  if [ -d "${HOME}/fuzzing" ]; then
    cd ${HOME}/fuzzing
  else
    echo "Assert: ${HOME}/fuzzing does not exist"
    exit 1
  fi
fi

# TODO: hangs processing (ref output_*/hangs directories)

echo 'Deleting known bugs...'
./del_known_bugs
echo 'Processing, this may take a minute...'
TOTA=$(find . | grep 'crashes.*sig:' | grep -v 'pos:[0-9]\+\.' | wc -l)  # all testcases (i.e. total of all files w/o any .ext)
DONE=$(find . | grep 'crashes.*sig:' | grep '\.string$' | wc -l)      # already done
NOCO=$(find . | grep 'crashes.*sig:' | grep '\.NOCORE$' | wc -l)      # no core
REPR=$(find . | grep 'crashes.*sig:' | grep '\.report$' | wc -l)      # completed reports
BCNT=$(find . | grep '\.string' | xargs -I{} cat {} | sort -u | wc -l)
BCNF=$(find . | grep '\.string' | xargs -I{} cat {} | sort -u | grep -v 'FALLBACK' | wc -l)

echo ""
echo "Total testcases:          ${TOTA}"
echo "Already done:             ${DONE}"
echo "Still to do testcase:     $[ ${TOTA} - ${DONE} ]"
echo "NOCORE testcases:         ${NOCO}  (Re-run these against the actual build used if you did not use the same build)"
echo "Completed reports:        ${REPR}"
echo "Unique bugs seen:         ${BCNT}"
echo "Unique bugs seen w/o FB:  ${BCNF} (without FALLBACK)"
echo ""
echo "Note: crashes with duplicate UniqueID's are automatically deleted, so the 'Already done' number is skewed."
echo "Note: ./newbugs/ (new bugs found by reducer while reducing) are included in these statistics."
