#!/bin/bash
# Created by Roel Van de Paar, MariaDB

find . | grep '\.report' | xargs -I{} echo "FILE=\$(echo '{}' | sed 's|\.report$||'); echo \"------ cat '\${FILE}.report'\"; cat \"\${FILE}.string\"" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}"
