#!/bin/bash
  
if [ -d "${1}" ]; then
  echo "Please pass instance number"
  exit 1
fi
INSTANCE="afl-${1}"

if [ ! -d ./lib ]; then
  echo "Directory ./lib not found - are you in a MariaDB BASEDIR?"
  exit 1
fi

if [ ! -r ./start ]; then
  echo "Start not present: execute ~/start"
  exit 1
fi

echo 'Remember that this needs to be run from a clean shell where no AFL variables were ever set, EVEN if they were made empty before starting! However, restarting this script is fine.'
echo "If you see '.shmat for map: Bad file descriptor' then __AFL_SHM_ID was likely set incorrectly!"
sleep 2
./all_no_cl
sleep 3
./stop

export AFL_TMPDIR=/dev/shm/fuzzcache
#export LD_LIBRARY_PATH=${PWD}/lib/  # This is not required on the server side
export AFL_MAP_SIZE=333041  # 10.3 specific!
INSTANCE="afl-${1}"
export __AFL_SHM_ID="$(cat ~/fuzzing/${INSTANCE}.log | grep --binary-files=text 'SHM_ENV_VAR' | tail -n1 | grep --binary-files=text -o '[0-9]\+')"
./start
echo 'Ready!'
echo "AFL_MAP_SIZE: ${AFL_MAP_SIZE} | __AFL_SHM_ID: ${__AFL_SHM_ID} | AFL_TMPDIR: ${AFL_TMPDIR}"

while true; do
  if /test/AFL-MD180622-mariadb-10.3.36-linux-x86_64/bin/mysqladmin ping -uroot -S/test/AFL-MD180622-mariadb-10.3.36-linux-x86_64/socket.sock > /dev/null 2>&1; then 
    sleep 3
    continue
  else
    sleep 2
    ./kill
    sleep 1
    ./all_no_cl
    sleep 5
    clear
    echo "Server last restarted at: $(date)"
  fi
  echo -n '.'
done

