#!/bin/bash
# rm -f is used for the case where this script is being executed from two different places (~/ds and manually)
find . | grep string | xargs -I{} echo "STRING=\"\$(cat '{}')\"; if grep -Fli --binary-files=text \"\${STRING}\" /home/$(whoami)/mariadb-qa/known_bugs.strings >/dev/null 2>&1; then rm -f '{}'; FILE=\"\$(echo '{}'|sed 's|.string||')\"; if [ -d \"\${FILE}\" -a ! -d \"\${FILE}\" ]; then rm -f \"\${FILE}\"; rm -f \"\${FILE}.NOCORE\"; fi; fi" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" 2>/dev/null
