#!/bin/bash
# Created by Roel Van de Paar, MariaDB

KB=/home/$(whoami)/mariadb-qa/known_bugs.strings
cd /home/$(whoami)/fuzzing
if [ "${PWD}" != "/home/$(whoami)/fuzzing" ]; then
  echo "Assert: PWD!=/home/$(whoami)/fuzzing"
  exit 1
elif [ ! -r ${KB} ]; then
  echo "Assert: Known bugs list (${KB}) not present"
  exit 1
fi 
# rm -f is used for the case where this script is being executed from two different places (~/ds and manually)
find . | grep '\.string$' | xargs -I{} echo "STRING=\"\$(cat '{}')\"; if grep -Fli --binary-files=text \"\${STRING}\" ${KB} >/dev/null 2>&1; then FILE='{}'; FILESHORT=\"\$(echo \"\$FILE\" | sed 's|.string||')\"; if [ -r \"\${FILESHORT}.string\" ]; then rm -f \"\${FILESHORT}.string\"; fi; if [ -r \"\${FILESHORT}\" ]; then rm -f \"\${FILESHORT}\"; fi; fi" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" 2>/dev/null
