#!/bin/bash 
echo 'Processing new testcases... This will take a while...'
./process_testcases >/dev/null 2>&1
echo 'Deleting known bugs...'
./del_known_bugs
echo 'Reporting outcomes...'
COUNT="$(./list_unique_bugs | wc -l)"
echo "----------------------------------------- ${COUNT} Bugs ---------------"
./list_unique_bugs
echo '----------------------------------------------------------------'
