#!/bin/bash
# From top, down
ps -ef | grep 'afl-process_testcases' | awk '{print $2}' | xargs -I{} kill -9 {} >/dev/null 2>&1
screen -wipe >/dev/null 2>&1
screen -admS afl-process_testcases bash -c "BASEDIR='/test/dbg1010'; find . | grep 'sig:' | grep -vE 'string|NOCORE' | sed 's|^\./||' | sort -h | xargs -I{} echo \"if [ ! -r '{}.string' -a ! -r '{}.NOCORE' ]; then cp '{}' \${BASEDIR}/in.sql; cd \${BASEDIR}; ./all_no_cl; ./test_pquery; sleep 2; if [ -r ./data/core ]; then echo '----------- /home/\$(whoami)/fuzzing/{}.string:'; ~/t | tee '/home/\$(whoami)/fuzzing/{}.string'; echo '-----------'; else echo '----------- /home/\$(whoami)/fuzzing/{}.NOCORE:'; touch '/home/\$(whoami)/fuzzing/{}.NOCORE'; echo '-----------'; fi; cd /home/\$(whoami)/fuzzing; fi\" | tr '\n' '\0' | xargs -0 -I{} timeout --signal=9 15m bash -c \"{}\"" 
# From bottom, reverse
screen -admS afl-process_testcases_rev bash -c "BASEDIR='/test/dbg1010_rev'; find . | grep 'sig:' | grep -vE 'string|NOCORE' | sed 's|^\./||' | sort -hr | xargs -I{} echo \"if [ ! -r '{}.string' -a ! -r '{}.NOCORE' ]; then cp '{}' \${BASEDIR}/in.sql; cd \${BASEDIR}; ./all_no_cl; ./test_pquery; sleep 2; if [ -r ./data/core ]; then echo '----------- /home/\$(whoami)/fuzzing/{}.string:'; ~/t | tee '/home/\$(whoami)/fuzzing/{}.string'; echo '-----------'; else echo '----------- /home/\$(whoami)/fuzzing/{}.NOCORE:'; touch '/home/\$(whoami)/fuzzing/{}.NOCORE'; echo '-----------'; fi; cd /home/\$(whoami)/fuzzing; fi\" | tr '\n' '\0' | xargs -0 -I{} timeout --signal=9 15m bash -c \"{}\"" 
COUNT=$(find . | grep 'sig:' | grep -vE 'string|NOCORE' | sed 's|^\./||' | wc -l)
if [ ! -z "${COUNT}" ]; then
  if [ "${COUNT}" -gt 500 ]; then
    HALFCOUNT=$[ ${COUNT} / 2 ]
    # From middle, down
    screen -admS afl-process_testcases_mid bash -c "BASEDIR='/test/dbg1010_mid'; find . | grep 'sig:' | grep -vE 'string|NOCORE' | sed 's|^\./||' | sort -h | tail -n ${HALFCOUNT} | xargs -I{} echo \"if [ ! -r '{}.string' -a ! -r '{}.NOCORE' ]; then cp '{}' \${BASEDIR}/in.sql; cd \${BASEDIR}; ./all_no_cl; ./test_pquery; sleep 2; if [ -r ./data/core ]; then echo '----------- /home/\$(whoami)/fuzzing/{}.string:'; ~/t | tee '/home/\$(whoami)/fuzzing/{}.string'; echo '-----------'; else echo '----------- /home/\$(whoami)/fuzzing/{}.NOCORE:'; touch '/home/\$(whoami)/fuzzing/{}.NOCORE'; echo '-----------'; fi; cd /home/\$(whoami)/fuzzing; fi\" | tr '\n' '\0' | xargs -0 -I{} timeout --signal=9 15m bash -c \"{}\""
    # From middle, reverse
    screen -admS afl-process_testcases_mid_rev bash -c "BASEDIR='/test/dbg1010_mid_rev'; find . | grep 'sig:' | grep -vE 'string|NOCORE' | sed 's|^\./||' | sort -h | head -n ${HALFCOUNT} | sort -r | xargs -I{} echo \"if [ ! -r '{}.string' -a ! -r '{}.NOCORE' ]; then cp '{}' \${BASEDIR}/in.sql; cd \${BASEDIR}; ./all_no_cl; ./test_pquery; sleep 2; if [ -r ./data/core ]; then echo '----------- /home/\$(whoami)/fuzzing/{}.string:'; ~/t | tee '/home/\$(whoami)/fuzzing/{}.string'; echo '-----------'; else echo '----------- /home/\$(whoami)/fuzzing/{}.NOCORE:'; touch '/home/\$(whoami)/fuzzing/{}.NOCORE'; echo '-----------'; fi; cd /home/\$(whoami)/fuzzing; fi\" | tr '\n' '\0' | xargs -0 -I{} timeout --signal=9 15m bash -c \"{}\""
  fi
fi
