#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ "${STY}" == "" ]; then
  echo "Not a screen, restarting myself inside a screen"
  screen -admS "run_reducers_loop" bash -c "./$0"
  sleep 1
  screen -d -r "run_reducers_loop"
  return 2> /dev/null; exit 0
fi

while true; do
  if [ -z $(screen -ls | grep 'reducers_run') ]; then
    echo "reducers_run screen not found, terminating any running instances of reducers_run at $(date)..."
    ps -ef | grep 'reducers_run' | grep -v 'grep' | awk '{print $2}' | xargs -I{} kill -9 {}
    sleep 3
    ps -ef | grep 'reducers_run' | grep -v 'grep' | awk '{print $2}' | xargs -I{} kill -9 {}
    sleep 3
    sync
    echo "Restarting at $(data)..."
    ./reducers_run
  fi
  sleep 30
done
