#!/bin/bash
# Created by Roel Van de Paar, MariaDB

killall -9 afl-fuzz 2>/dev/null
sleep 0.1
killall -9 afl-fuzz 2>/dev/null
sleep 0.1
ps -ef | grep 'afl-fuzz' | grep -vE 'grep|g++' | grep 'defunct' | awk '{print $3}' | xargs -I{} kill -9 {} 2>/dev/null  # Kill the PPID
screen -wipe >/dev/null 2>&1
ps -ef | grep afl | grep -v grep | awk '{print $2}' | xargs -I{} kill -9 {} 2>/dev/null
screen -wipe >/dev/null 2>&1
sleep 0.1
ps -ef | grep afl-fuzz | grep -vE 'grep|g++'  # Success or not status output
