-- Coverage bootstrap schema: gives generated DML/DQL real, varied objects so
-- execution paths (optimizer, executor, handlers, InnoDB) run, not just the parser.
SET sql_mode='';
SET foreign_key_checks=0;
SET max_recursive_iterations=100000;
CREATE DATABASE IF NOT EXISTS test;
USE test;

CREATE TABLE nums (n INT PRIMARY KEY);
INSERT INTO nums WITH RECURSIVE r(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM r WHERE n < 600) SELECT n FROM r;

CREATE TABLE t1 (c1 INT PRIMARY KEY, c2 INT, c3 VARCHAR(64), c4 DATETIME, KEY(c2), KEY(c3)) ENGINE=InnoDB;
CREATE TABLE t2 (c1 BIGINT UNSIGNED PRIMARY KEY, c2 DECIMAL(20,4), c3 TEXT, c4 DATE, KEY(c2)) ENGINE=InnoDB;
CREATE TABLE t3 (c1 INT PRIMARY KEY, c2 DOUBLE, c3 CHAR(32), c4 TIMESTAMP NULL, KEY(c3,c2)) ENGINE=Aria;
CREATE TABLE t4 (c1 INT PRIMARY KEY, c2 INT, c3 ENUM('a','b','c','d'), c4 SET('x','y','z'), KEY(c2)) ENGINE=MyISAM;
CREATE TABLE t5 (c1 INT PRIMARY KEY, c2 FLOAT, c3 VARCHAR(255), c4 TIME, FULLTEXT(c3)) ENGINE=InnoDB;

INSERT INTO t1 SELECT n, n%97, CONCAT('s',n), FROM_UNIXTIME(1600000000+n*37) FROM nums;
INSERT INTO t2 SELECT n, n*1.25, REPEAT(CHAR(65+n%26),1+n%40), DATE_ADD('2020-01-01', INTERVAL n DAY) FROM nums;
INSERT INTO t3 SELECT n, n/7.0, CONCAT('c',n%53), NOW()-INTERVAL n MINUTE FROM nums;
INSERT INTO t4 SELECT n, n%13, ELT(1+n%4,'a','b','c','d'), 'x,y' FROM nums;
INSERT INTO t5 SELECT n, n*0.5, CONCAT('full text body ',n,' lorem ipsum dolor data query index'), SEC_TO_TIME(n%86400) FROM nums;

CREATE VIEW v1 AS SELECT c1,c2,c3 FROM t1 WHERE c2 > 10;
CREATE VIEW v2 AS SELECT a.c1, b.c2 FROM t1 a JOIN t2 b ON a.c1=b.c1;
CREATE VIEW v3 AS SELECT c2, COUNT(*) cnt, SUM(c1) s FROM t1 GROUP BY c2;
CREATE VIEW v4 AS SELECT c1 FROM t1 UNION SELECT c1 FROM t3;
CREATE VIEW v5 AS SELECT * FROM (SELECT c1,c2 FROM t4 WHERE c2<5) d;

CREATE TABLE ft_json (id INT PRIMARY KEY, j JSON, jc INT AS (JSON_VALUE(j,'$.k')) VIRTUAL, KEY(jc)) ENGINE=InnoDB;
INSERT INTO ft_json SELECT n, JSON_OBJECT('k',n,'a',n%10,'arr',JSON_ARRAY(n,n*2),'tags',JSON_ARRAY('x','y'),'s',CONCAT('v',n)), NULL FROM nums WHERE n<=200;

CREATE TABLE ft_geo (id INT PRIMARY KEY, g GEOMETRY NOT NULL, p POINT, SPATIAL KEY(g)) ENGINE=InnoDB;
INSERT INTO ft_geo SELECT n, POINT(n, n%50), POINT(n%10,n%10) FROM nums WHERE n<=200;

CREATE TABLE ft_part (c1 INT, c2 INT, dt DATE, PRIMARY KEY(c1,dt))
  ENGINE=InnoDB PARTITION BY RANGE (YEAR(dt))
  (PARTITION p0 VALUES LESS THAN (2021), PARTITION p1 VALUES LESS THAN (2023),
   PARTITION p2 VALUES LESS THAN (2025), PARTITION pm VALUES LESS THAN MAXVALUE);
INSERT INTO ft_part SELECT n, n%50, DATE_ADD('2019-01-01', INTERVAL n DAY) FROM nums;

CREATE TABLE ft_gen (c1 INT PRIMARY KEY, c2 INT, c3 INT AS (c2*2) STORED, c4 INT AS (c2+c1) VIRTUAL, KEY(c3)) ENGINE=InnoDB;
INSERT INTO ft_gen (c1,c2) SELECT n, n%200 FROM nums;

CREATE TABLE ft_fk (id INT PRIMARY KEY, ref INT, FOREIGN KEY(ref) REFERENCES t1(c1) ON DELETE CASCADE ON UPDATE SET NULL) ENGINE=InnoDB;
INSERT INTO ft_fk SELECT n, 1+n%600 FROM nums;

ANALYZE TABLE t1,t2,t3,t4,t5,ft_json,ft_geo,ft_part,ft_gen;
