#!/bin/bash 

# Check screens for the same reducer having been started multiple times
CHECK="$(grep "reducer[0-9]\+.sh" /dev/shm/*/reducer.log | sed 's|.* Reducer: ||' | uniq -c | grep -v '^      1 ' | sed 's|.*/reducer|s|;s|\.sh||' | xargs -I{} echo "screen -ls | grep -vE 'grep|Dead' | grep -o '[0-9]\+\.{}'" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" | grep -o '\.s[0-9]\+$' | grep -o '[0-9]\+' | uniq -c | grep -v '^      1 ')" 
if [ ! -z "${CHECK}" ]; then
  echo "Multiple screens with/for the same reducer found:"
  echo "${CHECK}"
fi
CHECK=

# Check screens for pr vs ge counts
CNT1="$(screen -ls | grep pr | grep -v 'Dead' | wc -l)"
CNT2="$(screen -ls | grep ge | grep -v 'Dead' | wc -l)"

if [ "${1}" != "automation" -o "${CNT1}" != "${CNT2}" ]; then
  echo "pr: ${CNT1}"
  echo "ge: ${CNT2}"
fi

missing_screen_info=$(screen -ls | grep -o 'pr[0-9]\+' | grep -v 'Dead' | sort -V | awk '
{
  counts[$0]++;
  num = substr($0, 3) + 0;
  if (num > max_num) {
    max_num = num;
  }
}
END {
  for (item in counts) {
    count_freqs[counts[item]]++;
  }
  mode = 0;
  max_freq = 0;
  for (c in count_freqs) {
    if (count_freqs[c] > max_freq || (count_freqs[c] == max_freq && c > mode)) {
      max_freq = count_freqs[c];
      mode = c;
    }
  }
  if (mode <= 1) {
    exit;
  }
  missing_items = "";
  missing_count = 0;
  for (item in counts) {
    if (counts[item] < mode) {
      num = substr(item, 3) + 0;
      if (num != max_num) {
        missing_items = (missing_items == "" ? "" : missing_items ", ") item;
        missing_count++;
      }
    }
  }
  if (missing_count == 1) {
    print "one pr screen - " missing_items " - appears to be missing!";
  } else if (missing_count > 1) {
    print "multiple pr screens - " missing_items " - appear to be missing!";
  }
}
')

if [ "${CNT1}" != "${CNT2}" -o ! -z "${missing_screen_info}" ]; then
  echo '!!!!! ======= WARNING ======= !!!!!'
  if [ "${CNT1}" != "${CNT2}" ]; then
    echo "WARNING: 'pr' and 'ge' sessions were detected. A quick automated check then noticed that the number of 'pr' screens does not equal the number of 'ge' screens (check 's' output)."
    if [ ${CNT1} -gt ${CNT2} ]; then
      echo "As the number of 'pr' screens was larger than the number of 'ge' screens, to prevent a /data/ OOS, you will likely want to fix this by running ~/sge <workdir_number> where workdir_number is the /data/<workdir_number> which is missing from the 's' list (compare with an up-to-date 'vr' list to find which is missing, or check the list below.)"
    fi
    if [ ! -z "${missing_screen_info}" ]; then
      if [ ${CNT1} -lt ${CNT2} ]; then
        echo "WARNING: Note: ${missing_screen_info}"
      else
        echo "WARNING: Additionally, ${missing_screen_info}"
      fi
    fi
  else
    if [ ! -z "${missing_screen_info}" ]; then  # Defensive coding
      echo "WARNING: 'pr' and 'ge' sessions were detected. A quick automated check then noticed that while the number of 'pr' screens matches the number of 'ge' screens, ${missing_screen_info}"
    fi
  fi
  echo ''
  ls --color=never -1d /dev/shm/[0-9][0-9][0-9][0-9][0-9][0-9] 2>/dev/null | sed 's|/dev/shm/||' | xargs -I{} echo "if [ -z \"\$(screen -ls | grep '{}')\" ]; then echo '*** Run ~/sge {} to restart sge for workdir '{}', which is currently missing from the screen list'; fi" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}"
  echo ''
  exit 1
fi
exit 0
