#!/bin/bash
set +H
# New method. Not perfect as two reducers with the same number from different workdirs will count as one
ps -ef | grep 'bash -c ./reducer' | grep -o 'reducer[0-9]\+\.sh' | sort -u | wc -l

# New method, old grep approach (improved by 'bash -c ./reducer' grep above)
# Note the grep -v grep is necessary as for example ~/pr greps from reducer files and reducerx.sh will appear in ps output for those scripts, whereas they are not running reducers
# ps -ef | grep -v grep | grep -o 'reducer[0-9]\+\.sh' | sort -u | wc -l

# Old method
#COUNT1=$(ps -ef | grep --binary-files=text 'SCREEN' | grep --binary-files=text 'reducer[0-9]\+.sh' | sed 's|.*reducer|reducer|;s|;bash||' | sort -u | wc -l)
#COUNT2=$(screen -d -r | grep "\.reducer" | sort -u | wc -l)
#echo $[ ${COUNT1} + ${COUNT2} ]

# Incorrect (only counts screens, not truly active reducers)
#screen -ls | grep '\.s[0-9]' | wc -l
