#!/bin/bash
if [ -z "${1}" ]; then echo "Please pass a MENT bug number!"; exit 1; fi
BUG="$(echo "${1}" | grep -o '[0-9]\+')"
vi ~/mariadb-qa/BUGS/MENT-${BUG}.sql
if [ -r ~/mariadb-qa/BUGS/MENT-${BUG}.sql ]; then
  cd ~/mariadb-qa/BUGS/
  git add MENT-${BUG}.sql
  cd - >/dev/null 2>&1
fi
