#!/bin/bash

# For the BASEDIR, either specifying -opt or -dbg is fine, the script will auto-compute the other directory
# A single opt or dbg workdir instance will tend to take 0.4-0.8 GB of space (usually on /dev/shm)
#BASEDIR=/test/MDEV-35915_7_MD141025-mariadb-12.2.0-linux-x86_64-opt
#BASEDIR=/test/MDEV-35915_7_UBASAN_MD141025-mariadb-12.2.0-linux-x86_64-opt
#BASEDIR=/test/MDEV-35915_8_MD201025-mariadb-12.2.0-linux-x86_64-opt
#BASEDIR=/test/MDEV-37833_MD011125-mariadb-12.2.0-linux-x86_64-opt
#BASEDIR=/test/bb-10.11-monty_MD101225-mariadb-10.11.16-linux-x86_64-dbg
#BASEDIR=/test/bb-10.11-monty_UBASAN_MD101225-mariadb-10.11.16-linux-x86_64-dbg
BASEDIR=/test/MDEV-9826_MD201225-mariadb-12.3.0-linux-x86_64-opt
#BASEDIR=/test/MDEV-9826_UBASAN_MD201225-mariadb-12.3.0-linux-x86_64-opt
#BASEDIR=/test/MDEV-37833_UBASAN_MD011125-mariadb-12.2.0-linux-x86_64-dbg
#BASEDIR=/test/MD081025-mariadb-11.4.9-linux-x86_64-opt
#MDEV-35915_5_UBASAN_MD160925-mariadb-12.2.0-linux-x86_64-dbg
#MDEV-35915_2_MD060925-mariadb-12.0.1-linux-x86_64-dbg
RUNSOPT=2
RUNSDBG=2
#CONF=pquery-run-MD-Aria-enc.conf  # Encryption, PS=2, Aria swap
#CONF=pquery-run-MD-spider.conf  # PRE_SHUFFLE_SQL=2, and spider swap
#CONF=pquery-run-MD-spider-SAN.conf  # Using PRE_SHUFFLE_SQL=2, SAN
#CONF=pquery-run-MD-optimizer.conf
#CONF=pquery-run-MD-replication.conf  # Replication, PRE_SHUFFLE_SQL=2. Use at least 3 dbg to get RBR, SBR, MBR auto-rotation
##CONF=pquery-run-MD.conf  # Set currently to PRE_SHUFFLE_SQL=2
###CONF=pquery-run-MD-r1.conf
#CONF=pquery-run-MD-federated.conf
#CONF=pquery-run-mdev-31152.conf
#CONF=pquery-run-MD-crt.conf
#CONF=pquery-run-MD-allb.conf
#CONF=pquery-run-MD-MDEV-32830.conf  # Replication, PS=2, custom interleave grammar
#CONF=pquery-run-MD-MDEV-34680.conf  # Audit log, PS=2, custom interleave grammar
#CONF=pquery-run-MD-MDEV-34680x2.conf  # Audit log x2, PS=2, custom interleave grammar
#CONF=pquery-run-MD-3.conf
#CONF=pquery-run-MD-4.conf
#CONF=pquery-run-MD-5.conf
#CONF=pquery-run-MD-6.conf
##CONF=pquery-run-MD-MDEV_35915.conf
#CONF=pquery-run-MD-MDEV-37833.conf
CONF=pquery-run-MD-MDEV-9826.conf
#CONF=pquery-run-MD_mtr.conf  # PRE_SHUFFLE_SQL=1
#CONF=pquery-run-MD-XA.conf  # PRE_SHUFFLE_SQL=1, using xa-main-ms-ps-md_v2.sql (replication enabled)
#CONF=pquery-run-MD-repl.conf  # Using PRE_SHUFFLE_SQL=2
#CONF=pquery-run-MD2.conf  # Using PRE_SHUFFLE_SQL=2
#CONF=pquery-run-MD.conf  # Using PRE_SHUFFLE_SQL=2
#CONF=pquery-run-MD_saahil.conf  # Using PRE_SHUFFLE_SQL=2
#CONF=pquery-run-MD-multi.conf  # Using PRE_SHUFFLE_SQL=2, multithreaded
#CONF=pquery-run-MD-SAN.conf  # Using PRE_SHUFFLE_SQL=2, SAN
#CONF=pquery-run-MD-VAL.conf  # Using PRE_SHUFFLE_SQL=2, VAL
#CONF=pquery-run-MD-innodb.conf  # Using PRE_SHUFFLE_SQL=2
#CONF=pquery-run-MD-innodb-SAN.conf  # Using PRE_SHUFFLE_SQL=2, SAN
#CONF=pquery-run-MD-innodb-MDEV-30531-SAN.conf  # PRE_SHUFFLE_SQL=2, SAN, PRELOAD_SQL
#CONF=pquery-run-MD-btrfs.conf
#CONF=pquery-run-MDEV-24660.conf   # File name only, no spaces, no directories
#CONF=pquery-run-MD-buf.conf
#CONF=pquery-run-MD-rr.conf
#CONF=pquery-run-MD-idb1.conf
#CONF=pquery-run-MD105-MT.conf

if [ -z "${CONF}" ]; then
  echo "Error: \$CONF was not set. Please point it to a pquery-run.conf file like pquery-run-MD.conf (path is not required)"
  exit 1
elif [[ "${CONF}" == *"/"* ]]; then 
  echo "Assert: no paths/directories allowed in CONF (${CONF}) setting!"
  exit 1
elif [ ! -r "${HOME}/mariadb-qa" ]; then
  echo "Assert: ${HOME}/mariadb-qa not available"
  exit 1
elif [ ! -r ${HOME}/mariadb-qa/${CONF} ]; then
  echo "Assert: ${HOME}/mariadb-qa/${CONF} not available"
  exit 1
fi

if [ -z "${BASEDIR}" ]; then
  echo "The basedir variable BASEDIR was not set. Typo?"
  exit 1
fi

if grep -qi '^[ \t]*PRE_SHUFFLE_SQL[ \t]*=[ \t]*2' ${HOME}/mariadb-qa/${CONF}; then
  echo "*************************************************************************************************************************"
  echo "*** IMPORTANT NOTE: PRE_SHUFFLE_SQL=2 is set. No custom-set SQL input file will be used! Make sure this was intended! ***"
  echo "*************************************************************************************************************************"
  sleep 2
fi
COMPILER="unknown"
if [ -r ${BASEDIR}/BUILD_CMD_CMAKE ]; then
  COMPILER="GCC"  # GCC is not specified, but the old/previous default on test servers
  if grep -qi '/clang ' ${BASEDIR}/BUILD_CMD_CMAKE; then  # Clang is specified
    COMPILER="Clang"
  fi
fi
PSS="$(grep -io '^[ \t]*PRE_SHUFFLE_SQL[ \t]*=[ \t]*[0-9]\+' ${HOME}/mariadb-qa/${CONF} | grep -o '[0-9]\+')"
INF=''
if [ "${PSS}" != "2" ]; then
  INF=" $(grep '^INFILE=' ${HOME}/mariadb-qa/${CONF} | sed 's|=|: |' | tr -d '\n') |"
fi
echo "# Compiler: ${COMPILER} | PRE_SHUFFLE_SQL setting: ${PSS} |${INF} $(grep '^PQUERY_RUN_TIMEOUT' ${HOME}/mariadb-qa/${CONF} | sed 's|[ ]\+#.*||;s|PQUERY_RUN_TIMEOUT=|Trial runtime: |;s|$|s|')"
if grep -qi '^PRELOAD=1' ${HOME}/mariadb-qa/${CONF}; then
  echo "# PRELOAD is enabled: using sql preload file: $(grep -o '^PRELOAD_SQL[^#]\+' ${HOME}/mariadb-qa/${CONF} | sed 's|PRELOAD_SQL=||;s| *$||')"
fi
if [[ "${BASEDIR}" != "/test"* ]]; then
  BASEDIRNEW="$(echo "/test/${BASEDIR}" | sed 's|/\./|/|g')"
  if [ -d "${BASEDIRNEW}" ]; then
    BASEDIR="${BASEDIRNEW}"
    echo "# Basedir updated to ${BASEDIR}"
  fi
  BASEDIRNEW=
fi

if [ ! -d "${BASEDIR}" ]; then
  echo "The basedir (${BASEDIR}) does not exist or is not readable by this script! Terminating."
  exit 1
fi

echo "# Basedir: ${BASEDIR}"
echo "# Configuration in use: ${HOME}/mariadb-qa/${CONF}"
echo "This script should show further output in 10-20 seconds. If it does not, see:"
echo "screen -d -r pr1  # for the cause"
echo ""

rm -Rf /data/tmp/*.sql

TOTALRUNS=$[ ${RUNSOPT} + ${RUNSDBG} ]
MON=
for RUN in $(seq 1 ${TOTALRUNS}); do
  rm -f /tmp/gomd_helper
  cd ${HOME}/mariadb-qa
  if [ ! -r ${CONF} ]; then echo "Assert: ${CONF} not found!"; exit 1; fi
  sed -i "s|^BASEDIR=\([^#]\+\)|BASEDIR=${BASEDIR}   |" ${CONF}
  if [ ${RUN} -le ${RUNSOPT} ]; then  # Opt runs
    sed -i 's|^BASEDIR=\([^#]\+\)-dbg|BASEDIR=\1-opt|' ${CONF}
  else  # Dbg runs
    sed -i 's|^BASEDIR=\([^#]\+\)-opt|BASEDIR=\1-dbg|' ${CONF}
  fi
  screen -admS pr${RUN} bash -c "cd ${HOME}/mariadb-qa; ./pquery-run.sh ${CONF}; bash"
  while :; do
    sleep 1
    if [ -r /tmp/gomd_helper ]; then
      sleep 0.3
      DIR="$(cat /tmp/gomd_helper)"
      if [ -d "${DIR}" ]; then
        rm -f /tmp/gomd_helper
        cd ${DIR}/..
        DIREND="$(echo "${DIR}" | sed 's|.*/||')"
        if [ ! -d ./${DIREND} ]; then
          echo "Assert: ./${DIREND} should exist, based on directory passed by gomd_helper (${DIR})"
          exit 1; break
        else
          if [[ "${CONF}" != *"crt"* && "${CONF}" != *"CRT"* ]]; then  # Do not stat ge instances for crash recovery runs
            if [ ! -r ~/sge ]; then 
              echo "Assert: ~/sge not available! Cannot start pquery-go-expert!" 
              exit 1; break
            else
              ~/sge "${DIREND}" "pr${RUN}"
              TYPE="DBG"
              if [ ${RUN} -le ${RUNSOPT} ]; then TYPE="OPT"; fi
              echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN}), and pquery-go-expert started for the same!"
              MON[RUN]="$(echo "${DIR}" | sed 's|.*/||' | grep -o '[0-9]\+')"
              break
            fi
          else
            if [ ! -r ~/crc ]; then
              echo "Assert: ~/crc not available! Cannot start crash recovery handlers!" 
              exit 1; break
            else
              screen -admS "crc$(echo "${DIR}" | sed 's|.*/||')" bash -c "cd ${DIR}; while true; do ~/crc; sleep 20; done; bash"  # Start crash testing handler for the (each) workdir
              TYPE="DBG"
              if [ ${RUN} -le ${RUNSOPT} ]; then TYPE="OPT"; fi
              echo "MD ${TYPE} Run ${RUN} started (Dir: ${DIR} Screen: pr${RUN}), and a crash recovery handler (~/crc) started for the same!"
              MON[RUN]="$(echo "${DIR}" | sed 's|.*/||' | grep -o '[0-9]\+')"
              break
            fi
          fi
        fi 
      fi
    fi
  done
done
echo ''
echo 'For updating the results script (add/edit /data/results.list, then run the /data/results script):'
for RUN in $(seq 1 ${TOTALRUNS}); do
  echo "MON[${RUN}]=${MON[${RUN}]}"
done
