#!/bin/bash
if [ -z "${1}" ]; then
  echo "Please pass trial number to locate the basedir for it!"
  exit 1
fi
if [ ! -r ./reducer${1}.sh -o ! -d ./${1}/ ]; then
  echo "./reducer${1}.sh or trial dir ./${1}/ not found!"
  exit 1
fi
cat ${1}/MYBUG | sed 's|^|MYBUG    : |'
grep '^BASEDIR' ./reducer${1}.sh | sed 's|^[^"]\+"||;s|".*||' | sed 's|^|BASEDIR  : |'
tail -n2 ${1}/pquery.log | head -n1 | sed 's|^|PQUERY   : |'
tail -n2 ${1}/pquery.log | tail -n1 | sed 's|^|           |'
cat ${1}/log/master.err | grep -vE '^[-=]+$' | tail -n3 | head -n1 | sed 's|^|ERRORLOG : |'
cat ${1}/log/master.err | grep -vE '^[-=]+$' | tail -n3 | tail -n2 | sed 's|^|           |'
ls -s ${1}/default.node.tld_thread-0.sql| grep --binary-files=text -vE "backup|failing|prev" | tac | head -n1 | sed "s|^[ 0-9]\+||;s|^/||" | xargs -I{} wc -l ${1}/{} | sed 's| | Lines: cat |;s|^|TESTCASE : |'
if [ -z "$(ls ${1}/data/*core 2>/dev/null)" ]; then
  echo "CORE     : No core"
else
  ls ${1}/data/*core| sed 's|^|CORE     : |'
fi
CHARS_MY_INIT="$(wc -m ${1}/MYINIT 2>/dev/null | sed 's| .*||')"
if [ "${CHARS_MY_INIT}" -gt 1 ]; then
  cat ${1}/MYINIT | sed 's|^|MYINIT   : |'
fi
cat ${1}/MYEXTRA | sed 's|\-\-no\-defaults ||;s|^|MYEXTRA  : |'
