#!/bin/bash

grep -io 'Basedir:.*' pquery-run.log | sed 's|basedir:[ \t]\+|BASEDIR                 |i'  # Use pquery-run.log instead of pquery*.conf as that one may have incorrect basedir depending on what it was set to
if grep -q '^PRE_SHUFFLE_SQL=[01]' pquery*.conf; then
  grep '^INFILE' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|;s|\${SCRIPT_PWD}|~/mariadb-qa|'
fi
ls pquery*.conf | tr '\n' ' ' | sed 's|^|PQUERY_CONFIGURATION    |;s|$|\n|'
grep '^PQUERY_BIN' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|;s|\${SCRIPT_PWD}|~/mariadb-qa|'
grep '^PRE_SHUFFLE_SQL' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t|'
grep '^STORAGE_ENGINE_SWAP' pquery*.conf | grep -v PERCENTAGE | sed 's|[ ]\+#.*||;s|=|   \t|;s|""|No|' | sed "s|''|No|"
grep '^SWAP_ALL_TABLE_NAMES_TO_T1' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
grep '^SWAP_CREATE_TABLE_NAMES_TO_T1' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
grep '^ADD_RANDOM_OPTIONS' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
grep '^PQUERY_RUN_TIMEOUT' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
grep '^THREADS' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
grep '^PRELOAD=' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
if grep -q 'PRELOAD=[^0]' pquery*.conf; then
  grep '^PRELOAD_SQL' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|;s|\${SCRIPT_PWD}|~/mariadb-qa|'
fi
if grep -q '^USE_GENERATOR_INSTEAD_OF_INFILE=1' pquery*.conf; then
  grep '^USE_GENERATOR_INSTEAD_OF_INFILE' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
  grep '^ADD_INFILE_TO_GENERATED_SQL' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
  grep '^QUERIES_PER_GENERATOR_RUN' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
  grep '^GENERATE_NEW_QUERIES_EVERY_X_TRIALS' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
fi
if grep -qi '^MYEXTRA.*log.bin' pquery*.conf || grep -qi '^MASTER_EXTRA.*log.bin' pquery*.conf; then
  if grep -qi '^MYEXTRA.*binlog.format' pquery*.conf || grep -qi '^MASTER_EXTRA.*binlog.format' pquery*.conf; then
    grep '^ROTATE_BINLOG_FORMAT' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
  fi
fi
grep '^PRE_SHUFFLE_INTERLEAVE' pquery*.conf | grep -vE '^PRE_SHUFFLE_INTERLEAVE_' | sed 's|[ ]\+#.*||;s|=|\t|'
if grep -q '^PRE_SHUFFLE_INTERLEAVE=1' pquery*.conf; then
  grep '^PRE_SHUFFLE_INTERLEAVE_' pquery*.conf | sed 's|^PRE_SHUFFLE_| > |' | sed 's|[ ]\+#.*||;s|=|\t|'
fi
grep '^MYINIT' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
grep '^MYSAFE' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
if grep -q '^QUERY_CORRECTNESS_TESTING=1' pquery*.conf; then
  grep '^QUERY_CORRECTNESS_TESTING' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
  grep '^MYEXTRA' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
else
  grep '^MYEXTRA' pquery*.conf | grep -v 'MYEXTRA2' | sed 's|[ ]\+#.*||;s|=|   \t\t|'
fi
if grep -q '^REPLICATION=1' pquery*.conf; then
  grep '^REPLICATION=' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
  grep '^REPL_EXTRA' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
  grep '^MASTER_EXTRA' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
  grep '^SLAVE_EXTRA' pquery*.conf | sed 's|[ ]\+#.*||;s|=|   \t\t|'
fi
if grep -q '^ENABLE_ENCRYPTION=[^0]' pquery*.conf; then
  grep '^ENABLE_ENCRYPTION' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t|'
  grep '^MYENCRYPTION' pquery*.conf | sed 's|[ ]\+#.*||;s|=|\t\t|'
fi
