#!/bin/bash
~/mariadb-qa/kill_all_procs.sh
if [ -r /test/kill_all ]; then
  cd /test
  ./kill_all
fi
for ((i=1;i<=3;i++)); do
  screen -ls | sed 's|\.newbug.*||;s| ||g' | grep -v pts | xargs -I{} kill -9 {} 2>/dev/null 1>&2
  screen -wipe 2>/dev/null 1>&2
  sleep 0.43
done
rm -Rf /dev/shm/[0-9]*
rm -Rf /dev/shm/var*
