#!/bin/bash
# Created by Roel Van de Paar, MariaDB
# This script is a copy of ~/kbs with $KB modified
set +H

KB=~/mariadb-qa/known_bugs.strings.SAN

if [ "$#" -eq 0 ]; then
  echo 'Please pass a string to search for in the known *SAN bugs list'
  exit 1
elif [ "$#" -ne 1 ]; then
  if [ "${1}" == "REVERSE" -a "$#" -eq 2 ]; then
    sleep 0.01  # If two options are provided and first is REVERSE then all input is correct
  else
    echo "*** ASSERT ***"
    echo "Remember to pass only a single argument surrounded by double quotes. Single quotes will not work when the searched-for string contains single quotes as well given that Bash will see this as multiple options to the script rather than the actual string to search for. Usage example:"
    echo "kbsa \"some'bug'searchstring\""
    exit 1
  fi
fi

if [ "${1}" != "REVERSE" ]; then  # Standard search (show the string if it exists)
  grep --binary-files=text -Fi "${1}" ${KB}
else   # Reverse search (show the string if it does not exist yet)
  if [ -z "$(grep --binary-files=text -Fi "${2}" ${KB})" ]; then  # Not found at all
    echo "${2}"
  else  # Found, but possible a fixed bug (prefixed with leading '#') 
    SEARCH="$(grep --binary-files=text -Fi "${2}" ${KB})"
    if [[ "${SEARCH}" == "#"* ]]; then 
      echo "${2}"
      echo "Note: a fixed bug with the same UniqueID was found ${KB}!"
    fi
  fi
fi
