#!/bin/bash

if [ "${STY}" == "" ]; then
  echo "Not a screen, restarting myself inside a screen"
  screen -admS "loop_tmpfs" bash -c "$0;bash"
  sleep 1
  screen -d -r "loop_tmpfs"
  return 2> /dev/null; exit 0
fi

COUNT=0
while true; do 
  ~/mariadb-qa/tmpfs_clean.sh 1
  if [ ${COUNT} -eq 0 ]; then
    if [ -r "${HOME}/ds" ]; then
      timeout --signal=9 60s ${HOME}/ds automated  # Run ds for 90 sec
    fi
    if [ -r "${HOME}/memory" ]; then
      timeout --signal=9 60s ${HOME}/memory  # Run memory for 90 sec
    fi
    COUNT=20
  fi
  # Cleanup filtered_infile.sql from finished data WORKDIRs
  PSLIST="$(ps -ef | grep --color=never -o '\.ge[0-9][0-9][0-9][0-9][0-9][0-9][^0-9]' | grep -o '[0-9]\+' | tr '\n' '|' | sed 's/[|]\+$//')"
  if [ -z "${PSLIST}" ]; then
    PSLIST='EMPTY'
  fi
  ls --color=never /data/[0-9][0-9][0-9][0-9][0-9][0-9]/filtered_infile.sql 2>/dev/null | grep -vE "${PSLIST}" | xargs -I{} rm -f "{}"
  PSLIST=
  sleep 60
  COUNT=$[ ${COUNT} -1 ]
done
