#!/bin/bash
# Created by Roel Van de Paar, MariaDB

if [ -z "${1}" ]; then
  echo 'Please pass the trial number for which you want to make a base_reducer.sh script'
  exit 1
elif [ ! -d "./${1}" ]; then
  echo "Assert: trial [directory] './${1}' does not exist, please pass the trial number for which you want to make a base_reducer.sh script"
  exit 1
elif [ ! -r "./reducer${1}.sh" ]; then
  echo "Assert: no ./reducer${1}.sh exists, please pass a trial number (only) for which a reducer.sh script already exists (run ~/pg ?)"
  exit 1
else
  TRIAL="${1}"
fi

FEATURE_DIR="$(grep '^BASEDIR=' ./reducer${TRIAL}.sh | head -n1 | grep -o '/test/[^"]\+')"
if [ -z "${FEATURE_DIR}" ]; then
  echo "Assert: could not determine the feature base directory from ./reducer${TRIAL}.sh"
  exit 1
fi
MAJOR_VERSION="$(echo "${FEATURE_DIR}" | grep -o '1[0-9]\.[0-9]\+\.[0-9]\+' | grep -o '1[0-9]\.[0-9]\+')"
if [ -z "${MAJOR_VERSION}" ]; then
  echo "Assert: could not determine the major MariaDB version number from the feature base directory name: '${FEATURE_DIR}'"
  exit 1
fi
DBG_OR_OPT="$(echo "${FEATURE_DIR}" | grep -o '\-[do][bp][gt]' | grep -o '[a-z]\+')"
if [ "${DBG_OR_OPT}" != "dbg" -a "${DBG_OR_OPT}" != "opt" ]; then
  echo "Assert: could not determine build type (dbg or opt) from the feature base directory name: '${FEATURE_DIR}'"
  exit 1
fi
if [ ! -r /test/gendirs.sh ]; then
  echo "Assert: /test/gendirs.sh does not exist"
  exit 1
fi
BASEDIR=
if [ -r ./BASEDIR ]; then
  BASEDIR="$(cat ./BASEDIR | head -n1 | sed 's|^[ \t]\+||;s|[ \t]\+$||')"
  if [ ! -d ${BASEDIR} ]; then
    echo "Assert: ./BASEDIR found, yet the directory/contents therein (${BASEDIR}) do not point to an actual BASEDIR. Please specify a fully qualified and existing directory name within it, or remove the ./BASEDIR file allowing this script to use gendirs.sh instead."
    exit 1
  fi
  echo "BASEDIR for 'base_' reducers set to ${BASEDIR} as specified in ./BASEDIR"
else
  # TODO: possible improvement: auto-base BASEDIR where instead of using gendirs.sh in this script, gendirs.sh is used from the patched reducer instead
  BASEDIR="/test/$(cd /test; ./gendirs.sh | grep "\-${MAJOR_VERSION}" | grep "${DBG_OR_OPT}" | sort -h | tac | head -n1)"
fi
if [ -z "${BASEDIR}" ]; then
  echo "Assert: BASEDIR variable empty after running gendirs.sh"
  exit 1
elif [ ! -d "${BASEDIR}" ]; then
  echo "Assert: BASEDIR set to '${BASEDIR}' yet this is not a directory"
  exit 1
fi

cp ./reducer${TRIAL}.sh ./base_reducer${TRIAL}.sh
sed -i "s|${FEATURE_DIR}|${BASEDIR}|" ./base_reducer${TRIAL}.sh
sed -i 's|^FORCE_SKIPV=[0-9]\+|FORCE_SKIPV=0|' ./base_reducer${TRIAL}.sh
sed -i 's|^MULTI_THREADS=[0-9]\+|MULTI_THREADS=10|' ./base_reducer${TRIAL}.sh
sed -i 's|^MULTI_THREADS_MAX=[0-9]\+|MULTI_THREADS_MAX=40|' ./base_reducer${TRIAL}.sh
sed -i 's|^STAGE1_LINES=[0-9]\+|STAGE1_LINES=10|' ./base_reducer${TRIAL}.sh
cp ./base_reducer${TRIAL}.sh ./feature_reducer${TRIAL}.sh
sed -i "s|${BASEDIR}|${FEATURE_DIR}|" ./feature_reducer${TRIAL}.sh

TEXT="$(grep '^   TEXT=' reducer${TRIAL}.sh | head -n1 | sed 's|^   TEXT="||;s|"[ \t]*$||')"
if [ ! -z "${TEXT}" ]; then
  echo '#!/bin/bash' > ./find${TRIAL}
  echo "echo '--- All occurrences of this issue:'" >> ./find${TRIAL}
  echo "LIST1=\"\$(grep -FiH --color=never --binary-files=text \"$(echo "${TEXT}" | sed 's|"|\\"|g')\" /data/[0-9]*/[0-9]*/MYBUG | sed 's|MYBUG:|MYBUG: |')\"" >> ./find${TRIAL}
  echo 'echo "${LIST1}" | grep --binary-files=text -v "^[ \t]*$"' >> ./find${TRIAL}
  echo "LIST2=\"\$(grep -iH --color=never --binary-files=text \"$(echo "${TEXT}" | sed 's|"|\\"|g')\" /data/[0-9]*/[0-9]*/log/*.err | sed 's|\.err:[-0-9: ]\+|.err: |' | grep --binary-files=text -v '^[ \\t]*$')\"" >> ./find${TRIAL}
  echo 'echo "${LIST2}" | grep --binary-files=text -v "^[ \t]*$"' >> ./find${TRIAL}
  echo "echo ''" >> ./find${TRIAL}
  echo "echo '--- Reduced testcases for the same issue:'" >> ./find${TRIAL}
  echo 'echo "${LIST1}" | sed "s|MYBUG.*||" | xargs -I{} echo "ls --color=never -S {}*out 2>/dev/null" | xargs -I{} bash -c "{}" | sed "s|^[ \t]\+||" | xargs -I{} wc -l {} | sort -h' >> ./find${TRIAL}
  echo 'echo "${LIST2}" | sed "s|log/[^ ]\+\.err:.*||" | xargs -I{} echo "ls --color=never -S {}*out 2>/dev/null" | xargs -I{} bash -c "{}" | sed "s|^[ \t]\+||" | xargs -I{} wc -l {} | sort -h' >> ./find${TRIAL}
  chmod +x find${TRIAL}
fi

# As it was observed that issue reproducibility on base BASEDIRs is higher with the original input in certain cases, the created base_reducer{trial}.sh script is set to use the original full input file, instead of any already partially reduced files as general reducers automatically do
INPUTFILE_LINE="$(grep '^INPUTFILE=' ./base_reducer${TRIAL}.sh 2>/dev/null | grep -o '[-_=/a-zA-Z0-9]\+/default.node.tld_thread-0.sql' | sed "s|^|INPUTFILE='|;s|$|'|")"
if [ ! -z "${INPUTFILE_LINE}" ]; then
  sed -i "s|^INPUTFILE=.*|${INPUTFILE_LINE}|" ./base_reducer${TRIAL}.sh
fi

if [ "${2}" == "NOSTART" ]; then  # pg automation
  echo "[async upd thread][mb] Created ./base_reducer${TRIAL}.sh, ./feature_reducer${TRIAL}.sh and ./find${TRIAL}"
else
  echo "Testing if the issue seen in trial ${TRIAL} also exists in CS BASEDIR ${BASEDIR}"
  echo "Feature BASEDIR: ${FEATURE_DIR} | Major MariaDB Ver: ${MAJOR_VERSION} | Build type: ${DBG_OR_OPT}"
  echo "Created ./base_reducer${TRIAL}.sh, ./feature_reducer${TRIAL}.sh and ./find${TRIAL}"
  echo ''
  if [ -x ./find${TRIAL} ]; then
    echo "Executing ./find${TRIAL} to search for other occurrences first:"
    ./find${TRIAL}
    sleep 2
    echo ''
  fi
  echo "Now Starting ./base_reducer${TRIAL}.sh..."
  ./base_reducer${TRIAL}.sh
fi
