#!/bin/bash
# Also see ~/mariadb-qa/memory_leaks_howto.txt for related throubleshooting info, otherwise unrelated to the monitoring script below

# User variables
KILL_LARGE=1    # Will kill any process consuming equal to or more then KILL_PERCENT.0 percent of memory
KILL_PERCENT=7  # For example: 4: All processes up to 3.99 will be left, 4.00 and onwards will be killed

if [ "${STY}" == "" ]; then
  THIS_SCRIPT="$(readlink -f $0)"  # Resolves symlinks, result is the actual script including directory
  SCREEN_NAME='memory'
  echo "Not a screen, restarting myself inside a screen"
  screen -admS "${SCREEN_NAME}" bash -c "${THIS_SCRIPT} ${*}"
  sleep 1
  screen -d -r "${SCREEN_NAME}"
  return 2> /dev/null; exit 0
fi

# Script variables
while :; do
  clear
  CMD="ps --sort -rss -eo pid,pmem,rss,vsz,comm | grep --binary-files=text -vE 'fireworks|mtr_to_sql|generator.sh|cc|clang|reducer'"
  eval "${CMD}" | head -n7
  HEADLINE=;PERCENT=;PID=
  if [ "${KILL_LARGE}" -eq 1 ]; then
    # Do not terminate generator.sh nor cc1plus or any other *cc* program
    HEADLINE="$(eval "${CMD}" | head -n2 | tail -n1)"
    PERCENT="$(echo ${HEADLINE} | awk '{print $2}' | sed 's|\.[0-9]\+||;s|[ \t]||g')"
    PID="$(echo ${HEADLINE} | awk '{print $1}' | sed 's|[ \t]||g')"
    if [ ${PERCENT} -ge ${KILL_PERCENT} ]; then
      echo "Process ${PID} is consuming too much memory (${PERCENT}%): terminating..."
      echo "Process ${PID} snapshot:"
      ps -ef | grep "${PID}" | grep -v grep
      sleep 1
      kill -9 ${PID}
      kill -9 ${PID}
      kill -9 ${PID}
      sleep 5  # Allows user to notice/read message
    fi
  fi
  echo ''
  echo -e "USER\tTTY\tJCPU\tPCPU\tCOMMAND"
  w -h | awk '{print $1"\t"$2"\t"$6"\t"$7"\t"$8" "$9" "$10" "$11" "$12" "$13" "$14" "$15" "$16" "$17" "$18" "$19" "$20}' | grep -E '[0-9][0-9]\.[0-9][0-9]s|[0-9]:[0-9][0-9]m' | grep -v 'sleep' | grep -v 'awk'
  sleep 7
done
