#!/bin/bash
PGE_LOOPS=2  # Immediately improves testcase quality after first reducer round. Ideal to maxout machine time. Set to 0 to disable. At least 1 recommended as it can greatly improve testcase quality

if [ -z "${1}" ]; then
  echo "Assert: please pass reducer/trial nr to start. No action was taken."
  exit 1
fi
if [[ ! "${PWD}" =~ ^/data/[0-9]{6}$ ]]; then
  echo 'Assert: you are not in a /data/work_dir_nr directory, like /data/123456. No action was taken.'
  exit 1
fi
CHECK_REDUCER_PATH="$(echo "${PWD}/reducer${1}.sh" | sed 's|[//]\+|/|g')"
if grep --binary-files=text -qi "${CHECK_REDUCER_PATH}" /dev/shm/*/reducer.log 2>/dev/null; then  # Does the /data/workdirnr/trialnr dir already exist in /dev/shm logs. If so, check more comprehensively if the trial is still running:
  CHECK_IF_TRIAL_LIVE="$(grep --binary-files=text -i "${CHECK_REDUCER_PATH}" /dev/shm/*/reducer.log 2>/dev/null | sed 's|reducer.log:.*|reducer.log|' | sort -u | xargs -I{} grep --binary-files=text -o 'Init] Reducer PID:.*' {} 2>/dev/null | grep -o '[0-9]\+' | tr '\n' '|' | sed 's/|$//' | xargs -I{} echo "ps -ef | grep -E '{}' | grep -v grep" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}")"  # Used to check if the trial specified in ${1} is indeed still running by checking ps output for the right PID's
  if [ ! -z "${CHECK_IF_TRIAL_LIVE}" ]; then
    echo "Assert: a reducer for trial $(echo "${CHECK_REDUCER_PATH}" | sed 's|reducer||;s|.sh||') is already running! No action was taken."
    exit 1
  fi
  CHECK_IF_TRIAL_LIVE=
fi
if [ "${2}" != "1" ]; then  # $2=1 enables starting a reducer for a given UniqueID when another reducer with/for the same UniqueID is already running. If it used, we don't need to check the following
  TEMP_UID_IN_DEVSHM_LIST=$(mktemp)
  grep "reducer[0-9]\+.sh$" /dev/shm/*/reducer.log 2>/dev/null | sed 's|.* Reducer: ||' | sort -u | xargs -I{} echo "grep --binary-files=text '^[ ]*TEXT=' {} 2>/dev/null | head -n1 | sed 's|.*TEXT=\"||;s|\"[ \t]*$||'" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}" | sort -u > ${TEMP_UID_IN_DEVSHM_LIST}  # All reducers of all trials which have /dev/shm directories are checked for their UniqueID
  UNIQUE_ID="$(grep --binary-files=text '^[ ]*TEXT=' reducer${1}.sh 2>/dev/null | head -n1 | grep --binary-files=text -v "^TEXT=''" | grep --binary-files=text -v "^TEXT=.*somebug" | sed 's|.*TEXT="||;s|"[ \t]*$||')"  # grep ... -v "^TEXT=''": exclude MODE=0 trials which have ^TEXT='' in the 'Machine configurable variables section' as the first TEXT=... The somebug grep -v is for blank reducer's
  if [ ! -z "${UNIQUE_ID}" ]; then
    if [ ! -z "$(grep --binary-files=text -Fi "${UNIQUE_ID}" ${TEMP_UID_IN_DEVSHM_LIST} 2>/dev/null)" ]; then  # The UniqeID is being reduced in /dev/shm/ already
      CHECK_IF_TRIAL_LIVE="$(grep "reducer[0-9]\+.sh$" /dev/shm/*/reducer.log 2>/dev/null | sed 's|.* Reducer: ||' | sort -u | xargs -I{} grep -Film1 "${UNIQUE_ID}" {} 2>/dev/null | sed 's|.*[0-9]/reducer|reducer|' | xargs -I{} echo "ps -ef | grep -E '{}' | grep -v grep" | tr '\n' '\0' | xargs -0 -I{} bash -c "{}")"
      if [ ! -z "${CHECK_IF_TRIAL_LIVE}" ]; then
        echo "Assert: another reducer for UniqueID \"${UNIQUE_ID}\" is already running. No action was taken. Add '1' as a second option to this script to overwrite and start the reducer for trial ${1} anyways."
        exit 1
      fi
      CHECK_IF_TRIAL_LIVE=
    fi
  fi
  UNIQUE_ID=
  rm -f "${TEMP_UID_IN_DEVSHM_LIST}"
  TEMP_UID_IN_DEVSHM_LIST=
fi
CHECK_IF_TRIAL_LIVE=
PGE=
if [ -r "${HOME}/pge" ]; then PGE="${HOME}/pge";
elif [ -r "${HOME}/mariadb-qa/pquery-goexp-patch.sh" ]; then PGE="${HOME}/mariadb-qa/pquery-goexp-patch.sh"; 
fi
if [ -z "${PGE}" -o -z "${PGE_LOOPS}" ]; then
  echo "Assert: PGE or PGE_LOOPS is empty?"
  exit 1
fi
mkdir -p ./reducer.logs
if [ -r reducer_val${1}.sh ]; then
  screen -admS s${1} bash -c "./reducer_val${1}.sh 2>&1 | tee -a ./reducer.logs/reducer_val${1}.log; for((i=1;i<=${PGE_LOOPS};i++)); do echo \"---------------- PGE Run \${i}/${PGE_LOOPS} ----------------\" | tee -a ./reducer.logs/reducer_val${1}.log; ${PGE} ${1} | tee -a ./reducer.logs/reducer_val${1}.log; done; bash"
elif [ -r reducer${1}.sh ]; then
  #screen -admS s${1} bash -c "ulimit -u 4000;./reducer${1}.sh;bash"
  screen -admS s${1} bash -c "./reducer${1}.sh 2>&1 | tee -a ./reducer.logs/reducer${1}.log; for((i=1;i<=${PGE_LOOPS};i++)); do echo \"---------------- PGE Run \${i}/${PGE_LOOPS} ----------------\" | tee -a ./reducer.logs/reducer${1}.log; ${PGE} ${1} | tee -a ./reducer.logs/reducer${1}.log; done; bash"
elif [ -r ${1} ]; then
  LOGNAME="$(echo ./${1} | sed 's|\.sh|.log|')"
  screen -admS s${1} bash -c "./${1} 2>&1 | tee -a ./reducer.logs/${LOGNAME}; for((i=1;i<=${PGE_LOOPS};i++)); do echo \"---------------- PGE Run \${i}/${PGE_LOOPS} ----------------\" | tee -a ./reducer.logs/reducer${1}.log; ${PGE} ${1} | tee -a ./reducer.logs/reducer${1}.log; done; bash"
elif [ -r ${1}.reducer.sh ]; then
  screen -admS s${1} bash -c "./${1}.reducer.sh 2>&1 | tee -a ./reducer.logs/${1}.reducer.log; for((i=1;i<=${PGE_LOOPS};i++)); do echo \"---------------- PGE Run \${i}/${PGE_LOOPS} ----------------\" | tee -a ./reducer.logs/reducer${1}.log; ${PGE} ${1} | tee -a ./reducer.logs/reducer${1}.log; done; bash"
elif [ -r ${1}.sh ]; then
  screen -admS s${1} bash -c "./${1}.sh 2>&1 | tee -a ./reducer.logs/${1}.log; for((i=1;i<=${PGE_LOOPS};i++)); do echo \"---------------- PGE Run \${i}/${PGE_LOOPS} ----------------\" | tee -a ./reducer.logs/reducer${1}.log; ${PGE} ${1} | tee -a ./reducer.logs/reducer${1}.log; done; bash"
else
  echo "Assert: No such reducer script: reducer${1}.sh, nor ${1}, nor ${1}.sh"
  exit 1
fi
if [ "${2}" != "" -a "${2}" != "1" ]; then screen -d -r s${1}; fi
exit 0
