mdg1:
  build: .
  hostname: mdg1
  command: sh -c "ln -s /usr/lib64/libreadline.so.6.2 /usr/lib64/libreadline.so.5; /mysql/bin/mysqld --basedir=/mysql --user=mysql --wsrep-new-cluster --skip-grant-tables --log-error=error.log"
  ports:
      - "10000:3306"
      - "10001:4567"
      - "10002:4568"
mdg2:
  build: .
  hostname: mdg2
  command: sh -c "/bin/sleep 30 && ln -s /usr/lib64/libreadline.so.6.2 /usr/lib64/libreadline.so.5;/mysql/bin/mysqld --basedir=/mysql --user=mysql --wsrep-node-name=mdg2 --wsrep_cluster_address=gcomm://mdg1 --skip-grant-tables  --wsrep-sst-method=rsync --log-error=error.log"
  links:
      - mdg1:mdg1
  ports:
      - "11000:3306"
      - "11001:4567"
      - "11002:4568"

mdg3:
  build: .
  hostname: mdg3
  command: sh -c "/bin/sleep 100 && ln -s /usr/lib64/libreadline.so.6.2 /usr/lib64/libreadline.so.5;/mysql/bin/mysqld --basedir=/mysql --user=mysql --wsrep-node-name=mdg3 --wsrep_cluster_address=gcomm://mdg1,mdg2 --skip-grant-tables  --wsrep-sst-method=rsync --log-error=error.log"
  links:
      - mdg1:mdg1
      - mdg2:mdg2
  ports:
      - "12000:3306"
      - "12001:4567"
      - "12002:4568"
